### ISSUE TITLE
What is the difference between 'docs/lib' and 'src/lib' ?

### ISSUE THREAD

**Issue by PhilTheAir** [rrag/react-stockcharts#102]
As a beginner, what is the difference between 'docs/lib' and 'src/lib' ?
Thank you!

**Comment by rrag** [comment]
`src/lib` - contains the source of the library. the source under here is what gets published to `npm`

`docs/lib` - contains the source code of the documentation website, including all the example charts in the documentation

**Comment by PhilTheAir** [comment]
Since the demo is not opensource, will you please give us a little bit hint on how to implement this demo, say how to switch between different series, is it like using d3-shape to render this kind of switch?
