### ISSUE TITLE
is svg support really necessary?

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#103]
I am thinking of removing `svg` support completely in a future version,

Benefits:

1. smaller library size, because all code related to svg will be removed
1. less testing time, possibly faster development of the library as no svg related code to write or test

Drawbacks:

1. vector graphics mean ability to create resolution independent charts, so I could server render a chart with svg and create high resolution images
1. no server side rendering to svg, server side rendering to canvas is possible with node-canvas though I have never tested it myself
1. when developing new components I usually start with svg as it is easier to develop and troubleshoot, so development might become a little harder initially till we get used to developing with canvas first
1. doing interactive components on canvas is much more difficult, and needs to be explored if it is even possible with the current design

The main motivation behind this thought is that, in order to improve the performance on pan actions, there are some hacks in place for canvas, and these hacks are getting bigger and complex to deal with to support both svg and canvas. I think most users don't really care if it is svg or canvas, they care about performance and usability.

Thoughts?

**Comment by yinhm** [comment]
+1 for performance and faster development

**Comment by Svjard** [comment]
Server-side can be a bummer however SVG performance is definitely not created equal among the browsers especially mobile, so I actually like the idea of Canvas only. For drawback 1, it is still easy enough to do off-screen canvas render for a given size and canvas save to image is trivial compared to passing svg to the server to get an image. Plus for my Ng2 port currently composing components inside the svg namespace is not possible because of Shadow DOM and workaround is not forthcoming anytime soon, so Canvas makes it much easier.

**Comment by trevorbernard** [comment]
Right now I use SVG because over canvas because it's doesn't render well on retina screens

**Comment by WaiSiuKei** [comment]
How about seperating into two repo, one using `canvas`, and one using `SVG` ( or `react-native-svg` for `react-native` support)

just attached my demos FYI
[https://github.com/WaiSiuKei/nila](https://github.com/WaiSiuKei/nila)
[https://github.com/WaiSiuKei/react-native-nila](https://github.com/WaiSiuKei/react-native-nila)

**Comment by psunderr** [comment]
Developing on 4k monitor, canvas render is not very sharp compared to SVG, as @trevorbernard also experienced with retina display.

**Comment by rrag** [comment]
Thank you all for your input, SVG output may be sharp on high res monitors, but the responsiveness will not match canvas. There were some anti aliasing issues with canvas earlier which I think I have rectified in the work in progress 0.6 version. 
@trevorbernard  @psunderr 
Can you please check [this](http://rrag.github.io/react-stockcharts-next/documentation.html#/edge_coordinate) on a 4k monitor, retina screen please. Is this any better?

**Comment by psunderr** [comment]
I'm not sure I see a difference on 4k, it seems to render the same (though the stroke around bars/candles may give a slight impression of increased crispness)

**Comment by rrag** [comment]
RE: https://github.com/rrag/react-stockcharts/issues/119

@trevorbernard @psunderr
can you test this?

http://rrag.github.io/react-stockcharts-next/documentation.html#/macd

**Comment by rrag** [comment]
I am going to keep svg support for now. it is so easy to debug with svg

**Comment by itsjimbo** [comment]
https://github.com/Flipboard/react-canvas
Just thought I throw this out there..
I believe https://cryptowat.ch is built with react-canvas
