### ISSUE TITLE
There is no "HaikinAshi.js" in "src/lib/series" 

### ISSUE THREAD

**Issue by PhilTheAir** [rrag/react-stockcharts#104]
Just a kind reminder, there is no "HaikinAshi.js" in "src/lib/series" directory. But there is a customized file with the same name in the "docs/lib/chart" directory.

**Comment by rrag** [comment]
underlying chart of HaikinAshi is a a candlestick. just the open, high, low, close are derived. So if you look at `docs/lib/chart/HaikinAshi.jsx` you will see it uses `CandlestickSeries`
