### ISSUE TITLE
Publish 0.5

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#105]
Almost ready with 0.5, I already merged the code to `master`

Appreciate help in reviewing the docs and especially the change log section of 0.5

http://rrag.github.io/react-stockcharts-next/documentation.html#/change_log

I still have to add block, plunker for these charts

- intraday scales - continuous
- intraday scales - discontinuous
- volume profile
- volume profile by session

I am not planning to add blocks for bar, grouped bar, stacked bar, horizontal bar

**Comment by Jonwheeler** [comment]
What needs to be done to help get v0.5 released? I would to be able to use the intraday scales in a current project. What can I do to help?

**Comment by rrag** [comment]
@Jonwheeler I will be releasing it soon

If you can review the the documentation and changelog that would be very helpful.

**Comment by rrag** [comment]
published 0.5 to npm however, the newer plunkers are not working.

Logged an [issue](https://github.com/filearts/plunker_www/issues/90) with plunker
