### ISSUE TITLE
xScale as prop or contextType

### ISSUE THREAD

**Issue by jsleeuw** [rrag/react-stockcharts#107]
I'm looking to add a custom component as a child of a `Chart`. I want this custom component to have access to the xScale and yScale. yScale I am managing to pick up from context, but I'm having difficulty with x. Any pointers?

**Comment by rrag** [comment]
My recommendation is to use the `wrap` method like the other components like `CandlestickSeries` are using, that will give access to `xScale` as a prop.

I cannot think of a reason you want to avoid using `wrap`, but if you did, then add this to the `contextTypes`

```
xScale: React.PropTypes.func
```

**Comment by jsleeuw** [comment]
Had wondered about using `wrap`. Will give it a try tomorrow. Thanks Ragu!

**Comment by jsleeuw** [comment]
OK, both of the the methods you mention are returning an `xScale` function that works as expected. What I am finding though, and I should have mentioned this in my original question, is that the `xScale` returned when using an `xScaleProvider` is not behaving as expected and is returning coordinates that are way off.

**Comment by rrag** [comment]
did you do
```
xScale(xAccessor(d))
```

how did you get `d`

When using `xScaleProvider`, it converts discontinuous data into a continuous linear scale, so 

```
xAccessor(d) // will be an integer 0 to data.length - 1
```

**Comment by jsleeuw** [comment]
That did the trick. Thanks!!
