### ISSUE TITLE
Custom components

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#108]
Related to https://github.com/rrag/react-stockcharts/issues/103

I am exploring an alternative that supports both `svg` and `canvas` but also avoids the hacks in place to make canvas work fast. In doing this there could be changes to the components, and the `wrap` function, it could even be removed. However I do not anticipate changes to any charts.

So this change if successful, will result in breaking changes to anyone who has developed a custom component. I want to get a feeling of how many of you have developed or planning to build a custom component. If so would you consider making a PR to add that here to the repo?

**Comment by Pinxie** [comment]
Hello, well I did a Custom component (ScatterLineSeries) which mainly permits me to draw curves on discontinuous data, and data points of different shapes. I don't know if a similar series exists exists in 0.5 but a PR is possible. It draws only on canvas (no svg).

**Comment by rrag** [comment]
@Pinxie could you share it in an email may be. I would like to see if it can be replaced using a combination of existing `LineSeries` and `ScatterSeries` and may be a custom `XXXMarker`

**Comment by rrag** [comment]
here is a preview to a list of potential changes in 0.6

in `0.6` - 
https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartWithEdge.jsx

in `0.5` -
https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithEdge.jsx

### Changes

1. `CurrentCoordinate`, `MouseCoordinateX`, `MouseCoordinateY` no longer need a required prop `id`
1. `TooltipContainer` is removed, and the tooltips (`OHLCTooltip`, `MovingAverageTooltip`) are now moved inside the `Chart` relative to which you you specify the origin, so this makes the `forChart` prop on the different `XXXTooltip` unnecessary
1. `EventCapture` is removed, and you get event capture added by default

Please comment on how you like the changes

**Comment by rrag** [comment]
merged to master and `0.6.0-beta.2` published to npm
