### ISSUE TITLE
Understanding makeInteractive  in 0.5

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#109]
If I understand the changes correctly, the desired way to interact with a makeInteractive component is to pass in interactiveState, which is controlled by the component?

In the render method, the interactiveState is a property:
```
render() {
		var { enabled, endPointCircleFill, endPointCircleRadius } = this.props;
		var { xScale, chartConfig, plotData, xAccessor, interactiveState, show } = this.props;
               ...
```
https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/TrendLine.jsx#L266

Also defined as  a property Type
```
interactiveState: PropTypes.object,
```
https://github.com/rrag/react-stockcharts/blob/22fdff0298c50b690eb6a6d077f3feef92b81061/src/lib/interactive/TrendLine.jsx#L489

So if we are using trendline, and wanted to "load" in previously saved data (eg trends[] array), is interactiveState the best way to reflect that?
```
(pretend I have 2 lines that I have saved...)
var myTrends={trends: [{ start: [Ax1, Ay1], end: [Bx2, By2] }, { start: [Cx1, Cy1], end: [Cx2, Cy2] }]}

render(){
	                    <EventCapture mouseMove zoom pan>
					<TrendLine forChart={1} id={1} ref="trend"
						enabled={this.state.enableTrendLine}
						type="LINE"   
                                                interactiveState={myTrends}
						snap={true} snapTo={d => [d.high, d.low]}
						onStart={() => console.log("START")}
						onComplete={this.onTrendLineComplete}
						/>
				</EventCapture>
}
```

I am stumbling understanding the different usages of
* overrideInteractive
* state.interactiveState 
- props.interactiveState
- interactive
where they are applicable, seems like there were many changes

I guess just wondering is there a brief description out there about the rational, so I can understand it better?

**Comment by rrag** [comment]
To be honest, I have not thought about loading the chart with pre defined interactive state.

In `0.5` interactive components were heavily refactored to enable interactivity. I wanted to get a canvas version and also was not excited with moving them out of `Chart` into `EventCapture`. More importantly I did not like the `eventMeta`. But I was pressed for time and did not want to delay `0.5` so released it in this interim state. You would have seen the notes in change log about potential upcoming breaking changes in interactive indicators.

Let me try to explain how `makeInteractive` works, but keep in mind that this is only for `0.5`

`interactiveState` - is part of `EventHandler` like any other datapoint, but it is not part of the `state`. It is [mutable](https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventHandler.js#L58). That is the ideal place to set up any predefined interactivestate,

something like

```
this.interactiveState = [
  { chartId: 0, id: 0, interactive: { trends: [...] } },
  { chartId: 0, id: 1, interactive: { retracements: [...] } }
]
```

Let me think about any other way to provide pre defined trends without making changes to the library.

`makeInteractive` makes this `interactiveState` becomes a `prop` to the `TrendLine`.

https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/makeInteractive.jsx#L190
https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/makeInteractive.jsx#L153

But when you draw an indicator or move an existing indicator around, the value of the indicator changes, and this change is temporary, the `EventHandler` is bothered about the final states, not the interim transitional changes. These are stored as `state.interactiveState` in `makeInteractive`

Does this help?

**Comment by itsjimbo** [comment]
Yes thanks @rrag this does help a lot.  

> Let me think about any other way to provide pre defined trends without making changes to the library.

Going forward would appreciate any other suggestions or ideas you may recommend regarding this topic.

Ideally, passing in the trends as a prop is the easiest for developers to understand, but I don't think it would work in the current paradigm, without  of course mods to the lib
```
 <TrendLine
       trends={myTrends}
         ..
   />
``` 
What did you have in mind for 0.6 regarding interactive components?  I am trying to keep lock and step with the latest release, so just asking for any heads up...

**Comment by rrag** [comment]
> Ideally, passing in the trends as a prop is the easiest for developers to understand,

I agree, I will consider making this change for 0.6

for `0.6` I am thinking of moving `TrendLine` and other interactive indicators back inside `Chart` and supporting both canvas and svg. To support the current feature set of interactives on canvas the core has to be updated to be able to handle hit testing, and that also comes in quite handy for other things too, like for e.g. when you move hover over a `LineSeries` if you want to say change the color or width of the `LineSeries`, we can do that also.

**Comment by itsjimbo** [comment]
Just wanted to contribute a small plunkr about this for others, which to my understanding is the correct way to load in previous trends[]

https://plnkr.co/edit/e42l6Dk7NaHFHLS3PkIQ?p=info

**Comment by rrag** [comment]
this is a clever use of props to override the default behavior. Thanks for sharing. Please use this till a better solution comes out in `0.6`
