### ISSUE TITLE
How to add zoom-in and zoom-out buttons

### ISSUE THREAD

**Issue by pshashanka** [rrag/react-stockcharts#110]
I am trying to add zoom-in and zoom-out buttons. Clicking on it would zoom to currently selected element. Any thoughts on how I could achieve this?

**Comment by rrag** [comment]
update the `xExtents` to the values you want
```
<ChartCanvas ...
        seriesName=...
        ...
        xExtents={[new Date(2015, 0, 1), new Date(2015, 2, 1)]}>
```

What do you mean by

> currently selected element
