### ISSUE TITLE
Line, Area gradient option

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#111]
Hi Ragu, 

with gradient(area and lines) users available to create more informative charts

http://bl.ocks.org/d3noob/4433087

is it possible to add gradient options to 0.6 roadmap?

**Comment by rsklyar** [comment]
also, gradient options  for X,Y series - allow to create easy Charts for stress indicators.

**Comment by rrag** [comment]
can you explain how the gradient on line is useful? I get Area, but why line?

Also what do you mean by X,Y Series I am not sure I follow that

**Comment by rsklyar** [comment]
yep,
i'm trying to share with you new approaches and ideas for trader friendly interfaces: 
 for example:
 - with gradient on line you could prepare average daily trading only in line (When traders saw the line with g
<img width="639" alt="screen shot 2016-08-14 at 15 22 13" src="https://cloud.githubusercontent.com/assets/6270599/17649067/fc7c3822-6232-11e6-8db6-66dabc6419ca.png">
<img width="920" alt="screen shot 2016-08-14 at 15 20 20" src="https://cloud.githubusercontent.com/assets/6270599/17649068/0332837e-6233-11e6-800a-7ca4f6642d89.png">
<img width="451" alt="screen shot 2016-08-14 at 15 13 38" src="https://cloud.githubusercontent.com/assets/6270599/17649070/09cd2784-6233-11e6-8118-da8448dfd10b.png">
<img width="571" alt="screen shot 2016-08-14 at 15 10 47" src="https://cloud.githubusercontent.com/assets/6270599/17649071/183d1c0c-6233-11e6-9446-6bdad7b45f92.png">



radient, he understand that line is RED - trading volume is high.
- with gradient on line you could insert any analytics (for example custom stress indicator)
- with gradient on series XYScale you could insert analytics

**Comment by rrag** [comment]
oooh shiny. 👍

**Comment by Telemakhos** [comment]
Hi @rrag, what would be the quicker way to draw a gradient in the area fill? maybe with svg via css?

**Comment by gyss** [comment]
Any ETA for this?

**Comment by rrag** [comment]
@Telemakhos sorry for the delay, I don't know how I missed your question. Doing a gradient area should be simple via svg, but gradient line I have no idea right now. I would think just adding a `def` for a `lineargradient` and using that id for an area `path` might work. I can try to add an example

@gyss no ETA, right now planning on `0.6` presently

**Comment by Telemakhos** [comment]
Thanks for the pointers @rrag. I forked your repo an added a test ``` <linearGradient id="Gradient2">``` [here](https://github.com/Telemakhos/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L803-L806), then added a css selector with ```fill: url(#Gradient2)```. It should work but it seems like the new def is not rendered.

If I start Chrome Dev tools and explore the react-stockchart > svg > defs.. then that ```<linearGradient>``` is not present... If I edit the <defs> as HTML, and I add it directly from Chrome, then it works.

Do you know now if I am missing any step? I'm not sure if it is a caching problem with the clips/svg..

**Comment by rrag** [comment]
Glad it works, did you do a gradient for an area path or a line? just curious how to do that for a line like 

https://cloud.githubusercontent.com/assets/6270599/17649114/9010d434-6234-11e6-9595-06ae09e2655d.png

or

https://cloud.githubusercontent.com/assets/6270599/17649071/183d1c0c-6233-11e6-9446-6bdad7b45f92.png

**Comment by Telemakhos** [comment]
We used area path. It's a simple linear gradient with 2 stops and some opacity (our charts are dark), based on some examples from [Mozilla's docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients).  They look easy to parametrise via props.

Regarding gradients along line paths, apparently they're not that easy, albeit certainly possible. See http://stackoverflow.com/a/35739199/1193512

**Comment by Telemakhos** [comment]
FYI: https://unsplash.github.io/react-trend/

**Comment by rrag** [comment]
No plans to add this feature now
