### ISSUE TITLE
change the period of  EMA doesn't work

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#112]
![image](https://cloud.githubusercontent.com/assets/18010449/17401421/2f1d8f02-5a80-11e6-8702-99bbf65314bf.png)
![qq 20160804201707](https://cloud.githubusercontent.com/assets/18010449/17401544/d987ece4-5a80-11e6-995e-b88f57e45d6b.png)

**Comment by rrag** [comment]
http://plnkr.co/edit/u0FuAgh9gIfsnBXRRyer?p=preview

change the type from to svg and back to canvas. It seems to be working fine.
