### ISSUE TITLE
Annotation for empty graph

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#113]
for example data collection is empty (no trades for the first time) how should call annotation in  `<Chart>` and how should call with `<Chart>` for drawing only Axis.

**Comment by rrag** [comment]
you mean a chart with just x & y axis with no data? you need a data[] of size 2 at least to be able to draw a chart

**Comment by rsklyar** [comment]
@rrag yep, just a chart x & y axis, so if my data[] is empty, than better show only x&y axis, and tell user that no market data for now using annotation on `<Chart>`,  for now i should render another component with text props without x&y axis.

**Comment by rrag** [comment]
if you have an empty data[], then what would be the domain values of x and y axis?, if you have a length >= 2, then max and min values for x & y can be calculated and the axes will extend between those 2 values.

You could send a data[] with just x values and all the yValues be undefined, and in the `yExtents` of the chart, give a fixed domain. That would give you an empty chart. But that is all in your side of the code.
