### ISSUE TITLE
financial time scale defect

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#114]
<img width="495" alt="screen shot 2016-08-04 at 23 57 38" src="https://cloud.githubusercontent.com/assets/6270599/17418099/5dd65152-5a9f-11e6-82ee-45fe2c5fb8ea.png">

issue #73

**Comment by rrag** [comment]
could you explain why this is a defect? I do see the proper discontinuity.

**Comment by rsklyar** [comment]
there are no gap between PM and 07:05

**Comment by rsklyar** [comment]
there are no gap between PM and 07:05, maybe is it possible synhrone zoom interval with times scale interval ?

**Comment by rrag** [comment]
you could change the `ticks` prop to a lower number in `XAxis` and see how it behaves, the default if none specified is `10`.
