### ISSUE TITLE
Support `react-native`

### ISSUE THREAD

**Issue by filod** [rrag/react-stockcharts#116]
seems [victory](https://github.com/FormidableLabs/victory) has a consistent model which allow charts to run in both react & react-native.

i'm wondering if it's a good start for  react-stockcharts to support react-native?

**Comment by rrag** [comment]
Extending victory will be a huge undertaking, From a quick glance, there are many defaults in victory which I am not convinced are the right way to go about.

They also don't seem to support canvas, and provide the interactivity of zoom, pan, ability to calculate indicators.

I have not looked at react native yet, I would like to support that in the future, right now my priority is to get `0.6` out, so may be after that.

**Comment by rrag** [comment]
I would change the subject of this issue to support RN if you want to keep this open. There is no plan to extend victory

**Comment by WaiSiuKei** [comment]
`victory` is built on top of `svg` for `react` and they're developing a `react-native` version using `react-native-svg` ,  I thing the `svg` part of `react-stockcharts` is also good enough to support a `react-native` version, things to do are replacing tags and reducing features like transform, which are not working alike between `svg` and `react-native-svg`

**Comment by rrag** [comment]
@WaiSiuKei Thanks, I don't know anything about react native, so I have to ask this, there is no canvas support in RN ?

**Comment by WaiSiuKei** [comment]
The only one way I know is to manipulate a `webview` by injecting scripts in html string 
```
<WebView html={"<canvas></canvas><script>var canvas = document.querySelector('canvas');(" + renderString + ").call(" + contextString + ", canvas);</script>"} />
```
copied from the [react-native-canvas](https://github.com/lwansbrough/react-native-canvas/blob/master/Canvas.js#L26)

**Comment by hustcer** [comment]
Will [Preact](https://github.com/developit/preact) be better than `react`? 
Preact is a fast, 3kb alternative to React, with the same ES2015 API.

**Comment by rrag** [comment]
I don't have any plans right now to build a RN version. the current project by itself has been a huge undertaking, and I don't have the time or enough motivation to build a RN version.
