### ISSUE TITLE
show only one record when loading data with shorter length

### ISSUE THREAD

**Issue by yupan21** [rrag/react-stockcharts#117]
The chart sometimes show only one record when loading data from different data files in shorter length. 

I found one cause is that getFilteredResponse function in src\lib\scale\evaluator.js
 doesn't handle the case when the data length is shorter than the left position.

So I add codes below to handle the case and it works.
`if(data.length-1<left){
		var gap=right-left;
		newLeftIndex= gap>data.length?0:data.length-gap;
		return data.slice(newLeftIndex, data.length-1);
	}`

I'm wondering if it's the right place to enhance getFilteredResponse to fix the case, or should we handle the case by making left and right position correct at earlier code outside.

**Comment by rrag** [comment]
if you load data from different files, are you looking to basically reset the chart? If so you should also change the `seriesName`

```
<ChartCanvas width={...} height={...}
  ...
  seriesName="X"
  data={...}
```

when you change the `data []` completely, make sure to change the seriesName also, that will reset the chart and calculate new x, y domain values appropriate for that `data []`

**Comment by yupan21** [comment]
Yes, seriesName is what I want. Change back getFilteredResponse and use different seriesName. It works fine. Thank you！
