### ISSUE TITLE
X,Y scale text horizontal orient

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#118]
suggestion: add default props for X, Y scale orient= "horizontal, vertical" 
<img width="746" alt="screen shot 2016-08-13 at 00 04 56" src="https://cloud.githubusercontent.com/assets/6270599/17637046/b1f714e2-60e9-11e6-965d-fc00fe21c864.png">

**Comment by rrag** [comment]
will plan for 0.7

**Comment by iamstephenwang** [comment]
If we could even rotate the text say by 45%, that would be ideal.

**Comment by rrag** [comment]
any one interested in sending a PR?
