### ISSUE TITLE
Fuzzy rendering on 'retina' screens

### ISSUE THREAD

**Issue by stevesouth** [rrag/react-stockcharts#119]
When rendering canvas on 'retina' screens, you need to use the devices pixel ratio to increase the size of the canvas then resize down with css. 

See http://www.html5rocks.com/en/tutorials/canvas/hidpi/

Is this something that is already available in the library? I gave it a quick go myself but cant see an easy way to do it without digging into the code.

**Comment by rrag** [comment]
retina support is not there yet. I do not have a retina monitor, so I have never seen the issue myself. It is also not on the roadmap for 0.6 or 0.7.

Is it as simple as changing the dimensions and scaling it down with css, 
then after `context.scale(ratio, ratio);` drawing with original dimensions?

If you could sign up to work with me on this, and be open to testing it and providing feedback I can add this to 0.6

**Comment by stevesouth** [comment]
Sounds good. Any modern mobile device should highlight the issue too.

I'm not sure context.scale is always needed. If you draw with the larger size in mind, then simply scale with css that has always worked for me. Perhaps i'm missing something though.

**Comment by rrag** [comment]
could you please test this now?

http://rrag.github.io/react-stockcharts-next/documentation.html#/macd

I followed the reference you shared. It looks like it is fixed now

**Comment by stevesouth** [comment]
Looks good to me
