### ISSUE TITLE
negative fitWidth 

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#120]
<img width="537" alt="screen shot 2016-08-19 at 14 59 38" src="https://cloud.githubusercontent.com/assets/6270599/17809204/9cb3b28c-661d-11e6-8b47-ea7440298740.png">

when window resized, width could be negative.

**Comment by rrag** [comment]
resize would not reset a chart. This must be something else. more details would help.

**Comment by rsklyar** [comment]
reset chart - it  just after previous error - negative fitWidth return. 
maybe fitWidth should return 0, or null when argument is negative  ?
<img width="728" alt="screen shot 2016-08-21 at 21 12 22" src="https://cloud.githubusercontent.com/assets/6270599/17839026/ad614428-67e4-11e6-9581-453c34413704.png">

**Comment by rrag** [comment]
sorry, I need more details and steps to recreate. Preferably with a plunker

**Comment by JohnnyDoe404** [comment]
plunker:

http://plnkr.co/edit/gist:70ea3fe28ad35bf3ed4c?p=preview

screen shoot
<img width="1331" alt="screen shot 2016-08-29 at 02 40 57" src="https://cloud.githubusercontent.com/assets/21206232/18037645/116dbb88-6d92-11e6-8517-09353df39c52.png">

steps:
open plunker + console 
resize window

**Comment by rrag** [comment]
changing so the min width cannot below 25px

**Comment by neosavvy** [comment]
I'm having a lot of these errors as well and it's tough to determine the actual cause. 

Error: <rect> attribute height: A negative value is not valid. ("-14.979520187243963")
