### ISSUE TITLE
Chart breaks when panning it out to the left and zooming out repeatedly

### ISSUE THREAD

**Issue by stevesouth** [rrag/react-stockcharts#123]
Reproducible on the demo page.

http://rrag.github.io/react-stockcharts/

Scroll the chart as far out of view to the left as you can, then zoom out with the mouse cursor over to the right of the chart. Repeat and eventually the chart is empty as I think all X values end up being 0 (meaning you can't zoom in again as multiplying by 2 does nothing).

Is this a known issue? I can't seem to reproduce it here. How have you limited the panning / zooming?

http://rrag.github.io/stockcharts-demo/

**Comment by rrag** [comment]
the demo is almost 8 months old. was built with an older version `0.2`

I think, this new zoom issue must be introduced in `0.4` due to the finance scale rewrite. I am aware of the issue, but considered this as a lower priority and have not spent the time to investigate this

**Comment by stevesouth** [comment]
I would say it's high / critical as it's so easy to break the chart completely.

We tried to dig into the zooming code but it wasn't obvious where we should be looking for a fix. Do you have any ideas?

**Comment by rrag** [comment]
I pushed a fix, can you check if this fixes it?

http://rrag.github.io/react-stockcharts-next/documentation.html#/macd

**Comment by stevesouth** [comment]
I can't seem to break it, but I also can't work out the behaviour. It seems as though more bugs might be possible.

If you drag the chart all the way to the left or right it stops, I guess there is some sort of maximum distance you can drag data out of view which makes sense. I think this is how it should work.

However if you zoom in / out then try and drag it again you seem to be able to go further. If you keep doing this you can get close to the end but I didn't manage to break it this time.

How is the maximum drag distance meant to work?

**Comment by rrag** [comment]
the drag/zoom is limited by the number of data points displayed, it is restricted at 1 datapoint per pixel.

so if you zoom out and pan to the right, there might be a situation where you are trying to show say 100 datapoints in 99.5 px, so the pan would stop.

if you do this pan slowly, you could may be do more. Have to think through how to get the same consistent pan distance, it gets increasingly more difficult to debug when you show lot of data. and you pan real fast. So for now as I was not able to break it, I think this is a good solution.

**Comment by stevesouth** [comment]
To confirm, I can't seem to break it in the 0.6 beta 2.
