### ISSUE TITLE
offset for pan?

### ISSUE THREAD

**Issue by jsleeuw** [rrag/react-stockcharts#124]
I'd like to initialize a pan-enabled chart with an offset that would result in the last data point being rendered close to the middle of the ChartCanvas.

What would be the best way to go about doing this?

![screen shot 2016-08-22 at 12 53 13 pm](https://cloud.githubusercontent.com/assets/136064/17863380/76daaab0-6867-11e6-8eeb-ee00229f1a38.png)

**Comment by rrag** [comment]
I suggest you add more datapoints to your `data []` like for e.g if

```js
var data = [
{ date: "2016-01-01", close: 100 },
{ date: "2016-01-02", close: 101 },
...
...
{ date: <today date>, close: 130 },
{ date: <tomorrow date> },
{ date: <tomorrow date + 1> },
{ date: <tomorrow date + 2> },
{ date: <tomorrow date + 3> },
...
]
```

with the other values as `undefined`. If you are working with a discontinuous scale data, make sure to skip weekends, or non trading hours.

This should also give you x axis ticks beyond the last visible candle, and your mouse cursor can also go beyond the last candle.

I have not tried this myself, so let me know how this goes.

**Comment by jsleeuw** [comment]
I also arrived at this solution! Working well. Thanks!
