### ISSUE TITLE
Problem with JSON with Plunker example

### ISSUE THREAD

**Issue by criles25** [rrag/react-stockcharts#126]
I'm trying to figure out what's wrong with this JSON data. Here is a plunker http://plnkr.co/edit/PuHefNtT8WBXYZlnbz3F?p=preview.

Thanks again.

**Comment by rrag** [comment]
> XMLHttpRequest cannot load http://charlesriley.co/api/v1/chart_info/get/th1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://run.plnkr.co' is therefore not allowed access.

**Comment by criles25** [comment]
Whoops, CORS is enabled now.

**Comment by rrag** [comment]
fixed http://plnkr.co/edit/7uJ3pxV0TydpZrM217HX?p=preview

**Comment by criles25** [comment]
Awesome! Cheers.
