### ISSUE TITLE
SyntaxError: Only one default export allowed per module.

### ISSUE THREAD

**Issue by ZachLiuGIS** [rrag/react-stockcharts#129]
I had this error when run `npm run watch`.

`
ERROR in ./src/lib/interactive/makeInteractive.jsx
Module build failed: SyntaxError: Only one default export allowed per module.

204 | export default makeInteractive;
`

**Comment by ZachLiuGIS** [comment]
I created a PR with single line.

**Comment by rrag** [comment]
Thank you
