### ISSUE TITLE
CandlestickSires (or other OHLC-sires) are not working with custom data format

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#131]
Hello! My input data looks like:
```javascript
[
  {
    "date":"2016-09-09T14:03:21.000Z",
    "forex.instrument.bid.10s.avg":1.1207925423728817,
    "forex.instrument.bid.10s.min":1.12027,
    "forex.instrument.bid.10s.max":0,
    "forex.instrument.bid.10s.open":0,
    "forex.instrument.bid.10s.close":0
  }
]
```
And I'm using yAccessor to convert it to OHLC-object, but there is no one candle on chart (no errors\warnings).

So, I've investigated this bug and there is some problems with [getWickData method](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.jsx#L178):

```javascript
var wickData = plotData
			.filter(d => isDefined(d.close))
```

For my data d.close is always undefined. I beilive we should use yAccessor to get that property:

```javascript
var wickData = plotData
			.filter(d => isDefined(yAccessor(d).close))
```

It should fix the problem. But I'm not shure how to fix **PointAndFigureSeries** [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/PointAndFigureSeries.jsx#L110) and [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/PointAndFigureSeries.jsx#L119)  because there is no yAccessor.

**Comment by rrag** [comment]
close?

**Comment by iNikNik** [comment]
@rrag can you take a look at PointAndFigureSeries, please? As I mentioned before - it seems like there is same problem:
```javascript
while (isNotDefined(anyBox)) {
		if (isDefined(plotData[j].close)) { // <--- here
			anyBox = plotData[j].boxes[0];
		}
		j++;
	}
```

```javascript
var columns = plotData
			.filter(d => isDefined(d.close)) // <--- and here
```

But I'm not shure how is PointAndFigureSeries working (there is no yAccessor prop, also indicator is used)

**Comment by rrag** [comment]
point and figure is not ohlc data, it uses ohlc to calculate the columns. it needs high/low or close only depending on the type of calculation method for each `x` or `o` 

https://github.com/rrag/react-stockcharts/blob/next/src/lib/indicator/algorithm/pointAndFigure.js#L82-L83
