### ISSUE TITLE
Update to d3 4.2.3

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#133]
I'm just wondering if v0.6 will ship with the latest d3, or is that breaking?  Seems like some of the api changed in v4

**Comment by rrag** [comment]
v4 is quite nice and offers some good gains for us due to its modular design. however v4 is a lot of changes so 0.6 will continue to use v3.

**Comment by rrag** [comment]
since I answered this, it was bugging me how big could it possibly be? not too big !!!

Need to revisit volume profile as the before and after results dont exactly match, but the rest was pretty smooth.

\o/

**Comment by rrag** [comment]
**using d3 v3:**
react-stockcharts.min.js + d3 v3 = 383,145 bytes
http://rrag.github.io/misc/withd3v3.html

**using d3 v4 modules:**
react-stockcharts.min.js + d3 v4 individual modules = 317,439 bytes
http://rrag.github.io/misc/withd3modules.html

\o/

**Comment by itsjimbo** [comment]
@rrag  👍  cheers and nicely done
