### ISSUE TITLE
getXExtents() - retrieve currently displayed xExtents values from ChartCanvas

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#135]
There are several examples of setting xExtents in the ChartCanvas, what is the best way of getting the currently displayed xExtents after a zoom or pan event?

**Comment by rrag** [comment]
```jsx
someOtherMethod() {
  this.refs.viz.getDataInfo()
}
...
render() {
  return <ChartCanvas ref="viz" ...>
    ...
  </ChartCanvas>
}
```

this is not working in the `next` branch, will fix it soon

Also I don't like the name `getDataInfo`, suggestions welcome

**Comment by rrag** [comment]
it is broken in master too. must have been broken since `0.5`

**Comment by rrag** [comment]
I can fix the getDataInfo to the `next` branch, will that help?

there are a few breaking changes in `next` all of which are not documented yet.

**Comment by itsjimbo** [comment]
Thanks @rrag it would help a lot
I believe I'm on 0.5-alpha version right now (before the major changes to the EventCapture happened in 0.5-release) 


1) In 0.6 are you reverting back to the 0.4 "style" of EventCapture?  Or did you happen to rethink/redesign that part?  

2) I am currently just trying to save the existing chart state as from my examples above, don't know if there was an example of load/save chart state, maybe others could benefit?

**Comment by rrag** [comment]
0.6 is where `EventHandler` is removed, and `EventCapture` is no longer exposed. there is no going back to 0.4 style, `EventCapture` needed to be removed as now events can be captured by dragging an axis too, so removing `EventCapture` helps avoid anyone misusing it.

Look at the different examples in the next branch, the changes are not that big really.

**Comment by itsjimbo** [comment]
That works..but I am having difficulty saving the exact position where the user left off in the chart, I should say updating the xExtents works but does not leave the padding/gutter saved.

-Sidenote: There maybe an opportunity to establish some common terminology about the items in the chart, which may help other developers...just a thought..

What is the gutter area (in purple) between the xExtents and the Axis called?  Is there a way thus far to get/set the value programmatically?

 (Rational would be utilizing react-stockcharts in a real-time charting application, the chart should update the position and "advance" the position through time)


![image](https://cloud.githubusercontent.com/assets/11524813/18844113/b33a2e20-83d0-11e6-99d0-c584d51e2f00.png)

**Comment by rrag** [comment]
well, there really is no name for the purple rectangle, I like gutter :)

Reading what you are interested in doing, you are pushing to do some advanced stuff, there are 2 suggestions I can think of

1. Add more data points, like mentioned [here](https://github.com/rrag/react-stockcharts/issues/124), this means you get xaxis ticks beyond the last candle, which I kind of like.

2. pre calculate the data, and its index for the discontinuous scale and use `xScale` (not `xScaleProvider`) and `xAccessor` and `displayXAccessor` props. This gives you complete control of the xScale and you have much more flexibility to show the size of the gutter.

I am using option 2 above in an advanced demo which I am building (at my own sweet and slow pace)

If you have some trouble figuring out how to do option 2, I can put up an example later when I find some time.

**Comment by rrag** [comment]
and one more thing, xExtents is the complete domain of the xscale, similarly yExtents in the complete y domain, it is not just the rectangle around the candles
