### ISSUE TITLE
Overlapping dates on x-axis

### ISSUE THREAD

**Issue by kayazinc** [rrag/react-stockcharts#137]
hi @rrag, I have similar issue to https://github.com/rrag/react-stockcharts/issues/85.

![crowded x-axis](https://cloud.githubusercontent.com/assets/19774010/18749155/17550b08-8108-11e6-8a34-fb090715c95d.PNG)
 
I am using v0.5.0 and ```discontinuousTimeScaleProvider``` for EOD data.

Please advise me?  Thanks.

**Comment by rrag** [comment]
```jsx
<XAxis axisAt="bottom" orient="bottom"/>
```

**Comment by kayazinc** [comment]
Thanks @rrag, perfect!

**Comment by mezafits** [comment]
Does that work with multiple charts on the same page? Because some of my charts are not respecting the 5 tick max. And some are.

**Comment by gldstrrbt** [comment]
@mezafits Any chance you found a solution?

I'm currently experiencing the same issue. Setting the ticks to 5 is not working for me. The dates are overlapping and exceeding the 5 tick max on zoom/pan.
