### ISSUE TITLE
AxisZoomCapture reset

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#138]
@rrag nice job on the new version and on AxisZoomCapture

In the next branch (0.6 pre release) would there be a way to reset the axis after a chart pan/zoom? 
Eg user may get "lost" in the chart after scaling the axis and want to reset the view back to "auto" scaling

**Comment by rrag** [comment]
Try this

```jsx
<ChartCanvas ...>
  <Chart id={0} yPan={true}...> //true is the default
  </Chart
  <Chart id={1} yPan={true}...>
...
  </Chart>
</ChartCanvas>
```

change the yPan to false and then back to true.

**Comment by itsjimbo** [comment]
Works as expected, although I have to call this.forceUpdate() to reflect the changes though...
should yPan be a candidate for reset?

https://github.com/rrag/react-stockcharts/blob/next/src/lib/ChartCanvas.jsx#L25-L27

**Comment by rrag** [comment]
> should yPan be a candidate for reset?

no, it should not do a reset, this is supposed to be a trivial change. I have to check what is going on

> For me it appears that the y-axis panning is not enabled until the user initiates the drag event on the y-axis, then panning up/down on the chart works

Yes that is correct, did you want this to be enabled by default?

**Comment by itsjimbo** [comment]
> Yes that is correct, did you want this to be enabled by default?

That's fine, just making sure it was the expected behavior, I actually prefer it that way so the initial drag event is mainly on independent axis, less of a chance of getting "lost" by accidental dragging..

**Comment by itsjimbo** [comment]
Also, forgot to ask for the ability to "invert" the axis zoom, so that a drag-up event can be mapped to zoom-in (default currently appears to zoom-out)

**Comment by rrag** [comment]
try this.

https://github.com/rrag/react-stockcharts/blob/next/src/lib/axes/AxisZoomCapture.jsx#L66

```diff
- .map(d => d + sign(d - center) * diff);
+ .map(d => d - sign(d - center) * diff);
```

**Comment by rrag** [comment]
I thought the defaults were more intuitive. Why do you like it this way?

Then again I have never been a mac guy :(
