### ISSUE TITLE
x,y pan error (next)

### ISSUE THREAD

**Issue by JohnnyDoe404** [rrag/react-stockcharts#139]
<img width="1666" alt="screen shot 2016-09-26 at 15 17 00" src="https://cloud.githubusercontent.com/assets/21206232/18834215/5e037a9c-83fd-11e6-9315-5dd0c77da807.png">
<img width="862" alt="screen shot 2016-09-26 at 15 15 13" src="https://cloud.githubusercontent.com/assets/21206232/18834234/6cac81a6-83fd-11e6-94f8-55aeff659e19.png">

use the CandleStickChartForDiscontinuousIntraDay.jsx in my project

**Comment by JohnnyDoe404** [comment]
<img width="525" alt="screen shot 2016-09-26 at 17 53 33" src="https://cloud.githubusercontent.com/assets/21206232/18839061/50d6b388-8412-11e6-91de-00ab6ae6b656.png">
<img width="529" alt="screen shot 2016-09-26 at 17 54 20" src="https://cloud.githubusercontent.com/assets/21206232/18839071/58ff5cb8-8412-11e6-81db-9ece09d5f356.png">

not able to prepare plunker, have no idea what wrong

**Comment by rrag** [comment]
how are you building, webpack 2?
can you try with webpack 2 and with modules option on.

This could be because you are not using ES6 live bindings

https://github.com/d3/d3-selection/blob/master/README.md#event

**Comment by JohnnyDoe404** [comment]
looks like unable to use with meteor ES6 etc

maybe rect-stockcharts should use  event.preventDefault etc  instead native pageX,Y?

**Comment by rrag** [comment]
sorry, not following. are you saying webpack 2 is not compatible with meteor es6?

I will try later to use the d3 v4 bundle instead of using individual d3 modules. may be that could solve this problem when you do not use  webpack 2. But I need to know if not using webpack 2 is the problem first.

**Comment by JohnnyDoe404** [comment]
@rrag i don't using webpack 2

**Comment by rrag** [comment]
> can you try with webpack 2 and with modules option on.

**Comment by JohnnyDoe404** [comment]
@rrag sorry, not for this project

**Comment by rrag** [comment]
I don't think this will not be a problem for the npm built version, since you are using from source you have to use the live bindlings of es6 modules, like explained in the d3 docs.

**Comment by rsklyar** [comment]
same problem with meteor app (npm built version with ES6)
