### ISSUE TITLE
OHLC Charts

### ISSUE THREAD

**Issue by fxcebx** [rrag/react-stockcharts#14]
do you support OHLC charts?

**Comment by rrag** [comment]
Not yet. I did not think it is very useful since candle stick does the same data points. It should be easy to add though.

**Comment by rrag** [comment]
Just wondering why do you prefer OHLC to candlestick, any insight on how widely it is used will help prioritize this for me.

**Comment by rrag** [comment]
I do not plan to implement this for now. Welcome a PR if you feel this is useful
