### ISSUE TITLE
What is a recommended way to add color coded labels?

### ISSUE THREAD

**Issue by ontofractal** [rrag/react-stockcharts#140]
For example, if I have two line Chart components inside single ChartCanvas, how do I label different line charts with respective colors and names?

![chart_example](https://cloud.githubusercontent.com/assets/4211840/18836340/3d3236ae-8408-11e6-9906-96536d8c93b9.png)

I want to do something similar to the "long" and "short" labels on the attached image.

**Comment by rrag** [comment]
you could use the `SingleValueTooltip` and provide the `labelStroke` and/or `valueStroke` prop.

If you want what you have shown, like a filled circle and a text next to it, You could simple add the svg element inside the `Chart`, the ones on the top right are static, and do not change on mouse move, so use svg for that

**Comment by ontofractal** [comment]
Tried to use labelStroke/valueStroke but it wasn't perfect so I ended up just using svg, thanks for the suggestion!
