### ISSUE TITLE
Question: adjusting column width

### ISSUE THREAD

**Issue by timhwang21** [rrag/react-stockcharts#142]
Hello, I am trying to construct a bar chart with one month's worth of data (dates on x axis). However, the bars are being made too wide. I've looked through the props and various components, but can't find any way to adjust column width. Is this possible? Or is width always automatically calculated based on number of bars?

Here is a picture of what my chart currently looks like. As the crosshair shows, the bars currently overlap each other.

![screen shot 2016-09-28 at 4 11 47 pm](https://cloud.githubusercontent.com/assets/5831434/18930516/5511a9b4-8596-11e6-8b6b-b44a9d9445ea.png)

I'm new to SVG and charting libraries as a whole, maybe I am missing something obvious. Any help would be greatly appreciated. Thanks!

**Comment by rrag** [comment]
are you using a `d3.time.scale()` ?

Share the dataset so I can see what is going on.

The bar width is calculated as [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/StackedBarSeries.jsx#L177-L179). This calculation is perfect for bars which are spaced evenly, but looking at your chart it appears your data is not continuous.

**Comment by timhwang21** [comment]
Thanks for the quick response. I am indeed using `d3.time.scale()`.

I'm just working with mock data right now, but my data will not necessarily be contiguous:

```javascript
let TEST_DATA = [ // this will have 14 items going back 14 days
	{
		yesterday_spend_actual: 2030,
		yesterday_spend_expected: 2830,
		date: "2016-05-01T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2130,
		yesterday_spend_expected: 2830,
		date: "2016-05-02T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2230,
		yesterday_spend_expected: 2830,
		date: "2016-05-03T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2330,
		yesterday_spend_expected: 2830,
		date: "2016-05-05T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2430,
		yesterday_spend_expected: 2830,
		date: "2016-05-06T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2530,
		yesterday_spend_expected: 2830,
		date: "2016-05-07T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2630,
		yesterday_spend_expected: 2830,
		date: "2016-05-08T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 7330,
		yesterday_spend_expected: 2830,
		date: "2016-05-09T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 5330,
		yesterday_spend_expected: 2830,
		date: "2016-05-10T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 3330,
		yesterday_spend_expected: 2830,
		date: "2016-05-11T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 2630,
		yesterday_spend_expected: 2830,
		date: "2016-05-12T04:00:00.000Z",
	}, {
		yesterday_spend_actual: 3430,
		yesterday_spend_expected: 2830,
		date: "2016-05-30T04:00:00.000Z",
	}
];
```

In my use case, the x-axis will always be a 1 month range, but the amount of elements in the data array could be anywhere from zero to 31.

**Comment by rrag** [comment]
you would have to use a slightly modified version of `StackedBarSeries` where the width is calculated in a different manner. right now the width of each bar is 

width of chart / (length of the data [] - 1) * 0.5

try with a different formula in [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/StackedBarSeries.jsx#L177-L179) on the next branch

**Comment by timhwang21** [comment]
Will do, thanks with the response.

**Comment by timhwang21** [comment]
I ended up writing a function to calculate the desired `widthRatio` for `<BarSeries />` based on `xExtents`. Thanks!
