### ISSUE TITLE
next branch - 0.6 - forcibly set drawOnNextTick for GenericChartComponent to repaint

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#149]
I like the changes for generalization in GenericComponent and GenericChartComponent you have made.

I'm working on a component that is very similar to EdgeIndicator, except this bar moves in realtime.  It seems to work, and I prefer to use canvas instead of svg for performance reasons, but I am having trouble clearing the canvas without an event such as a mouse move or pan event.  
(screenshot below)

The canvas is not being cleared which stems from here...
https://github.com/rrag/react-stockcharts/blob/next/src/lib/GenericComponent.jsx#L58-L112

Any suggested way to forcibly drawOnNextTick so the canvas can repaint?

```

import { drawOnCanvas, renderSVG } from '../react-stockcharts/lib/coordinates/EdgeCoordinateV2'

class RealTimeEdgeIndicator extends Component {
...
// this class subscribes to a event listener, sets the state of the databar objectwhen
// a databar arrives at some moment in time 
// the databar has properties open,high,low,close,volume
dataListenerMethod(databar){
  this.setState({ databar} )
}

 drawOnCanvas(ctx, moreProps) {
    var {databar}=this.state
    var edge = helper(this.state,this.props, this.context, moreProps);
    var props = {
      ...this.props,
      ...edge,
    };

    // Draw an OHLC bar (really just a HL bar), but not part of the data set yet..
    if (databar)
    {
      var { xAccessor } = this.context;
      var { yAccessor} = this.props;
      var { xScale, chartConfig: { yScale }, plotData } = moreProps;
      var db=[yScale(databar.low),yScale(databar.high)]
      var item =  last(plotData, yAccessor)
      var xValue = xAccessor(item)+1
      var x1 = Math.round(xScale(xValue))
      
      ctx.strokeStyle = hexToRGBA("#0000FF", 0.8);
      ctx.beginPath();
      ctx.moveTo(x1, db[0]);
      ctx.lineTo(x1 , db[1]);
      ctx.closePath();
      ctx.stroke();
    }

    drawOnCanvas(ctx, props);
  }

render() {
    return <GenericChartComponent
      canvasToDraw={getAxisCanvas}
      canvasDraw={this.drawOnCanvas}
      svgDraw={this.renderSVG}
      clip={false}
      edgeClip={true}
      drawOnPan={true}
      drawOnMouseMove={true}
      debug={false}
    />;
  }

```

![image](https://cloud.githubusercontent.com/assets/11524813/18981599/a707fa9e-8694-11e6-9c5c-6a87659ec101.png)

When I move the mouse over/pan/zoom it renders it correctly...
![image](https://cloud.githubusercontent.com/assets/11524813/18981821/69dfebde-8696-11e6-85a8-420d48c55e41.png)

**Comment by rrag** [comment]
mouse over renders correctly? are you sure. you are drawing on the 
```
      canvasToDraw={getAxisCanvas}
```
 so only pan/zoom will fix clear and draw again

I was not sure if the new change will be easy to understand, and it might be too complex to debug. I am glad you find it easy. Appreciate any other feedback you have on the new refactor. In particular, I am interested in ways to

- avoid using context where possible
- avoid [this](https://github.com/rrag/react-stockcharts/blob/next/src/lib/utils/ChartDataUtil.js#L47-L48)

coming to your question

My suggestion is you do 

```jsx
class MyCustomChart extends Component {
// this class subscribes to a event listener, sets the state of the databar objectwhen
// a databar arrives at some moment in time 
// the databar has properties open,high,low,close,volume
dataListenerMethod(databar){
  this.setState({ databar} )
}
...
...
render() {
  return <ChartCanvas ...>
    <Chart ...>
      <RealTimeEdgeIndicator data={this.state.databar} />
    </Chart>
    <Chart ...></Chart>
    <Chart ...></Chart>
    <CrossHairCursor />
  </ChartCanvas>
}
}
```

and in `RealTimeEdgeIndicator.js`

```diff
-// this class subscribes to a event listener, sets the state of the databar objectwhen
-// a databar arrives at some moment in time 
-// the databar has properties open,high,low,close,volume
-dataListenerMethod(databar){
-  this.setState({ databar} )
-}

...

 drawOnCanvas(ctx, moreProps) {
-   var {databar}=this.state
+   var {databar}=this.props
-   var edge = helper(this.state,this.props, this.context, moreProps);
+   var edge = helper(this.props, this.context, moreProps);

```

**Comment by rrag** [comment]
now when you do the above you will end up running all the calculators and calculating the index for the `discontinuousScaleProvider`, for every update. If you have a lot of data this will introduce some lag. so you should precalculate the index and the data.

Example of how to do that is [here](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L146) moves a bunch of code to user land and hence avoids the calculation on every update

would love to hear any suggestions for this too

**Comment by itsjimbo** [comment]
Thanks that probably will work well, moving the state up the chain and trading state for props is usually better.

In the meantime I had fixed my problem with a hackish clearRect before drawing..
```
ctx.clearRect(0, 0, ctx.canvas.width,  ctx.canvas.height);
```

Have you noticed any performance problems with the examples if you are putting everything on the state (calculators and such..)?  My concern is that if some property on the state changes (unrelated to the chart even), it will trigger an entire state change, and recalculate/redraw will take place, then you are left with the ubiquitous shouldComponentUpdate() method to try and gain some performance..

I was trying to separate some concerns and some state wherever possible

FYI I am testing react-stockcharts for 5 monitors with 8x8 charts = 320 charts for performance testing, and the latest version is handling things quite well to my surprise

**Comment by rrag** [comment]
> 2) Have you noticed any performance problems with the examples if you are putting everything on the state (calculators and such..)? 

I did have a performance problem for a chart with fairly large data set about 50,000 rows, and I was building a chart resize functionality. Where say you have 3 charts

1. main chart with candles
2. rsi
3. macd

I could drag the bottom of 1 to increase the height of 1 and decrease the height of 2 at the same time.

When I was implementing this feature, since I was testing it with a large data set, it was calculating the index with the `discontinuousTimeScaleProvider` for every mousedrag event during the resize. So once I figured out the problem I went on to pre calculating the index, and the calculators, and put that in state. This made the resize quite smooth. So once you pre-calculate the indicators and the index, there is nothing of import happening in the `ChartCanvas` so it happens to be fast

> FYI I am testing react-stockcharts for 5 monitors with 8x8 charts = 320 charts for performance testing, and the latest version is handling things quite well to my surprise

wow, 320 charts is serious.

If possible I would appreciate if you can give me a private demo of what you have done.

It would be great to get a testimony on the README to showcase your experience, and name the website/company using it (if you don't mind that is)
