### ISSUE TITLE
Meteor Application using a latest availeble version of React 0.1.13(for meteor) than react-stockcharts will error out

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#15]
TypeError: Cannot read property 'findDOMNode' of undefined
    at componentDidMount (react-stockcharts.js?:9904)

**Comment by rrag** [comment]
`v0.2.2` depends on react `0.14.0-rc1`
https://github.com/rrag/react-stockcharts/blob/master/package.json#L15-L16

**Comment by rrag** [comment]
published 0.2.3 on npm to address this and https://github.com/rrag/react-stockcharts/issues/12

**Comment by laomouzi** [comment]
This problem is back for v0.3.1 and react 0.14.3?
