### ISSUE TITLE
Error when panning

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#150]
<img width="1540" alt="screen shot 2016-10-03 at 17 10 12" src="https://cloud.githubusercontent.com/assets/6270599/19040433/179dc06a-8995-11e6-9e76-202141b317bd.png">

**Comment by rrag** [comment]
there is nothing react-stockcharts related in the stacktrace.

While I appreciate the logging of defects, It would be a huge time saver with an accompanying gist/plunker, or at least some steps to recreate.

Without these I am afraid I will have to close this defect due to lack of information.

**Comment by rsklyar** [comment]
i woul like to share with you dataset and component (.jsx file)
