### ISSUE TITLE
Pan limits

### ISSUE THREAD

**Issue by moon47usaco** [rrag/react-stockcharts#151]
Can you set the limit of the pan so that it does not go past the chart data or only goes past by a defined value? Currently in the Zoom & Pan demo ( http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan ) you can pan right past all the data leaving a blank chart.

Is there a way to limit the amount it can go past the last data point and set it to not ever go before the first data point?

Say 10-20 bars past the last bar and never before the first bar.

**Comment by rrag** [comment]
dupe of https://github.com/rrag/react-stockcharts/issues/123 fixed in `next` branch

The pan/zoom limit is not configurable. You need a minimum of 2 datapoints on a chart, so you cannot go before the first 2, and go after the last 2

**Comment by khaphannm** [comment]
@moon47usaco did u come up with a solution for that ?
