### ISSUE TITLE
mouseXY

### ISSUE THREAD

**Issue by jsleeuw** [rrag/react-stockcharts#152]
Is there anything particular that I need to do to have passed to my component as a prop? I'm looking at other components for guidance, `MouseCoordinateX `, for example, but no go. Any pointers?

**Comment by rrag** [comment]
Can you explain what you are looking for? I read the issue 3 times and I have no clue what you are asking.

**Comment by jsleeuw** [comment]
Yeah, sorry for not making myself very clear there. I'd like my component to have knowledge of the mouseXY coordinates

**Comment by rrag** [comment]
in the `next` branch (`0.6 beta`), `MouseCoordinateX` and `MouseCoordinateY` are good examples.
