### ISSUE TITLE
Flicker when updating data during pan / zoom

### ISSUE THREAD

**Issue by stevesouth** [rrag/react-stockcharts#153]
0.6 beta 2

I don't think this happened with the previous version. To reproduce:

1) Have some realtime data streaming into the chart
2) Mouse down and pan the chart slowly
3) Every now and again the data will flicker. It seems to temporarily revert back to its point at the start of the pan.

**Comment by rrag** [comment]
Yup, bug in 0.6, thanks for reporting

**Comment by rrag** [comment]
not published yet, but it is fixed on master. Feedback please
