### ISSUE TITLE
Manually appending data - value undefined in discontinuousTimeScaleProviderBuilder

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#154]
Trying to manually append some data, and update the indexes, most of the examples include an array that is already indexed.  
For this situation, assume data is on the state (large array) and append() is called with some small array to be appended to it.

```

const indexAccessor = d => d.idx
const dateAccessor= d=> d.date

function append(newData)
{
       var {data:oldData}=this.state
        var lastIndex = indexAccessor(last(oldData)).index
        var lastDate = dateAccessor(last(oldData))
        //filter to avoid any overlap in case of duplicates, our data provider may be goofy
        var filtered=newData.filter((v)=>v.date>=lastDate)
        var indexCalculator = discontinuousTimeScaleProviderBuilder().initialIndex(Math.ceil(lastIndex)).indexCalculator();
        var { index, interval } = indexCalculator(filtered);
        filtered.map((each,idx)=>{
          each.idx=index[idx]
        })
        oldData=oldData.concat(filtered);
        /* you can update calculators here ... */

        /* at this point our data should be good enough to display */
        this.setState({data:oldData})

}
```

Throws the following error, which I am not sure why... I see there is a "For Renko/p&f" comment there, not really sure what this is all about, or is there a completely better way?

https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/discontinuousTimeScaleProvider.js#L146

```
discontinuousTimeScaleProvider.js:202 Uncaught TypeError:
 Cannot read property 'value' of undefined(anonymous function) @ 

discontinuousTimeScaleProvider.js:202componentWillReceiveProps @ MyChart.js?f9bd:111proxiedMethod @

```

**Comment by itsjimbo** [comment]
I think i figured it out, based on your example [here](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartPanToLoadMore.jsx)

```
function append(newData)
{
        var {data:oldData, xScale}=this.state
        var {xstart, xend}=xScale.domain()
        var lastDate = dateAccessor(last(oldData))
        var filtered = newData.filter((v)=>v.date >= lastDate)
        var dataToCalculate = oldData.concat(filtered.slice(1))
 
        var indexCalculator = discontinuousTimeScaleProviderBuilder().indexCalculator();
        var { index, interval } = indexCalculator(dataToCalculate);
        var xScaleProvider = discontinuousTimeScaleProviderBuilder()
          .initialIndex(Math.ceil(xstart))
          .withIndex(index)
          .withInterval(interval);

        var { data: freshData, xScale, xAccessor, displayXAccessor } = xScaleProvider(dataToCalculate)

        this.setState({
          data: freshData,
          xScale,
          xAccessor,
          displayXAccessor,
        });


}
```

**Comment by rrag** [comment]
glad you were able to figure this out, I did not get time to look at this yesterday.

I think there is further optimization that can be made in 

https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L124

we dont need to recalculate the index that is already calculated, I will update the example soon

**Comment by itsjimbo** [comment]
There may be a problem, but haven't had a chance to look at why...
When initialIndex is 0, then everything works fine, when it is set to a value other than 0 it throws a 
```
financeDiscontinuousScale.js:85 Uncaught TypeError: Cannot read property 'level' of undefined
```
Here is some code, with initial index set to 1, and inputData is an array of 862 elements [0-861]
```
let inputData=[....]
let initialIndex=1
let indexCalculator = discontinuousTimeScaleProviderBuilder().initialIndex(initialIndex).indexCalculator();

let { index, interval } = indexCalculator(inputData);
let xScaleProvider = discontinuousTimeScaleProviderBuilder()
      .withIndex(index)
      .withInterval(interval);
    
  let { data: linearData, xScale, xAccessor, displayXAccessor} = xScaleProvider(inputData)
  ...
```

The result shows end==862, and index[].length==862, the last element is at position 861, not 862

![image](https://cloud.githubusercontent.com/assets/11524813/21422790/4bb362a0-c7ee-11e6-9ada-19ba58912687.png)


How can someone set the discontinuousTimeScaleProviderBuilder intialIndex then?  (Eg I want my 
index to start at 1000 and go to 1861)

**Comment by rrag** [comment]
using partial indexes causes some other problems, say you pan to load only one more candle, then I dont have enough information to find if that is start of week/start of month/quarter/year etc. so for that reason the index has to be calculated for more than the data that has to be downloaded, this is how it is shown in the example also
