### ISSUE TITLE
Unable to add tooltip and clickcallbackhandler

### ISSUE THREAD

**Issue by pshashanka** [rrag/react-stockcharts#156]
TypeError: chartConfig.filter is not a function at makeInteractive.js:118

http://plnkr.co/edit/5PHy6WkjwgyLtjjMwcHr?p=preview is working.

But I tried to use same in 0.5 version, it throws error

componentWillReceiveProps	@	makeInteractive.js:118
componentWillMount	@	makeInteractive.js:99
(anonymous function)	@	ReactCompositeComponent.js:347
measureLifeCyclePerf	@	ReactCompositeComponent.js:74
performInitialMount	@	

Any suggestion why chartConfig is null.

**Comment by rrag** [comment]
the plunker you shared is.

There are breaking changes from 0.5 to 0.6, there is no `makeInteractive` in 0.6
