### ISSUE TITLE
v0.6.0-beta.3  - mouse wheel zoom

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#158]
Anyone else having a potential problem with the wheel zoom?  Seems to be acting wonky.
The previous version used in the demo [here](http://rrag.github.io/react-stockcharts/) works fine though

**Comment by itsjimbo** [comment]
It could just be a OSX update to Sierra + Logitech + Chrome issue though

**Comment by rrag** [comment]
http://rrag.github.io/react-stockcharts/ is not the prev version, it is 0.6-beta.5 right now.

Can you explain what the problem is.

**Comment by itsjimbo** [comment]
On the Demo at http://rrag.github.io/react-stockcharts/  if you can mouse wheel zoom in all the way and then slowly zoom out at a constant speed, does it seem to zoom in again, then zoom out?
As I continue to zoom out, it becomes very choppy..maybe a video may help, I am not sure how else to explain the problem

**Comment by rrag** [comment]
well, the demo is old, like last touched in Dec 2015 old. I think it uses 0.3 or may be 0.2 I don't remember.

is this similar to #80 ?

could you try the suggestion in
https://github.com/rrag/react-stockcharts/issues/80#issuecomment-247501966

and let me know what it works. Unfortunately I don't have a mac.

**Comment by itsjimbo** [comment]
Nice 👍  Thanks @rrag for pointing me in the right direction!!

https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L437-L440

**Comment by rrag** [comment]
1.5 instead of 2 solves the wonkyness?

**Comment by itsjimbo** [comment]
Not really, just playing with values, this seems to smooth it out though
```
	    c = zoomDirection > 0 ? 1.1 : 0.9,
```

Was looking for an edge case that may make the calculation goto an unexpected value for the calculation, just need some time to review
```
cx + (x - cx) * c
```

**Comment by itsjimbo** [comment]
Thus far this seems to work very well for me with track pad and different mice, all LOGITECH, but has smooth scroll effect
```
        c = zoomDirection > 0 ? 1.1 : 0.9,
```

**Comment by itsjimbo** [comment]
So looking at  https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.jsx#L62
I am getting a  value of -0 for e.deltaY
This is what I believe is causing the jitter

```
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} 40
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} 35.9991455078125
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} 83.9990234375
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} 51.99951171875
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig: Object, _targetInst: ReactDOMComponent, _dispatchInstances: ReactDOMComponent, nativeEvent: WheelEvent, type: "wheel"…} -0
EventCapture.js:99 Proxy {dispatchConfig
```

**Comment by itsjimbo** [comment]
Can we add something like this?
https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.jsx#L58
```
if (zoom && this.focus && e.deltaY!==0) {
```

**Comment by rrag** [comment]
I don't like the name `zoomInertia`, it implies that if I zoom fast enough the zoom will continue even after the wheel scroll is complete. 

I prefer `zoomMultiplier`

and the calculation for c has to be

```diff
- c = zoomDirection > 0 ? 1 + zoomMultiplier : 1 - zoomMultiplier,
+ c = zoomDirection > 0 ? 1 * zoomMultiplier : 1 / zoomMultiplier,
```

with a default of `1.1`
```js
c = 1.1 // (when zoomDir > 0)
c = 0.90909 // when zoomDir < 0)
```

Mind sending a PR with those changes?

**Comment by itsjimbo** [comment]
Added PR https://github.com/rrag/react-stockcharts/pull/160
