### ISSUE TITLE
v0.6.0-beta.3 - Suggest to Add state to zoom event in ChartCanvas

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#159]
Just wondering as a suggestion to add state to zoom or other events, in the example below, an event is triggered when the last item becomes visible on "panend" event..
It would be nice to have this on "zoom" or even better a "zoomend" event...
The zoom event currently just provides the mouseXY,currentCharts,currentItem

```
  componentDidMount() {
    var {canvas}=this.refs
    canvas.subscribe('canvasWidget', (eventType,chartProps,e)=> {
      this.eventChange(eventType,chartProps,e)
    });
  }
```

```
  /**
   * zoom,mousemove,draw,mouseleave,mouseenter,pan,panend
   * @param eventType
   * @param chartProps
   * @param e
   */
  eventChange(eventType,chartProps,e)
  {
    var {lastItemVisible}=this.state
    if (!isDefined(chartProps))
      return;
    switch (eventType){
      case 'panend':{
        var visibility= (dateAccessor(last(chartProps.plotData)) === dateAccessor(last(this.props.data)))
        if (lastItemVisible !== visibility)
        {
          //signal a change when the last item (most recent) changes visiblity
         console.log("lastItemVisible?",visibility)
        }
        break;
      }
    }
  }

```

```
 <ChartCanvas
            ref="canvas"
            ratio={ratio} width={width} height={height} type={type}
            margin={margin}
...
```

**Comment by rrag** [comment]
Yes, I have been thinking about it too, that will eliminate the need to use `context` in the `XXXSeries` and `XXXTooltip`

**Comment by rrag** [comment]
this is a little more complex than I though, how about this

https://github.com/rrag/react-stockcharts/blob/42a1695f5649d72ffda6df7fab381fdc8c92d74a/src/lib/ChartCanvas.jsx#L594

```diff
-each.callback(type, props, e);
+each.callback(type, props, { ...this.state, fullData: this.fullData }, e);
```

Where we add state and fullData as the 3rd argument and move `e` to 4th ?

**Comment by itsjimbo** [comment]
That works for me! Easy enough, and it keeps parameters consistent..

**Comment by rrag** [comment]
changed my mind again, published beta-9 to npm now, state and fullData is now part of 2nd parameter, let me know how it goes

**Comment by rrag** [comment]
is this good. close?

**Comment by rrag** [comment]
Changed again to go with initial approach of using state as third param and event as 4th
