### ISSUE TITLE
How to use updating data

### ISSUE THREAD

**Issue by Luchanso** [rrag/react-stockcharts#16]
Hi, i don't know how to use http://rrag.github.io/react-stockcharts/documentation.html#/updating_data, maybe you can give live examples?

**Comment by Luchanso** [comment]
I found solution

**Comment by rrag** [comment]
Great. I missed to add the link to the example from that page. All examples are available 
http://rrag.github.io/react-stockcharts/documentation.html#/quick_start_examples
