### ISSUE TITLE
v0.6.0-beta.5 - Possibility to disable mouse events

### ISSUE THREAD

**Issue by canastro** [rrag/react-stockcharts#161]
**Problem:** At the moment is not possible to disable any of the mouse events.

**Suggestion:** I believe that the developer should be given the possibility to disable the zoom and drag to move the chart.

**Additional Request:** It would be nice that the developer could define the current zoom by passing in a parameter, this would allow to have `zoom in` and `zoom out` buttons next to the chart.

**Comment by rrag** [comment]
> It would be nice that the developer could define the current zoom by passing in a parameter

You can do that already using `xExtents` prop on `ChartCanvas`

**Comment by rrag** [comment]
Fixed via https://github.com/rrag/react-stockcharts/pull/164

published new beta version, install again as `npm i -S react-stockcharts@next`
