### ISSUE TITLE
Support passive event handlers for mouse/touch events

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#162]
Just to keep pace with the react team, maybe adding these options to the scroll/wheel listeners could boost performance..
https://github.com/facebook/react/issues/6436

**Comment by rrag** [comment]
I am using

`react` event listeners for mousemove, zoom, touch
`d3` event listeners for pan actions, drawing interactive indicators

`d3` event listeners also don't seem to support it yet

https://github.com/d3/d3-selection/blob/9c18dd488acc1c3b5582f069302ed3089edac032/src/selection/on.js#L70

for zoom which uses the mouse wheel listener, it has to be active listener so default action (which is page scroll) can be prevented. 

For the rest of the events I guess we can benefit from this once React and d3 starts to support it.
even then if I remove the `e.preventDefault()` for the [mousedown event](https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.jsx#L148) action, depending on how you drag the chart, it selects the chart, like when you click and drag on text to select. While it is definitely worth investigating when the dependencies support it, the initial impression I get is that this will not solve our need

**Comment by cj-clifton** [comment]
I'm getting this error in chrome when I scroll to zoom.
> Unable to preventDefault inside passive event listener due to target being treated as passive.
> 

I expect it to only zoom on the chart but it zooms and scrolls the page at the same time. 
Is there somewhere I need to make the listener active?

**Comment by jedrichards** [comment]
Same here.

**Comment by alexbom** [comment]
Same error in Chrome. I'm using nextjs.
