### ISSUE TITLE
Is there a way to limit chart zooming out?

### ISSUE THREAD

**Issue by rrki** [rrag/react-stockcharts#168]
When zooming out, can we have an option so the start/end bars are sticked with chart canvas's left boundary/right boundary? I just feel it'll make the chart pretty..

**Comment by rrag** [comment]
you mean like a clamp mode?

**Comment by rrki** [comment]
Yes, thanks!

**Comment by rrag** [comment]
added example http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan
