### ISSUE TITLE
10px white circle in OHLCTooltip

### ISSUE THREAD

**Issue by dianavermilya** [rrag/react-stockcharts#169]
I'm not sure what the goal was with this white circle in the OHLCTooltip?  It exists only in /v0.6.0-beta.7 and /v0.6.0-beta.6.
It is positioned right on top of the text, covering up part of the word "Date".  I had to hide it with CSS.
<img width="468" alt="screen shot 2016-11-15 at 2 16 11 pm" src="https://cloud.githubusercontent.com/assets/1463108/20319956/208e07be-ab3e-11e6-907b-c461f8b60a3e.png">

https://github.com/rrag/react-stockcharts/blob/v0.6.0-beta.7/src/lib/tooltip/OHLCTooltip.jsx#L61

**Comment by rrag** [comment]
my bad, will publish a new beta version removing it

**Comment by dianavermilya** [comment]
👍 Cool, thanks!

**Comment by XmelesX** [comment]
You can temporary fix this with css, for example:
circle {
dyslay: none;
}

**Comment by rrag** [comment]
published `0.6.0-beta.8` install latest as

`npm i -S react-stockcharts@next`
