### ISSUE TITLE
Kagi Transformation 

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#17]
ref="chartCanvas" - unavailable for Kagi Transformation 

TypeError: Cannot read property 'idx' of undefined (When try to update data (using update example ) )

**Comment by rrag** [comment]
where is this error message?
provide more details please and a plunker.

**Comment by rsklyar** [comment]
http://plnkr.co/edit/JMm2lgrzBgWnh3hkoTAR?p=preview

<img width="1680" alt="screen shot 2015-10-01 at 19 32 59" src="https://cloud.githubusercontent.com/assets/6270599/10226956/6d384412-6873-11e5-9ad7-08512d2f48f8.png">

**Comment by rrag** [comment]
that is a good one. What is happening is on each data push the chart is moved one period, but since Kagi data is non linear it is not able to keep up. This will happen for Renko and P&F too.

**Comment by rrag** [comment]
Fixed in 0.2.4 

Added working example also in http://rrag.github.io/react-stockcharts/documentation.html#/updating_data

**Comment by rsklyar** [comment]
Awesome! Thanks for your work!
