### ISSUE TITLE
Adding pre- post-market zone

### ISSUE THREAD

**Issue by XmelesX** [rrag/react-stockcharts#171]
There are "before-" and "after-market" sessions in the US stock market. And it will be good to mark it some color.
For example YAHOO chart:
![_2016-11-17_21-23-41](https://cloud.githubusercontent.com/assets/16750139/20402085/649aadca-ad0c-11e6-9617-3d553234bb5a.png)

name :   pre-market |    main session    | post-market
time:          to9:29     | from9:30 to15:59 | from16:00

You can base it as in VolumeProfileSeries
change: sessionStart: ({ d, i, plotData }) => d.idx.startOfMonth
to: sessionStart: ({ d, i, plotData }) => d.idx.startOfDay

**Comment by rrag** [comment]
how can I get free data for pre / post market trading for say the last 10 days? If you can PR some sample data I can implement this. I am thinking this can be accomplished with a new component.

**Comment by XmelesX** [comment]
SPY, time frame 1min, period 10days, pre/post market include, format JSON:
[spy_1min_10day.txt](https://github.com/rrag/react-stockcharts/files/602052/spy_1min_10day.txt)

**Comment by rrag** [comment]
and I can add this to the documentation right? please confirm that there is no legal implications for adding this data to the [data](https://github.com/rrag/react-stockcharts/tree/master/docs/data) folder

**Comment by XmelesX** [comment]
Yes, you can add this quotes to data folder, if you want.
And I mean to make more flexible configuration, for marking time zones on the chart. Not only pre/post market. For example to make two versions 
1) the Session time zone which is repeated each trading day, and you can set the color, transparency.
2) Configurable time zones are set where the period for discharge, and you can set the color, transparency.

**Comment by rrag** [comment]
No plans to add an example.

I am confident this is possible even now, but not readily apparent, any one interested in implementing an example and sharing a PR, show me your work in progress and I can guide you through any problems you may face

**Comment by sasha-id** [comment]
Hey @rrag, here's my implementation of Zone component, with configurable zones. I used plotData to calculate the boundaries, maybe there's a better way to do it. Feel free to refactor/use it in your project or as an example. Also SVG is not implemented since I'm not using it.

[Zone.js](https://gist.github.com/alex-klepa/23711382add03aa606e392f2d5f266ba)

Cheers, Alex

![Screen Shot 2020-05-20 at 12 27 58 AM](https://user-images.githubusercontent.com/1385751/82405030-cc9a6680-9a30-11ea-8597-643134fccce6.png)
