### ISSUE TITLE
does it support chart download/screenshot as an image?

### ISSUE THREAD

**Issue by li-huo** [rrag/react-stockcharts#173]
lots of the chart libraries support download feature. it is a good feature to add.

**Comment by shprink** [comment]
@rrag with canvas it will be easy but not sure about the svg version. Any idea?

**Comment by rrag** [comment]
@shprink thanks to package `save-svg-as-png` 👍 

@li-huo 
look at the green button on the top right http://rrag.github.io/react-stockcharts/documentation.html#/stochastic_oscillator

use it like [this](https://github.com/rrag/react-stockcharts/blob/d6952062d81fc514023b12cd2a937e4d0a70aa53/docs/lib/page/DarkThemePage.jsx#L28)

**Comment by li-huo** [comment]
i tried encode the svg chart into URI which serves as the source of an image. It works fine.

thanks save-svg-as-png works too.
