### ISSUE TITLE
Replace development console.log with deactivable output

### ISSUE THREAD

**Issue by dbrugne** [rrag/react-stockcharts#174]
Use for example https://github.com/visionmedia/debug.
Or simply wrap console.log in a function and test a global variable to allow output or not.

In a realtime data consumption scenario (few render/second), while developping, the actual console.log output of RSC could be very annoying and make diagnosis of other components harder.

**Comment by rrag** [comment]
Good idea, point taken

**Comment by rrag** [comment]
used `visionmedia/debug` for logging

to enable log set in the browser when in development mode
```
localStorage.debug = "react-stockcharts:*"
```

not published to `npm` yet.

**Comment by rrag** [comment]
`0.6.0-beta.9` published
