### ISSUE TITLE
CHART RESET triggers react-bootstrap modal to hide accidentally 

### ISSUE THREAD

**Issue by li-huo** [rrag/react-stockcharts#175]
i have a button to show a react-bootstrap modal, when the modal pops up, the stockchart is reset and triggers the modal to hide automatically. what is more interesting is the screen scrolls to the bottom automatically as well.

![image](https://cloud.githubusercontent.com/assets/17079439/20526435/028478e0-b0ff-11e6-8291-ed04819fad52.png)

**Comment by rrag** [comment]
not enough details here for me to help you. Post a working example.

**Comment by li-huo** [comment]
it turns out is irrelevant with react-stockchart.
