### ISSUE TITLE
Support draw custom icons in annotation?

### ISSUE THREAD

**Issue by CharlieChiu** [rrag/react-stockcharts#176]
For now I can only draw up down arrows on the candle sticks, could you please make it possible to draw custom icons(svg or static image)  in annotations so I can add more meaningful signals on the chart.Any support plan for this?Thanks!

**Comment by rrag** [comment]
https://github.com/rrag/react-stockcharts/blob/879f95cdeca50a87f184672a1492e5f8cbe8c288/docs/lib/charts/MovingAverageCrossOverAlgorithmV2.jsx#L116-L119

`SvgPathAnnotation` is just an example, you can create `MyOwnAwesomeAnnotation` and use that,

**Comment by CharlieChiu** [comment]
Thanks for the explanation!
