### ISSUE TITLE
v0.6.0-beta.9  - getPrevMoreProps() is breaking

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#177]
Just an FYI - this 
https://github.com/rrag/react-stockcharts/blob/master/src/lib/GenericComponent.jsx#L33

is breaking
https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/MouseLocationIndicator.jsx#L59

**Comment by rrag** [comment]
thanks for reporting.

(facepalm) this project needs automated tests, and I am getting bad at testing all edge cases manually.

Any suggestions for a project like this?

**Comment by itsjimbo** [comment]
We can start small maybe with jest and enzyme??
https://facebook.github.io/jest/docs/tutorial-react.html

**Comment by rrag** [comment]
how good is jest in dealing with emulating events? snapshot testing is good for svg initial render, but for canvas?

**Comment by itsjimbo** [comment]
I know with enzyme you can simulate events, but I am not an expert in any react+testing, so I am interested in what others might say...
Example https://github.com/airbnb/enzyme/issues/426

**Comment by rrag** [comment]
This is great, there are a few cases where I have to register events outside of react, for pan and interactive drawing. Will have to try this out soon

:+1:

**Comment by rrag** [comment]
fixed in `0.6.0-beta.10`
