### ISSUE TITLE
GenericComponent should include keyboard events?

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#178]
mouse-*, pan, zoom, draw events are being handled, what about keyboard events?  Just curious is this was intentional..

Alternative can be just to specify your keyboard event per component...

```
      constructor(props) {
		super(props);
		this.onKeyPress = this.onKeyPress.bind(this);
                ....
	}
	componentDidMount() {
		document.addEventListener("keyup", this.onKeyPress);
	}
	componentWillUnmount() {
		document.removeEventListener("keyup", this.onKeyPress);
	}
	onKeyPress(e) {
		...
	}
```

**Comment by rrag** [comment]
mouse*, pan, zoom are the events needed by the chart, keyboard events are not used by `ChartCanvas`

**Comment by itsjimbo** [comment]
Ok, then this is really not an issue, but more of a clarification, thank you!
