### ISSUE TITLE
Charts are non-responsive on the npm version

### ISSUE THREAD

**Issue by MaiaVictor** [rrag/react-stockcharts#180]
I've used `npm install react-stockcharts`, required it, copied the candlestick example and browserified. Opening the resulting HTML, I can see the chart, but it doesn't respond. I can't zoom or move it. There isn't even a crosshair...

**Comment by MaiaVictor** [comment]
The version on [the example](http://plnkr.co/edit/gist:b13b739458e65ff93f4a?p=preview) works fine if you adapt it to browserify, so it might be worth updating the npm release...

**Comment by rrag** [comment]
If I change the plunker version to use npm next it works

```diff
+<script type="text/javascript" src="//unpkg.com/react-stockcharts@next/dist/react-stockcharts.min.js"></script>
-<script type="text/javascript" src="//rrag.github.io/react-stockcharts/dist/react-stockcharts.min.js"></script>
```

so I am not sure what the issue is. any errors on the console you get when you zoom/pan?

**Comment by MaiaVictor** [comment]
That is really weird. The version I had from `npm` was at 5.0, whereas this is 6.0, right? I thought that was the issue. If you can't replicate, then who knows what happened. I'm in a real hurry right now, so I can't investigate further / build a minimal reproducible test right now. I guess we'll just have to disregard this question. I'm sorry. Thanks for the great lib, though.

**Comment by rrag** [comment]
oh all the examples are using 0.6 beta, there are breaking changes in 0.6 beta

you can get it via

```
npm install react-stockcharts@next
```
