### ISSUE TITLE
file in the dist : react-stockcharts.js   line--21974

### ISSUE THREAD

**Issue by YufJi** [rrag/react-stockcharts#182]
error: you write  the 'high' -> 'height'  !!!  please revise
Example:
var displayDate, open, high, low, close, volume;
displayDate = open = hight= low = close = volume = "n/a";

**Comment by rrag** [comment]
Thanks for the issue, will fix in next release

**Comment by rrag** [comment]
fixed in `0.6.0-beta.10`
