### ISSUE TITLE
this isn't a issue, i just wanna ask a question!

### ISSUE THREAD

**Issue by YufJi** [rrag/react-stockcharts#187]
1.Why do I have to give 2 initial data to chart ,it could  show kLine-chart.
2.If i give one intial data or no data  it will :Uncaught TypeError: Cannot read property 'value' of undefined.
I was using react to build a project, Look forward to your reply.

**Comment by rrag** [comment]
the `data []` is used to determine the x and y domains, and the ticks that have to be shown on the x and y axis. I need atleast 2 values to determine the max and min of x and y.  this is called `extents` in d3.

x and y extents are key to drawing a chart, so without them you will get errors

**Comment by YufJi** [comment]
thank your reply 


                                        ---YufJi
On 12/07/2016 01:39, Ragu Ramaswamy wrote:

the data [] is used to determine the x and y domains, and the ticks that have to be shown on the x and y axis. I need atleast 2 values to determine the max and min of x and y. this is called extents in d3.

x and y extents are key to drawing a chart, so without them you will get errors
