### ISSUE TITLE
HoverTooltip sizing bug in canvas mode

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#188]
Hello! I'm facing with wrong tooltip width calculation if my `x` label is too long:

![image](https://cloud.githubusercontent.com/assets/7679749/21049535/6e5a80bc-be26-11e6-88bd-ba537a4b09f6.png)

On image above `bgwidth` is adjusted: tooltip goes far away from vertical blue line, but bg is still same size, `PADDING` is `5`.

I believe we should calculate x label size same way with y label sizes. And I see no reason to use `bgwidth` when we're [drawing on the canvas](https://github.com/rrag/react-stockcharts/blob/master/src/lib/tooltip/HoverTooltip.jsx#L48-L49).

So, I'll make a PR with fix. Also there would be some tooltip `x` coord calculation improvements: if PADDING is 0 - tooltip will stick right to the vertical blue line:

![image](https://cloud.githubusercontent.com/assets/7679749/21049771/d0b3790c-be27-11e6-9729-f223ca6e1912.png)

**PS it's only fix for tooltip with yAccessor prop**

**Comment by rrag** [comment]
Thank you, how can we fix this for svg too?

**Comment by shprink** [comment]
it should also work on SVG with @iNikNik code #189. I think we can close

**Comment by iNikNik** [comment]
@rrag we're using props with svg mode... Maybe we should calculate svg bg size same way with canvas, I'm not shure.

**Comment by rrag** [comment]
Thanks @iNikNik i made a small change to get svg also use the same helper methods as canvas. This is fixed now

**Comment by iNikNik** [comment]
@rrag also I had little proposal https://github.com/rrag/react-stockcharts/pull/189#issuecomment-266029923 . Does it makes sense for you?
