### ISSUE TITLE
Having trouble getting example to run..

### ISSUE THREAD

**Issue by raptoria** [rrag/react-stockcharts#19]
I'm following the example, and trying to split up the code according to how it would look in my application, but I can't see anything.

here's a plunker of what I'm trying to do:
http://plnkr.co/edit/diQDOcNwz547R4hObWMG?p=preview

I am a n00b..please help!

**Comment by rrag** [comment]
I am not able to tell what you are trying to do here, but I fixed it 
http://plnkr.co/edit/sevddjiXhw7svUshbkZS?p=preview

Things I changed
1. changed the order of jsx file include in index.html to be Candlestick...jsx first then Pnl...jsx
2. changed CandleStickChartWithFullStochasticsIndicator.jsx to export the variable to window. so it is accessible to other files
3. changed PnlChart.jsx to use window.CandleStickChartWithFullStochasticsIndicator

I get a feeling you are trying to organize your project into multiple files, and are not able to import one file into another. If that is the problem you should use commonjs spec with webpack/browserify. There is also AMD, and other options, but I am not going there.

**Comment by raptoria** [comment]
thanks! That's exactly what I'm looking for.

**Comment by rrag** [comment]
I do recommend using 0.14 as the warning for using `withContext` is gone. but there should be no error when using 0.14 vs 0.13

here is a slightly modified example using 0.13
http://plnkr.co/edit/tVEhZE74JjOzMZm6QdiY?p=preview

**Comment by raptoria** [comment]
thanks so much!!
