### ISSUE TITLE
xExtents does not work in some cases

### ISSUE THREAD

**Issue by shprink** [rrag/react-stockcharts#191]
Hey @rrag, we would love to have your opinion on a bug we are having.

I reproduced it on this branch https://github.com/rrag/react-stockcharts/tree/bugDomain, run `npm run watch` and open `http://localhost:8080/documentation.html#/line_scatter`

 You will see that:

![image](https://cloud.githubusercontent.com/assets/1388706/21056079/5caaabfe-be34-11e6-86bc-1ee98a86ca7e.png)

note that the first point is 9.11am. the xExtents however start at 9am. 

```
const minDate = new Date(1480579255864); // Thu Dec 01 2016 09:00:55 GMT+0100
const maxDate = new Date(1480580777028); // Thu Dec 01 2016 09:26:17 GMT+0100
xExtents={[minDate, maxDate]}
```

The points before 9.11am are displayed as you can see if you drag the chart:

![dec-09-2016 17-26-48](https://cloud.githubusercontent.com/assets/1388706/21056199/e2bd2a46-be34-11e6-87da-13d3c6038a80.gif)

We found it that using `plotFull` props on ChartCanvas will work but is not performant when zooming.

Thanks for your help, it means a lot to us :)

CC @dbrugne

**Comment by iNikNik** [comment]
Maybe number of points from xExtents interval is more than a maximum amount of points that can be displayed? Take a look at [these lines](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/evaluator.js#L65-L73)

**Comment by rrag** [comment]
thanks @iNikNik it is possible

if it is due to that, the logs would tell, enable logs like

```
localStorage.debug = "react-stockcharts:*"
```

**Comment by shprink** [comment]
We are indeed in the case where there are too many points to display:

> Trying to show 1523 in 467px, I can show up to 840 in that width. Also FYI the entire chart width is 468px

We are going to think about a way to customize that number instead harcoding it.

**Comment by rrag** [comment]
what value `pointsPerPxThreshold` did you end up with for you app?

**Comment by iNikNik** [comment]
@rrag I'm using this PR too. On chart below `pointsPerPxThreshold = 6`:
![image](https://cloud.githubusercontent.com/assets/7679749/21148724/35fecdbc-c16a-11e6-99e5-c9847e72e67a.png)
...and about 7k points. It's pretty extreme amount, but looks very nice.
I believe we should use lower values with candles, but, anyway - @shprink big big thanks for this :+1:

**Comment by rrag** [comment]
wow that is a lot. but looks good.

pan actions fast?

I have been thinking a default of 3 is better

**Comment by iNikNik** [comment]
@rrag yep, pan is ok. Also - my chart is real-time with 1s update rate - and there is some lags during rerender. But I think it is ok. Usually, you never need this amount of points on a real-time chart)

**Comment by shprink** [comment]
For us the requirement is `pointsPerPxThreshold` = 4 maximum.

@iNikNik we also need live charts here and it works great too! 

I was wondering how you created the following: 

![image](https://cloud.githubusercontent.com/assets/1388706/21162063/bb846246-c18b-11e6-83ff-59168c1b12c1.png)

I have the same thing to do :P

**Comment by iNikNik** [comment]
@shprink It's not a part of the chart.. just html + css. For my purposes it is easier to customize for different chart types:
![image](https://cloud.githubusercontent.com/assets/7679749/21198622/110be804-c251-11e6-9beb-c795dcee3d8e.png)
![image](https://cloud.githubusercontent.com/assets/7679749/21198688/4fdd7f84-c251-11e6-9879-65f431683320.png)
