### ISSUE TITLE
First and last value rendering issue 

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#196]
Hello there! Unfortunately there is issue with first and last value: if you're using CandlestickSeries or even OHLCBarSeries you can see only half of the first and the last candle. Take a look at [second chart](http://rrag.github.io/react-stockcharts/documentation.html#/candlestick_chart)

![image](https://cloud.githubusercontent.com/assets/7679749/21352843/66a4067a-c6d4-11e6-859a-9189051a50b5.png)

Probably - in the most cases it is doesn't really matter, but I'm trying to implement this kind of chart:
![image](https://cloud.githubusercontent.com/assets/7679749/21352896/abd6b65c-c6d4-11e6-891f-dd3347b59724.png)

And as you see last bar (x = 500) draws like a line. With stockcharts 0.4 I've used a dirty hack:
```javascript
function overrideDomain(scale) {
  const overrideDomain = scale.domain
  scale.domain = x => {
    console.log('new domain');
    return x ? overrideDomain([x[0] - 0.3, x[1] + 0.7]) : overrideDomain()
  }
  return scale
}

scale = overrideDomain(scale);
```

Because it allows to expand X axis. Any suggestions how to fix it (or hack it :smiley:) with 0.6 ?

**Comment by rrag** [comment]
good catch, in `0.5` you could have also done
```jsx
<CandlestickSeries ... clip={false} />
```

but in 0.6 this was missed. it is however easier to implement on your custom series though

```jsx
// your MarketComparisonSeries.jsx

<GenericChartComponent 
  clip={false} ... /> 
```

as for `CandlestickSeries` and all the other series, I don't have an answer yet, let me think about this.

**Comment by iNikNik** [comment]
@rrag thanks for tip: `clip={false}` with `padding={20}` fits good as a temporary solution for me:
![image](https://cloud.githubusercontent.com/assets/7679749/21358064/943b82b6-c6e8-11e6-8b43-011f73aefb42.png)
