### ISSUE TITLE
Fix build with Browserify

### ISSUE THREAD

**Issue by Arilas** [rrag/react-stockcharts#2]
There's an Error occurred, when you want to build lib with Browserify:
```
[Error: Cannot find module 'lib/utils/PureComponent' from '....../node_modules/react-stockcharts/lib']
```

In many files you use
```js
import PureComponent from 'lib/utils/PureComponent'
```
But should use relative paths (because Browserify try to find lib package):
```js
import PureComponent from './utils/PureComponent'
```

**Comment by rrag** [comment]
oops

I switched from relative to this because I found it easier to reason with and also webpack allowed me to :)

```
resolve: {
	root: [__dirname, path.join(__dirname, "src"), path.join(__dirname, "docs")],
```

Thanks for the issue. I will update with a fix.

**Comment by Arilas** [comment]
I've made fork for this, and makes some changes, there's also need to add extensions, because some files with ".js", some with ".jsx", and browserify have troubles with this.

**Comment by rrag** [comment]
I just saw your fork and compared the changes, I wonder why you need to add the `.js`, `.jsx` to the `import`

https://github.com/babel/babelify#customising-extensions

says the default extensions include `.js` and `.jsx`. I think the solution is to add the `browserify` node to `package.json` and play with the options there.

**Comment by ezeql** [comment]
Thanks Arias.

**Comment by rrag** [comment]
pushed a [fix](https://github.com/rrag/react-stockcharts/commit/53e23f4b5fe2efe131ae5381dcacf215cef15974) to master, but I am having trouble testing with `npm link`. and multiple React versions. If you have figured it out give it a try.

**Comment by rrag** [comment]
I verified the fix using browserify from a different project using `npm link` to this. Works. Reopen this if you still have an issue
