### ISSUE TITLE
[Discussion] Keep SVG type rendering in the future

### ISSUE THREAD

**Issue by poksme** [rrag/react-stockcharts#205]
Hello Ragu,

First thank you for such an amazing project.

I am currently writing an universal javascript app with rendering on both server and client side. (for those of you unfamiliar with the concept you can read about it [here](https://medium.com/@mjackson/universal-javascript-4761051b7ae9#.ibynox9oz))

At first I thought I will never use `svg` render type since it's slower but then I realised I could render my charts on the server using this feature.
When handing over the rendering to the client I switch to `hybrid` rendering type.

Using both rendering types depending on the environment I can get best of both worlds: a fully rendered HTML page coming from the server with great performance and interactivity on the client side.

So please, before removing `svg` module completely (see [roadmap](https://github.com/rrag/react-stockcharts/blob/master/docs/md/COMING-SOON.md#v08)), consider this use case of server-side rendering.

**Comment by rrag** [comment]
I agree server rendering with svg is a nice feature, not just for an universal app, but also for things like creating images to be sent in emails.

There has been a discussion earlier https://github.com/rrag/react-stockcharts/issues/103

Do you really have server rendered charts with svg, and then on client side switch to hybrid? What is the benefit you get by doing that?

**Comment by poksme** [comment]
Thank you for the link to the discussion I will definitely follow this thread.

Yes I have a project where this feature is enabled (not live yet). The benefit of server rendering is being able to send at least a _preview_ event if the user is surfing on a potato.

I was also considering _gray rendering_ on the server using shades of black and white and _colored rendering_ on the client to give a visual feedback to the user (gray when disabled/loading and colored when enabled).

Facebook does something similar with a light animation when loading articles, I believe it's way better than an empty page with a spinner
![gray rendering](https://cloud.githubusercontent.com/assets/1689983/22052129/b23eb864-dd8b-11e6-9ff0-7a06eff2c736.PNG)

Of course all these considerations make sense when using a cached rendered chart.

**Comment by rrag** [comment]
Closing this, we can continue the discussion here, or in the other issue.

I like canvas for performance but svg is hard to beat for ease of development, so I am myself biased to svg for a different reason. While I understand the benefits of svg right now I cannot make any guarantees on how the future of the library will shape.
