### ISSUE TITLE
Annotation output

### ISSUE THREAD

**Issue by jsleeuw** [rrag/react-stockcharts#207]
I'm looking to render items that will appear on top of a CandleStick chart at various positions along the x axis. It looks as though I may be able to accomplish this via Annotations, but I could also see a Scatter working, with a custom Marker. Annotation feels like a more natural fit, but it the drawing seems limited to paths, at least with `SvgPathAnnotation`. What might be the simplest way for me to render my own SVG output for an Annotation? 
<img width="315" alt="screen shot 2017-01-15 at 12 02 56 pm" src="https://cloud.githubusercontent.com/assets/136064/21964592/d0ea3afc-db1c-11e6-8761-0c85db29ce13.png">

**Comment by rrag** [comment]
ScatterSeries with custom marker is simpler, but if you go with the canvas version, there cannot be click events attached (atleast not yet). By using Annotate, and a custom path as an annotation you can draw any svg path you like and it could also have events attached to it.

**Comment by jsleeuw** [comment]
Very helpful, thanks! Have decided to go the Annotate route.
