### ISSUE TITLE
Canvas only GenericComponent disappears

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#211]
Hello!) I want to implement canvas-only version of some tooltip:
```javascript
class VisibleDataAggregationTooltip extends Component {
  constructor(props) {
    super(props)
    this.drawOnCanvas = this.drawOnCanvas.bind(this)
  }

  drawOnCanvas(ctx, moreProps) {
    drawOnCanvas(ctx, this.props, this.context, moreProps)
  }

  render() {
    return <GenericComponent
      canvasDraw={this.drawOnCanvas}
      clip={false}
      drawOnMouseMove
      drawOnPan
      drawOnMouseExitOfCanvas
    />
  }

}
````

So, I expect the tooltip will be visible all the time. But it is disappearing randomly when mouse leaves the canvas... 

![dissapearing-tooltip](https://cloud.githubusercontent.com/assets/7679749/22069847/ed4814c2-ddaa-11e6-930e-d07a6ede3840.gif)

**Comment by rrag** [comment]
are you trying this on master?

[this](https://github.com/rrag/react-stockcharts/commit/32afb4a094eb33d918faf7726ea03a290a5555fe#diff-41d1ada5dedd81b1cf87ba553bd67a67) must have addressed the inconsistency, so it is cleared everytime mouse exits. I think it was broken in 0.6 but fixed in 0.6.1

can you try this and see if that does not break anything and also addresses this?

```diff
handleMouseLeave(e) {
	this.clearMouseCanvasOnly();
	this.triggerEvent("mouseleave", { show: false }, e);
+	this.triggerEvent("draw")
}
```
https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L382-L385

But why tooltip on canvas? I mean, when I wanted a complete canvas version I was having html tooltip in mind. using `div/span`.

**Comment by iNikNik** [comment]
@rrag I've tested it on master - less frequently but still same issue.

> can you try this and see if that does not break anything and also addresses this?

Yep, this is fix.

> I was having html tooltip in mind. using div/span.

I'm preparing for server side rendering (canvas to png) in the future... so, I'm trying to use more canvas-only elements instead of svg\html.

**Comment by rrag** [comment]
> I'm preparing for server side rendering

why not do svg only?
https://github.com/rrag/react-stockcharts/tree/master/docs/lib/serverside

has an example I did a long time ago, might not be perfect now, but it can be fixed up.

Also out of curiosity, how would you know the height/width of a chart if you are doing server render? is it always a static dimenstions?

**Comment by iNikNik** [comment]
@rrag I do not render on the server Now, and, I believe, canvas has better performance. If so - I can:
1. have both canvas (for browser) and svg (for server) implementations
2. use only canvas components
3. ???

> Also out of curiosity, how would you know the height/width of a chart if you are doing server render

I my case I don't want to render it on server and then use it on the client (browser). I just need to provide an API that will allow to render chart to the png image for PDF-reports (or something similar):
```
GET /api/brokers/some-broker/eurusd/chart.png?height=123&width=456
```
And in the same time I want to keep my components as unversal as possible (same component for the webapp and server render)


I dont clearly figured out how to implement it with a stockcharts, but I think I can be done with https://github.com/Automattic/node-canvas . Probably I should create custom CanvasContainer and [provide canvas object here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/CanvasContainer.jsx#L14-L19)

**Comment by rrag** [comment]
you are on the right track, I would suggest you option 1.

canvas on browser and svg on server. but that means you have to create svg versions for all your custom components, if you have a lot of custom components it would not be trivial.

good luck, let me know what you decide.

**Comment by iNikNik** [comment]
> I would suggest you option 1.

What about roadmap and further versions? I saw for v0.8:

> Explore removal of svg mode & all svg components completely, so this becomes a canvas only library (Tentative)

**Comment by rrag** [comment]
that is still tentative :)

**Comment by rrag** [comment]
in the next branch I am working on creating canvas based interactive components, and I have done the changes suggested earlier there
