### ISSUE TITLE
Commercialization issues

### ISSUE THREAD

**Issue by gullyy** [rrag/react-stockcharts#212]
Can I take this piece of code and write my own customization on top of it and commercialize it?

**Comment by rrag** [comment]
Legally speaking, the project is MIT licence, which means I offer no warranty, and the code is provided ASIS, and if you choose to make changes and redistribute, it needs to contain a copy of the licence.

Personally, I would like a link back to the documentation site and a "powered by react-stockcharts" on your product, or a donation. But you are under no legal obligation to do that.
