### ISSUE TITLE
Demo on Github

### ISSUE THREAD

**Issue by m4w** [rrag/react-stockcharts#213]
Since your documentation is still work in progress, it would be great if you could add you demo src files to the github project. So one could read through the example code and create easier a project of his own.

**Comment by rrag** [comment]
Sorry the demo is not open source. Why do you say documentation is work in progress? I have spent significant time in maintaining the documentation, while there is always more that can be done I am wondering how you got that impression. Is there any where that mentions that?

**Comment by leedstyh** [comment]
Kind of OT, but I think listing all the props (with descriptions) of a Component would be helpful. 

This is a good example: http://www.material-ui.com/#/components/app-bar

**Comment by m4w** [comment]
The following is just a hint to improve your documentation. Its not about making your work bad or something. I think you do great stuff here. And I know its taking a lot of time. But I also think you want, that people use your stuff. In order to do that, you should not hesitate if you can improve something or if you get some usefull critik. 

The real stuff now:
I got the impression that the documentation is still in progress by looking at the chart Point & Figure or the chart Bubble Chart, there is only a graph in it. If you take the Area Chart for example, it looks like a real Area Chart documentation. You have a example, you have the props listed, you have the incomming data explained and you said something about customizing it.
And if you take a look on the Github Readme it says, Documentation - Getting Startet. If you click on it your are on you documentation page, but there is nothing about getting startet. There should be a short introduction (okay, that you migh have) and a short hello world example.

**Comment by rrag** [comment]
It is a valid critique. I agree with it. Documentation of props and default values is on the todo list, on the [roadmap](https://github.com/rrag/react-stockcharts/blob/master/docs/md/COMING-SOON.md) also

> Detailed documentation of each component and its props

I have so far been prioritizing api changes and adding new features over better documentation. I do however feel that the existing documentation is good enough, it gives the user just enough information, and the examples on plunker offer a playground, and for those interested in doing more customizations or something advanced, it is just one file for them to look at.

**Comment by leedstyh** [comment]
Sorry that forget to check the roadmap
