### ISSUE TITLE
port to vue.js?

### ISSUE THREAD

**Issue by chovy** [rrag/react-stockcharts#214]
Anyone know if this module could be ported to work with vue.js and what level of effort that would take?

**Comment by rrag** [comment]
I have not used vue so I have no suggestions to offer. I have been working on the react version in my free time for a little less than 2 years now, but that is not a port, and also not a full time gig.

If you end up porting this to vue and would like some common modules to be shared between both, we can discuss that.

Keeping this issue open for some time for others to provide their thoughts
