### ISSUE TITLE
how do I use the moving average?

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#218]
i have been trying to figure out how the moving average with line chart is working. so far i have created the line and all the components needed, added the sma20 like that : 
		var sma20 = sma()
			.windowSize(20)
			.sourcePath("close")
			.merge((d, c) => {d.sma20 = c;})
			.accessor(d => d.sma20);
currently i see no line or anything like that in the graph, so my question is, does the sma calculate the data by itself or is it a field i need to pass by myself in the data objects?

**Comment by rrag** [comment]
you will have to pass that `sma20` to the calculator, [this](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithMA.jsx#L68) example shows a few different moving averages and how they can all be plot on the same chart

**Comment by omryr** [comment]
so just to be sure because i didnt understand much from that example, 
			.merge((d, c) => {d.sma20 = c;})
			.accessor(d => d.sma20);
the d here is the data object? and if yes where does the .sma come from? and what is the c? (sry for the flod of questions )

**Comment by omryr** [comment]
ah nvm i just figured it out, thanks!

**Comment by rrag** [comment]
no worries, this
```
var sma20 = sma()
.windowSize(20)
.sourcePath("close")
.merge((d, c) => {d.sma20 = c;})
.accessor(d => d.sma20);
```

creates a function `sma20`, lets say you have

```
var data = [
 ...
 ...
  { date: ..., open: ..., high: ..., low: ..., close: ... },
  { date: ..., open: ..., high: ..., low: ..., close: ... },
  { date: ..., open: ..., high: ..., low: ..., close: ... },
  { date: ..., open: ..., high: ..., low: ..., close: ... },
  { date: ..., open: ..., high: ..., low: ..., close: ... },
]
```
you can do
```
console.log(sma20(data))
```

That will output
```
[
  ...
 ...
  { date: ..., open: ..., high: ..., low: ..., close: ..., sma20:... },
  { date: ..., open: ..., high: ..., low: ..., close: ..., sma20:... },
  { date: ..., open: ..., high: ..., low: ..., close: ..., sma20:... },
  { date: ..., open: ..., high: ..., low: ..., close: ..., sma20:... },
  { date: ..., open: ..., high: ..., low: ..., close: ..., sma20:... },
]
```

in this style you can have multiple functions `smaxx`, `emaxx` and these are just functions, they dont have data yet. sort of `pointfree` style where the behavior is defined as a function and data is passed as the final argument.
