### ISSUE TITLE
LineSeries interpolation

### ISSUE THREAD

**Issue by coffenbacher** [rrag/react-stockcharts#219]
My data is best visualized using "step" interpolation, I see LineSeries interpolation is in Coming-Soon.md! Any thoughts on how difficult this would be to implement or how it should be approached?

Here are the options I see available in d3:
https://coderwall.com/p/thtwbw/d3-js-interpolation-options

**Comment by rrag** [comment]
The logic to add all interpolations would go inside [`LineSeries.jsx`](https://github.com/rrag/react-stockcharts/blob/next/src/lib/series/LineSeries.jsx). Using these interpolation in d3 is like

```js
var line = d3.line()
  .curve(xxx)
  .x(function(d) { return x(d.date); })
  .y(function(d) { return y(d.close); })
```
where xxx is one of
```js
d3.curveLinear
d3.curveStep
d3.curveStepBefore
d3.curveStepAfter
d3.curveBasis
d3.curveCardinal
d3.curveMonotoneX
d3.curveCatmullRom
```

for svg
```
<path ... d={line(plotData}} ... />
```
for canvas
```
line.context(ctx)(plotData);
```

It does not look too complex, would you be interested in taking a stab at it and sending a PR. Please make sure you work on top of the `next` branch

Reference:
https://bl.ocks.org/d3noob/ced1b9b18bd8192d2c898884033b5529
https://github.com/d3/d3-shape

**Comment by rrag** [comment]
Writing this answer got me interested and I could not stop, and I made the [change](https://github.com/rrag/react-stockcharts/commit/c14484744069fb6a0e126332e791f352ede9c2e3)

example build from `next` branch

http://rrag.github.io/react-stockcharts-next/documentation.html#/grid

now this is not published to npm yet, it will be some time till a beta version is published, but you can try this out by building from source if you are interested.

**Comment by coffenbacher** [comment]
> Writing this answer got me interested and I could not stop, and I made the change

You're awesome, thank you!!! This is perfect!
