### ISSUE TITLE
Right side of the latest candle is not displayed

### ISSUE THREAD

**Issue by metstrike** [rrag/react-stockcharts#220]
Hello, thank you for this amazing package.

This is a cosmetic visual issue, the current layout seems to cut off the right side of the latest candle in a chart (see the screenshot below). The full candle is displayed after manually dragging the chart to the left by a few pixels. Is it possible to shift the chart's drawing area in the code? Thank you!

![image](https://cloud.githubusercontent.com/assets/15493274/22792365/58318b0e-eea1-11e6-9048-7b256e0e3535.png)

**Comment by rrag** [comment]
that is intentional, the chart gets clipped, if you dont like that behavior, you could use a combination of

```jsx
<CandlestickSeries ... clip={false} />
```
and `padding`, like [here](https://github.com/rrag/react-stockcharts/issues/196#issuecomment-268265932)

**Comment by metstrike** [comment]
Thank you, this workaround worked for me pretty well.

**Comment by rrag** [comment]
👍  that is not a workaround, that is the right solution.

alternatively you can add some more dates with no values like say you have

```
var data = [
{ date: yesterday, open, high, low, close },
{ date: today, open, high, low, close },
{ date: today + 1 }, // notice no ohlc values
{ date: today + 2 }, // notice no ohlc values
{ date: today + 3 }, // notice no ohlc values
{ date: today + 4 }, // notice no ohlc values
{ date: today + 5 }, // notice no ohlc values
...
]
```
