### ISSUE TITLE
how to fill in path areas by 2 colors

### ISSUE THREAD

**Issue by c4il** [rrag/react-stockcharts#221]
Hi, 
I have 2 LineSeries A and B that crosses each other, and I want to fill the path by 2 colors in such a way that when line A is above line B then fill in red and when line B is above A then fill in blue.  Is this possible by modifying some part of series/AreaOnlySeries.jsx? I'm using svg, so I would like to apply renderSVG function.

Thanks

**Comment by rrag** [comment]
svg path can have only one fill color, so you cannot do that with an `AreaOnlySeries` it has to be a new series. However I am not sure how you can achieve that even if you have 2 `path`s

**Comment by c4il** [comment]
Hi, thank you for checking. I was able to achieve this by using `clip-path`. Basically, I have followed the method described at below link and applied it into your series classes.
[http://www.d3noob.org/2015/07/difference-charts-with-d3js-science-vs.html](http://www.d3noob.org/2015/07/difference-charts-with-d3js-science-vs.html)

Thanks

**Comment by rrag** [comment]
interesting solution, I am thinking the same can be used for canvas also. Mind sending a pr for a new series?

**Comment by c4il** [comment]
I'm happy to, but it requires some calculator to be fed into the `base ` function with `scale`. I needed this alternating color thing for the implementation of IchimokuClouds series, which is nowhere near completion, but that is where I'm calling this modified `AreaOnlySeries` from. It would be better if I could just feed plain OHLC in `scale` to `base ` so that it would work as a simple demonstration of this feature, but it doesn't seem to work.  (If you know how to feed OHLC as a `scale ` function to `base`, I would like to know) 

So, I would like to contribute, but I don't have a complete working set of example that I can send you as a pr at this point..

**Comment by rrag** [comment]
no rush, when ever you are ready. If you are having trouble with something, open a PR with some work that is in progress, and we can discuss further on that.

Remember that there are changes I have made on the `next` branch, so make sure to send PR to that branch.

**Comment by c4il** [comment]
Thanks! I will.
