### ISSUE TITLE
can i change chart type?

### ISSUE THREAD

**Issue by benoms12** [rrag/react-stockcharts#223]
hi. thanks for your great works.

I want to change chart type CandleStick->Renko by select or click some button.
It can do with demo page but I don't know how to do this.

I'm not using demo source, just doing with your great example sources.

can you tell me how to do it?

**Comment by rrag** [comment]
in `0.6.1`

when using candlestick chart
```jsx
<ChartCanvas seriesName="MSFT" calculator={[]} ...>
```

renko
```jsx
<ChartCanvas seriesName="MSFT-RENKO" calculator={[renkoCalculator]} ...>
```

you will have to change the `seriesName` to reset the chart, the `xScale` will have to discontinuous scale when using renko/kagi/p&f

where `renkoCalculator` is like [this](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/Renko.jsx#L28)
