### ISSUE TITLE
Use-case: appending historical data

### ISSUE THREAD

**Issue by kayazinc** [rrag/react-stockcharts#224]
### Use-case
1. On chart initialization, the chart will request to server and 2 years of historical data (eg, 2015-2016) will be loaded.
2.  User pan the chart to left (looking at more backdated prices).
3.  Upon no more backdated prices, the chart will request to server for another year of historical data (eg. 2014) and will be pre-appended to the input data.

Thanks to the following code example (https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx),
I have successfully implemented the above use-case.  However, when the new data is pre-append to the input data array, the zoom ratio is reset (forced) to display all data on chart.

Question: is there anyway NOT to reset the zoom ratio when new data is pre-appended?

EDIT: further investigation, the zoom ratio didn't changed.  It is the chart is "reset" to show the entire dataset instead of the selected viewset.

**Comment by rrag** [comment]
zoom does not reset on loading data, check http://rrag.github.io/react-stockcharts-next/documentation.html#/load_more_data_on_pan

**Comment by kayazinc** [comment]
hmm thanks, let me revisit my codes again.  :)

**Comment by kayazinc** [comment]
As you can see from the gif below, the chart is "forced" to display the entire dataset upon re-calculate due to new pre-append data.
![stockcharts-zoom-reset](https://cloud.githubusercontent.com/assets/19774010/22960821/fc3a2326-f37b-11e6-9c66-78d4b00c6560.gif)

Let me add more comments to my codes and I will post it below for your advice.  Thanks.

**Comment by kayazinc** [comment]
Additional info
- using tag 0.6.1

**Comment by kayazinc** [comment]
Really appreciate your help on this, @rrag.   I cannot find the root cause of the issue.  

I suspect it could be due to index corruption or the xscale on my codes.  The question to ask is why the chart force to show on entire dataset instead of the viewset?  What parameter is controlling the repaint range?  

Please advise me, thanks.

**Comment by rrag** [comment]
your code looks ok, it is hard to tell because this is only part of the class, I cannot help much without a reproducible plunker or project on github.

The `interval` is no longer used, I should have removed it in 0.6.1, it is benign.

Only thing I can think of is are you using `xScaleProvider`? you should not, it should be using the `xScale` which is set in state. The [example](http://rrag.github.io/react-stockcharts/documentation.html#/load_more_data_on_pan) I shared above has it working, so I don't follow why you say it is not working.

**Comment by kayazinc** [comment]
The example (https://rrag.github.io/react-stockcharts/documentation.html#/load_more_data_on_pan) you shared works perfectly.  However, I copied the same exact codes from https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx and it exhibit the same issue.  Am I referring to the wrong source codes?

I will try to use ```xScale``` instead of ```xScaleProvider``` and see the result, something for me to explore on.  Alternately, I will try to reproduce the issue in plunker.  

Thanks for the hint, @rrag.

**Comment by rrag** [comment]
there is no `xScaleProvider` used in the [example](https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L142-L147) I am guessing that is the problem

**Comment by kayazinc** [comment]
Sorry I am confused, is this the correct codes (https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx) for the example?  Thanks.

**Comment by rrag** [comment]
The example you have mentioned is correct,

based on your response earlier you seem to be using `xScaleProvider` but the example does *not* use `xScaleProvider` but only `xScale` so I was guessing that must be the problem with your program.

**Comment by kayazinc** [comment]
Reference to example codes, https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L119-L124, it is using ```xScaleProvider``` too.  

The ```xScaleProvider``` will then compute the xScale and set it as a state.

Sorry but I cannot see the differences compare to my codes.

**Comment by rrag** [comment]
it is not there as a prop of `ChartCanvas` 

https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L143-L147

**Comment by kayazinc** [comment]
hmm, are you saying the codes (https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx) are outdated or incorrect?

**Comment by rrag** [comment]
omg, the example is correct, it works. That file is what you see on the documentation page also.

Share a plunker with your example to take this forward.

**Comment by kayazinc** [comment]
Sorry for my misunderstanding, I have reproduce the doc example on plunker and it works perfectly.

While using the same working codes (https://github.com/rrag/react-stockcharts/blob/v0.6.1/docs/lib/charts/CandleStickChartPanToLoadMore.jsx), I still have the issue.
This mean there is something wrong with my chart container as that is the only difference.

As such I will close this issue, thanks for your patience and help @rrag.
