### ISSUE TITLE
_react2.default.Children.map(...).filter is not a function

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#225]
I update my version of react-stockcharts from v5.0.0 to v6.1.0.
Then I  try to draw a simple chart, and it comes out an error. 
Thank you for helping me fix it.

 **The version of packages list  as follows**：
"react": "^15.0.0",
"react-dom": "^15.0.0",
"react-stockcharts": "^0.6.1",

![image](https://cloud.githubusercontent.com/assets/18010449/23092630/43748c3c-f60a-11e6-96b9-c360de50863a.png)
![image](https://cloud.githubusercontent.com/assets/18010449/23092633/523f5b48-f60a-11e6-8582-5519f1f41151.png)

**This is part of my code** 
```
return <ChartCanvas ratio={ratio} width={width} height={height}
                    margin={{ left: 50, right: 50, top: 10, bottom: 30 }} type={type}
                    seriesName={seriesName}
                    data={data}
                    xAccessor={d => d.date} xScaleProvider={discontinuousTimeScaleProvider}>

                    <Chart id={1} yExtents={d => [d.high, d.low]}>
                        <XAxis axisAt="bottom" orient="bottom" ticks={6}/>
                        <YAxis axisAt="left" orient="left" ticks={5} />
                        <CandlestickSeries />
                    </Chart>
            </ChartCanvas>
```

and my data is ok
![image](https://cloud.githubusercontent.com/assets/18010449/23092662/4448aaa2-f60b-11e6-923d-30c8fb49dcf0.png)

**Comment by rrag** [comment]
I dont see a problem it looks ok. Can you create a plunker?

**Comment by rrag** [comment]
?

**Comment by sunshineying** [comment]
I can't create a plunker, because there is no sense to do it. 
It just  comes out an error in my project , and I  doubt that the dependency of other installation packages makes the mistake.  I'm looking for the reason and try to fix it .

**Comment by rrag** [comment]
I will not be able to help without a reproducible example or plunker. reopen when you have one
