### ISSUE TITLE
Using xScale

### ISSUE THREAD

**Issue by tautek** [rrag/react-stockcharts#227]
Hi

I'm having trouble using the xScale to determine an SVG coordinate using a date inside a custom chart component. When I use an xScaleProvider for discontinuous time scale I get a huge value for the xScale result in renderSVG (23166018413114.754) -

```
<ChartCanvas
    ...
    xExtents={[new Date(2012,0,4), new Date(2012, 4, 17)]}
    xScaleProvider={discontinuousTimeScaleProvider}
>
```

```
renderSVG(moreProps) {
    var { className, yAccessor } = this.props;
    var { xAccessor, plotData, xScale, chartConfig: { yScale } } = moreProps;
    var x = xScale(new Date(2012,0,4));  // 23166018413114.754
    ...
```

If I change the chart canvas to use D3 scaleTime the value of xScale result in renderSVG makes sense (0 for the left bound) -

```
<ChartCanvas
    ...
    xExtents={[new Date(2012,0,4), new Date(2012, 4, 17)]}
    xScale={scaleTime()}
>
```

```
renderSVG(moreProps) {
    var { className, yAccessor } = this.props;
    var { xAccessor, plotData, xScale, chartConfig: { yScale } } = moreProps;
    var x = xScale(new Date(2012,0,4));  // 0
    ...
```

Am I using xScale correctly? I couldn't see from the examples if I need to initialize the xScaleProvider in some way?

Thanks for any assistance.

**Comment by rrag** [comment]
the discontinuous scale converts time into a linear scale, to do that it creates an index 0 - n and uses that as the underlying scale, so for e.g.

```
var data = [
    { date: "2017-01-03", ...ohlcv }, // index = 0
    { date: "2017-01-04", ...ohlcv }, // index = 1
    { date: "2017-01-05", ...ohlcv }, // index = 2
    { date: "2017-01-06", ...ohlcv }, // index = 3
    { date: "2017-01-09", ...ohlcv }, // index = 4
    { date: "2017-01-10", ...ohlcv }, // index = 5
    { date: "2017-01-11", ...ohlcv }, // index = 6
    { date: "2017-01-12", ...ohlcv }, // index = 7
    { date: "2017-01-13", ...ohlcv }, // index = 8
    { date: "2017-01-17", ...ohlcv }, // index = 9
    { date: "2017-01-18", ...ohlcv }, // index = 10
    { date: "2017-01-19", ...ohlcv }, // index = 11
    { date: "2017-01-20", ...ohlcv }, // index = 12
    { date: "2017-01-23", ...ohlcv }, // index = 13
}
```

with this discontinuous xScale if you want to say plot at `2017-01-09`, then you have to do `xScale(4)`  to get the x coordinate.

So now the problem becomes how to get this arbitrary index when all I have is a date? you do a binary search on the entire dataset with your date and then get the index of that item and use it. there are utilities available in the library itself

assuming `0.6`
```
import * as ReStock from "react-stockcharts"

const { utils } = ReStock
const { getClosestItem } = utils
...

renderSVG(moreProps) {
    var { xAccessor, fullData, xScale, displayXAccessor } = moreProps;
    // displayXAccessor is d => d.date this is usually the xAccessor you have passed as a prop in `ChartCanvas`
    const item = getClosestItem(fullData, new Date(2017, 0, 20), displayXAccessor)
    console.log(xAccessor(item)) // 12

    const x = xScale(xAccessor(item))
```

**Comment by tautek** [comment]
Ah! Thanks, makes perfect sense now.

I'm working on putting together something akin to HighCharts' navigator (http://www.highcharts.com/docs/chart-concepts/navigator).
I'm happy to contribute it back when I get it working.
To make it reusable what would be the recommended way to go about determining if xScale expects a date or an index?
Is there a way to query this from xScale or should I just determine if the user specified an xScale prop (`xScale={scaleTime()}`)? Does the xScale from xScaleProvider always expect an index (even if it was linear)?

**Comment by rrag** [comment]
Thank you, contributions are always welcome

in `0.7` I am getting rid of `xScaleProvider`, using `xScale` all the time makes code much simpler and less edge cases to deal with. you can read the issue about breaking changes in 0.7 to see some examples, the `next` branch has all the examples converted so you can see how it works. You can do the same in 0.6 also, meaning, completely avoid `xScaleProvider` prop and use `xScale` only

Remember to read the breaking changes issue and use the next branch before contributing

You can always assume that the `xScale` is discontinuous and program with that assumption, it should handle the continuous scale also

I dont see a usecase where you have to behave differently depending on if x is continuous or not. Can you?

> Does the xScale from xScaleProvider always expect an index (even if it was linear)?
yes

**Comment by tautek** [comment]
Thanks. I'll take a look at the 0.7 examples.
