### ISSUE TITLE
Add a constant line accross the chart

### ISSUE THREAD

**Issue by Jr9192** [rrag/react-stockcharts#229]
Hi,
First of all this is a great library! I have been trying to figure out how to add "boundaries" lines accross the chart. Similar to the picture below (the dashed lines).

![31f4d7d1-6d67-4745-9b43-6205f412c85b-7125-0000060490372d6a_tmp](https://cloud.githubusercontent.com/assets/25945150/23198530/33b70dfa-f903-11e6-90b9-bc2ccb9ceacf.png)

I tried to achieve the same with annotation but it seems that it expect a condition, which is evaluated for every datapoint. Is there any other way besides adding it to my data array?

**Comment by rrag** [comment]
you could try with `StraightLine` there is an example of using it to draw a vertical line in the Stochastic oscillator example.

But that is not interactive, meaning you cannot drag and drop the straight line.

**Comment by moonlight16** [comment]
NOTE: There's 2 versions of StraightLine.js.  This one version was giving me a lot of headache:

import StraightLine from "react-stockcharts/lib/interactive/components/StraightLine"

This one is what Stochastic oscillator is using and is much easier interface to work with:

import { StraightLine } from "react-stockcharts/lib/series"
