### ISSUE TITLE
Performance for rendering million data points per second

### ISSUE THREAD

**Issue by gullyy** [rrag/react-stockcharts#232]
I wanted to understand the performance capability if I wanted to render the chart per second. Asuuming there are a million data points being updated a single second.What is the cost for rending these data points on the chart.
I understand the library perhaps has nothing controlled with respect to the render performance,nor that I expect it to be .The core features of React and browser affects the performance for rendering.Having said that I wanted to surface the idea so that anyone can share their experience and opinions

**Comment by rrag** [comment]
I have never tried with million data points, I cannot speak to that, you could profile this and share your findings,

Generally you can start seeing performance issues when dealing with more than 4x data points, say you have a chart of width 1000 px, more than 4000 data points, you can see lag

Out of curiosity why would you want to show million datapoints in a chart? if you are talking about finance data, it could be rolled up to that month/year so you have less points and you can still see the trend from the resulting chart.

**Comment by gullyy** [comment]
If I display tick charts,which means its rendered every second(considering tick=1sec, it can be even microseconds).And if one page has average 5 instrument listed then its almost million data points considering market is open for more than 18-20 hours..

**Comment by rrag** [comment]
I dont know of anyone who sees second data over 20 hours, minute/5m is better also of trend.

You can certainly try it and share your finding. there is a prop `pointsPerPxThreshold` you could tweak to show more points - discussion about it [here](https://github.com/rrag/react-stockcharts/issues/191#issuecomment-266787293)

There is nothing actionable in this issue, so closing it, open a new one if you find any problems or to share your results
