### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by pinkpanther576** [rrag/react-stockcharts#234]
Hi I have downloaded the code and then what? How do I run? and modify existing code? I am pretty new to client side development in nodejs so can anyone help me out?

**Comment by rrag** [comment]
Hello, welcome to frondend development. This library works with `react` a popular frontend framework. I recommend you begin with a simple react app. There are many getting started tutorials available, search for `create-react-app` as a quick way to get started on a react app.

Once you have a react app up and you know how to add your own components to it, start using `react-stockcharts`. This is my recommendation, but different people learn in different ways, so YMMV.

Good luck with your journey.

**Comment by pinkpanther576** [comment]
Yes I have created react apps..but I am struggling to start react-stockcharts.After I download how do I see one example?

**Comment by rrag** [comment]
the plunker examples should give you an idea, also almost all the examples under https://github.com/rrag/react-stockcharts/tree/master/docs/lib/charts could be directly used to get started.
