### ISSUE TITLE
drawOnMouseExitOfCanvas - not behaving correctly

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#237]
The draw() event is not called after a mouseleave (after enabling debug)

https://github.com/rrag/react-stockcharts/blob/master/src/lib/GenericComponent.jsx#L97-L98

Suggest to just call the draw() event directly if the prop is enabled...

```
case "mouseleave": {
			  if (this.props.drawOnMouseExitOfCanvas)
			   {
			     this.draw();
			   }	
			break;
		}
```

**Comment by rrag** [comment]
draw is triggered from a separate `draw` event, `mouseleave` event sets up the variables and the `draw` event after that draws it.

The problem was with mouse move triggering after a mouseleave, I think this has already been addressed in the `next` branch. Breaking changes though
