### ISSUE TITLE
EventCapture setTimeout time should be a property

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#238]
I have different use cases where the setTimeout is inappropriate, can this be a property?

https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.jsx#L145

https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.jsx#L193

**Comment by rrag** [comment]
the `setTimeout` is to not have 2 click events on double click. I dont want to have a prop like your suggestion, but open to other solutions which fulfill your requirement and also double click

**Comment by rrag** [comment]
Closing this as it appears you are not interested in sending a PR for the feature
