### ISSUE TITLE
CandlestickSeries yAccessor change

### ISSUE THREAD

**Issue by mixtale** [rrag/react-stockcharts#239]
I want to change yAccessor datas of CandlestickSeries with my custom variables. so I tried like below but it's not work.

<CandlestickSeries yAccessor={d => open: d.newopen, high: d.newhigh, low: d.newlow, close: d.newclose} />

- ERROR: unknown: Unexpected token

I know I can change original data(d.open,high,low,close) but I'll make two candlestick chart so I must use original data too.

Is there a way to solve this?

**Comment by rrag** [comment]
```
ERROR: unknown: Unexpected token
```

that is a syntax error

```diff
-<CandlestickSeries yAccessor={d => open: d.newopen, high: d.newhigh, low: d.newlow, close: d.newclose} />
+<CandlestickSeries yAccessor={d => ({ open: d.newopen, high: d.newhigh, low: d.newlow, close: d.newclose })} />
```
