### ISSUE TITLE
React 14 for meteor

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#24]
ChartWidthMixin.js:28

Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

**Comment by rrag** [comment]
Yes, it is documented in http://rrag.github.io/react-stockcharts/documentation.html#/getting_started

Using `react-dom` will remove compatibility with 0.13. So I am not going to be fixing this for some more time
