### ISSUE TITLE
[Bug] Toolip on ordinal scale does not work

### ISSUE THREAD

**Issue by iamstephenwang** [rrag/react-stockcharts#240]
I tried to add a hover tool tip to a bar chart but it does not work. It seems the Canvas does not respond to any event at all if the scale of my XAxis is `scalePoint()`. 

The reason is due to the `isInteractionEnabled` function in `ChartCanvas.jsx`. It checks whether the "invert" is defined in the XAxis; however, there is no "invert" defined in `scalePoint()`.

Could you please help fix this?
```
function isInteractionEnabled(xScale, xAccessor, data) {
	var interaction = !isNaN(xScale(xAccessor(first(data)))) && isDefined(xScale.invert);
	return interaction;
}
```

**Comment by rrag** [comment]
any suggestions on how to fix?

it is not possible to do `pan` `zoom` with ordinal scale, but I see the problem with tooltip. Looking for feedback on this

**Comment by rrag** [comment]
Closing this as it appears you are not interested in sending a PR for the feature
