### ISSUE TITLE
Click callback

### ISSUE THREAD

**Issue by iamstephenwang** [rrag/react-stockcharts#242]
It seems I cannot see the console output produced in the click callback example: http://rrag.github.io/react-stockcharts/documentation.html#/click_callback

Could it be a bug?

**Comment by wshark86** [comment]
@iamstephenwang  I am using the latest version and the click seems to be working fine. What version are you using? 

Also, I just did a fresh checkout and I have no issues with the click example. Maybe has to do with your implementation?

**Comment by iamstephenwang** [comment]
I was just looking at the click example on the documentation website listed above (I just open the chrome Dev tools and tried to click on the chart to see the console output). Maybe it's working in the latest version. Let me do a fresh checkout and try again.

**Comment by wshark86** [comment]
I just tested from the current version in the link you posted and I see the logs being printed as I click both left and right click 
<img width="1252" alt="screen shot 2017-03-05 at 17 00 39" src="https://cloud.githubusercontent.com/assets/26197055/23585929/790ebc2a-01c5-11e7-8449-6c785617b6e8.png">

**Comment by iamstephenwang** [comment]
@wshark86 I think I found out why. The click will work when the "pan" is enabled. When it is not enabled, the click event will somehow get stolen by the "mousedown" event and never routed back.

**Comment by rrag** [comment]
might have to fix that. want to do a PR on the `next` branch?

**Comment by rrag** [comment]
this should be fixed in the latest beta
