### ISSUE TITLE
Historical performance + Future forecast chart

### ISSUE THREAD

**Issue by 4mgad** [rrag/react-stockcharts#243]
Hi,

Is there a way to represent historical performance and future forecast of a specific stock in one chart?

kinda similar to this one:

<img width="333" alt="screen shot 2016-04-03 at 9 05 18 am" src="https://cloud.githubusercontent.com/assets/1541846/23596120/81cb3ffc-01dc-11e7-9a6e-06ebf1a5d9a5.png">

**Comment by iamstephenwang** [comment]
@4mgad Yes it is possible (i have done similar charts). 

You need: 
Annotations (for the text)
Dashed lines (for the upper and lower border of the fan chart)
AreaOnly series (for the fan chart)

If you check how BollingerSeries is implemented, you will see it is just a few LineSeries plus an AreaOnlySeries.

**Comment by 4mgad** [comment]
All examples are showing charts on top of each other. What I'm looking for is an example showing charts side-by-side on the same time scale.

**Comment by rrag** [comment]
I see 2 ways of doing it, depends on how you have the data configured, if 


### case 1

you already have these forecast values as part of your data [] like

```
var data = [
  { date: yesterday, ohlcv },
  { date: today, ohlcv, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
  { date: today + 1, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
  { date: today + 2, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
  { date: today + 3, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
  { date: today + 4, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
  { date: today + 5, forecasthigh: ..., forecastlow: ... forecastmedian: ... },
]
```

then you can create a `LineSeries` for the high, low, median and an `AreaOnlySeries` with the `base` prop like [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/BollingerSeries.jsx#L52)


### case 2

forecast is separate from data [], in this case you first have to make the data [] as large as the forecast end, if you have a 2 month forecast then make

```
var data = [
  { date: yesterday, ohlcv },
  { date: today, ohlcv },
  { date: today + 1 }, // no ohlcv data here, just the date
  { date: today + 2 }, // no ohlcv data here, just the date
  ...
  { date: today + 2 months }, // no ohlcv data here, just the date
]
```
and you also have a 

```
var forecast = {
  on: today+ 2 months,
  high: ...
  low: ...
  median: ...
}
```

you would have to write a custom component, and once you have access to the `xScale` and `yScale` you would have to interpolate these values so zoom and pan all show up. This case is more advanced, so you would have to understand the internals to get a grip on how to implement it. If you are really interested show me your work in progress (on plunker) and I can help you take it forward

**Comment by 4mgad** [comment]
Thanks Ragu. I was able to successfully use AreaOnlySeries to highlight the area between high and low. However, I still have a problem showing a specific date exactly in the middle of a chart, is there a way to programmatically pan to a specific date?

**Comment by rrag** [comment]
use `xExtents` prop on `ChartCanvas`
