### ISSUE TITLE
Minimum width of the indicator line of HoverToolip

### ISSUE THREAD

**Issue by iamstephenwang** [rrag/react-stockcharts#244]
In HoverTooltip.jsx, line 278, 

var pointWidth = Math.abs(xScale(xAccessor(last(plotData))) - xScale(xAccessor(first(plotData)))) / (plotData.length - 1);

Is it possible to add a minimum width of this pointWidth? The reason being if there are too many data in plotData, the pointWidth will be too small and the indicator line will be too faint to see. 

Maybe we shall add a minimum width of say 5px.

**Comment by rrag** [comment]
I dont want to default to any min width > 0, but I am open to adding a prop. want to send a pr to `next` branch?

**Comment by rrag** [comment]
Closing this as it appears you are not interested in sending a PR for the feature
