### ISSUE TITLE
Customize theme & reversal value for Kagi chart

### ISSUE THREAD

**Issue by parth-solute** [rrag/react-stockcharts#245]
is it possible to change theme(light -> dark) & provide dynamic reversal values for the kagi chart.

**Comment by rrag** [comment]
dark theme - http://rrag.github.io/react-stockcharts/documentation.html#/theme_dark

for kagi you can do

```
var kagiCalculator = kagi()
  .reversal(2)
  .reversalType("ATR"), // "ATR", "FIXED"
  .windowSize(14) // ATR window size, if you choose FIXED, this is not used
```
