### ISSUE TITLE
Can it repain the display with real-time data?

### ISSUE THREAD

**Issue by coco101000000000** [rrag/react-stockcharts#248]
Can  it support displaying  real-time data on canvas with a  timer fetching data from sever.

**Comment by rrag** [comment]
yes, it can you have to update the `data` prop

**Comment by coco101000000000** [comment]
Can you give a  example? please .

**Comment by rrag** [comment]
http://rrag.github.io/react-stockcharts/documentation.html#/updating_data

press
```
1 to start adding new data
Esc to stop
+ to increase the speed
- to reduce the speed
```

**Comment by coco101000000000** [comment]
Thank you .
