### ISSUE TITLE
default Font size, font color (xAxis, yAxis)

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#25]
Hi,

how i could change default font size, color etc. on xAxis, yAxis ?

**Comment by rrag** [comment]
add `fontSize={22} fontFamily="Comic Sans MS"` to the `XAxis` or `YAxis`

http://plnkr.co/edit/Ymb81eGyE4zrRbMBXh24?p=preview

Alternatively, if you are using svg as the type, add css class to `.react-stockcharts-axis text`
