### ISSUE TITLE
Chart disappears on zoom in/out from mobile

### ISSUE THREAD

**Issue by parth-solute** [rrag/react-stockcharts#250]
One mobile pinch zooming in and out causes the whole canvas to disappear every now and again. Touching and panning then seems to bring it back.

**Comment by rrag** [comment]
there is a bug in 0.6.x where the touch pan causes the chart to flicker and reset the pan position. it is fixed in the `next` branch no release ETA yet

**Comment by cesardeazevedo** [comment]
@rrag Can you publish a `beta` release? i am always unable to install directly from `git+https://github.com/rrag/react-stockcharts.git#next`, because it will install a non-compiled version.

**Comment by itsjimbo** [comment]
You should be able to build it yourself, try the following steps:

Clone the next branch of this repo
```
git clone https://github.com/rrag/react-stockcharts.git -b next
```
Install dependencies
```
cd react-stockcharts && npm i
```
Build the next version
```
npm run release 
```
Confirm the files are in the build/ directory, and package.json should be there...
```
{
  "name": "react-stockcharts",
  "version": "0.6.1",
```

Hope this helps!

**Comment by rrag** [comment]
Thanks @itsjimbo I will do a beta release later this week

**Comment by rrag** [comment]
new version `react-stockcharts@0.7.0-beta.1` published to npm you can install as

`npm install react-stockcharts@next` Be sure to review the [breaking changes](https://github.com/rrag/react-stockcharts/issues/206)
