### ISSUE TITLE
Discontinuous scatter plot

### ISSUE THREAD

**Issue by netheril96** [rrag/react-stockcharts#251]
Could I have a scatter plot where the x axis isn't continuous? Similar to how in matplotlib, you can have

```python
matplotlib.pyplot.scatter([1,2,4,100], [1,5,7,9])
```

I need this scatter plot to coexist with an line plot that has a continuous x axis, as an emphasis on certain special points. Is it possible with react-stockcharts?

**Comment by rrag** [comment]
similar to https://github.com/rrag/react-stockcharts/issues/170#issuecomment-261154797
