### ISSUE TITLE
Problem on formatting date

### ISSUE THREAD

**Issue by xreef** [rrag/react-stockcharts#252]
Hi All,
I have a little problem on formatting y.
with 
xScaleProvider={discontinuousTimeScaleProvider} on ChartCanvas
and 
tickFormat={timeFormat('%b %d')} on XAxis
the date on y become the same date  1-1-1977

In this example
http://embed.plnkr.co/HGYCob1woj2PI51VHLha/
if you remove 
xScaleProvider={discontinuousTimeScaleProvider}
than working.
Bye

**Comment by rrag** [comment]
please format the question using code blocks

 there is no date on `y` in the plunker

**Comment by rrag** [comment]
you have both

```
xScale={d3.scaleTime()}
xScaleProvider={discontinuousTimeScaleProvider}
```

on the chart, use one or the other, x scale cannot be both continuous and discontinuous
