### ISSUE TITLE
mobileWeb   component  OHLCTooltip  onclick event Executive No ？

### ISSUE THREAD

**Issue by 1003865572** [rrag/react-stockcharts#255]
![qq 20170430001405](https://cloud.githubusercontent.com/assets/7412054/25556983/5e52b9fe-2d3a-11e7-9fe0-f93f5875345a.png)

**Comment by rrag** [comment]
is this a mobile only issue? `OHLCTooltip` only has a click listener, Do you think adding a touch end listener solve the problem? Appreciate a PR to fix this

**Comment by rrag** [comment]
closing due to no response
