### ISSUE TITLE
Eventcapture - Right Click

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#256]
The handling of a menu is a more specific use-case then for generics.  In keeping with the library, maybe the Right Click should be refactored to just handle the termination of events such as pan, but the user can override this behavior... thoughts?

https://github.com/rrag/react-stockcharts/blob/next/src/lib/EventCapture.jsx#L118-L145

**Comment by rrag** [comment]
no quite following this, the user can provide a callback for right click to get custom behavior.

**Comment by rrag** [comment]
?

**Comment by itsjimbo** [comment]
Thanks, I'm satisfied with that answer, just the onContextMenu and contextMenuClicked terms seemed to convey only a menu can be utilized
