### ISSUE TITLE
Uncaught TypeError: Cannot read property 'date' of undefined for xAccessor

### ISSUE THREAD

**Issue by madhumurugan89** [rrag/react-stockcharts#258]
When  xAccessor={d => d.date} this is set and data = [{ date: new Date('2011-01-24').getTime() }, {date: new Date('2011-01-25').getTime() }], then below error occurs
'Uncaught TypeError: Cannot read property 'date' of undefined'

**Comment by rrag** [comment]
There is not enough information for me to provide any helpful reply. There are dozens of examples with `xAccessor={d => d.date}` 

Kindly share a plunker/fiddle with your issue

**Comment by theorye** [comment]
@madhumurugan89 Are you by chance using redux?  And/or by chance is the initial data you send in equal to null?
