### ISSUE TITLE
Candle wick is shifts relative to center.

### ISSUE THREAD

**Issue by dmtrdmtr** [rrag/react-stockcharts#259]
In [several](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.jsx#L210) [places](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.jsx#L238) `x` and `candleWidth` is rounded. And with some `widthRatio` values they rounded in different directions. In this case wick is shifts relative to center. When candle width less 5 it becomes noticeable.

When i remove all `Math.round` everything works great.

[plunker](http://plnkr.co/edit/665NZV3HmsN5CBnz5tfW?p=preview)

**Comment by rrag** [comment]
nice job. the lib did not have the `Math.round` earlier, but that led to antialiasing problems, so the trick to solve that was to [shift by 0.5 px](http://stackoverflow.com/a/18405791/4244495), this means every shape has to have round x and y values, (there is a bug in `master` where the x values are rounded but y is not, fixed in `next` branch).

I did some changes in `next` branch which solved some of this issue keeping the `round` in place, could you try with the latest beta `npm i -S react-stockcharts@next` remember to read about the [breaking changes](https://github.com/rrag/react-stockcharts/issues/206)

I am open suggestions, which addresses both the antialias and this problem too

**Comment by dmtrdmtr** [comment]
At `next` a little better, but the same problems with wicks.

This solution does not look elegant.
And candles width cant be `3`.

I do not quite understand how to handle all odd candle width values and leave the rounding ...

```js
const candleWidth = cw >= 4 ? Math.round(cw) : cw - cw % 2;   // ----- Math.round(cw)

const offset = (candleWidth === 1 ? 0 : 0.5 * cw);
let candles = [];

for (let i = 0; i < plotData.length; i++) {
	const d = plotData[i];
	if (isDefined(yAccessor(d).close)) {
		const x = Math.round(xScale(xAccessor(d)) - offset);

		const ohlc = yAccessor(d);
		const y = Math.round(yScale(Math.max(ohlc.open, ohlc.close)));
		const height = Math.round(Math.abs(yScale(ohlc.open) - yScale(ohlc.close)));

		candles.push({
			x: x,
			y: y,
			wick: {
				stroke: wickStroke(ohlc),
				x: Math.round(x - candleWidth/2), // ----- Math.round(xScale(xAccessor(d)))
				y1: Math.round(yScale(ohlc.high)),
				y2: y,
				y3: y + height,
				y4: Math.round(yScale(ohlc.low)),
			},
			height: height,
			width: candleWidth,
			className: className(ohlc),
			fill: fill(ohlc),
			stroke: stroke(ohlc),
			direction: (ohlc.close - ohlc.open),
		});
	}
}
```



In the `v0.8` it is planned to completely migrate to `canvas` from 'svg'. Because there are performance problems with `svg`?

**Comment by rrag** [comment]
you are right, I was thinking of fixing the `x` of the wick first and then define the `x` and `width` of the candle based on that. Let me put this together in the `next` branch and we can discuss this after.

about `v0.7` it will continue to have `canvas` and `svg` options. I have discussed this earlier in some other issues also, I like canvas for its performance, and svg for its easy of development, so I like both, and I really cannot pick one. any how for v0.8 all the interactive indicators are canvas only, once the svg versions of these are implemented, it would get out of beta

`0.8` - It is too early to tell :)

**Comment by rrag** [comment]
sorry for the delay. Fixed in `next` by adding the width / 2 on both sides of center. Not published to npm yet, check out the [next docs](http://rrag.github.io/react-stockcharts-next/documentation.html#/forceindex).

**Comment by dmtrdmtr** [comment]
Thanks.
