### ISSUE TITLE
axis color

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#26]
Hi! 

how i could change default color (black) of axis ?

**Comment by rrag** [comment]
`stroke="green" tickStroke="green"`

http://plnkr.co/edit/Ymb81eGyE4zrRbMBXh24?p=preview

Some other props available

`strokeWidth` - Width of the axis domain (works on svg, but not on canvas - a bug I need to fix)
`opacity` - takes values 0 to 1 - controls the opacity of the axis domain
`tickStrokeOpacity` - similar to above, controls the opacity of the tick line, not the tick labels though

There is currently no way to control the stroke colors of axis label and ticks individually.

**Comment by rsklyar** [comment]
is it possible to customize without component replacement OHLC Tooltip font color ?

**Comment by rrag** [comment]
all tooltips are svg for now, you could add the following to the css file/style tag of the html

```
      .react-stockcharts-tooltip {
        fill: red;
      }
      .react-stockcharts-tooltip-label {
        fill: green;
      }
```
does this work?
http://plnkr.co/edit/Ymb81eGyE4zrRbMBXh24?p=preview

**Comment by rsklyar** [comment]
yes, thank you!

**Comment by UserAlikhan** [comment]
Hello! How to change the color of interactive objects, such as InteractiveText, Trendline or FibonacciRetracement? I want to make easily customizable tools so that users can control any style of interactive objects they want.
