### ISSUE TITLE
Smooth Curves for AreaSeries

### ISSUE THREAD

**Issue by PatrickDuncan** [rrag/react-stockcharts#260]
Hello, is there a way to make the AreaSeries curves smooth around vertices?

[Looks like A and I want B](https://i.stack.imgur.com/HLvBS.png)

**Comment by rrag** [comment]
added a new prop to interpolate in `0.7`

http://rrag.github.io/react-stockcharts-next/documentation.html#/grid

source - https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/LineAndScatterChartGrid.jsx#L94

0.7 is in beta, you can install it as `npm install react-stockcharts@next` remember to look at the [breaking changes](https://github.com/rrag/react-stockcharts/issues/206)
