### ISSUE TITLE
ERROR: ReStock is not defined. What's error is that mean?

### ISSUE THREAD

**Issue by perlawk** [rrag/react-stockcharts#261]
When I try the example like Areachart from gist,
three files come with,  README.md  4 index.html  4 AreaChart.jsx.
But when run in firefox under linux, the error comes.
I tried every examples, They give similar error. 
Any help to run the examples ?
Thanks for anybody to give a hand.

**Comment by rrag** [comment]
I just tested the plunkers and they are working. Kindly share a plunker showing the problem I will reopen and help troubleshoot this
