### ISSUE TITLE
discountinousTimeScaleProvider warning v.7

### ISSUE THREAD

**Issue by theorye** [rrag/react-stockcharts#263]
```discontinuousTimeScaleProvider.js:220 Are you sure you want to use a discontinuousTimeScale? Use this only if you have discontinuous data which needs to be displayed as continuous. If you have continuous data use a d3 scale like `d3.scaleTime```

Is there a reason why this warning is happening?  Is discontinousTimeScaleProvider unsafe to use?

I don't want gaps in the display, such as the Sunday gap.

**Comment by rrag** [comment]
`discontinousTimeScaleProvider` is the right scale for discontinuous data. I have had many queries about this scale when using continuous data, like for bitcoin, where there is no gaps. for such cases using a d3 scale is a better solution.

There has to be a code change to make the warning appear only once, and not on every update.

**Comment by theorye** [comment]
Could you be more specific on what you mean by a code change?  Looks as though I'd have to delete it the library on line 165.
