### ISSUE TITLE
Question, How set min and max zoom limit?

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#264]
Subj,
[plunker](http://plnkr.co/edit/gist:b9658ffa431f1ffb8d6b?p=preview)

So, when zoom max ( first and second frame on my attach ) i see spaces left and right sides, it`s okay?
But i hope view full filled area of chart

![zoom](https://cloud.githubusercontent.com/assets/4027842/26173701/7fad2cfa-3b55-11e7-9446-46487d027191.gif)

And i found bug,
try zoom to max and drag to left many time ( so about 10 times )
![drag](https://cloud.githubusercontent.com/assets/4027842/26221434/2d9672c6-3c1f-11e7-8617-cd62efeb6f08.gif)

P.S. thank you for you library, it is best solution) like

Edited, 
how about [this ( Zoom to Domain )](https://bl.ocks.org/mbostock/431a331294d2b5ddd33f947cf4c81319) sample ,

So, how set min and max zoom value?
similar 
```
d3.zoom()
    .scaleExtent([1, Infinity])
```

So, i understand what zoom depended from plotData
[https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L595](https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L595)

**Comment by borm** [comment]
About bug, i find it and fix, wait the pull request from me, maybe tomorrow

**Comment by rrag** [comment]
the gap in the data is due to weekends, as market is closed on weekend there is no data to show. You should use a discontinuous scale to remove weekend breaks.

**Comment by borm** [comment]
What about bug?

**Comment by borm** [comment]
So, i need help please
how set max zoom in
how implement don`t disable render when pan enabled, i found you disabled render graph when pan started
how create custom indicator for only last point on chart?
how set min and max view domain range when pan, i want see max 50% domain width when pan left or right end of chart
how set animation for updating data component

**Comment by rrag** [comment]
These are different types of feature requests, kindly file a separate issue for each explaining with pictures if possible. I have questions on all of these, we can discuss them in those issues

**Comment by borm** [comment]
1. [how set max zoom in ( i like zoom as v 0.3.1 )](https://github.com/rrag/react-stockcharts/issues/274)
2. [how implement don`t disable render when pan enabled](https://github.com/rrag/react-stockcharts/issues/275)
3. [how set min and max view domain range when pan, i want see max 50% domain width when pan left or right end of chart](https://github.com/rrag/react-stockcharts/issues/276)
4. [how set animation for updating data component](https://github.com/rrag/react-stockcharts/issues/277)
