### ISSUE TITLE
SVG + Canvas Fullscreen freezing problem

### ISSUE THREAD

**Issue by stanbor** [rrag/react-stockcharts#266]
Hi,

I have a problem with the chart. I have downloaded 0.7 version and took http://rrag.github.io/react-stockcharts/documentation.html#/trendline to build chart, so basically it's the same as on http://rrag.github.io/fullpage/documentation.html only with trendline example.

I'm running into very specific issue. I have tried on Opera, Firefox and Chrome on Windows PC. Opera and Firefox are a bit slow but they handle it. Chrome however when in fullscreen SVG + Canvas mode.. it freezes. Zooming is very slow and chart is almost unusable. When I exit maximized browser... when I make browser window little bit smaller and its not on full screen it is scrolling normally. Also when I'm using SVG only it's slow but it's scrolling.

So still like http://rrag.github.io/fullpage/documentation.html this version has some sort of bug on Chrome when its maximized. 

I have recorded it here https://youtu.be/9fSNS0hdI5k
btw I do have 32GB RAM and 4GB graphics card

Any solution to this?

**Comment by rrag** [comment]
0.7 is still not released yet, the trendline example with 0.7 is available http://rrag.github.io/react-stockcharts-next/documentation.html#/trendline

notice the `-next` I am not following the problem, if you can give a reproducible github project that would be greatly appreciated

**Comment by stanbor** [comment]
I have realised this is Chrome problem. it is just freezing on WinPC in Chrome when in SVG+Canvas mode while fullscreen.
