### ISSUE TITLE
xAccessor: cannot read property 'date' of undefind

### ISSUE THREAD

**Issue by amhed** [rrag/react-stockcharts#268]
Trying to plugin my own data source, but it fails with xaccessor setting. 

Here's the source: 
```ts 
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as d3 from 'd3';

import { ChartCanvas, Chart, series, axes, helper } from 'react-stockcharts';
const { AreaSeries } = series;
const { XAxis, YAxis } = axes;

const { fitWidth, TypeChooser } = helper;

type ChartType = 'svg' | 'hybrid';

interface AreaChartProps {
    data: any[],
    width: number,
    ratio: number,
    type: ChartType;
};

class AreaChart extends React.Component<AreaChartProps, any> {
    constructor(props: AreaChartProps) {
        super(props);
    }

    render() {
        const { data, type, width, ratio } = this.props; 
        return (
            <ChartCanvas ratio={ratio} width={width} height={400}
                margin={{ left: 50, right: 50, top: 10, bottom: 30 }}
                seriesName="TEST SERIES"
                data={data} type={type} xScale={d3.scaleTime()}
                xAccessor={(d: any) => d.date}
                xExtents={[new Date(2017, 4, 20), new Date(2017, 4, 30)]}
                >
                <Chart id={0} yExtents={(d: any) => d.close}>
                    <XAxis axisAt="bottom" orient="bottom" ticks={10} />
                    <YAxis axisAt="left" orient="left" />
                    <AreaSeries 
                        yAccessor={(d: any) => d.close} 
                    />
                </Chart>
            </ChartCanvas>
        );
    }
}

const FixedWidthChart: any = fitWidth(AreaChart);

const parseDate = d3.timeParse('%Y-%m-%d %H:%M:%S');

// This tsv works: 
//d3['tsv']('//rrag.github.io/react-stockcharts/data/MSFT.tsv', (err, data) => {

// This one doesn't
d3['tsv']('http://localhost:5000/data.tsv', (err, data) => {
    data.forEach((d:any, i:number) => {
        d.date = new Date(d3.timeParse('%m/%d/%Y %X')(d.date).getTime());
        d.close = parseFloat(d.close);
    });

    /* change the type from hybrid to svg to compare the performance between svg and canvas */
    ReactDOM.render(<TypeChooser type="hybrid">
        {(type: 'svg' | 'hybrid') => <FixedWidthChart data={data} type={type} />}
        </TypeChooser>, document.getElementById('chart'));
});
``` 

Here's the stack trace:
```
Uncaught TypeError: Cannot read property 'date' of undefined
    at xAccessor (bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:49564)
    at domain (bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:43432)
    at calculateState (bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:35104)
    at resetChart (bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:34995)
    at ChartCanvas.componentWillMount (bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:35703)
    at performInitialMount (react.min.js:13)
    at p.mountComponent (react.min.js:13)
    at Object.mountComponent (react.min.js:15)
    at performInitialMount (react.min.js:13)
    at p.mountComponent (react.min.js:13)
xAccessor @ bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:49564
domain @ bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:43432
calculateState @ bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:35104
resetChart @ bundle-chart.js?v=4C1FKVHSSIfyq0xZhXoJPqUqGcZYajd8Tp5HbmYTexo:34995
componentWillMount @ bundle-chart.js?
...
...
```

**Comment by borm** [comment]
What is 
```
xAccessor={(d: any) => d.date}
```
d: any? 
You sure you have date key in your data?

**Comment by rrag** [comment]
This is likely because of `xExtents={[new Date(2017, 4, 20), new Date(2017, 4, 30)]}`

Does your data have any values in that range?

**Comment by amhed** [comment]
@borm `d:any`  is typescript.

**Comment by amhed** [comment]
@rrag you're right. Removing the xExtents param worked :+1:

**Comment by amhed** [comment]
Hmm, keeps happening to me. Very strange. Demo data works fine, as soon as I plugin my own I get the same xAccessor error. Here's my HTML + JSX file

Hmm, keeps happening to me. Very strange. Demo data works fine, as soon as I plugin my own I get the same xAccessor error. Here's my HTML + JSX file

```html
<head>
    <meta charset="utf-8" />
    <title>React Stockcharts - AreaChart Example</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/4.2.7/d3.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.2/react.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/react/15.3.2/react-dom.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.17.0/babel.min.js"></script>
    <!-- <script type="text/javascript" src="//unpkg.com/react-stockcharts@latest/dist/react-stockcharts.min.js"></script> -->
    <script type="text/javascript" src="//rrag.github.io/react-stockcharts/dist/react-stockcharts.min.js"></script>
    <script src="~/js/bundles/bundle-chart.js" asp-append-version="true"></script>
</head>

<body>
    <span id="iconPreload" class="glyphicon glyphicon-arrow-down"></span>
    <div id="chart"></div>

    <script>
        d3["json"]("/Home/Data", (err, data) => {
            window.initChart(data);
        });
    </script>
</body>
```

```js
"use strict";
var { ChartCanvas, Chart, series, scale, coordinates, tooltip, axes, indicator, helper } = ReStock;
var { CandlestickSeries } = series;
var { XAxis, YAxis } = axes;
var { fitWidth, TypeChooser } = helper;

class CandleStickChart extends React.Component {
	render() {
		var { type, width, data, ratio } = this.props;
		return (
			<ChartCanvas ratio={ratio} width={width} height={400}
                margin={{ left: 50, right: 50, top: 10, bottom: 30 }} type={type}
                seriesName="Test Series"
                data={data}
                xAccessor={d => d.date} 
                xScale={d3.scaleTime()}>

				<Chart id={1} yExtents={d => [d.high, d.low]}>
					<XAxis axisAt="bottom" orient="bottom" ticks={6}/>
					<YAxis axisAt="left" orient="left" ticks={5} />
					<CandlestickSeries />
				</Chart>
			</ChartCanvas>
		);
	}
}

CandleStickChart.propTypes = {
	data: React.PropTypes.array.isRequired,
	width: React.PropTypes.number.isRequired,
	ratio: React.PropTypes.number.isRequired,
	type: React.PropTypes.oneOf(["svg", "hybrid"]).isRequired,
};

CandleStickChart.defaultProps = {
	type: "svg",
};
CandleStickChart = fitWidth(CandleStickChart);


window.initChart = function(data) {
    data.forEach((d, i) => {
        d.date = new Date(d.date);
        d.low = +d.low;
        d.high = +d.high;
        d.open = +d.low;
        d.close = +d.high;

        // checking on Console that no d.date value is undefined/null
		console.log(d.date);
    });
    
    /* change the type from hybrid to svg to compare the performance between svg and canvas */
	ReactDOM.render(<CandleStickChart data={data} type={"hybrid"} />, document.getElementById("chart"));
}
```

**Comment by amhed** [comment]
Data being requested from **/Home/Data** endpoint looks like the following

```json
[
    {
        "date": "2017-05-23T00:00:33Z",
        "low": 160.26,
        "high": 166.83132,
        "type": "Buy"
    },
    {
        "date": "2017-05-22T23:01:59Z",
        "low": 128.7324,
        "high": 168.50013,
        "type": "Buy"
    },
    {
        "date": "2017-05-22T22:00:22Z",
        "low": 132.16,
        "high": 172.00001,
        "type": "Buy"
    },
    ...
]
```

**Comment by rrag** [comment]
I dont see a problem with this code, `xExtents` is not even there. if you could share a plunker or a minimal reproduction example in a public github project, I will be happy to help.

**Comment by amhed** [comment]
Here it is :D 
https://plnkr.co/edit/4txaTBEeaL0kLzgX5rS5?p=preview

**Comment by amhed** [comment]
🤔 I think the problem is that my market data was ordered in descending order. I sorted correctly and now working as expected. Thanks for all the help! your library rocks!

**Comment by rrag** [comment]
cool

**Comment by PrimeTimeTran** [comment]
@rrag mind giving me a pointer as well? 

Is there a minimum amount of data points we need have for CanvasCharts to work? I'm trying to implement this [CandleStick chart](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChart) and I've been troubleshooting for some time now and can't seem to figure it out. 

I searched through the documentation and couldn't seem to find something I understood to explain it. I also read through other posts and implemented the correct sort, but I'm sorta outta ideas of what to do at this point.

# Works, when I specify the default range:
```
const xExtents = [
  xAccessor(last(data)),
  xAccessor(data[data.length - 100])
];
```
![screen shot 2018-01-13 at 12 24 01 am](https://user-images.githubusercontent.com/16382165/34887289-8d51d594-f7f8-11e7-91e0-b231c4d71127.jpg)

# Fails when I specify a custom range:
```
const xExtents = [
  xAccessor(last(data)),
  xAccessor(data[data.length - 10])
];
```
![screen shot 2018-01-13 at 12 23 47 am](https://user-images.githubusercontent.com/16382165/34887299-9913fe0c-f7f8-11e7-8324-03db6a7f2eb2.jpg)

# Correctly sorted:
![screen shot 2018-01-13 at 12 33 15 am](https://user-images.githubusercontent.com/16382165/34887522-660956c8-f7f9-11e7-9c54-996cdb1378ff.jpg)

# Thanks for reading and for the awesome library!

**Comment by rrag** [comment]
could you enable some debug like 
```
// from console
localStorage.debug="react-stockcharts:*"
```

and then refresh the page

few things which you might want to check 

1. `xExtents` has to be `[small, big]` but you have it as `[big, small]`
2. `xAccessor` can you make it as `d => d.date` I am not sure why do `new Date(d)` inside `xAccessor` `d` would be an object `{ date, open, high, low, close }`

**Comment by PrimeTimeTran** [comment]
@rrag thanks for the pointer. That helped. I believe the problem is how the data is structured from the original TSV parse `.then(data => tsvParse(data, parseData(parseDate)))` to when I try to render from my own backend JSON API. 
![screen shot 2018-01-16 at 9 02 29 am](https://user-images.githubusercontent.com/16382165/34968505-3dda7902-fa9c-11e7-8a5e-e3b12adcd42c.jpg)
![screen shot 2018-01-16 at 9 02 54 am](https://user-images.githubusercontent.com/16382165/34968506-3e0b77aa-fa9c-11e7-9de8-65f8e926c9d1.jpg)


Once again, I poked around [this documentation ](http://rrag.github.io/react-stockcharts/documentation.html#/candlestick_chart), but I couldn't find anywhere where that's documented. Would you mind giving me a recommendation? Thanks again for your help

**Comment by rrag** [comment]
Hi, looks like you are parsing a tsv as a JSON. that wont work.

**Comment by PrimeTimeTran** [comment]
Yeah, I noticed that after posting. My bad once again, lol. I corrected it though.
![screen shot 2018-01-16 at 9 14 54 am](https://user-images.githubusercontent.com/16382165/34968761-bd9bd31a-fa9d-11e7-9027-cf289ac65a31.jpg)

**Comment by PrimeTimeTran** [comment]
@rrag thanks being so helpful bro. Sorry I suck at JS. I'm a ruby / C++ dev and haven't really ever got to use JS extensively. I appreciate the pointers.

**Comment by rrag** [comment]
what is the problem again? I am not following sorry

**Comment by PrimeTimeTran** [comment]
I'd like to be able to parse a JSON response that looks like this. I tried to structure it as similarly to the TSV as I could but keep getting errors when parsing. 
![screen shot 2018-01-16 at 9 23 31 am](https://user-images.githubusercontent.com/16382165/34968964-ff1fd556-fa9e-11e7-9b04-d466a5e67924.jpg)

**Comment by rrag** [comment]
just do a `JSON.parse` on this, and you will also have to parse the date which is a string into a `Date` object.

if you are using `fetch` you can do `response.json` which will parse the result for you. Then `console.log` the output and find where the data is present.

**Comment by johnreytanquinco** [comment]
Hi @rrag , when you say
>xExtents has to be [small, big] but you have it as [big, small]

Could you please clarify why it should be that way?
I can see that even in the example chart like https://codesandbox.io/s/pj4l0jwkpm, xExtents is in  [big, small].

Question related to xExtent, why do I get an error message saying `Showing 0 datapoints, review the 'xExtents' prop of ChartCanvas` when the end value of my xExtent is on `0`? Wont the chart consider it as the first index of the data? Or it is related to other problem?

Actual value in console logs:
`xExtents (2) [44, 0]`

Appreciate your response. Thanks!

**Comment by NoCluePS** [comment]
Hey, had the same issue, nothing helped... 
Only changing xExtents to `xExtents={[xAccessor(chartData[0]), xAccessor(last(chartData))]}` didn't throw a fatal error...

The chart is looking like this at the moment:

![image](https://user-images.githubusercontent.com/93134247/144663089-8d543154-4fd8-4ca8-8459-42f4f8f8307c.png)

Code in use: 
![Screenshot 2021-12-03 at 21 42 20](https://user-images.githubusercontent.com/93134247/144663308-c423c1b9-0ac5-41ff-85e3-eef398c44597.png)

![Screenshot 2021-12-03 at 21 45 24](https://user-images.githubusercontent.com/93134247/144663690-ff070ce6-3c86-40f3-9155-ad92f553e133.png)
