### ISSUE TITLE
http://rrag.github.io/stockcharts-demo/ source

### ISSUE THREAD

**Issue by stanbor** [rrag/react-stockcharts#269]
Hi,

is it possible to share the source of this http://rrag.github.io/stockcharts-demo/ ?

In here there is empty repo https://github.com/rrag/stockcharts-demo

It would be nice to have a source of some chart with top menu (indicator selection, chart type, drawing, settings)

Or maybe you already have the latest version with top menu?

This one http://rrag.github.io/react-stockcharts/ doesn't have any menus in source

**Comment by madhumurugan89** [comment]
Yes. It will be really helpful for us. Please share the source

**Comment by stanbor** [comment]
I'm still beginner and I'm sort of learning with this so pardon my questions, maybe trivial for you, but it's more complicated for me

**Comment by leedstyh** [comment]
@rrag said that demo is not open source. https://github.com/rrag/react-stockcharts/issues/95

**Comment by fxhst329** [comment]
ah ok thanks

**Comment by stanbor** [comment]
I'm not sure why is it not open source if all other examples are, but at least I will try it myself
