### ISSUE TITLE
Market depth custom series

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#27]
As far as I know you are planning to demonstrate an example of custom dataTransform, and custom indicator documentation.
Could you for example, use the graph type market depth. I tried to encode similar but it didn't work.

**Comment by rrag** [comment]
Custom indicator & series is already documented. Data transform it little complex, and I will need some more time before I do that.

About market depth graph, that will be an indicator not dataTransform. I will look at it and update the documentation or add the indicator, but not for few more days, sorry.

On a different topic, I started to work on a [demo](http://rrag.github.io/stockcharts-demo/) and running into some problems which I want to fix first before adding more features. would appreciate some feedback for the demo,

**Comment by nosenko86** [comment]
Demo is super! I have a couple of questions. I didn't find a licence file. What kind of licence, MIT or another? Can i use your charts free?

How i can change time frame on charts? Where is the window of changing/choosing symbols stocks?

Thanks in advance!

**Comment by 3456smille** [comment]
The demo looks great! At first glance, I would recommend a quick-remove button on indicators so you don't have to click the settings in order to do so. I realize this is a trivial feature though.

In addition to the questions regarding timeframe/symbol changes, I was wondering about some additional documentation for additional interactive tools such as trendlines, fibonacci retracements, etc. Any help would be appreciated!

**Comment by 3456smille** [comment]
Also, would you happen to have any examples of passing data to the chart from a live feed such as a websockets server?

**Comment by rrag** [comment]
Let us take the discussion on demo to https://github.com/rrag/react-stockcharts/issues/28

**Comment by rrag** [comment]
@nosenko86 it is MIT, I thought I had the license file, will add when releasing next version

**Comment by rsklyar** [comment]
could you provide email for demo feedback ?

**Comment by rrag** [comment]
Sorry, I am not following the question. We can use #28 to discuss demo
