### ISSUE TITLE
how to set x axis zoom level ? 

### ISSUE THREAD

**Issue by madhumurugan89** [rrag/react-stockcharts#270]
how to set x axis zoom level ? actually i need to set the x-axis zoom level based on some dropdown values. need to show the graph in minutes, 5 minutes and 30 minutes. pls let me know any way

**Comment by rrag** [comment]
I am not following how does showing a chart with 5/30 min candles impact the x axis. it is the same as displaying a 1d candle. I guess you want to control the domain of the x axis, and to do that `xExtents` is your friend. Look at the [brush](http://rrag.github.io/react-stockcharts/documentation.html#/brush) example

there will be breaking changes (it will be easier) in 0.7 though, check out https://github.com/rrag/react-stockcharts/issues/206 for more details if you are interested

**Comment by madhumurugan89** [comment]
@rrag thanks for the reply. 
The problem is i am showing values in minutes, but when the chart by default is showing at the higher level. so inorder to see the values of x-axis in minutes/hours we have to zoom in.

**Comment by rrag** [comment]
If you have a drop down of intervals (say 1min, 5min, 10min, 1h, 1d, 1w, 1m) and upon changing the drop down, you wish to show a chart of that interval, then you need to have `data[]` for that interval. if all you have is 1 min data, then you need to be able to aggregate/rollup that 1 min data into the intervals and provide that data[] upon dropdown value change.

**Comment by borm** [comment]
If i right understand, we must filter our data ourselves
