### ISSUE TITLE
How do you delete a specific interactive tool?

### ISSUE THREAD

**Issue by SangYi** [rrag/react-stockcharts#271]
I have multiple trendlines and Fibonacci up and I just want to delete the specific one I've selected.  Currently the example charts only delete the last trendline in the array.

Can anybody help me out please?

Thank you very much in advance.

**Comment by rrag** [comment]
if you have 5 trendlines, and wanted to remove the 2nd, then you would have to modify the array without the 2nd trendline. The examples do not show advanced usecases, only simple ones, but I was hoping it would give an idea of how to achieve a more complex requrement
