### ISSUE TITLE
Getting started with wrong nodejs version (must use latest nodejs 6.10.3)

### ISSUE THREAD

**Issue by jameslulusoft** [rrag/react-stockcharts#272]
I ran into issues when trying to start nodejs on the source code. I was using nodejs 4.6.0 which was the root cause of the issue. After updating my nodejs to 6.10.3 my issue disappeared. Below was my help request to @rrag and his response. 

==Question===

Hey Ragunath,

Great project! I want to make a contribution to the project by adding a few extra features to the axis.js .  I'm getting stuck on the first step of setting up for development. I've followed the steps:

$ git clone <git url>
$ cd react-stockcharts
$ npm install
$ npm run watch <<<<< stuck on the last step

The npm run watch fails when it tries to parse config/webpack.config.js .  It appears that npm doesn't like the ES6 syntax in the file. For example, npm reports the following error

const { getIfUtils, removeEmpty } = require("webpack-config-utils");
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/Users/jameslu/Desktop/react-stockcharts-y-axis-fix/node_modules/webpack/bin/convert-argv.js:96:18)

    at /Users/jameslu/Desktop/react-stockcharts-y-axis-fix/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)

Do you have this issue? I should have babel installed but I still get the error. Running npm install doesn't generate any errors. I also see babel listed as a dependency. Do you have any recommendations? Thanks!

==Response===
Hello James,

I guess the problem is the node version you have. It should be 6.10+
based on the error looks like object destructuring is the problem I think it was introduced in node 6.8, to be safe use the latest node version.

I really appreciate you taking the time to contribute, but it would be great if you ask such questions in github so it helps not only you but also others who might have a similar problem. 

-Ragu

**Comment by rrag** [comment]
Thank you
