### ISSUE TITLE
How to create a market depth chart?

### ISSUE THREAD

**Issue by ashishkkhatri** [rrag/react-stockcharts#273]
<img width="1209" alt="screen shot 2017-05-25 at 11 45 41 am" src="https://cloud.githubusercontent.com/assets/15785745/26439167/8c63be38-4144-11e7-8a67-b7c35509d945.png">
Is it somehow possible to make depth chart as in image above using react-stockchart library.

Any suggestions is welcome even if it is achievable by using any other charting library in react.

**Comment by rrag** [comment]
it is currently not possible to implement this in react-stockcharts, unfortunately I dont have a suggestion on how to do this using a different library.
I also don't think it is complex to implement, so I would welcome some ideas via a PR if anyone is interested

related: https://github.com/rrag/react-stockcharts/issues/31

**Comment by stanbor** [comment]
In financial markets, the mid price is the price between the best price of the sellers of the stock or commodity offer price or ask price and the best price of the buyers of the stock or commodity bid price. It can simply be defined as the average of the current bid and ask prices being quoted.
... so first you need Bid and Ask to construct middle point (bid+ask/2)

then you need market depth (full book) so you have volume for each corresponding price... so the charts would need to get full book info for given tick from which you can get the volumes for all price levels between bid  and ask to construct the volume

so the charts would need to be able to work with full book data and not only classic OHLCV data - either csv files or real-time streaming

**Comment by rrag** [comment]
yes @stanbor this has to be a separate from the regular ohlc data.

If anyone is interested in implementing this I welcome a PR (on the `next` branch), but I am not going to implement this myself

**Comment by trevorbernard** [comment]
@rrag How much effort do you think it would take? I'd be interested in tackling a market depth chart or potentially paying someone to

**Comment by shprink** [comment]
Guys I got pretty close:

![image](https://user-images.githubusercontent.com/1388706/32001534-5cd74792-b99a-11e7-8379-56edee074bf3.png)

```
  render() {
    const { ticks, width, muiTheme } = this.props;

    const gridHeight = height - margin.top - margin.bottom;
    const gridWidth = width - margin.left - margin.right;
    const yGrid = showGrid ? { innerTickSize: -1 * gridWidth } : {};
    const xGrid = showGrid ? { innerTickSize: -1 * gridHeight } : {};

    const xExtents = [first(ticks).x, last(ticks).x];

    return (
      <Wrapper>
        {isSubmitting || !ticks
          ? <CircularProgress />
          : <ChartCanvas
            height={height}
            ratio={2}
            width={width}
            margin={margin}
            type="svg"
            seriesName="MSFT"
            data={ticks}
            panEvent={false}
            zoomEvent={false}
            xScale={scaleLinear()}
            xExtents={xExtents}
            xAccessor={d => d.x}
          >
            <Chart
              id={1}
              yExtents={d => [d.y_buy, d.y_sell]}
              yScale={scaleLinear()}
            >
              <XAxis
                axisAt="bottom"
                orient="bottom"
                {...xGrid}
              />
              <YAxis
                axisAt="right"
                orient="right"
                ticks={5}
                {...yGrid}
              />
              <AreaSeries
                yAccessor={d => d.y_sell}
              />
              <AreaSeries
                yAccessor={d => d.y_buy}
              />
            </Chart>

            <CrossHairCursor />
          </ChartCanvas>}
      </Wrapper>
    );
  }
```

and the data looks likes this:

```
const data= [{x: 0, y_sell: 0.5, y_buy: undefined}, {x: 1, y_sell: undefined, y_buy: 0.5}]
```

**Comment by Alexander-Herranz** [comment]
Hi,

Great job man! I'm also struggling with market depth chart, trying to achieve it merging histograms or trying to modifying default cuve in line charts, but not getting expected. 

Did you get something more? Thanks!

**Comment by ryardley** [comment]
Hi. I need to build this for the project I am working on. My plan is to fork and modify to make this work after which I will gladly submit a PR to this lib. Looking at the work that @shprink has done, @rrag would I be correct in my understanding that all that is really needed here from RSC point of view is a "stepped" area series or is there more complexity you would expect I need to take into account? eg. do we need to be able to control the direction of the steps left or right or is that unimportant? (I am new to financial dashboards sorry if that is a naive question)

**Comment by flavioespinoza** [comment]
https://gist.github.com/flavioespinoza/e7b086abf3f28ee05967d205f850b6af

This is a work in progress, but it's a good start.

<img width="455" alt="screen shot 2017-12-01 at 1 26 50 am" src="https://user-images.githubusercontent.com/2214913/33474323-654eddae-d637-11e7-8f1d-5cd001c7ddc8.png">

**Comment by oskarer** [comment]
@rrag How do you mean change interpolation to stepBefore / stepAfter?

**Comment by gbalabasquer** [comment]
@oskarer @rrag I have same the question. `interpolation` seems to ask for a function?

**Comment by JeffScaturro** [comment]
> Hey can anybody post a complete working example for the depth chart? =]

Or better yet, an integration branch or diff? 😄

**Comment by Ejnot** [comment]
![image](https://user-images.githubusercontent.com/25398663/38792255-a541949e-417e-11e8-8754-25b9da6b9d95.png)


I created this one using same approach that @shprink does the only problem that i'm having here is it doesnt always centered or no middle points. I think controlling xExtents but I haven't figured out hpw. I also tried using 2 totally different area charts one only rendering the bid side and the other one is only rendering the ask side which resulted to good view but the problem now is the XAxis since 2 chart will have a different xaxis. If anyone willing to work with me to figured out how to render the depth in always centered.

**Comment by chanmathew** [comment]
@Thurstonjhon did you end up figuring it out? Mind sharing if anyone has a fully working example?

**Comment by Thurstonjhon** [comment]
I can't create an example because of a busy schedule, but the trick is you need to zoom in where the buy and sell orders met, and to do that you need to modify your data series you can achieve that editing this line from the example of shprink above `[first(ticks).x, last(ticks).x];` you can put dynamic data points instead of displaying all the orders from first tick to last tick.

**Comment by weishiji** [comment]
> ![image](https://user-images.githubusercontent.com/25398663/38792255-a541949e-417e-11e8-8754-25b9da6b9d95.png)
> 
> I created this one using same approach that @shprink does the only problem that i'm having here is it doesnt always centered or no middle points. I think controlling xExtents but I haven't figured out hpw. I also tried using 2 totally different area charts one only rendering the bid side and the other one is only rendering the ask side which resulted to good view but the problem now is the XAxis since 2 chart will have a different xaxis. If anyone willing to work with me to figured out how to render the depth in always centered.

how do you solve this question finally, I got the same proplem

**Comment by machy44** [comment]
I made it with two separated chart canvases.

`  <ChartCanvas
          ratio={1}
          width={width / 2 - 10}
          height={height}
          margin={{ left: 5, right: 0, top: 5, bottom: 30 }}
          seriesName="MSFT"
          data={buyOrdersSorted}
          type={type}
          xAccessor={d => d.price}
          panEvent={false}
          seriesName={`MSFT_${this.state.suffix}`}
          xExtents={xExtentsBuy}
          zoomEvent={false}
          xScale={scaleLinear()}
        >
          <Chart id={10} yExtents={yAxisRange} width={width / 2}>
            <Gradient
              id="buyGradient"
              color1="#009900"
              color2="#00b200"
              color3="#00cc00"
            />
            <XAxis
              axisAt="bottom"
              orient="bottom"
              tickStroke={axisColor}
              ticks={5}
              zoomEnabled={false}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <AreaSeries
              yAccessor={d => d.type == "buy" && d.volume}
              fill="url(#buyGradient)"
              canvasGradient={buyGradient}
              strokeWidth={2}
              stroke={COLOR_PALETTE.depthBuyGreen}
              interpolation={curveStep}
            />
            <YAxis
              stroke="#000000"
              axisAt="left"
              orient="right"
              tickStroke={axisColor}
              ticks={5}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <HoverTooltip
              tooltipContent={tooltipContent(currency)}
              bgFill={linesColor}
              stroke={linesColor}
              fill="#ffffff"
              bgOpacity={1}
              fontFill="#000000"
              opacity={1}
              fontFamily={"inherit"}
            />
            <CurrentCoordinate
              yAccessor={d => d.volume}
              fill={linesColor}
              r={5}
              onHover
            />
          </Chart>
        </ChartCanvas>
        <ChartCanvas
          ratio={1}
          width={width / 2 - 10}
          height={height}
          margin={{ left: 0, right: 5, top: 5, bottom: 30 }}
          seriesName="MSFT"
          data={sellOrdersSorted}
          type={type}
          xAccessor={d => d.price}
          panEvent={false}
          seriesName={`MSFT_${this.state.suffix}`}
          xExtents={xExtentsSell}
          zoomEvent={false}
          xScale={scaleLinear()}
        >
          <Chart
            id={11}
            // yExtents={d => d.volume}
            yExtents={yAxisRange}
            width={width / 2}
          >
            <Gradient
              id="sellGradient"
              color1="#cc0000"
              color2="#b20000"
              color3="#990000"
            />
            <XAxis
              axisAt="bottom"
              orient="bottom"
              tickStroke={axisColor}
              ticks={5}
              zoomEnabled={false}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            {/* empty axis in the middle of depth chart */}
            <YAxis
              stroke="#000000"
              axisAt="left"
              orient="right"
              tickStroke={axisColor}
              ticks={0}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <YAxis
              axisAt="right"
              orient="left"
              tickStroke={axisColor}
              ticks={5}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <AreaSeries
              yAccessor={d => d.type == "sell" && d.volume}
              canvasGradient={sellGradient}
              fill="url(#sellGradient)"
              stroke={COLOR_PALETTE.depthSellRed}
              strokeWidth={2}
              interpolation={curveStep}
            />
            <HoverTooltip
              tooltipContent={tooltipContent(currency)}
              bgFill={linesColor}
              stroke={linesColor}
              fill="#ffffff"
              bgOpacity={1}
              fontFill="#000000"
              opacity={1}
              fontFamily={"inherit"}
            />
            <CurrentCoordinate
              yAccessor={d => d.volume}
              fill={linesColor}
              r={5}
              onHover
            />
          </Chart>
        </ChartCanvas>`

**Comment by machy44** [comment]
I made it with two separated chat canvases.
Your buy and sell data need to be sorted by volume: 
buy side [greatestVolume, minimalVolume]
sell side [minimalVolume, greatestVolume ]

object structure needs to look like this:
```javascript
[{ price: 3971.28
  type: "sell"
  volume: 7.05501075,
  cost: volume* price
},...]
```

you need to see which side have greater value(volume) and make that as a yExtents=[minVolume, maxVolume] on both charts. They need to have the same range on y-axis
```javascript
  <ChartCanvas
          ratio={1}
          width={width / 2 - 10}
          height={height}
          margin={{ left: 5, right: 0, top: 5, bottom: 30 }}
          seriesName="MSFT"
          data={buyOrdersSorted}
          type={type}
          xAccessor={d => d.price}
          panEvent={false}
          seriesName={`MSFT_${this.state.suffix}`}
          xExtents={xExtentsBuy}
          zoomEvent={false}
          xScale={scaleLinear()}
        >
          <Chart id={10} yExtents={yAxisRange} width={width / 2}>
            <Gradient
              id="buyGradient"
              color1="#009900"
              color2="#00b200"
              color3="#00cc00"
            />
            <XAxis
              axisAt="bottom"
              orient="bottom"
              tickStroke={axisColor}
              ticks={5}
              zoomEnabled={false}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <AreaSeries
              yAccessor={d => d.type == "buy" && d.volume}
              fill="url(#buyGradient)"
              canvasGradient={buyGradient}
              strokeWidth={2}
              stroke={COLOR_PALETTE.depthBuyGreen}
              interpolation={curveStep}
            />
            <YAxis
              stroke="#000000"
              axisAt="left"
              orient="right"
              tickStroke={axisColor}
              ticks={5}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <HoverTooltip
              tooltipContent={tooltipContent(currency)}
              bgFill={linesColor}
              stroke={linesColor}
              fill="#ffffff"
              bgOpacity={1}
              fontFill="#000000"
              opacity={1}
              fontFamily={"inherit"}
            />
            <CurrentCoordinate
              yAccessor={d => d.volume}
              fill={linesColor}
              r={5}
              onHover
            />
          </Chart>
        </ChartCanvas>
        <ChartCanvas
          ratio={1}
          width={width / 2 - 10}
          height={height}
          margin={{ left: 0, right: 5, top: 5, bottom: 30 }}
          seriesName="MSFT"
          data={sellOrdersSorted}
          type={type}
          xAccessor={d => d.price}
          panEvent={false}
          seriesName={`MSFT_${this.state.suffix}`}
          xExtents={xExtentsSell}
          zoomEvent={false}
          xScale={scaleLinear()}
        >
          <Chart
            id={11}
            // yExtents={d => d.volume}
            yExtents={yAxisRange}
            width={width / 2}
          >
            <Gradient
              id="sellGradient"
              color1="#cc0000"
              color2="#b20000"
              color3="#990000"
            />
            <XAxis
              axisAt="bottom"
              orient="bottom"
              tickStroke={axisColor}
              ticks={5}
              zoomEnabled={false}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            {/* empty axis in the middle of depth chart */}
            <YAxis
              stroke="#000000"
              axisAt="left"
              orient="right"
              tickStroke={axisColor}
              ticks={0}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <YAxis
              axisAt="right"
              orient="left"
              tickStroke={axisColor}
              ticks={5}
              yZoomWidth={0}
              tickStroke={linesColor}
              stroke={linesColor}
            />
            <AreaSeries
              yAccessor={d => d.type == "sell" && d.volume}
              canvasGradient={sellGradient}
              fill="url(#sellGradient)"
              stroke={COLOR_PALETTE.depthSellRed}
              strokeWidth={2}
              interpolation={curveStep}
            />
            <HoverTooltip
              tooltipContent={tooltipContent(currency)}
              bgFill={linesColor}
              stroke={linesColor}
              fill="#ffffff"
              bgOpacity={1}
              fontFill="#000000"
              opacity={1}
              fontFamily={"inherit"}
            />
            <CurrentCoordinate
              yAccessor={d => d.volume}
              fill={linesColor}
              r={5}
              onHover
            />
          </Chart>
        </ChartCanvas>

```

![image](https://user-images.githubusercontent.com/7934791/54760795-13a08800-4bf1-11e9-9444-7626d09fe63c.png)

**Comment by 0xAskar** [comment]
@machy44 you mind just expanding a bit more on all the variables you used, such as the sorted sells/buys, the xExtentsBuy/Sell, type, buyGradient, COLOR_PALETTE,... 

it's my first time learning the library. thanks for your help
