### ISSUE TITLE
how implement don`t disable render when pan enabled

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#275]
This issue about updating data example, when panInProgress - data not render

Here you set default panInProgress = false;
https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L280

and here you check if it true don`t appended any new data to the chart
https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.jsx#L755

**Comment by rrag** [comment]
During pan action the state is not updated (in canvas mode), this is to provide a better performance, but updating data during pan means there has to be a `setState` to show the new data. I understand the issue, but fail to see why this is important or the motivation to get this fixed. I lean on on a `wont fix` status for this till I am convinced of the value of this change

**Comment by borm** [comment]
So, only one case for why i want you fix it,
when last Point is Visible only

**Comment by rrag** [comment]
ha ha that is the only case where it wont work, provide a rationale on why this is important. will reopen if I am satisfied, but for now this will be a `wont fix` type of issue. It is complex and I dont see the benefit
