### ISSUE TITLE
how set min and max view domain range when pan, i want see max 50% domain width when pan left or right end of chart

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#276]
When pan on the chart left or right side, if pan max to left side we see
![1](https://cloud.githubusercontent.com/assets/4027842/26507249/29937d06-4258-11e7-86cf-bb1ee18f3ac2.gif)

I want can only max 50% pan from full width of chart
![2](https://cloud.githubusercontent.com/assets/4027842/26507642/f787df44-4259-11e7-897d-5c6d2200ca98.gif)

**Comment by rrag** [comment]
Can you explain the value of this feature?

Initially (till v0.3 I think) I had it as 33% pan was allowed, that complicated the code, and caused a few defects so that is all in the past now. This also I am leaning on `wont fix` till I am convinced of the value of this

**Comment by borm** [comment]
I dont full understand what you asked me, i like max pan as your [demo](http://rrag.github.io/stockcharts-demo/)

**Comment by rrag** [comment]
I want to understand why this has to be implemented. I don't understand the benefit over the current implementation
