### ISSUE TITLE
how set animation for updating data component

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#277]
This issue about updating data example

So, how add animation Seies and XAxis when data updating like this 
https://codepen.io/atticweb/pen/GZKvgv

for see animations series scroll up down up down up down

**Comment by rrag** [comment]
right now there are no animations anywhere in the lib, it would be a nice addition though. Although I would like to think about animation on the whole, 

for e.g. in zoom, and pan to load more data also appearing slowly in an animation, hover tooltip box moving, or even when a new `LineSeries` is added/removed it could animate in/out

This one is close to my heart to see these animations in place. When ever I think about this, it comes to mind that this will be too big of an undertaking with many edge cases and I pass. I like to hear your thoughts, it would be good if we could work together and bounce ideas on this

**Comment by borm** [comment]
I would gladly help you, but while your project is complicated for the level of my knowledge, the more I do not know canvas at all, maybe later, when i figure out more in the code, I can make my own

**Comment by rrag** [comment]
No plans for now
