### ISSUE TITLE
Looking for feedback on demo

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#28]
[demo](http://rrag.github.io/stockcharts-demo/) 

Working on this now, Looking for feedback,
Might lead to new features implemented on the real project

**Comment by rrag** [comment]
https://github.com/rrag/react-stockcharts/issues/27#issuecomment-150018452
> How i can change time frame on charts? Where is the window of changing/choosing symbols stocks?

You can zoom in/out using mouse scroll and pan left/right with mouse drag. Are you looking for a separate component as a shortcut with values like 5D, 1M, 3M, 6M, 1Y, 5Y, ALL?

That is not built yet. I don't see that as demo specific, it should be a new feature on the chart library

https://github.com/rrag/react-stockcharts/issues/27#issuecomment-150237510
> The demo looks great! At first glance, I would recommend a quick-remove button on indicators so you don't have to click the settings in order to do so. I realize this is a trivial feature though.

Noted, I thought the same also, but it would mean changing the component. Alternatively I was thinking on the lines of right click, remove /  make invisible.

https://github.com/rrag/react-stockcharts/issues/27#issuecomment-150238997
> Also, would you happen to have any examples of passing data to the chart from a live feed such as a websockets server?

There is an example on [updating data](http://rrag.github.io/react-stockcharts/documentation.html#/updating_data) you should check out

**Comment by rsklyar** [comment]
Demo reference:

1. OHLCTooltip

Tooltip not informative:
    additional functionality:
        - Change: +/- %%
            Description:  Just take last (or current) "+Close", and calculate percentage using mouse position.
            Example:
        - Amplitude: +/- %%
            Description:
            Example:
        - OFFSET: < +/- hours,days,weeks, ...>, <Change> / -<Change>,
            Description:
            Example:

    improvments:
    Date: <YYMMDD> <time> <WeekDay> O: <>, C: <>, H: <>, L: <>, V: <>

2. Timescale:

  Add: 1W 3d 1d(24h) 12h 4h 2h 1h 30m 15m 5m 3m 1m
  1W: 2015 <May> <SEP> 2016 <MAY> <SEP> 2017 <MAY> <SEP> 2018 <MAY> <SEP> etc.
  3D: 2014 <Mar> <May> <Jul> <Sep> <Nov> 2015  Mar> <May> <Jul> <Sep> <Nov> etc.
  1D: 2015 <Feb> <Mar> <Apr> <May> <Jun> <Jul> <Aug> <Sep> <Oct> <Nov> <Dec> 2016
  ...


  Add
  Time position on indicators


3. Volume currency switch button
  Full market data for candlestick is:
      + Volume <Base> (USD for example) <Quote> (S&P...)

  Fo more cute demo try to add Volume switcher (is it volume profile ? )

4. TimeZone Switcher (Local, UTC)

5. Scale switcher (Linear, Logarithmic):

6. Theme Switcher

  Dark or Light

  light is a pain for traders eyes

7. Indicator section:

add abbreviation for each indicators

8. Basic Chart and Advanced Chart

Add:
    <Chart Style>: Area, Line (add Line o), CandleStick, CandleStickHLC, OHLC, (etc Renko ...)

For Area:
    <Area Style>: <Close>, <Medium Price>, <Volume Wighted>

For Line (Line o):
    <Line Style>: <Close>, <Medium Price>, <Volume Wighted>

For CandleStick:

Candle Stick Style:
    CandleStick Style:  <CandleStick>, <CandleStickHLC>, <OHLC>

9. Chart Range switcher: <Auto>, <Max>


10. PopUp Window for Technical parameters:

Traders should customize indicator parameters

MACD (4), RSI (1), ...

add default button

**Comment by rsklyar** [comment]
Demo reference:

OHLCTooltip

Tooltip not informative:
    additional functionality:
        - Change: +/- %%
            Description:  Just take last (or current) "+Close", and calculate percentage using mouse position.
        - Amplitude: +/- %%
            Description:

        - OFFSET: " +/- hours,days,weeks, ...", "Change" / -"Change",
            Description:
            Example:
        - Date: "YYMMDD" "time" "WeekDay" O: "", C: "", H: "", L: "", V: ""

Timescale:

  Add: 1W 3d 1d(24h) 12h 4h 2h 1h 30m 15m 5m 3m 1m
  1W: 2015 "May" "SEP" 2016 "MAY" "SEP" 2017 "MAY" "SEP" 2018 "MAY" "SEP" etc.
  3D: 2014 "Mar" "May" "Jul" "Sep" "Nov" 2015  Mar" "May" "Jul" "Sep" "Nov" etc.
  1D: 2015 "Feb" "Mar" "Apr" "May" "Jun" "Jul" "Aug" "Sep" "Oct" "Nov" "Dec" 2016
  ...


  Add
  Time position on indicators


Volume currency switch button
  Full market data for candlestick is:
      + Volume "Base" (USD for example) "Quote" (S&P...)

  Fo more cute demo try to add Volume switcher (is it volume profile ? )

4. TimeZone Switcher (Local, UTC)

5. Scale switcher (Linear, Logarithmic):

6. Theme Switcher

  Dark or Light

  light is a pain for traders eyes

7. Indicator section:

add abbreviation for each indicators

8. Basic Chart and Advanced Chart

Add:  "Chart Style": Area, Line (add Line o), CandleStick, CandleStickHLC, OHLC, (etc Renko ...)

For Area: "Area Style": "Close", "Medium Price", "Volume Wighted"

For Line (Line o): "Line Style": "Close", "Medium Price", "Volume Wighted"

For CandleStick:
CandleStick Style:  "CandleStick", "CandleStickHLC", "OHLC"

9. Chart Range switcher: "Auto", "Max"


10. PopUp Window for Technical parameters:

Traders should customize indicator parameters

MACD (4), RSI (1), ...

add button "default"

**Comment by psunderr** [comment]
When adding multiple indicators of the same type (EMA, for example), changing the indicator period modifies the first indicator rather than the one selected.

**Comment by psunderr** [comment]
User configurable ATR setting for Renko bricks would be a useful feature as well.

**Comment by rrag** [comment]
> User configurable ATR setting for Renko bricks would be a useful feature as well.

This can be done now, click on the ohlc tooltip

> The same happens when you mix EMA + SMA indicators -- any time the period is edited, only the first indicator is modified.

Thanks, I have to fix that.

**Comment by rrag** [comment]
@rsklyar Thanks for the feedback. There are some I am not following. would you mind expanding on them. like for. e.g. I am not understanding

> Add: 1W 3d 1d(24h) 12h 4h 2h 1h 30m 15m 5m 3m 1m
1W: 2015 "May ...
...
Add
Time position on indicators

It would be great if you can reference your suggestions with http://stockcharts.com/h-sc/ui

**Comment by psunderr** [comment]
@rrag Looks good, the Renko adjustments work fine for me.

I sent you a message via the Gitter chat -- let me know if you see it, or if there's a better way to contact you directly. Thanks!

**Comment by rrag** [comment]
> When adding multiple indicators of the same type (EMA, for example), changing the indicator period modifies the first indicator rather than the one selected

Fixed now.

**Comment by ewindso** [comment]
hi @rrag is there a direct way to capture mouse clicks?  perhaps an event that would send back the data the mouse is currently over?

**Comment by rrag** [comment]
Currently the tooltips have an onclick handler, it is used in the demo.

Can you give an example of what you are trying to achieve it will help me provide a better answer.

I am working on some interactive indicators [trendline](http://rrag.github.io/react-stockcharts/documentation.html#/interactive_indicators_trendline) [fib retracements](http://rrag.github.io/react-stockcharts/documentation.html#/interactive_indicators_fibonacci_retracement), (work in progress and still has some issues), after this I will create documentation on how to create your own custom interactive indicators.

These Interactive indicators will be able to subscribe to various events, currently the two I have mentioned above subscribe to `click` and `mousemove` events, each of which will provide a lot of information including the current mouse xy position, the scales, the nearest datapoint, the entire array of points which is visible on the chart, and more.

Let me know If you are looking for a different usecase.

**Comment by ewindso** [comment]
Thanks for your response.  Yes something like that is what I'm looking for.  Currently I got it to work with  `EventCapture`, using `ChartDataUtil` and I added `plotData` in `contextTypes`.  I'm passing in `onMouseMove` to `EventCapture`.  I have a feeling though it's more of a hack though, but if you'd like me to do a PR I'd be happy to.

**Comment by rrag** [comment]
let me try to understand it better.

you have a `onMouseMove`, `onClick` on `EventCapture` and you send `plotData` and more to the callback when those events happen, is that right?

**Comment by ewindso** [comment]
Almost -- it's in `handleMouseMove` that I added these lines: 

```
		if(this.props.onMouseMove) {
			var chartData = this.context.chartData;
			var newPos = Utils.mousePosition(e);
			var currentItems = ChartDataUtil.getCurrentItems(chartData, newPos, this.context.plotData);
			this.props.onMouseMove(currentItems);
		}
```

**Comment by rrag** [comment]
I like the idea of providing callback, but this is exposing some of the internal objects used, I am not too sure if that is good.

what are you using this callback for? may be there is an alternative.

**Comment by ewindso** [comment]
I understand, hm...  ideally I'd like to be able to identify entry and exit points by clicking on the chart, and dynamically update an overlay chart with that data / persist data to DB.

**Comment by rrag** [comment]
@ewindso [fib retracements](http://rrag.github.io/react-stockcharts/documentation.html#/interactive_indicators_fibonacci_retracement) [trendline](http://rrag.github.io/react-stockcharts/documentation.html#/interactive_indicators_trendline) are done, I will be releasing a new version with these next week. I am guessing you can use this for your needs.

I do like the idea of providing callbacks from `EventCapture` as sort of a catch all scenario.

**Comment by rrag** [comment]
This is the roadmap for now.

https://github.com/rrag/react-stockcharts/blob/master/docs/md/COMING-SOON.md

**Comment by denisriabchenko** [comment]
Hey guys, have you some solution for "Scale switcher (Linear, Logarithmic)" ?

**Comment by dmytro-y-dev** [comment]
@dryabchenko I know it is a bit late, but still here is the solution.

Since react-stockcharts are based on **d3**, you can use any scales from [d3-scale](https://github.com/d3/d3-scale) library. For example, to use logarithmic scale, simply pass it to Chart component in the next way:

```
import { scaleLog } from 'd3-scale';

<ChartCanvas {...canvasProps}>
   <ChartCanvas yScale={scaleLog()} {...moreChartProps}>
       {/* ... axis, series, tooltips and other components */}
   </Chart>
</ChartCanvas>
```

Make sure that you have a call `scaleLog()`. Simply putting `scaleLog` won't work.

_Disclaimer: I am not affiliated with this project in any way, just a random person who spotted your question._
