### ISSUE TITLE
Another issue on performance

### ISSUE THREAD

**Issue by borm** [rrag/react-stockcharts#280]
Hi, i generated 86400 points with interval 1 second, from yesterday to today 
```
let data = [];
let date = new Date(new Date().getTime() - (60*24)*60000);
// And then push every one second new point to data
for (let i = 0; i < 60*24*60; i++) {
  date = new Date(date.getTime() + 1000);
...
```

I create [plunker](http://plnkr.co/edit/RR5wbN4DwYR3XVjedolJ?p=preview)

Have any idea what can help me?

**Comment by rrag** [comment]
that is just too much data, you should do a pan to load more, so only a few datapoints are downloaded first and more data gets incrementally downloaded as the user pans to see the past

**Comment by rrag** [comment]
also 0.7 beta has some performance improvements which almost improves the performance by 100% when there is lot of data, no difference with 0.6 when there is small amount of data displayed

**Comment by borm** [comment]
Oh, thank, I am try do it now
Note: i use 0.7 beta on my local project too

**Comment by borm** [comment]
Yeah, load more work perfectly, thanks again

**Comment by borm** [comment]
but i add two features to my loadMore function

initial set 
```this.handleDownloadMoreInProgress = false;```

on 
```handleDownloadMoreInProgress(start, end) {

**Comment by rrag** [comment]
when will this `this.handleDownloadMoreInProgress` become false again?

The way I would recommend is, to deal with this on userland, where if there are 2 successive calls to `downloadMore`, the user should cancel the prior download and download the latest only. also a debounce of say 200ms would also help

By doing this way, when one reaches the left most candle and there is nothing more to download the `handleDownloadMore` would simply do nothing

**Comment by borm** [comment]
```javascript
handleDownloadMore(start, end) {
    ...... ( here all code from your example )

    // Check if download more now
    if ( this.handleDownloadMoreInProgress ) return;
    
   // Set state for render
    this.setState({
      handleDownloadMoreInProgress: true,
    }, () => {
      // set local true
      this.handleDownloadMoreInProgress = true;
      .....

      setTimeout(() => {
        // simulate a lag for ajax
        this.setState({
          ....
          handleDownloadMoreInProgress: false, // become false
        }, () => {
          // become false for local
          this.handleDownloadMoreInProgress = false;
        });
      }, 300);
    });

 }

render() {
const {
      data, handleDownloadMoreInProgress,
      ....
    } = this.state;
   return <ChartCanvas
        .... 
        panEvent={!handleDownloadMoreInProgress}
        zoomEvent={!handleDownloadMoreInProgress}
}
```

but i do not understand how combine updating data and load more example

**Comment by rrag** [comment]
oh `handleDownloadMoreInProgress` is already in userland, I understood it as a change in `ChartCanvas.js`, although I still recommend a debounce

RE updating data, I am not sure what the problem is, they are both independent of each other, kindly explain the problem

**Comment by borm** [comment]
my problem is i have copy your [EdgeIndicator](https://github.com/rrag/react-stockcharts/blob/next/src/lib/coordinates/EdgeIndicator.jsx#L118) and change

```javascript
const x1 = Math.round(xScale(xValue)),
y1 = Math.round(yScale(yValue));
```

to
```javascript
const x1 = 0// Math.round(xScale(xValue)),
y1 = Math.round(yScale(yValue));
```

for always see edge indicator

also change [helper](https://github.com/rrag/react-stockcharts/blob/next/src/lib/coordinates/EdgeIndicator.jsx#L93)

```javascript
const { plotData } = moreProps;
```

to 
```javascript
const { fullData: plotData } = moreProps;
```

**Comment by rrag** [comment]
why is `x1 = 0` ? do you want to show the `EdgeIndicator` of the left most candle?

**Comment by rrag** [comment]
scratch that, what is your `itemType`? `last` I guess

if so, then the change 

```diff
- const { plotData } = moreProps;
+ const { fullData: plotData } = moreProps;
```
should be enough no?

**Comment by borm** [comment]
No, i want see line from edge indicator olways from left to right my chart, and for edgeindicator show always only last point of all data no matter when i pan now
![edge](https://cloud.githubusercontent.com/assets/4027842/26528900/b3c9d928-43bd-11e7-992f-80f967bcecb6.gif)

**Comment by rrag** [comment]
ok, so the `x1 = 0` is to get the line from the start of the chart.

Still not following why that is a problem for updating data, `last(fullData)` will continue to remain the same after the pan to add more

**Comment by borm** [comment]
Problem becase when [panToLoadMore](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L151) you calculated new data and it is not full

**Comment by rrag** [comment]
huh

`xScaleProvider(calculatedData.slice(-rowsToDownload).concat(prevData));`

`.concat(prevData)` will make it full right?

**Comment by borm** [comment]
On this case i have  full data with 86400 points, and it very lags,
for chart work normally [here](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L98) we slice our data to [180 points](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L34)

when we have panToDownloadMore, we again slice initialData to 180 points back, and we dont pass full 86400 points to our chart, we pass only 180 points always, i right?

**Comment by borm** [comment]
If i use concat, my data can be very big again

**Comment by rrag** [comment]
initially show 180 points, then when you pan, say you download 100 more, now after [this](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartPanToLoadMore.jsx#L151)

the `linearData []` is of length 100 + 180, so `fullData` would be the 280 points

**Comment by borm** [comment]
Oh, you have right

**Comment by borm** [comment]
Maybe you can tell me what i do write in ```componentWillReceiveProps``` for append new data to state and dont lost my pan position

**Comment by rrag** [comment]
in 0.7 the secret to not losing pan position is to not change `seriesName` or `xExtents` that is all, you could send in a new data[] with data appended.

**Comment by borm** [comment]
I can push new data to state and that all?

**Comment by rrag** [comment]
yes

**Comment by borm** [comment]
Huh, i do not understand what is wrong

[plunker](http://plnkr.co/edit/sdzk7aAji7Zl7zhavmQJ?p=preview)

**Comment by borm** [comment]
Oh, i fix it, [plunker](http://plnkr.co/edit/wOqXijWCUmhsgAKcDsmF?p=preview),
but when pan to left, and wait i see free space
![pan-lag](https://cloud.githubusercontent.com/assets/4027842/26529626/101d0cbe-43cc-11e7-8883-7d2d348271b6.gif)

**Comment by borm** [comment]
Huh, please help, what wrong ?

```javascript
componentWillReceiveProps(props) {

    const { data: prevData, ema26, ema12, macdCalculator, smaVolume50 } = this.state;
    const { data: inputData } = props;
    
    /* SERVER - START */
    const dataToCalculate = inputData.slice(-1);

    const calculatedData = ema26(ema12(macdCalculator(smaVolume50(dataToCalculate))));
    const indexCalculator = discontinuousTimeScaleProviderBuilder()
      .indexCalculator();
    
    const { index } = indexCalculator(
      prevData.concat(calculatedData)
    );
    /* SERVER - END */

    const xScaleProvider = discontinuousTimeScaleProviderBuilder()
      .withIndex(index);

    const { data: linearData, xScale, xAccessor, displayXAccessor } =
      xScaleProvider(prevData.concat(calculatedData));

    this.setState({
      linearData,
      data: linearData,
      xScale,
      xAccessor, displayXAccessor,
    });
    
  }
```

**Comment by rrag** [comment]
that is correct, are you expecting the end to be shown when a new candle is added?

**Comment by borm** [comment]
No, i take screen now

**Comment by rrag** [comment]
Not following, is every thing good?

**Comment by borm** [comment]
https://youtu.be/Klg3mP9ysp0

**Comment by rrag** [comment]
the problem here is App is adding data to the end every second, and the pan to load more is adding data to the front,

but the next second App is adding data to the end without the values already added by the pan to load more, checkout the first and last data in the render method to see this

**Comment by borm** [comment]
So, maybe you can create worked example with dynamic update and load more on pan?

**Comment by rrag** [comment]
Sure that would be useful, I would appreciate if you can make that contribution. I am afraid I will not be able to do that now
