### ISSUE TITLE
Request for Y-axis annotation example

### ISSUE THREAD

**Issue by jameslulusoft** [rrag/react-stockcharts#281]
The chart CandleStickChartWithAnnotate shows an example of how to annotation labels and placing a graphic above a date.  I've been struggling to generate an example that will annotate a graphic beside the yaxis (price). For example, I want to mark a price on the y-axis for my viewers to keep an eye on (ie. their Average Cost of Buying).  

What should I change or add to this to a marker beside a price? Is this feature just missing?

`
		const annotationProps = {
			fontFamily: "Glyphicons Halflings",
			fontSize: 20,
			fill: "#060F8F",
			opacity: 0.8,
			text: "B",
			y: ({ yScale }) => yScale.range()[0],
			onClick: console.log.bind(console),
			tooltip: d => timeFormat("%B")(d.date),
			// onMouseOver: console.log.bind(console),
		};
`

**Comment by borm** [comment]
I think you can use `Label`

```
<Label 
  x={yAxisLabelX} y={yAxisLabelY}
  rotate={-90}
  fontSize="12" text="YAxis Label here" />
```

**Comment by borm** [comment]
I you want use annotation on yAxis you can pass x to `annotationProps`
```
var annotationProps = {
...
  x: ({ xScale }) => xScale.range()[1],
..
};
```

and change `when` as example 
```
<Annotate with={LabelAnnotation}
  when={d => +d.high.toFixed(0) === 46}
  usingProps={annotationProps} />
```
[plunker](http://plnkr.co/edit/z8EBUqgpalEoRSOGLmvj?p=preview)

**Comment by rrag** [comment]
sounds like you want something like an `EdgeIndicator` but does not disappear or change based on the pan/zoom actions.

like show the latest price always irrespective of where you have panned, or may be show a price of a limit order which if breached will trigger an order. for such cases, you would have to create a copy of `EdgeIndicator` and edit it to get your requirement.

I wanted to create an interactive indicator for this, where one can click and drag such an edge indicator and it stays right there on the y irrespective of the pan position. I welcome a PR for such a feature (but on the `next` branch)

**Comment by jameslulusoft** [comment]
What rrag described is pretty much what I am looking for. One of my use cases is to generate an alarm if a price moves through a certain point. Yes, other applications of it can be to trigger an order. I wasn't thinking that far ahead but what a great idea! 

It appears that you already implemented the touch support for the axiszoom in the next branch -- thanks! I can dedicate my time to this feature instead. I'm still pretty new to reactjs so no promises, but I can try :).

**Comment by jameslulusoft** [comment]
Just issued a PR for half the feature you mentioned @rrag . I haven't figured out the drag and drop part yet but I can do that next.

**Comment by rrag** [comment]
thanks for the PR https://github.com/rrag/react-stockcharts/pull/285
