### ISSUE TITLE
How-to: linked pan on 2 or more charts

### ISSUE THREAD

**Issue by moconnell** [rrag/react-stockcharts#282]
Great library, first of all. I have previously used HighStock/HighCharts and haven't worked with React before, but am really enjoying and finding it productive, so thanks for making! 

I have a couple of candle charts that are showing the same EURUSD data series, but sampled at different timescales (1H & 30min). I adapted the CandleStickChartPanToLoadMore.jsx example to work with pouchdb as the data source. So now I can pan the charts individually and more data loads. Great.

But is there a way that I can listen to the pan event of one and bind it to the other and vice versa, so that the charts are always showing the same time window?

**Comment by rrag** [comment]
this is not documented, but here is how you could do that

below example is using `0.7.0-beta.1` there are breaking changes between 0.6 and 0.7 review them [here](https://github.com/rrag/react-stockcharts/issues/206) also there are some new features [here](http://rrag.github.io/react-stockcharts-next/documentation.html) is the documentation site for 0.7

```jsx
componentDidMount() {
  this.node.subscribe("someUniqueId", { listener: this.handleEvents })
}
componentWillUnmount() {
  this.node.unsubscribe("sameUniqueIdUsedToSubscribe")
}
handleEvents = (type, moreProps, state) => {
  if (type === "pan") {
    // do fun stuff here :)
    // you could also do this.node.getDataInfo()
    // which returns some useful internal info, though
    // all this information should already be available in `moreProps` and `state`
    // you can get the xDomain as moreProps.xScale.domain() but I doubt
    // that would be useful for you if you use discontinuous scale
    // if you *do* use discontinuous scale I suggest you do
    // moreProps.plotData -> get the first and last value from this array
    // and use that to calculate the `xExtents` of your other chart
  }
}
render() {
  return <ChartCanvas ref={node => this.node} ...>
    ...
  </ChartCanvas>
}
```

**Comment by moconnell** [comment]
Followed suggestion - nice speed-up in 0.7.0 btw - and have bubbled the event to the parent component, which is then setting first & last dates from `moreProps.plotData` and xDomain from `moreProps.xScale.domain()` as properties on the child components.

As you said, xDomain is of limited utility, because if I pan the hourly back, then I get a value of something like (-6.239, 9.878), which when passed to the 30min would need to be doubled via a scaling factor.

Actually, looking at the dates obtained from plotData, it never goes below "zero" i.e. the original left-hand-most date. In any case, when I attempted to set xExtents with these dates, I get blank charts! So not sure what I am doing there.

Actually now thinking that my original strategy might still be the most promising: I pass a handler function to the child components so that they can load more data; `handleLoadMoreData` calls this with a pair of dates translated from the xDomain value (which gets around the scaling issue); originally this would load more data for both charts, but the problem then was that only the one that had been panned was updated with/to the new time window, even though `render` was called with an updated `data` property on both. I guess setting `xExtents` would in theory be the solution? Although when I set it with a pair of dates, I get a blank chart as stated above.

**Comment by cliffhall** [comment]
I tried to use the above code and `this.node` does not exist in a component that extends React.Component. How do I listen for the pan event on a `ChartCanvas` that is output by the `render` function of a class extending `React.Component`?

**UPDATE**: You need to use a ref instead of 'node'.

    constructor(props) {
        super(props);
        this.chartRef = React.createRef();
    }

    componentDidMount() {
       this.chartRef.subscribe('chart-events', { listener: this.handleChartEvents });
    }

    componentWillUnmount() {
        this.chartRef.unsubscribe('chart-events');
    }

    handleChartEvents = (type, moreProps, state) => {
        switch (type) {
            case 'pan':
            // do stuff
            break;

            case 'mouseenter':
            // do stuff 
            break;
        }
    };

    render() {
        return <ChartCanvas ref={(chart) => {this.chartRef = chart;}}>....</ChartCanvas>
    }
