### ISSUE TITLE
ChartCanvas Helper Function Clarification

### ISSUE THREAD

**Issue by jameslulusoft** [rrag/react-stockcharts#287]
@rrag is a particular reason why the following functions are not member functions of the ChartCanvas class?

function pinchCoordinates(pinch) {
function setXRange(xScale, dimensions, padding, direction = 1) {
function calculateState(props) {
function updateChart(newState, initialXScale, props, lastItemWasVisible) {
function resetChart(props, firstCalculation = false) {
function calculateFullData(props) {
function getXScaleDirection(flipXScale) {
function getDimensions(props) {
function getCursorStyle(useCrossHairStyleCursor) {
function shouldResetChart(thisProps, nextProps) {

I would like to utilize the function resetChart(props, firstCalculation = false) to reset the chart when a user double clicks/taps on an axis. The way the code is currently setup, I can't access that function to get the data I need for yAxisZoom and xAxisZoom. Do you see any issues in moving the listed functions into a single file, export the functions, and then place that file under the utils directory?

**Comment by rrag** [comment]
I think you want to reset the `yDomain` on double click/tap, do you really wish to reset the chart? If so I want to understand the rationale behind that.

If you wish to just reset the `yDomain`, then you can do 

```js
handleResetYDomain = () => {
  this.node.resetYDomain()
}
```
```jsx
<ChartCanvas ... ref={node => { this.node = node }} ...>
  <Chart ...>
    ...
    <YAxis ... onDoubleClick={this.handleResetYDomain} />
  </Chart>
</ChartCanvas>
```

**Comment by jameslulusoft** [comment]
rrag, I was looking to mimic the double tap to reset Axis Domain feature of an online tool called trading view. In short, the feature is this:

 - double tap the yAxis and the graph's Y range is set to bring the graph by into visibility
 - double tap the xAxis, reset the x-axis to the initial domain. 

I actually just finished adding logic to accomplish the features last night and ended up no needing to perform the changes I requested for. The finished product does make use of the resetYDomain that you have mentioned. 

You can see the changes at 

https://github.com/jameslulusoft/react-stockcharts/commit/a684bc5edb0935e3b6320b8f176b1eabb8341e7a

and

https://github.com/jameslulusoft/react-stockcharts/commit/0aa98acfe5e4aeda4560a2a909757a08eeab1285

I am going to issue a PR for you after I finish some additional mobile testing. Let me know what you think.
