### ISSUE TITLE
How to flip histogram neg values?

### ISSUE THREAD

**Issue by raptoria** [rrag/react-stockcharts#29]
For my histogram values < 0, I would like to "flip" them so that they start drawing from 0 down towards the x-axis. I can see this kind of behavior in the MACD charts, but not sure how to do this with the Histogram. I tried direction={(d) => d.volume > 0 ? "up":"down"} but it didn't seem to work.
ex: http://i.stack.imgur.com/VuIY5.png
thanks a ton!!
<3 your charts.

**Comment by rrag** [comment]
http://plnkr.co/edit/DbiXOAr5iVu0Lrp3Pr4m?p=preview

look for 
```
baseAt={(xScale, yScale, d) => yScale(0)}
```
and
```
d.volume = -1 * +d.volume;
```
I changed the volume to `-ve` to show this.

**Comment by raptoria** [comment]
thanks!! works beautifully.

**Comment by rrag** [comment]
Glad it works, For more customization, the base can depend on `d` which is each element, this approach is used in [BollingerBand](http://rrag.github.io/react-stockcharts/documentation.html#/overlays_bollinger_band) by reusing the Area chart with a varying base for each element

https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/BollingerSeries.jsx#L40

base of both Area & Histogram are configurable.

**Comment by raptoria** [comment]
ah ok..still trying to re-remember all this math stuffs. http://embed.plnkr.co/HoqNYGRTGncvxzVpF4MC/preview
How do I remove the spaces between the bars?  Also, is there a way to format the dates on the xAxis? I tried to use tickFormat={d3.time.format("%b")} but I got an error. 

thanks so much!!

**Comment by rrag** [comment]
The Histogram does not allow for the spaces to be removed, the width of each bar is calculated something like

```
barWidth = (availableWidth / numberOfBars) * 0.5;
```

https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/HistogramSeries.jsx#L140

I can see how you would want that to be configurable. It will have to be a change to the `HistogramSeries.jsx` to accept a prop (0 to 1) - should default to 0.5

About the xAxis tickFormat. a slightly tangential comment to answer, The stock scale is not necessary for what you are doing.

I updated your plunker to remove the stockscale `dataTransform` and use `xAccessor` on both the `Chart`s

http://plnkr.co/edit/bodUXgWtfcZvW92OzJZF?p=preview

If this answer is not satisfactory, I would like to understand why stockscale is needed for this type of chart.

**Comment by rrag** [comment]
Oh and I also changed the mouse crosshair toolip format too. check it out

**Comment by raptoria** [comment]
Actually, I'm not too sure what the stockscale transformer does.. (plz feel free to explain) What you did looks much better than what I had before. A configurable prop would be great.

thanks as always, for such an awesome charting framework!

**Comment by rrag** [comment]
http://rrag.github.io/react-stockcharts/documentation.html#/candlestick_chart explains stockscale better

**Comment by raptoria** [comment]
quick question.. how to I add labels for the blue line which represents totals in my chart ? Does your next release include props for the width of each histogram bar? :dancers:

**Comment by rrag** [comment]
> how do I add labels for the blue line which represents totals in my chart ? I can see them in the CandleStick chart

sorry, not following the question, are you asking about a tooltip for the blue line?

> Does your next release include props for the width of each histogram bar?

Thanks for the reminder, I forgot. will add it

**Comment by raptoria** [comment]
![image](https://cloud.githubusercontent.com/assets/7387035/11154328/bcdbd438-8a0c-11e5-9217-46da11d83622.png)


How do I turn on these labels/tooltips? (blue and yellow)

**Comment by rrag** [comment]
these are for moving average. I am afraid you cant do that for a different series.

All the tooltips are for some type of stockchart related indicator, It should be easy to create one for a simple single value series like Line/Area which you have. Let me see what I can do

**Comment by rrag** [comment]
@raptoria 
http://rrag.github.io/react-stockcharts/documentation.html#/misc_charts

**Comment by raptoria** [comment]
nice!! is there a link to a plunker for that misc_chart? that looks more suited for what I'm trying to do since I"m not using the OHLC stuff

**Comment by rrag** [comment]
I don't want to create another plunker for this, it is getting difficult to maintain all the plunkers, testing them before every new version is not fun.

this [source](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/AreaChartWithZoomPan.jsx) from documentation should help

**Comment by raptoria** [comment]
understood. source is good enough for me :+1:

**Comment by rrag** [comment]
I am not sure, how this can happen. does this happen on plunker also?

just a shot, try to change the prop on `HistogramSeries`

```diff
-red
+#FF0000
```

**Comment by rrag** [comment]
I am not sure why you get that error, unrelated to that, I now removed some hard coding of colors to enable configurable colors (for the dark theme), so updated the example with some of those

http://rrag.github.io/react-stockcharts/documentation.html#/misc_charts

and the source is available in

https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/AreaChartWithZoomPan.jsx

new version also published on npm

**Comment by raptoria** [comment]
thanks..i got it work using your AreaChart example, no more errors! I like the new styling capabilities :+1:

**Comment by raptoria** [comment]
nevermind..on second thought, the labels seem unnecessary.
