### ISSUE TITLE
Trendline will not extend beyond xExtents

### ISSUE THREAD

**Issue by xlphs** [rrag/react-stockcharts#292]
I thought `XLINE` or `RAY` will literally extend the line to infinity but it only draws as far as the date range goes. I looked at the source code a bit but I cannot see why the line is being clipped. Could you offer some hints at how to do this? Would love to help, great library.

**Comment by rrag** [comment]
you are right, it must be possible to fix, let me take a look

**Comment by rrag** [comment]
fixed in `0.7.0-beta.10` check the updated example which uses RAY http://rrag.github.io/react-stockcharts-next/documentation.html#/trendline

in case you were using 0.6 be sure to check out the [breaking changes](https://github.com/rrag/react-stockcharts/issues/206)
