### ISSUE TITLE
How do you get rid of this warning for the discontinuousTimeScale?

### ISSUE THREAD

**Issue by SangYi** [rrag/react-stockcharts#293]
`discontinuousTimeScaleProvider.js:220 Are you sure you want to use a discontinuousTimeScale? Use this only if you have discontinuous data which needs to be displayed as continuous. If you have continuous data use a d3 scale like 'd3.scaleTime'`

This warning comes up every time I insert a new candle.  I wanted to use the discontinuous chart because I don't want gaps between my candles, but I can't get rid of this warning in my console.

Please help.  Thank you in advance.

**Comment by rrag** [comment]
I understand it gets annoying, I will be removing this in the next beta version

**Comment by rrag** [comment]
removed in `0.7.0-beta.9`
