### ISSUE TITLE
load more data 

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#295]
I would like to know that if the link http://rrag.github.io/react-stockcharts-next/documentation.html#/load_more_data_on_pan has a plunker?

**Comment by sunshineying** [comment]
First of all, My chartData.length is 300. I want to show 100 data at the beginning. When dragging or zooming, I want to show more data or load more data. But I don't know how to handle the event. 
Can you show some tips? Thanks.

**Comment by rrag** [comment]
there is no plunker for that, but the source is available [here](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartPanToLoadMore.jsx) this example however shows the last 180 candles and on pan to show the past, shows how to download more
