### ISSUE TITLE
Type of stochastic oscillator

### ISSUE THREAD

**Issue by yjwoo14** [rrag/react-stockcharts#297]
I use `type()` of indicators in my code and found out that the type of stochastic oscillator is defined as "RSI" although I expected "STO". Is it on purpose?

https://github.com/rrag/react-stockcharts/blob/master/src/lib/indicator/stochasticOscillator.js#L11

**Comment by rrag** [comment]
I had it fixed in the `next` branch, I suggest you try with that `npm install -S react-stockcharts@next` make sure to review the [breaking changes](I had it fixed in the `next` branch, I suggest you try with that `npm install -S react-stockcharts@next` make sure to review the breaking changes)
