### ISSUE TITLE
First & Last Bars Cut Off

### ISSUE THREAD

**Issue by AndersonTaylor** [rrag/react-stockcharts#3]
Is there a way to adjust the margins so that the first and last candlestick bars are fully displayed?

It's especially noticeable when showing a small number of candles.

http://plnkr.co/edit/gist:261fa4bc7b67536eb789?p=preview

**Comment by rrag** [comment]
Showing half of first and last candle is common in many charting software, There is no way currently to consistently force the full candle, however the following might help and I think it is a very good approximation of your request

add this to each of the `Chart`
```
padding={{ top: 0, right: 10, bottom: 0, left: 10 }
```

The moving average [example](http://plnkr.co/edit/gist:a27298bb7ae613d48ba2?p=preview) shows its usage

Remember to add the padding to both volume histogram and the price candlestick `Chart`

let me know if that helps

**Comment by AndersonTaylor** [comment]
Yeah, that looks a lot better for me, thanks.

**Comment by moonlight16** [comment]
Note: I found you must use the padding on the ChartCanvas, not Chart object.

**Comment by ahmed-numaan** [comment]
It worked. Thanks!
