### ISSUE TITLE
Domain is not current in subscribe callback

### ISSUE THREAD

**Issue by wrostek** [rrag/react-stockcharts#300]
Using ~0.7.0-beta.6 , I would like to use the "panend" event to get the new domain the user has panned to.

I have subscribed to the panend event, however, I notice that in that event, the domain is not the new domain (after the pan) as expected, but the previous domain (before the pan).

I have attempted to get domain via both this.node.getDataInfo().xScale.domain() and state.xScale.domain() (in case one may be current, but neither were). In fact, I can see domain is not updated until the second firing of "mousemove" event. (i.e. end your pan, and then move your mouse around a bit, then domain is updated) 

Any suggestions on how on panend I could get current domain? (I have included some pseudo code below for example) 

```js
componentDidMount() {
  this.node.subscribe("myUniqueId", { listener: this.handleEvents })
}
componentWillUnmount() {
  this.node.unsubscribe("myUniqueId")
}
handleEvents = (type, moreProps, state) => {
  console.log( type + " (Node) Domain: "+ this.node.getDataInfo().xScale.domain() + " (State) Domain: " +  state.xScale.domain() );
}

render() {
  return <ChartCanvas ref={node => { this.node = node; } } ...>
    ...
  </ChartCanvas>
}
```

**Comment by rrag** [comment]
could you try

```
handleEvents = (type, moreProps, state) => {
  console.log(moreProps.xScale.domain());
}
```

**Comment by wrostek** [comment]
Awesome, this was what I was looking for.  Thank you
