### ISSUE TITLE
Candle Volume

### ISSUE THREAD

**Issue by aariza-argentina** [rrag/react-stockcharts#301]
Hi!
Are you planning to support candlevolumen?
Thanks in advance!

**Comment by rrag** [comment]
I dont know what this is. there is already volume bars.

**Comment by aariza-argentina** [comment]
Sorry... It's called also equivolume.
Candles with diferents width related to the volume
Something like this http://i.investopedia.com/inv/dictionary/terms/equivolume.gif
Thanks!

**Comment by rrag** [comment]
this is a great example usage of being able to customize the `CandlestickSeries` right now it does fixed width, and it is not possible to give different stroke colors, hover/click interactions. An improved version of the candlestick series with all these could be customized to create this.

**Comment by aariza-argentina** [comment]
Excelent! I think its a mix of renko (uneven time axis) and vars... if you give me some hits where to star I try it!
Only diferent bar widths with a time axis like renko for start would be great .
PD: Sorry for me english

**Comment by truongvanu** [comment]
Hi Ragu,

Do you have a Window's version of the package.json for the
react-stockcharts package? I tried running from windows and it's not
working.

Thanks!

Van

**Comment by rrag** [comment]
no plans to work on this now
