### ISSUE TITLE
config the discontinuousTimeScaleProviderBuilder

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#303]
I want to config it according different graph. 
One graph the "startOfDay"  is true, but the other graph I want the "startOf30Minutes" is true.

![image](https://user-images.githubusercontent.com/18010449/28299671-190f4176-6bad-11e7-900b-859747389f50.png)

any advice?

**Comment by rrag** [comment]
those `startOfxxx` are internal variables and might get removed in a future version,

that said, you would have to manually filter out the data that you dont want and pass just the [] you wish to plot
