### ISSUE TITLE
Adding markers to the charts

### ISSUE THREAD

**Issue by ntom** [rrag/react-stockcharts#304]
Hi, 

I love these charts, but i think its missing some really useful tools.

1: Adding a marker on the chart, a "O" point, colored, of varying size overlaid over the candle sticks with a z order

2: Colored boxes  (x,y) - width - height. . or (x,y) - endless (endlessly fill right or up.. ) 

3: Horizontal lines that follow continiously from point X to endlessly right to the chart

4: Vertical Lines that fill the full vertical span from point X 

I would be happy to pay you to implement this and other stuff...

Also i think the updating of the chart realtime documentation is lacking ... 

One final thing, on new data set to add to candle, want to input  { open, high, low, close, volume, options } . . and the options could be stuff like color, a tool tip, a specific call back when clicked etc.... 

Thanks

**Comment by rrag** [comment]
1. are you referring to annotations? - http://rrag.github.io/react-stockcharts/documentation.html#/ma_crossover_using_svg_shape
2. drawing arbitrary rectangles on the background is possible, I dont suppose that is too difficult, it would be similar to the 3 and 4 you have mentioned
3. is this what you had in mind? - http://rrag.github.io/react-stockcharts-next/documentation.html#/price_marker_demonstration (this is available in the `next` version not in 0.6)
4. open http://rrag.github.io/react-stockcharts-next/documentation.html#/stochastic_oscillator and pan to Apr 2012, you can see 2 vertical lines dashed and solid.

about documentation on realtime chart update, I agree, there have been requests to share a plunker multiple times, and I have had my own reasons and procrastination to blame. However just today I got a whole bunch of examples working for the next version on codesandbox. - https://github.com/rrag/react-stockcharts-examples2 I agree that some additional documentation would surely help

the options thing you are suggesting for Candle is something I have been wanting to do for a long time, but just never got to it. right now, only the `LineSeries` can support a `hover / click / rightclick / doubeclick` supporting a per candle based appearance and interaction options is key to implementing this feature, I had made some very good progress on some new interactive indicators in the `next` branch http://rrag.github.io/react-stockcharts-next/documentation.html#/gann_fan which would pave way for interactivity to different series.

Having said all this, I also have to be honest that I dont spend the same time I used to, and I dont see that changing anytime soon. I get ideas for new features and indicators when ever I see something on a different trading platform, and then it stays just that way, an idea. May be some time I might create a commercial version with more features and indicators. My priority now is to release a proper 0.7 with all the new features already sitting in it.

The platform is highly customizable, and I believe that many of the features one wishes can be implemented without even touching the core of the library.
