### ISSUE TITLE
Histogram

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#31]
is it possible to flip histogram ? 
![tt_f_depth](https://cloud.githubusercontent.com/assets/6270599/11039225/a12c9b16-8717-11e5-831e-242105741ae9.jpg)

**Comment by rrag** [comment]
There are 2 problems to be solved to address this,

1. The `HistogramSeries` available is not capable of creating horizontal bars, but that is the easy problem to solve

2. The more difficult problem to solve is that market depth data is not derived from the ohlc volume data which is provided as input to `<ChartCanvas ... data={...} >`

I have been thinking of creating a [Volume profile chart](http://ibankcoin.com/raul3/files/2014/03/NQ_VolumeProfile_intermediateTerm_03132014.jpg) for some time now and that would address 1. above,

**Comment by rrag** [comment]
can you share some example data for this ask/bid prices. I want to explore how this can be done.

**Comment by rsklyar** [comment]
data for bid\ask price vis dropbox link

https://www.dropbox.com/s/mrv5n810t349tso/Depth.xlsx?dl=0

**Comment by rrag** [comment]
Not planning to add this now
