### ISSUE TITLE
Customizing CandlestickSeries

### ISSUE THREAD

**Issue by piotryordanov** [rrag/react-stockcharts#311]
I wanted to customize the CandleSeries to change from Green/Red as well as changing `stroke` and other functions. The docs don't tell me how to do it. But, inspired by the `macdApperance` I figured out that I can add this to the top of  my code:

```
const candlesAppearance = {
  wickStroke: "#000000",
  fill: function fill(d) {
    return d.close > d.open ? "rgba(196, 205, 211, 0.8)" : "rgba(22, 22, 22, 0.8)";
  },
  stroke: "#000000",
  candleStrokeWidth: 1,
  widthRatio: 0.8,
  opacity: 1,
}
```

Then, I would summon the CandlestickSeries as such.
```
        <CandlestickSeries
          {...candlesAppearance} />
```

This way, I would be able to customize my sticks!

I'm not sure how exactly to contribute this back to this repo, so i leave it to your discretion to decide how to proceed next. I'd be happy to make a pull request if you give me proper guidance as to where is best to do it.

Cheers and thx for this fantastic library!

**Comment by rrag** [comment]
Thanks for the PR

**Comment by piotryordanov** [comment]
My pleasure :)
