### ISSUE TITLE
{indicator}(...)options is not a function

### ISSUE THREAD

**Issue by Libertaro** [rrag/react-stockcharts#315]
When I try to add any indicator, I receive such error. Thanks
![image](https://user-images.githubusercontent.com/25828860/28815742-029088b6-76ab-11e7-91c4-c398668d8862.png)
![image](https://user-images.githubusercontent.com/25828860/28815751-0812a170-76ab-11e7-9b8a-53b457f96fd4.png)

**Comment by rrag** [comment]
what version, this syntax is in the 0.7 betas. I guess you installed as 

```
npm install -S react-stockcharts
```
instead do
```
npm install -S react-stockcharts@next
```

**Comment by Libertaro** [comment]
I installed via composer:
`"npm-asset/react-stockcharts": "^0.7.0-beta.12"`

**Comment by rrag** [comment]
not sure what composer is, but it is working in codesandbox with beta12

https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithMACDIndicator
