### ISSUE TITLE
Crash when holding left click then scroll wheel

### ISSUE THREAD

**Issue by sokai116** [rrag/react-stockcharts#316]
With pan and zoom both enabled, holding mouse left button on the table then scroll the mouse wheel, the graph will become blank.

**Comment by rrag** [comment]
good one. I guess the solution is to disable zoom when pan in progress, want to do a PR?

enclose [this](https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L550-L596)

with a 

```js
if (!this.panInProgress) {
  // https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L550-L596
}
```
