### ISSUE TITLE
AreaSeries line animation

### ISSUE THREAD

**Issue by shinrason** [rrag/react-stockcharts#317]
How can i animate line when adding new data? Like a smooth transition

**Comment by rrag** [comment]
right now it is not possible with the current AreaSeries or any other series. Animation is one of the areas the lib is lacking, there is almost no animation at all.

It is something I am very interested in. I have discussed this in other issues before, I want to be able to handle certain animations at the core level, like zoom/pan animation, and then there are other animations which are at a series level. unfortunately I don't have any ETA
