### ISSUE TITLE
In production, it breaks build

### ISSUE THREAD

**Issue by mantesat** [rrag/react-stockcharts#318]
I'm using react-stockcharts as a dependency and after initial devel tests, I tried to build a production package for my app. Howerver, using react-stockcharts seems to break production build:

ERROR in 0.2029fa2a064de68e00ef.chunk.js from UglifyJs
Invalid assignment [0.2029fa2a064de68e00ef.chunk.js:34188,80]

This happens only of I include stockcharts to my project (and only on production build phase). Does react-stockcharts use es6 features, who are known to break the UglifyJS minification process? Any ideas on that?

**Comment by mantesat** [comment]
OK, andwering my own question: it seems that the d3fc-rebind package depends on legacy uglifyjs package, so even if someone changes the minifying process to use uglify-es/UglifyJS3, errors still come up. I'm leaving this open, in case the project owner wants to comment something on this, before closing it.

**Comment by rrag** [comment]
I see. thanks for the details. I suppose removing the dependency to `d3fc-rebind` would solve this problem.

**Comment by jsgphd** [comment]
Hi, I am still having this issue with stockcharts version "0.7.0-beta.13" are you planning to fix this soon?

**Comment by rrag** [comment]
Removed usage of d3fc-rebind and published a `0.7.0-beta.14` can you try if this fixes the problem?

**Comment by jsgphd** [comment]
You fixed it.  Thanks so much!

**Comment by rrag** [comment]
perfect thanks for confirming
