### ISSUE TITLE
Adding tests

### ISSUE THREAD

**Issue by joshuavial** [rrag/react-stockcharts#319]
Great project @rrag  - if I were to add some tests where would you most want to see them first?

My preference would be to use jest but open to a different library if you'd prefer.

**Comment by rrag** [comment]
Thank you, jest is great, I am good with the choice. There are no tests right now so having any test is an improvement. I would like to chat and discuss some of the topics I am not sure how to solve

- Trigger mouse and touch events
- Testing with canvas elements
- comparing the output of canvas with an image

I suppose SVG compare can be done via jest snapshots

For starters, I would say testing the methods on `ChartCanvas`, `EventCapture` and `GenericComponent` will cover a lot of scenarios. Also many of these methods can be tested without triggering mouse/touch events and dealing with canvas/svg, so I guess using only jest for these would suffice.

**Comment by joshuavial** [comment]
Great, I've put this on my backlog and have some time coming up in September which I would love to spend on the project.

**Comment by rrag** [comment]
Hi @joshuavial still interested in working on this?
