### ISSUE TITLE
problems with xAxis

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#324]
1. how to set the width of each minute at xAxis

open time: [9:30-11:30][11:00-15:00]
the time_division chart has totally 240 data one day.

if there is  240 data, the chart is drawn like  this.
![image](https://user-images.githubusercontent.com/18010449/29065583-26432b7e-7c5f-11e7-811c-f7d5e04bf9b7.png)

but if there is  120 data, I would not like the chart is filled.
**how to make the chart width only 1/2 of xAxis, the other 1/2 of xAxis haven't drawn yet.**
**interval?** any advise? thanks.

2. how to **add the red straight line** in Specified coordinates as follows?

![image](https://user-images.githubusercontent.com/18010449/29067245-832dc678-7c64-11e7-8b0e-b98d16e8f9d2.png)

**Comment by rrag** [comment]
that would be `xExtents` you should set an array of [start, end].
