### ISSUE TITLE
change k line, keep indicators, the tooptip confusion

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#325]
first, it's ok
![image](https://user-images.githubusercontent.com/18010449/29199641-1df8a3e4-7e81-11e7-8b10-9fd882e5d52d.png)

then when I change k line from day to week, the tooltip has no style, but the value is ok. and I can't control the style of tooltip.
![image](https://user-images.githubusercontent.com/18010449/29199655-39be8ddc-7e81-11e7-9230-9b104678285d.png)

when I add another indicator,  The tootip that was added later is ok, and the original tooltip is problematic

![image](https://user-images.githubusercontent.com/18010449/29199746-f4b7dd00-7e81-11e7-8e57-687ca785f6d3.png)

how to fix it? when change k line, keep indicator, the css style of tooltip stay the same.

**Comment by rrag** [comment]
appears to be some extra space present in svg text

can you share a screenshot of how this looks like in the dev tools `Elements` tab?

I suspect it is similar to https://github.com/rrag/react-stockcharts/issues/49

make sure you dont have any space between the `<OHLCTooltip ..>` and `<BollingerBandTooltip>`

**Comment by sunshineying** [comment]
I found that when change k line,  the tooltip is out of svg.   but the tootip that was added later is in svg.

![image](https://user-images.githubusercontent.com/18010449/29200238-21993338-7e86-11e7-96fc-c7d9486480ff.png)

![2](https://user-images.githubusercontent.com/18010449/29200315-e49c2caa-7e86-11e7-89ac-28fdbed92e0e.png)

**Comment by rrag** [comment]
It seems that you have 2 `MovingAverageTooltip` and not one which takes in an array of `options`. I dont think that is the problem though, could you check if the source is formatted properly, for e.g. could you check if you have

```
<EdgeIndicator ...>    <OHLCTooltip ... />   <MovingAverageTooltip ... />
<MovingAverageTooltip ... />
<BollingerBandTooltip ... />
```

is there some space between

`<EdgeIndicator ...>___space here?___<OHLCTooltip ... />___or here?___<MovingAverageTooltip ... />`

also is this same across firefox too?

**Comment by sunshineying** [comment]
Thanks for help. 
I realize that when I  add indicator dynamically,  I have using <div> to wrap <LineSeries ... />  and <CurrentCoordinate .../>.  It's so silly.  then I use <g> instead of <div>.  It's ok now.
