### ISSUE TITLE
is there a way to create custom x values?

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#326]
is there a way i can use xAccessor without using a date field? i want to create a market depth chart with area series but i need the x values to be price and not date, is that possible? and if yes what do i use in xScaleProvider and xAccessor of charCanvas?

thanks for the help

**Comment by rrag** [comment]
I would think it is not possible to use ChartCanvas for marketdepth, the data for the timeseries and market depth is different, the xScales are different.

I think creating marketdepth as its own chart is the right solution.

**Comment by omryr** [comment]
Do you think you could point me at the right direction? How would I go on about creating a market depth chart ? I wanted to use an area chart with X values of price like I said but I'm open to suggestions if there is a way to create a custom chart. And if there is a custom where can I find a documentation? Thanks for the help

**Comment by rrag** [comment]
so first you have to format the data like

```js
ask: [
  { x: price1, y: countOfAsks at price1 },
  { x: price2 /* price 2 > price 1*/, y: countOfAsks at price1 + countOfAsks at price2 },
  { x: price3 /* price 3 > price 2*/, y: countOfAsks at price1 + countOfAsks at price2 + countOfAsks at price3 },
  { x: price4 /* price 4 > price 3*/, y: countOfAsks at price1 + countOfAsks at price2 + countOfAsks at price3 + countOfAsks at price4 },
 ...
],
bids: [
  { x: price1, y: countOfAsks at price1 },
  { x: price2 /* price 2 < price 1*/, y: countOfAsks at price1 + countOfAsks at price2 },
  { x: price3 /* price 3 < price 2*/, y: countOfAsks at price1 + countOfAsks at price2 + countOfAsks at price3 },
  { x: price4 /* price 4 < price 3*/, y: countOfAsks at price1 + countOfAsks at price2 + countOfAsks at price3 + countOfAsks at price4 },
 ...
]
```

WIth that kind of data you could either draw a path with `d3-path` or even pure svg path

or use `d3-shape` with a combination of

`stepBefore` - https://github.com/d3/d3-shape#curveStepBefore
`stepAfter` - https://github.com/d3/d3-shape#curveStepAfter

for the bid/ask lines
