### ISSUE TITLE
How can I use "structure of arrays" data format?

### ISSUE THREAD

**Issue by mindjuice** [rrag/react-stockcharts#327]
Thanks for this cool library!  Seems to be just what I was looking for.

One issue I have is that my data is in "structure of arrays" format rather than "array of structures".

So instead of:
```
[
  { date: 'June 1, 2017', MSFT: 140.00, AAPL: 120.00, TSLA: 340.00},
  { date: 'June 2, 2017', MSFT: 141.00, AAPL: 121.00, TSLA: 341.00},
  { date: 'June 3, 2017', MSFT: 142.00, AAPL: 122.00, TSLA: 342.00},
]
```

I have:
```
{
  date: [ 'June 1, 2017', 'June 2, 2017', 'June 3, 2017'],
  MSFT: [ 140.00, 141.00, 142.00],
  AAPL: [ 120.00, 121.00, 122.00],
  TSLA: [ 340.00, 341.00, 342.00],
}
```

I've looked through the examples and some of the code, but I'm not yet seeing how to configure the `discontinuousTimeScaleProvider`, `ChartCanvas` and the accessors to handle data in this format.

Is this currently possible?

A side issue is that my arrays are actually in `TypedArray` format like `Float32Array`.  I can convert them to normal JS arrays if necessary, but it would be better to avoid this conversion if the graph could use the data directly.

**Comment by rrag** [comment]
you have to convert data to 
```
[
  { date: 'June 1, 2017', MSFT: 140.00, AAPL: 120.00, TSLA: 340.00},
  { date: 'June 2, 2017', MSFT: 141.00, AAPL: 121.00, TSLA: 341.00},
  { date: 'June 3, 2017', MSFT: 142.00, AAPL: 122.00, TSLA: 342.00},
]
```

format, you could use some utilities like

`d3.zip`  - https://github.com/d3/d3-array/blob/master/README.md#zip
`_.zip` - https://lodash.com/docs/4.17.4#zip


I am not following what you mean by

> my arrays are actually in TypedArray format like Float32Array

is that Typescript?

**Comment by mindjuice** [comment]
I could convert the data, but that is wasteful of memory and CPU.  Other graph APIs can adapt to different data formats (e.g., I was trying out VictoryJS and was able to use data in column format as I showed above).

The `TypedArray`s are standard JavaScript arrays that let you read from buffers of various sizes (e.g., `Float32Array`, `Int8Array`, `UInt8Array`, etc.).  See here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray
