### ISSUE TITLE
[ Enchancement ] Market Depth

### ISSUE THREAD

**Issue by haydencarlson** [rrag/react-stockcharts#329]
Has anyone created a market depth chart before with react-stockcharts?
I'm working towards a solution but struggling here.

Any help would be appreciated.

**Comment by omryr** [comment]
i created one using 2 area charts and each of them only renders from the point it starts till it ends, so if you have the left side it would be from lowest - x and the next would be from x - highest.

**Comment by haydencarlson** [comment]
Thanks, I was able to do the same using react-highcharts.

**Comment by rrag** [comment]
Similar request has come up a few times. I might build one of these, and likely sell it in the future. but no plans to build one and open source it.

**Comment by flavioespinoza** [comment]
This is a work in progress, but it's a good start.
https://gist.github.com/flavioespinoza/e7b086abf3f28ee05967d205f850b6af

<img width="455" alt="screen shot 2017-12-01 at 1 26 50 am" src="https://user-images.githubusercontent.com/2214913/33474492-1ab2b7a6-d638-11e7-99d7-586041bbcf63.png">

**Comment by Ejnot** [comment]
2 Area charts seems bold technique i created depth chart also with the same approach the only problem im having is the XAxis is overlapping. How did you manage the XAxis if used two area charts?
