### ISSUE TITLE
Question on Theming

### ISSUE THREAD

**Issue by aajtodd** [rrag/react-stockcharts#33]
Just had a question, is there currently support for theming (changing chart appearance)?

If it is available can you point me in the right direction? This would be a great addition to the docs.

As an example, it would be cool to be able to recreate charts like Think or Swim:
http://business.fiu.edu/capital-markets-lab/thinkorswim2.jpg
OR
https://readtheprospectus.files.wordpress.com/2009/05/trailingstopexample51309.png

Just something to think about.

**Comment by rrag** [comment]
There are a few places where the colors and hardcoded and not used from props, fixing those would get closer to that. Even then I am not convinced we need theme support. The whole chart will be customizable so you could update the different props to get what you want.

http://rrag.github.io/react-stockcharts/documentation.html#/theme_dark

I made a few updates to remove some hard coding of colors to make this happen, will add a gist and plunker later

**Comment by aajtodd** [comment]
Agreed theme support may be overkill. Just removing any hard coded values
and an example of how to customize everything works for me.

Thanks!

**Comment by raptoria** [comment]
is there a plunker link for the dark theme example? (or some code example?)

**Comment by rrag** [comment]
added plunker example
