### ISSUE TITLE
Can't zoom or pan horizontally.

### ISSUE THREAD

**Issue by SangYi** [rrag/react-stockcharts#331]
"react-stockcharts": "^0.7.0-beta.15",

I'm not able to zoom in or out or pan horizontally since this new update.  I am able to do so vertically.

Any suggestions?

Thanks in advance.

**Comment by rrag** [comment]
I could not reproduce this

does your data have very little number of points? with beta.13 and before the minimum points supported was 2, recent change was done to show a minimum of

(width in pixels / 100) points
or 
2
which ever is greater

, you could change the defaults like

```js
<ChartCanvas ...
  minPointsPerPxThreshold={1 / 200}
```

**Comment by rrag** [comment]
?

**Comment by rrag** [comment]
closing due to no response

**Comment by cbrwizard** [comment]
Hey, I'd like to be able to navigate/pan the chart when there is not enough data. So even when there are 2 points of data for instance. How can I do that? I've tried setting `minPointsPerPxThreshold` to `1 / 200`, `1 / 2000000000000`, `1`, `100000000000` but it didn't affect anything
