### ISSUE TITLE
hide ticks on mobile

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#333]
hi im looking for a way to hide the ticks when in mobile? they overlap each other on the xAxis and i am looking for a way either to remove them on mobile or show less of them? any help would be appericiated!

**Comment by rrag** [comment]
```jsx
<XAxis axisAt="bottom" orient="bottom" ticks={5} />
```
or you could try a smaller number. 


```jsx
<XAxis axisAt="bottom" orient="bottom" showTicks={false} outerTickSize={0} />
```
to hide ticks completely

**Comment by omryr** [comment]
is there any way to make it dynamic? based on screen size or something? i want desktop to have all ticks and mobile none

**Comment by rrag** [comment]
no, not automatically, you have to listen to window resize events and change it. This is because of how d3 axis ticks work, they do not consider the length of the chart while calculating the number of ticks to display.

I am open to suggestions and alternative ideas, listening to resize events is too much work for a simple usecase here

**Comment by omryr** [comment]
and there is no way to add css styling to these elements right? because if it were css code we could easily use media queries

**Comment by rrag** [comment]
you can add css (when using svg mode), but ticks are not css controlled, 

ticks are created by - https://github.com/d3/d3-array/blob/master/README.md#ticks

**Comment by omryr** [comment]
im suprised this is the first time its brought up because other than that this library is one of the best ive seen, but its a pretty common thing to support for mobile devices

**Comment by rrag** [comment]
I am with you on this, this has to be made easier

One request I recall is to make the tick labels rotated by 45 or 90 degrees, that could solve some of the problems but I am not so sure that is the right solution for mobile

**Comment by omryr** [comment]
ok thanks a lot for your help, i guess ill create a util to check screen size and based on that show a different amount of ticks

**Comment by rrag** [comment]
I just read this on https://beta.observablehq.com/@tmcw/responsive-notebook-design-protips

under `Responsive ticks for d3 charts`

(facepalm) for not thinking such a simple solution.

```
ticks={width / 80}
```

solves the problem. I just tested this and it works great.
