### ISSUE TITLE
Minor bug in default value of displayValuesFor

### ISSUE THREAD

**Issue by mwreef** [rrag/react-stockcharts#334]
No default value on MovingAverageTooltip

[Minor_fix__no_default_value_for_displayValuesFor.patch.txt](https://github.com/rrag/react-stockcharts/files/1296405/Minor_fix__no_default_value_for_displayValuesFor.patch.txt)

**Comment by rrag** [comment]
Thanks for bringing this up. Will fix tomorrow.

**Comment by rrag** [comment]
fixed it, thank you
