### ISSUE TITLE
Extent "Clipping" Issue During Resize

### ISSUE THREAD

**Issue by mindjuice** [rrag/react-stockcharts#335]
I've got an app that is using `react-stockcharts` to draw multiple graphs.  The user can drag a splitter bar to resize the graphs, but when dragging, the graph that is being made smaller has its clipping rectangle made too small (or is drawing too few points?).  The other graph that is growing looks okay, although there could be a similar problem here that is masked by the clipping.

I've recorded a video clip of it here:

  https://vimeo.com/233706707

I had a similar issue previously where the chart `id` was not unique and the svg `clipPath`s were getting mixed up, but they now have different names (although there is still one `clipPath` that has a shared name between the two charts: `chart-area-clip`).  See below

```
// From the left chart
<defs>
    <clipPath id="chart-area-clip">
        <rect x="0" y="0" width="530" height="409"></rect>
    </clipPath>
    <clipPath id="chart-area-clip-source_817004">
        <rect x="0" y="0" width="530" height="409"></rect>
    </clipPath>
</defs>
```

```
// From the right chart
<defs>
    <clipPath id="chart-area-clip">
        <rect x="0" y="0" width="530" height="409"></rect>
    </clipPath>
    <clipPath id="chart-area-clip-source_817004">
        <rect x="0" y="0" width="530" height="409"></rect>
    </clipPath>
</defs>
```

Any idea what might be wrong?

Cheers!

**Comment by mindjuice** [comment]
I just also noticed that when I make the graph smaller, it does not draw the full domain anymore, even though I pass in the whole domain in the `xExtents`.

```typescript
const xExtents = [xAccessor(last(data)), xAccessor(data[0])]
```

Is there some internal limit on the the `xExtents` that shrinks it if there is "too much" data to draw?

**Comment by mindjuice** [comment]
This is related to the `extentsWrapper()` function that trims the data down if there are more than 2 points per pixel (which is the case when making the window smaller).

Still investigating how to fix it.

**Comment by mindjuice** [comment]
I was able to "fix" this by added `plotFull={true}` to my `<ChartCanvas>` instance.

Still feels like the code should work properly without this though.  If you have any ideas, please let me know, otherwise I will try to look into it again when I have some time.

Thanks.

**Comment by rrag** [comment]
I am not quite following here, are you adding a clipPath yourself? and you saying that clip path is the problem?

or is the points per pixel limit is reached that causes this clipping?

**Comment by rrag** [comment]
ok, I understood the problem, so this is the points / px causing fewer data points to be drawn. You could change the `pointsPerPxThreshold` to a bigger number and see if that helps

but the underlying problem is still there. Let me look at this tomorrow. I was having a different idea for handling resize,

current behavior:
On resize the chart tries to fit the same data in the resized width, but since that is not possible due to the points/px prop, it shows less points, and also this problem

Proposed behavior:
on resize, do not show the same data but instead maintain the current points/px, so as you resize small/big the number of data points shown will be reduced/increased, but they will still stay in the same points/px

**Comment by mindjuice** [comment]
Sorry for the confusion.  The `clipPath` was not the issue, although I thought it might be related at first, because I had a similar issue until I set an `id` for each chart.

Your proposed solution sounds reasonable.

**Comment by rrag** [comment]
@mindjuice finally I think I have a solution for this. check out the resize behavior for http://rrag.github.io/react-stockcharts/documentation.html#/macd

this chart has a lot of data displayed, so this mimics your scenario

sorry for the delay. appreciate your feedback on this

**Comment by mindjuice** [comment]
Thanks!  Demo looks good.  The project I was using this for is temporarily on hold, and I won't be able to go back and verify if it works for a while.  You can go ahead and close this and I can revisit later if necessary.

**Comment by rrag** [comment]
thank you

**Comment by somguyth** [comment]
> I've got an app that is using `react-stockcharts` to draw multiple graphs. The user can drag a splitter bar to resize the graphs, but when dragging, the graph that is being made smaller has its clipping rectangle made too small (or is drawing too few points?). The other graph that is growing looks okay, although there could be a similar problem here that is masked by the clipping.
> 
> I've recorded a video clip of it here:
> 
> https://vimeo.com/233706707
> 
> I had a similar issue previously where the chart `id` was not unique and the svg `clipPath`s were getting mixed up, but they now have different names (although there is still one `clipPath` that has a shared name between the two charts: `chart-area-clip`). See below
> 
> ```
> // From the left chart
> <defs>
>     <clipPath id="chart-area-clip">
>         <rect x="0" y="0" width="530" height="409"></rect>
>     </clipPath>
>     <clipPath id="chart-area-clip-source_817004">
>         <rect x="0" y="0" width="530" height="409"></rect>
>     </clipPath>
> </defs>
> ```
> 
> ```
> // From the right chart
> <defs>
>     <clipPath id="chart-area-clip">
>         <rect x="0" y="0" width="530" height="409"></rect>
>     </clipPath>
>     <clipPath id="chart-area-clip-source_817004">
>         <rect x="0" y="0" width="530" height="409"></rect>
>     </clipPath>
> </defs>
> ```
> 
> Any idea what might be wrong?
> 
> Cheers!

Hey, how did you achieve this dragging capability? What library is it?
