### ISSUE TITLE
Zoom Button Error

### ISSUE THREAD

**Issue by alph43oss** [rrag/react-stockcharts#336]
Noticed this with zoom buttons

```
Uncaught TypeError: Cannot read property 'valueOf' of undefined
    at getClosestItemIndexes (dll.js:322)
    at getFilteredResponse (dll.js:51852)
    at domain (dll.js:51800)
    at ChartCanvas.calculateStateForDomain (dll.js:39386)
    at ChartCanvas.xAxisZoom (dll.js:39584)
    at dll.js:40948
```

Happens when you zoom in/out too fast.

**Comment by rrag** [comment]
could you please share a codesandbox with the problem. I tried with http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan and cannot reproduce it

**Comment by alph43oss** [comment]
Just recreated it with the svg version on the link you provided.

**Comment by rrag** [comment]
thanks for reporting, let me check

**Comment by rrag** [comment]
Fixed by https://github.com/rrag/react-stockcharts/pull/350
not published to npm yet, will do in the next few days
