### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#337]
Is there a way to make touch events on mobile move the cursor? if i go to mobile view, i cant see the price because i cant move the cursor, is there a way to make touch event move the cursor to a specific location?

**Comment by rrag** [comment]
Touch events move the cross hair and also show the x and y values on the axes, tooltip gets updated also.

What version are you using?

**Comment by omryr** [comment]
ye touch events work but only if i enable zooming / panning but if i disable them, touch wont work

**Comment by shekenahglory** [comment]
I noticed this as well, is it possible to make touch events apply to the crosshairs and tooltips when pan and zoom are disabled?

**Comment by rrag** [comment]
This seems to be fixed now. Please let me know if you still have issues

**Comment by khaphannm** [comment]
Hi everyone, 
Could u guys pls help me find where I could define the onTouchStart event ?
