### ISSUE TITLE
Load Zoomed Out

### ISSUE THREAD

**Issue by alph43oss** [rrag/react-stockcharts#341]
Is there a simple way to load a chart zoomed all the way out (showing all data)?

**Comment by rrag** [comment]
By default a chart shows 2 points per pixel width, so if for e.g. the drawable width is 500px, it could show a max of 1000 points, you can change this default to a higher number by

```
<ChartCanvas ...
  pointsPerPxThreshold={4}
```

this will maintain that 4 points/pixel max

If you want to just show all the data at once you can try

```
<ChartCanvas ...
  plotFull={true}
```

but this does not optimize the drawing, for e.g your `data.length` is 1000 but are currently viewing say the last 100 points only, having `plotFull={true}` will draw all the points, even the ones which are not visible
