### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by j4rd44** [rrag/react-stockcharts#343]
see my console:
npm install  --save react-stockcharts@next
stockcharts@1.0.0 /home/d3f4ult/bin/nodejs_projects/stockcharts
├── UNMET PEER DEPENDENCY react@^15.0.0
├── UNMET PEER DEPENDENCY react-dom@^15.0.0
└─┬ react-stockcharts@0.7.0-beta.17 
  ├── d3-array@1.2.1 
  ├── d3-collection@1.0.4 
  ├─┬ d3-force@1.0.6 
  │ ├── d3-dispatch@1.0.3 
  │ ├── d3-quadtree@1.0.3 
  │ └── d3-timer@1.0.7 
  ├── d3-format@1.2.0 
  ├─┬ d3-interpolate@1.1.5 
  │ └── d3-color@1.0.3 
  ├── d3-path@1.0.5 
  ├── d3-scale@1.0.6 
  ├── d3-selection@1.1.0 
  ├── d3-shape@1.2.0 
  ├── d3-time@1.0.7 
  ├── d3-time-format@2.0.5 
  ├─┬ debug@3.0.1 
  │ └── ms@2.0.0 
  ├── lodash.flattendeep@4.4.0 
  ├─┬ prop-types@15.6.0 
  │ ├─┬ fbjs@0.8.16 
  │ │ ├── core-js@1.2.7 
  │ │ ├─┬ isomorphic-fetch@2.2.1 
  │ │ │ ├─┬ node-fetch@1.7.3 
  │ │ │ │ ├─┬ encoding@0.1.12 
  │ │ │ │ │ └── iconv-lite@0.4.19 
  │ │ │ │ └── is-stream@1.1.0 
  │ │ │ └── whatwg-fetch@2.0.3 
  │ │ ├─┬ promise@7.3.1 
  │ │ │ └── asap@2.0.6 
  │ │ ├── setimmediate@1.0.5 
  │ │ └── ua-parser-js@0.7.14 
  │ ├─┬ loose-envify@1.3.1 
  │ │ └── js-tokens@3.0.2 
  │ └── object-assign@4.1.1 
  └── save-svg-as-png@1.2.0 

npm WARN react-stockcharts@0.7.0-beta.17 requires a peer of react@^15.0.0 but none was installed.
npm WARN react-stockcharts@0.7.0-beta.17 requires a peer of react-dom@^15.0.0 but none was installed.
Any help is appreciated.

**Comment by rrag** [comment]
`react` and `react-dom` need to be peer dependencies. try adding them.

This library depends on react and cannot work without it.
