### ISSUE TITLE
MouseCoordinateX edge indicator discrepancy between homepage docs and sandbox

### ISSUE THREAD

**Issue by nktpro** [rrag/react-stockcharts#344]
Given the same exact example in 2 different places:

On docs:

http://rrag.github.io/react-stockcharts/documentation.html#/mouse_pointer

And on CodeSandbox, linked directly from the docs page:

https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithCHMousePointer

There is a bizarre difference in edge indicator behavior for MouseCoordinateX.

- On the docs page, mouseover any of the sub-chart (candlestick or volume) and the bottom edge indicator (date) always shows.
- On CodeSandbox, the bottom edge indicator only shows if the mouse pointer is over the volume chart, not the candlestick.

In fact this difference in behavior can be seen in any provided examples.

@rrag Was there something trivial that I missed here?

**Comment by rrag** [comment]
You are right, it is a bug introduced in the npm version which I later fixed and updated the documentation build, but did not release to npm yet.

Will publish new npm tomorrow.

Thanks for catching I forgot about this.

**Comment by rrag** [comment]
Fixed in beta 18, let me know if you have any problems
