### ISSUE TITLE
All examples have Error Chrome ver 61.0.3163.100

### ISSUE THREAD

**Issue by MrLei** [rrag/react-stockcharts#347]
All examples have error:
ERROR: Cannot read property 'responseText' of undefined 

I use this examples 
https://gist.github.com/rrag/46a2db7be6336500bedee27f5fa08713/52e13f729949653f88332c7b0e528a778e8c9529

Where i need   declaratin 'responseText' ?

**Comment by rrag** [comment]
the 0.7 beta version examples are available in https://github.com/rrag/react-stockcharts-examples2

the gist link you shared is for 0.6
