### ISSUE TITLE
Line with alternative colors

### ISSUE THREAD

**Issue by ghost** [rrag/react-stockcharts#349]
I've been trying to achieve an alternating line color similar to this.
<img width="1334" alt="screen shot 2017-09-30 at 3 04 42 pm" src="https://user-images.githubusercontent.com/753950/31044056-df7fec9c-a5f1-11e7-8ae4-7dd8a4ed6100.png">

Basically, it changes color if RSI is overbought or oversold.

I dug into the source code and realized that the line is basically a path, and my understanding from what I read online is that the path can have only one stroke color. 
I'm not sure how I should proceed to implement this behavior. @rrag if you can give me pointers, I'll be happy to try doing it.

Cheers!

**Comment by rrag** [comment]
it has to be multiple paths, I agree it is tricky to find the start and end positions of each of these paths. This has to be part of a custom component and not `RSISeries.js`

keeping it open if I will work on this when I find some time

**Comment by nimo23** [comment]
Then, please do also implement this kind of styling:

![filledlines](https://user-images.githubusercontent.com/3045549/34633361-0034ffb4-f27c-11e7-88f6-51ffee14b041.png)

**Comment by WaiSiuKei** [comment]
Maybe we can draw two path and then clipping them, no need to calculate the start and end of each parts.

**Comment by rrag** [comment]
@WaiSiuKei  Thats a great idea.

**Comment by rrag** [comment]
Published 0.7.3 with this

checkout the RSI [example](http://rrag.github.io/react-stockcharts/documentation.html#/rsi_and_atr) 

@nimo23 for the alternating fill area look at

[docs](http://rrag.github.io/react-stockcharts/documentation.html#/forceindex) or [codesandbox](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithForceIndexIndicator)

create it like
https://github.com/rrag/react-stockcharts/blob/v0.7.3/docs/lib/charts/CandleStickChartWithForceIndexIndicator.js#L148-L151

**Comment by rrag** [comment]
@WaiSiuKei Thanks a lot for the idea, implemented it both svg and canvas
