### ISSUE TITLE
Reset the x axis domain

### ISSUE THREAD

**Issue by alexandrkondrachuk** [rrag/react-stockcharts#351]
Hello!
Is there any way how can I reset the x axis domain after dragging?
I've found in the documentation only how to reset the y axis domain.(http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan)
Hope you can help. 
codesandbox:  https://codesandbox.io/s/vmyjrkoqm0
Thanks in advance!

**Comment by alexandrkondrachuk** [comment]
I've found the solution.

**Comment by tqwewe** [comment]
?? Thanks for sharing the solution so others can fix it too.
