### ISSUE TITLE
How to show time on XAsis?

### ISSUE THREAD

**Issue by Veniamin** [rrag/react-stockcharts#36]
Now it shows only dates and i can't set custom format. 

PS thanks for great work!

**Comment by rrag** [comment]
are you using the stockscale transformer? if not you can change the `tickFormat`

```jsx
<XAxis axisAt="bottom" orient="bottom" tickFormat={d3.time.format("%d")} />
```

**Comment by rrag** [comment]
and if you do use stockscale transformer the `tickFormat` is derived as shown [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/polylineartimescale.js#L33-L37)

**Comment by Veniamin** [comment]
Thanks a lot!
