### ISSUE TITLE
Any plans to add Ichimoku study?

### ISSUE THREAD

**Issue by alph43oss** [rrag/react-stockcharts#361]
Ichimoku study is a pretty standard range study. Any plans to add it?

**Comment by rrag** [comment]
no plans right now. Eventually I want to get a lot of indicators on, right now the focus is on getting drawing objects right and getting more of them on.

**Comment by res63661** [comment]
rrag - awesome repo.  Can you outline quickly what would be needed to create a new study/indicator using react-stockcharts?  I would love to give it  a go if you don't have time.  
Cheers, R
