### ISSUE TITLE
Can you show  sourse file in Demo? 

### ISSUE THREAD

**Issue by MrLei** [rrag/react-stockcharts#363]
i think this exactly http://rrag.github.io/stockcharts-demo/ 
i'm intresting hove  compose  all  function in menu  "typ of  chart, Inicatord, chroshair , gred on/off 
time 10d, ect.

can you show have  you build  all togedher?

**Comment by rrag** [comment]
sorry no I cant

**Comment by Tarique102** [comment]
Your source map is actually visible. Just letting you know.
