### ISSUE TITLE
Does not work with React 16.x.x - PropTypes

### ISSUE THREAD

**Issue by mkrds** [rrag/react-stockcharts#364]
Some of your libs i.e Chart.js have PropTypes taken out of react library - unfortunately they've been removed from React 16 and you need to add them as an additional package.

Snippet from Chart.js file \/
var _react = require("react");
...
Chart.contextTypes = {
	chartConfig: _react.PropTypes.array,
	subscribe: _react.PropTypes.func.isRequired,
	unsubscribe: _react.PropTypes.func.isRequired
};
^ This throws an error saying that PropTypes is undefined

https://reactjs.org/docs/typechecking-with-proptypes.html

**Comment by rrag** [comment]
0.7 beta uses the `prop-types` package https://github.com/rrag/react-stockcharts/blob/master/src/lib/Chart.js#L3

If you are using 0.6 then you might have to monkey patch the proptypes. Upgrade to 0.7 beta if you can. The only reason it is still in beta is the interactive indicators are changing a lot.
