### ISSUE TITLE
Multiple Series

### ISSUE THREAD

**Issue by piotryordanov** [rrag/react-stockcharts#367]
Is it possible to have more than one series running on the same plot? For example, say I want to see renko AND heiken ashi at the same time. Is it possible?

**Comment by rrag** [comment]
renko is not a linear time scale, it is a price movement chart, while haikin ashi is a regular time series chart.

you can combine multiple regular time series charts, like area, line, candle, ohlc, haikin ashi in one chart, it is possible, renko is a completely different xScale so it does not make sense to combine them in one chart

**Comment by piotryordanov** [comment]
haha, i should have given the actual example i wanted, and that was to combine candlesticks with heiken. Is that possible?
