### ISSUE TITLE
Showing 0 review the 'xExtents' prop of ChartCanvas

### ISSUE THREAD

**Issue by n4cr** [rrag/react-stockcharts#368]
I'm having this error when loading my data. The problem is that my array is empty before the data is loaded from the server and I get this error. The graph works properly after the data is there. The graph can be loaded empty.
https://github.com/rrag/react-stockcharts/blob/49f2e4e49f7d0445552085a1128ef3278c030315/src/lib/ChartCanvas.js#L240

**Comment by rrag** [comment]
Cannot render graph with empty data because the chart calculates the x and y domain based on the data you send in. Hence the error. This is per design. The solution is to show a loading icon/message prior to data being available

**Comment by n4cr** [comment]
@rrag thanks for the reply. Does this mean the whole `ChartCanvas` should be mounted after the data is available? and in case the data goes away completely removed?

**Comment by rrag** [comment]
yes mount after data is available.

**Comment by MaxYari** [comment]
Sry for necroposting but imo this shouldn't THROW error and crash whole app. Maybe just a console.error or warning while displaying nothing. In my experience, this error can be encountered if plot size (width/height) was set to be way too small as well as  (I think) when it's under display:none. Catching and preventing all of those get's annoying quickly.
