### ISSUE TITLE
Mobile touch event device it support?

### ISSUE THREAD

**Issue by stigmat4j** [rrag/react-stockcharts#37]
I can't move chart and zoom from mobile device. 
It's supported at all?

**Comment by rrag** [comment]
Yeah, I am aware of this, I have not tested with touch devices. I have to work on this.

**Comment by rrag** [comment]
Touch support added, for both pan & pinchzoom, Tested this in chrome & safari on ipad

http://rrag.github.io/react-stockcharts-next/documentation.html

appreciate if you could test in a different touch device and share feedback.

**Comment by rrag** [comment]
forgot to add, this is not release to npm yet, I plan to add a few more features before publishing the next version

**Comment by stigmat4j** [comment]
Good work! It works on my android device.
