### ISSUE TITLE
Issue with `fitDimension` when using stateless components

### ISSUE THREAD

**Issue by piotryordanov** [rrag/react-stockcharts#370]
My canvas is a stateless component. 
```
const Canvas = (props) =>
  <ChartCanvas {...props}>
     {...chartData}
  </ChartCanvas>

export default fitDimensions(Canvas);
```

When I resize the window, I get this error:
```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at getDimensions (fitDimensions.js?0e68dbf:50)
```

Any idea what is the best way to workaround this?

**Comment by rrag** [comment]
if you use `fitDimensions` it has to be a class as it uses a ref. you could not use `fitDimensions` and pass in the height, width, ratio yourself
