### ISSUE TITLE
formatting date to utc

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#371]
hi I am passing date object to my chart, im using discontinuousTimeScaleProvider. is there a way that the library can format my date to UTC time without me being forced to pass a formatted date ?

thanks for the help!

**Comment by rrag** [comment]
there is [discontinuousTimeScaleProvider.utc](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/discontinuousTimeScaleProvider.js#L230) does that work?
