### ISSUE TITLE
Callbacks for click events on data points

### ISSUE THREAD

**Issue by natew** [rrag/react-stockcharts#38]
I am building a dashboard and first: this library is incredible, congratulations on delivering such a high quality project.

I'm looking for have multiple different graphs linked together. I'd like to select a value on one and have it then show more data on that in another, different graph.

This library looks like it's focused on showing a single series of data which is great. I'd probably plug in a different chart library for some simple pie/line/bar graphs that I could show the detailed data on separately.

My question is, is there a callback to get the Y value on click?

**Comment by rrag** [comment]
thank you, this library can be used to show x, y series, so line, bar can be done no problem. not pie unfortunately as it is built on one dimensional data. It is quite customizable so if you need say stacked bar chart (which is not there yet) it is simple to implement yourself.

Now about an event to capture a y value on mouse click. It is certainly possible, though documentation lacking on that subject.

I suggest you look at the interactive indicators, TrendLine for e.g. it subscribes to mousemove and click events, and in your case you can subscribe to click events only, and in the `onClick` method get the yValue and invoke a callback method you have passed via props.

Let me know if you have trouble. I can whip up an example in plunker if you are stuck.

**Comment by natew** [comment]
@rrag thats great, thanks for the tip. It's hard to find the source:

http://rrag.github.io/react-stockcharts/documentation.html#/interactive_indicators_trendline

I don't see a link to source on that example, I'll search through source though now.

**Comment by rrag** [comment]
https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/TrendLine.jsx

is the source of `TrendLine` indicator. you would have to create a new interactive indicator for what you are asking, you can start with this, and delete almost all the code in all its functions, since all you need it just get the yValue and once you have it invoke a function which is passed in via prop.

**Comment by rrag** [comment]
here is an example

http://rrag.github.io/react-stockcharts/documentation.html#/click_callback

also created another interactive component to show something a little more complex
http://rrag.github.io/react-stockcharts/documentation.html#/brush

released a new version 0.3.0 with these 2 new interactive components.
