### ISSUE TITLE
Single date label for multiple charts

### ISSUE THREAD

**Issue by esseswann** [rrag/react-stockcharts#383]
I'm trying to get my dates appear only on the lowest chart and have lines going through all charts above like in this [example](https://rrag.github.io/react-stockcharts/documentation.html#/stochastic_oscillator) but I cannot quite understand how it's done from the source. I have standard CandleStick+MACD layout

**Comment by piotryordanov** [comment]
The date is created by the `YAxis`. What u want to try and do is have that yAxis only included in the code of the lower graph.

**Comment by esseswann** [comment]
I think it's `XAxis` actually :)
I figured it out, I was removing it but I didn't setup styles for the lower `XAxis` so no vertical lines were present

**Comment by piotryordanov** [comment]
Ah yes! Does that solve the issue then? :)

**Comment by esseswann** [comment]
Yeah, solved, thnx :)
