### ISSUE TITLE
Positioning, reflow and more (help wanted)

### ISSUE THREAD

**Issue by petren** [rrag/react-stockcharts#384]
Hi @rrag.

I have a couple of questions that I cannot seem to figure out.

1. Rescale the graph on container resize
Is there a way to recalculate the size when the container element is resized when using fitDimensions? There are specific events that I could use, or bind to if that helps.

2. OHLCTooltip positioned relative to the right side of the graph
Is it possible to set origin to the right side?

3. Styling CrossHairCursor
Can I change the width of the lines? And if so, could I have the X line looking different than the Y line?

Awesome to be working with your library as always, thank you!

**Comment by petren** [comment]
I got around #1 to resize the container by manually triggering a window resize event using:
`window.dispatchEvent(new Event('resize'));`

**Comment by petren** [comment]
@rrag I am also curious, what would be the proper way to pass in a completely new set of data, to make sure that everything is correctly garbage collected?

**Comment by rrag** [comment]
> 1.

There is nothing specific with the library, it is all DOM events, unfortunately there is no way to capture the resize of a container, only window.resize. there are different kinds of solutions available, and they are all outside of the scope of this lib

> 2.

you know the width of the chart, so you can just adjust the origin accordingly, but if you want to like right align the text with the right of the chart, you will have to create your own tooltip set the origin by accounting for the width and set `textAnchor="end"` on the svg text elements

> 3.

No, you can see the source [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/coordinates/CrossHairCursor.js#L33-L38) setting the `ctx.lineWidth` to change the width of the like, I will be happy to accept a PR to take a `strokeWidth` property. Why do you feel a need for different widths on x and y ?

> I am also curious, what would be the proper way to pass in a completely new set of data, to make sure that everything is correctly garbage collected?

change the `seriesName` in `<ChartCanvas seriesName={...}` that essentially resets the chart.

**Comment by petren** [comment]
Thanks for the answers @rrag. As far as #3, its purely a styling preference. I'd like to make the Y indicator the same width as the volume bars. This is not high priority, and if we end up doing it I will submit a PR.
