### ISSUE TITLE
Prevent yPan reset on state change

### ISSUE THREAD

**Issue by itsjimbo** [rrag/react-stockcharts#385]
Using 0.7.0-beta.19 when user has panned in the y-direction (by y-axis-drag), and then a state change is issued, the yPan and yDomain are reset to the chart data high/low.  Is there a recommended way of preserving the yExtents, to save this value on the state?

I have also noticed that the axis drag events are not being picked up by subscribe.
```
 this.node.subscribe("myUniqueId", { listener: this.handleEvents })
```

(I have yet to look at all the updates so forgive me if this was a redundant issue)

**Comment by piotryordanov** [comment]
If i'm not mistaken, this happen a state change occurs WHILE you are panning.
If your state changes every, say, five seconds, then the pan will happen and the state won't be interrupted.

However, i dunno how to help if the state changes fast enough.

**Comment by rrag** [comment]
there is a fix for the yExtents in the master branch, not published yet. could you please test if the master branch solves this problem?

**Comment by itsjimbo** [comment]
I saw this commented out, which was contributing to my issue. Thanks for pointing me in the right direction!
https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L964-L974


I also wanted to ask if there is a difference between using 
[react-stockchart's purecomponent](https://github.com/rrag/react-stockcharts/blob/master/src/lib/utils/PureComponent.js)
[react's purecomponent](https://github.com/facebook/react/blob/master/packages/react/src/ReactBaseClasses.js#L123-L131)

**Comment by itsjimbo** [comment]
I had to revert this block back to the previous, on my macbook pro trackpad it was doing some very strange behavior for the yaxis zooming, basically never decreasing the scale regardless of the mouse movement.

https://github.com/rrag/react-stockcharts/blob/master/src/lib/utils/ChartDataUtil.js#L130-L141


Here is the code that works for me:
```
function setRange(scale, height, padding, flipYScale) {
	if (scale.rangeRoundPoints || isNotDefined(scale.invert)) {
		if (isNaN(padding)) throw new Error("padding has to be a number for ordinal scale");
		if (scale.rangeRoundPoints) scale.rangeRoundPoints(flipYScale ? [0, height] : [height, 0], padding);
		if (scale.rangeRound) scale.range(flipYScale ? [0, height] : [height, 0]).padding(padding);
	} else {
		
		const { top, bottom } = isNaN(padding)
			? padding
			: { top: padding, bottom: padding };
		
		scale.range(flipYScale ? [top, height - bottom] : [height - bottom, top]);
		
		// const { top, bottom } = isNaN(padding)
		// 	? padding
		// 	: { top: padding, bottom: padding };
		//
		// scale.range(flipYScale ? [top, height - bottom] : [height - bottom, top]);
		// if (scale.invert) {
		// 	const trueRange = flipYScale ? [0, height] : [height, 0];
		// 	const trueDomain = trueRange.map(scale.invert);
		// 	scale
		// 		.domain(trueDomain)
		// 		.range(trueRange);
		// }

	}
	return scale;
}
```

**Comment by rrag** [comment]
Hi @itsjimbo are you saying you reverted the changes in both `ChartCanvas` and `ChartDataUtil` and it worked for you?

could you explain what the problem was. I had a problem where 

1. `yExtents` was set on the `Chart` 
2. and you pan on y
3. and then you update the chart, like say add a new indicator, the y

the chart updated back to the original `yExtents` from step 1. so the changes I made were to fix that.

**Comment by itsjimbo** [comment]
Hi @rrag - I was having this kind of issue with latest

  1. user drags on ```YAxis``` to perform a yaxis-zoom
  2. at some point the state is changed from another unrelated event
  3. the chart gets reset back to the high/low of the visible data after the state change

Now my class sort of looks like this:

```
class ChartWrapper extends PureComponent {
  constructor(props) {
      ...
   }
 render() {
      const {yExtentsFunctions}=this.state
     let yExtents=[...yExtentsFunctions]
      yExtents.push( (d) => [d.high, d.low] )
     return(
         <ChartCanvas ref={this.saveNode}
                       seriesName={seriesName}
                       yPan={yPan}
                       yPanEnabled={true}
         ....
                 <Chart id={1}  key={`chart`}
                         yPan={yPan}
                         yExtents={yExtents}
       ...

    )
  }

}
```

I have a configure() function that we can do something like this:
```
  let yExtentsFunctions = [];
    if (props.chartSettings.scaleYWithMovingAverages) {
      movingAverageCalculatorsKeys.map((c) => {
        if (calculators[c.key] && calculators[c.key].accessor) {
          yExtentsFunctions.push(calculators[c.key].accessor())
        }
      })
    }
   this.setState({yExtentsFunctions})
```

In previous versions this kind of code worked fine, but in latest version it was resetting on every state change, probably because I am pushing ```yExtents.push( (d) => [d.high, d.low] )``` on render, but I am not sure how to get the values of the yExtents after a y-axis zoom.

After uncommenting out the lines in ChartCanvas, which  preserves the current y-domain of the chart's state:
```
each.yScale.domain(sourceChartConfig[0].yScale.domain())
```
it seems to be functioning correctly.

Maybe we could introduce a ```forceReset``` parameter that can reset the domain? This way it can be preserved or reset..

**Comment by rrag** [comment]
Made a change to master, (not published yet) could you please check it out now

**Comment by rrag** [comment]
Published the fix to npm also. let me know if the issue is still open

**Comment by srhtylmz19** [comment]
@itsjimbo @rrag any update with related topic? i ve the same issue and couldnt deal with it , everytime when new data append to the state , yaxis reset (if i set yExtents on componentdidmount) !
