### ISSUE TITLE
Different time scales fix

### ISSUE THREAD

**Issue by jsappme** [rrag/react-stockcharts#386]
Part of my data is daily and the most recent ones are hourly. I can display everything on a stockchart but it shows the time scale differences. Is there a way to show the data properly with auto scaling the X axis ?

![cryptochart](https://user-images.githubusercontent.com/13439477/32388693-1c98f234-c08e-11e7-9c59-8bb1e06d5dc6.png)

**Comment by rrag** [comment]
You are using discontinuous scale, which is capable of dealing with gaps in the data. So this is correct behavior. If you want to plot continuous time, then use a `d3.scaleTime()`
