### ISSUE TITLE
Help I need encouragement!

### ISSUE THREAD

**Issue by QRMarketing** [rrag/react-stockcharts#387]
You have a very nice set of libraries and as you said, one of the better ones. But I hesitate with this "react" stuff. My skill level is just moderate - jQuery, D3, Node. Like most coders, my first react to react is, "Ouff!". Will I be learning another useless product like jQuery mobile (this is a pig, wish there was something better, there are so many other useless frameworks)? I have initial read a few articles on react, and a lot of negative, though perhaps just resistance to learning something new. The speed of change in react and the branches (native) concern me. In fact anything from FB concerns me (FBs's UI feels like spaghetti code). 

My critique of D3 is that the axis stuff renders poorly and a lot of hacking is required to get it right, especially on time-series charts and mouse events. Node I find is hard to debug, unlike JavaScript, though yes they have tools, it is painful and often I use a quick console.log. I just wonder that this reacts adds another abstraction, making debugging even more difficult - yippes!

This canvas vs svg concerns me as well, as canvas renders poorly, it often gets fuzzy compared to svg, regardless of performance. Raster based graphics I find renders slow, with tick level real-time charting. Once you get the charts going, I just wonder how easy it will be to build stuff on top, dropping back into other JavaScript application functions, etc ... for our applications - charts are just the beginning.

Though you have a lot of good examples, installation and usage documentation is poor. It assumes you know a lot already. I suggest you spend a little time doing a basic "hello world" chart tutorial, explaining more what is happening and how one could add to it.

I worry jumping into this rabbit hole, help I need encouragement!

**Comment by rrag** [comment]
I cannot solve you not liking javascript and react and d3. Sorry you have to look elsewhere.

**Comment by QRMarketing** [comment]
Well, I did not say I dislike JavaScript or D3, just concerns. React I do not know. But your thoughts on the support of your product are duly noted. Thanks for the honest reply.
