### ISSUE TITLE
Changing interval on zoom

### ISSUE THREAD

**Issue by timsu** [rrag/react-stockcharts#390]
Hi there! We have a data source that can provide data at multiple frequencies (daily, hourly, minutely). As the user zooms in / out, I'd like to capture that and change the data set so users see the appropriate frequency data for their time window. Is there a way to hook onto zoom events to do that? I see `zoomEvent` in ChartCanvas.js but there doesn't seem to be a public hook. Thanks!

**Comment by rrag** [comment]
try this - https://github.com/rrag/react-stockcharts/issues/300

and listen to the event type `zoom`
```
handleEvents = (type, moreProps, state) => {
  
}
```
