### ISSUE TITLE
Bug when CandlestickSeries only have one point

### ISSUE THREAD

**Issue by sokai116** [rrag/react-stockcharts#393]
![image](https://user-images.githubusercontent.com/5397428/32816987-79788944-c9f6-11e7-86a7-57bc11526329.png)

After i turn off the "review the 'xExtents' prop of ChartCanvas" Error, it show an incomplete candlestick.
And please remove the non-production Error for single data point, as it really exist some cases need to test for single data point chart =[

**Comment by rrag** [comment]
One datapoint is not enough to determine the x axis start and end positions, need a minimum of 2 points to get min and max date.

The error should also happen in production. I don't remember why I included that check just for dev mode. Could you not add a another datapoint to get over this problem?

**Comment by sokai116** [comment]
I think I cannot add another datapoint, as there are only one point in some production cases.
If it cannot determinate, can I provide the x axis scare to the chart in some way?

**Comment by xreef** [comment]
A workaround to show complete candlestick is to force on CandlestickSeries width to 20.

**Comment by rrag** [comment]
@sokai116 you need 2 data points, there is no easy way to solve this, I suggest adding one more made up data with just the x value and no y value to solve this.

**Comment by lunikon** [comment]
I am having the same issue. That there is only a single data point is a very common use-case for us. We ensure to provide `xExtents` manually, so in principle, the library should be able to compute the size of the x-axis. But it fails with an error.
