### ISSUE TITLE
data exceeds in volume bar chart 

### ISSUE THREAD

**Issue by tmclouisluk** [rrag/react-stockcharts#394]
![capture](https://user-images.githubusercontent.com/18186155/33113491-a9a900ce-cf93-11e7-8a41-6c09c9d5e80a.JPG)
something like that

here is my volume chart code.

```js
<Chart id={2} origin={(w, h) => [0, h - 150]} height={200} yExtents={[d => d.volume, smaVolume20.accessor()]}>
    <YAxis axisAt="left" orient="left" ticks={5} tickFormat={format(".3s")}/>
    <MouseCoordinateY
        at="right"
        orient="right"
        displayFormat={format(".3s")} />
    <BarSeries yAccessor={d => d.volume} fill={(d) => d.close > d.open ? green[500] : red[500]} />
    <LineSeries yAccessor={smaVolume20.accessor()} stroke={smaVolume20.stroke()}/>
    <CurrentCoordinate yAccessor={smaVolume20.accessor()} fill={smaVolume20.stroke()} />
</Chart>
```

and my json data:
![1](https://user-images.githubusercontent.com/18186155/33113563-ecb9c7f4-cf93-11e7-9d03-7fd4c35af9c7.JPG)

is it bug or my setting problem?
thanks

**Comment by rrag** [comment]
could you try this
```diff
-<Chart id={2} origin={(w, h) => [0, h - 150]} height={200} yExtents={[d => d.volume, smaVolume20.accessor()]}>
+<Chart id={2} origin={(w, h) => [0, h - 150]} height={150} yExtents={[d => d.volume, smaVolume20.accessor()]}>
```

**Comment by tmclouisluk** [comment]
Hello rrag,

it's the same even i remove chart id 1 and try this
`<Chart id={2} yExtents={[d => d.volume, smaVolume20.accessor()]}>`

**Comment by tmclouisluk** [comment]
notes: I'm using the testing data on NVDA/BA/MRK in 100 days daily data.

**Comment by rrag** [comment]
not sure you noticed this, you had
```js
 [0, h - 150]} height={200}
```

did you change the height also to `150` ?

**Comment by tmclouisluk** [comment]
Yes, 
but this doesnt help :(
![capture](https://user-images.githubusercontent.com/18186155/33114905-e7b04a48-cf99-11e7-8cd1-1bcfba97fdb4.JPG)

if i show the volume only and set 
`<Chart id={2}  yExtents={[d => d.volume, smaVolume20.accessor()]}>`
![1](https://user-images.githubusercontent.com/18186155/33114966-307e4aea-cf9a-11e7-8e99-0acf0ce8491a.JPG)

the problem is still here :(

**Comment by rrag** [comment]
it looks correct, I dont see what the problem is. can you share a codesandbox or the data file

**Comment by tmclouisluk** [comment]
[sandbox](https://codesandbox.io/s/github/tmclouisluk/react-stockchart-volume)

here you are. 
You can see the bug is still here

**Comment by rrag** [comment]
The problem was you were using string for volume, o, h, l, c.
I changed volume to a number and it worked

https://codesandbox.io/s/x74j5z11po

```diff
                var obj = data[key];
                obj = {
                    open: obj["1. open"],
                    close: obj["4. close"],
                    high: obj["2. high"],
                    low: obj["3. low"],
-                   volume: obj["5. volume"],
+                   volume: +(obj["5. volume"]),
                    date: new Date(key)
                }
                return obj;
            });
```

**Comment by tmclouisluk** [comment]
yeah
Once I change the volume to number then it's ok now
really thanks you so much!!!
