### ISSUE TITLE
Does react-stockcharts only support data as candles?

### ISSUE THREAD

**Issue by mkondel** [rrag/react-stockcharts#396]
I have a database where I store live trades that happen on my exchange. These are not candles, but individual trades throughout the day. Is it possible to feed this 'raw' trade data into react-stockcharts, or would I have to transform my data into candles first?

Example of what a trade might have vs a candle:
```javascript
{ // Candle
    date: '2010-01-04',
    open: 25.436282332605284,
    high: 25.835021381744056,
    low: 25.411360259406774,
    close: 25.710416,
    volume: 38409100
}
{ // Trade
    date: '2010-01-04',
    type: 'BTC-USD',
    side: 'buy',
    tradeId: 11995622,
    price: 25.436282332605284,
    size: 38.55
}
```

**Comment by rrag** [comment]
candles and trades are two different types of data, there could be multiple trades happening inside a single candle, I would not combine them, instead have them separate, like

```
/api/data/<ticker>?exchange=...&foo=bar&...
/api/trades/<ticker>?exchange=...&....
```

now as for plotting the trades, I would think it would be a different shape you will want to plot, and it will overlay the candles. There are different ways to achieve that, but for starters, look at the [annotation](http://rrag.github.io/react-stockcharts/documentation.html#/ma_crossover_using_svg_shape) api.

The biggest difference between the example in the docs and here is that data for the annotation is from a different api, so you will have to figure out a way to combine the two arrays client side.

Or you can create a new series say `<Trades data={tradeData} />` that takes in the trade data and interpolates and plots the data. I have used this approach to plot unrelated data, like for e.g. unemployment data or EPS as a separate series with a price chart

**Comment by mkondel** [comment]
I ended up writing an api end point that will do the work of reading DB and turning trades into candles. As for trades, I was picturing candles, but not as a time series. Each trade candle is always made up of N trades. This can also be done in the api, I suppose.

What you are suggesting with <Trades/>, is it to make a component that wraps <ChartCanvas/>, turns trades into candles, then passes them down?

**Comment by rrag** [comment]
> What you are suggesting with <Trades/>, is it to make a component that wraps <ChartCanvas/>, turns trades into candles, then passes them down?

no, rather

```jsx
<ChartCanvas ...>
  <Chart ...>
    ...
    ...
    <Trades data={tradeData} .../>
  </Chart>
  ...
</ChartCanvas>
```

so `Trades` will have access to the x/y scales it gets the trade data as a prop, so it could interpolate all the trades to be displayed for a given xdomain.

I still have trouble thinking of trades as a candle, could you share a screenshot of what you have done, it will help me understand it better

**Comment by mkondel** [comment]
Would Trades be a component under src/lib/series/Trades.js? I will take a look in CandlestickSeries.js to see if I can use it as a starting point. 

Trades as candles still just look like OHLC. With time based, every candle starts on the same interval, so the X-axis is uniformly scaled. Trade candles count a constant number of trades, so the X-axis updates whenever the candle fills up. Candles are still drawn next to each other, but one inch on the X-axis can be an hour or 5 minutes, depending on how active the market is.

I dont have an example of this working yet. So far I have an API server that returns time based candles. For example, last 12 hours as 1 hour candles. This is working with react-stockcharts and shows a plot. I dont have an example of trades as candles, but I can post a comparison once I do.

**Comment by rrag** [comment]
> Would Trades be a component under src/lib/series/Trades.js? I will take a look in CandlestickSeries.js to see if I can use it as a starting point.

you can have the component anywhere but yes it will follow the structure of `CandlestickSeries.js`
