### ISSUE TITLE
How to create own indicator?

### ISSUE THREAD

**Issue by tmclouisluk** [rrag/react-stockcharts#398]
Is it the flow like that?

1. create two .js file, says, indicator.js into calculator and indicator folders: custom/indicator + custom/calculator 
The code in these 2 .js file will take a reference to the current indicators, like sma, wma, etc.

2. Then we call it in the chart
```
import { indicator } from "../custom/indicator";

const indicator = indicator ()
            .options({ windowSize: 10 })
            .merge((d, c) => {d.indicator = c;})
            .accessor(d => d.indicator )
```

**Comment by rrag** [comment]
that is how I have it in the examples, the important thing to understand is that, the indicators are calculated outside of the chart. For e.g. you can calculate any indicator and just console log the data after it like

```
const calculatedData = defaultSar(initialData);
console.log(calculatedData)
```

The idea is that in future all the calculators can be external to the library / calculate using another library or even have the indicators calculated serverside. the Chart components expect the data to be in the format

```
[
 { date, open, high, low, close, sar },
  ...
  ...
]
```

if you are plotting multiple indicators in a chart, and can create data of the form

```
[
  { date, open, high, low, close, volume, indicator1, indicator2, indicator2 }
]
```

you have to set the correct accessors to the `<Indicator1/2/3 ...` 

hope that helps, feel free to let me know if you have any questions

**Comment by tmclouisluk** [comment]
btw if i setup
```
const indicator = indicator ()
            .options({ windowSize: 10 })
            .merge((d, c) => {d.indicator = c;})
            .accessor(d => d.indicator )
```

An error occurs that: indicator() is not a function
my indicator.js in calculator and indicator folders are copied from sma one.
So how can I setup the indicator object like 
```
const sma10 = sma()
            .options({ windowSize: 10 })
            .merge((d, c) => {d.sma10 = c;})
            .accessor(d => d.sma10)
```
in render()?
