### ISSUE TITLE
when intra-day support?

### ISSUE THREAD

**Issue by mikewin** [rrag/react-stockcharts#40]
wait for this function, thanks a lot.

**Comment by rrag** [comment]
I have not started on this yet. here is my initial plan on the next few releases.

https://github.com/rrag/react-stockcharts/blob/master/docs/md/COMING-SOON.md

 It can still change though.

**Comment by mikewin** [comment]
Really cool!

How about support trade info display on chart?

**Comment by rrag** [comment]
what is "support trade info"? I am not aware of that. Can you show me what that is? Let us continue on [gitter](https://gitter.im/rrag/react-stockcharts) chat, as this seems to be a new feature request. Let us not change topic on this thread

**Comment by svk31** [comment]
Curious about this one too since I would like to use your library for a live crypto currency trading website. Considering how crypto trading "never sleeps" and doesn't stop for weekends, do you think I'd be better off writing a custom time scale for that?

**Comment by rrag** [comment]
if you are working with continuous data, don't worry about creating a new scale. just use `d3.scale,time()`

There should be no big changes, but I would expect problems with chart types like Renko, Kagi, P & F. 

In any case I am doing a lot of refactor now part of 0.4 I will try to test this.

**Comment by svk31** [comment]
OK that's great, I can probably lay off the advanced chart types for now, thanks.

**Comment by brobits** [comment]
using `d3.time.scale()` in lieu of `financeEODDiscontiniousScale()` does not work.

- candlesticks render as lines (as if zoomed out far)
- zooming does not work properly
- mouse cursor x selection does not work properly (sticks to far left/right side of chart)

any way we can help get intraday scales moving along?

**Comment by rrag** [comment]
I know I have been procrastinating on this.

I assume the changes will be only limited to creating a new scale. I can try something out next week.

If you have access to and can share test intra day data for a security for a few months, at 1 min intervals, that would be very helpful.

**Comment by brobits** [comment]
similar to @svk31 I am also using cryptocurrency data.  I'll get you some datasets soon for multiple intraday intervals for XBT/USD.

**Comment by brobits** [comment]
a few notes, some of the changes I'm seeing that need to be done to support intraday scales:

- add financeIntradayDiscontinuousScale
- add financeIntradayCalculator
- add intradayIntervalCalculator
- better? way for evaluator to select the appropriate interval calculator (currently need to pass as a prop to ChartCanvas)
- calculate intraday boundaries in financeIntradayCalculator
- support data splicing for intraday scales in intradayIntervalCalculator
- update timeScaleSteps in financeIntradayDiscontinuousScale

I have some of these changes on a fork, I'll post the branch & hopefully an intraday dataset soon.

**Comment by rrag** [comment]
looks great. Looking forward to this

**Comment by brobits** [comment]
I have added a bitcoin/USD dataset for Bitfinex 1-minute OHLC bars on my branch, here: https://github.com/brobits/react-stockcharts/blob/intraday_scales/docs/data/bitfinex_xbtusd_1m.csv

disclaimer: the data may have some empty bars when the adapter was off, and may have some gaps.  the dataset is _mostly_ contiguous, but not entirely.

the changes I've pushed to the `intraday_scales` branch have basic support for resolutions I've tested around 1m thru ~6h bars.  if you'd like 5m, 10m, 15m, 30m, 1h, 2h, 4h, 6h, 12h, or 1d bars I have some additional datasets available.

I'll open a PR for the new branch, although I consider the branch to still be WIP and a working PR.  at a minimum the commits will need to be rebased and collapsed into something prettier.

**Comment by iNikNik** [comment]
Hello, guys!
I believe we need to change [eodCalculator](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/financeEODCalculator.js#L16-L31), [scale steps](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/financeEODDiscontiniousScale.js#L9-L31) and [formatters ](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/financeEODDiscontiniousScale.js#L34-L40) for different scales.

So, I suggest to export not `financeEODScale` but `financeEODScaleFactory` [here](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/financeEODDiscontiniousScale.js#L7):

```javascript
// before
export default function financeEODScale(indexAccessor = d => d.idx, dateAccessor = d => d.date, data = [0, 1], backingLinearScale = d3.scale.linear()) {

	var timeScaleSteps = [
		{ step: 864e5, f: function(d) { return isDefined(dateAccessor(d)) && true; } },  // 1-day
		{ step: 1728e5, f: function(d, i) { return isDefined(dateAccessor(d)) && (i % 2 === 0); } }, 
        // ...
	];
	var tickFormat = [
		[d3.time.format("%Y"), function(d) { return d.startOfYear; }],
		[d3.time.format("%b %Y"), function(d) { return d.startOfQuarter; }],
         // ...
	];
```

```javascript
// after
export default function financeEODScaleFactory(createTimeScaleSteps = createDefaultTimeScaleSteps, tickFormat = defaultTickFormat) {
  return function financeEODScale(indexAccessor = d => d.idx, dateAccessor = d => d.date, data = [0, 1], backingLinearScale = d3.scale.linear()) {
    var timeScaleSteps = createTimeScaleSteps(dateAccessor, data)
```

As you can see in this case you can set your own `timeScaleSteps` and `tickFormat` without copying and changing any code:

```javascript
const financeEODScale = financeEODScaleFactory(/* here you can pass your own stuff */)
const xScale = financeEODScale()
```

Then we can create `createDefaultTimeScaleSteps.js` with signature below:
```javascript
const createDefaultTimeScaleSteps = (dateAccessor) => [
  { step: 1e3, f: function(d) { return isDefined(dateAccessor(d)) } }, 
  { step: 2e3, f: function(d) { return isDefined(dateAccessor(d)) && d.startOfSecond } },  
  // ...
]
export default createDefaultTimeScaleSteps
```
And `defaultTickFormat.js`:
```javascript
export default [
  [d3.time.format("%b %Y"), function(d) { return d.startOfYear; }],
  //[d3.time.format("%b %Y"), function(d) { return d.startOfQuarter; }],
  // ..
]
```
With this stuff i've created my own intraday scale:
![intradey_scale](https://cloud.githubusercontent.com/assets/7679749/14709087/657e618a-07d7-11e6-80ce-05f3644508aa.gif)


@rrag @brobits what do you think about it?

**Comment by rrag** [comment]
I do like this, a scale factory is cool.

how about the interval calculator? how did you implement the interval jumps, when zoom in/out

@brobits has a [PR](https://github.com/rrag/react-stockcharts/pull/69). I would like your comment there

**Comment by brobits** [comment]
intraday scales are working on the PR. factories are great! if we decide to move to factory patterns, we should push the concept to all pieces of the chart rather than just the scales.

as a side note, even with this factory pattern you still may run into issues with your interval calculator.  specifically, intraday interval calculators may still need to be customized, such as the difference between `getHours()` and `getUTCHours()` for hour-bar boundaries in UTC or local time, depending on the data source and desired tick display to the user.

**Comment by rrag** [comment]
just curious, why cant we always use `getUTCHours`?

**Comment by iNikNik** [comment]
@rrag 
> how about the interval calculator? how did you implement the interval jumps, when zoom in/out

I've changed `eodCalucator`'s [accumulator](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/financeEODCalculator.js#L15-L35)
It's still a prototype. I'm using this scale for both realtime(intraday) and historical scales:
```javascript
.accumulator(([prev, now]) => {
        var prevDate = dateAccessor(prev);
        var nowDate = dateAccessor(now);


        var startOf100MilliSecond = Math.floor(nowDate.getMilliseconds() / 100) != Math.floor(prevDate.getMilliseconds() / 100)
        var startOfSecond = nowDate.getSeconds() !== prevDate.getSeconds()
        var startOf5Second = Math.floor(nowDate.getSeconds() / 5) !== Math.floor(prevDate.getSeconds() / 5)
        var startOfMinute = nowDate.getMinutes() !== prevDate.getMinutes()
        var startOf2Minutes = Math.floor(nowDate.getMinutes() / 2) !== Math.floor(prevDate.getMinutes() / 2)
        var startOf5Minutes = Math.floor(nowDate.getMinutes() / 5) !== Math.floor(prevDate.getMinutes() / 5)
        var startOf10Minutes = Math.floor(nowDate.getMinutes() / 10) !== Math.floor(prevDate.getMinutes() / 10)
        var startOf15Minutes = Math.round(nowDate.getMinutes() / 15) !== Math.round(prevDate.getMinutes() / 15)
        var startOf30Minutes = nowDate.getMinutes() >= 30 && prevDate.getMinutes() < 30
        var startOf2Hours = Math.floor(nowDate.getHours() / 2) !== Math.floor(prevDate.getHours() / 2)
        var startOf6Hours = Math.floor(nowDate.getHours() / 6) !== Math.floor(prevDate.getHours() / 6)
        var startOfHour = nowDate.getHours() !== prevDate.getHours()
        var startOfDay = nowDate.getDay() !== prevDate.getDay()
          //|| (nowDate.getTime() - prevDate.getTime() > 1000 * 60 * 60 * 24)
        var startOfHalfDay = nowDate.getHours() >= 12 && prevDate.getHours() < 12 && !startOfDay
        // According to ISO calendar
        // Sunday = 0, Monday = 1, ... Saturday = 6
        // day of week of today < day of week of yesterday then today is start of week
        var startOfWeek = d3.time.week(nowDate).getTime() !== d3.time.week(prevDate).getTime();
        // month of today != month of yesterday then today is start of month
        var startOfMonth = nowDate.getMonth() !== prevDate.getMonth();
        // if start of month and month % 3 === 0 then it is start of quarter
        var startOfQuarter = startOfMonth && nowDate.getMonth() % 3 === 0;
        // year of today != year of yesterday then today is start of year
        var startOfYear = nowDate.getYear() !== prevDate.getYear();

        var row = {
          ...now,
          startOf100MilliSecond,
          startOfSecond,
          startOf5Second,
          startOfMinute,
          startOf2Minutes,
          startOf5Minutes,
          startOf10Minutes,
          startOf15Minutes,
          startOf30Minutes,
          startOfHour,
          startOf2Hours,
          startOf6Hours,
          startOfHalfDay,
          startOfDay,
          startOfWeek,
          startOfMonth,
          startOfQuarter,
          startOfYear
        };
        return row;
      })
```
And that's all.

As @brobits said:
> if we decide to move to factory patterns, we should push the concept to all pieces of the chart rather than just the scales.

I've created factories for all `scale` parts (evaluator, interval Calculator ..)

**Comment by rrag** [comment]
ha ha

> startOf100MilliSecond,
> startOfSecond,

isnt that a little too much :)

If you dont use `getUTCHours` `getUTCMinutes`, `getUTCXXX` this would not work for day light saving shift right?

**Comment by iNikNik** [comment]
@rrag basically i have chart's like this:
![image](https://cloud.githubusercontent.com/assets/7679749/14714955/b635fabc-07ef-11e6-94bf-c6336e5588ef.png)
So, I need milliseconds for them) But anyway - I'd like to split it because there is too much calculations for each point

**Comment by brobits** [comment]
@rrag I suggest that we do, but I think there is a use case if you want your ticks to align on boundaries to the user's local time, in which case you'd need a new interval calculator.  I don't think we should include one in source though.

**Comment by rrag** [comment]
closing in favor of https://github.com/rrag/react-stockcharts/issues/73
