### ISSUE TITLE
Issue on Zoom on Change State

### ISSUE THREAD

**Issue by QRMarketing** [rrag/react-stockcharts#400]
I was looking at the Zoom function. I have Chart 1 Candlesticks (yExtents={[d => [d.high, d.low]]}) and Chart 2 RSI (yExtents={[0, 100]}). The events are the following:

1. The chart looks as normal, even with updating (every 500ms) data (the data looks good).
2. I then Zoom the Yscale scale.
3. It Zooms, but once I release the mouse (after state change), the Yscale goes to 0 to 100. On both Charts 1 and 2. One can still Zoom at this level (though wrong) but after state changes, the Yscale goes back to 0 to 100.
4. Reset, and the chart and it goes back to normal, but then reZoom and it happens again.

I get the feeling that the  "yExtents={[d => [d.high, d.low]]}" in my charts gets reset to "yExtents={[0, 100]})" on mouse release and after state change (on both Chart 1 and 2).

As a foot note (strange): If I make Chart 2 MACD (yExtents={macdCalculator.accessor()}). Chart 1 is OK when Zooming, though if I Zoom the MACD Chart 2, then Chart 1 gets the Yscale of the MACD, Chart 2.

Is this mycode or something related to the issue in the ref link?

Note: I did refresh a new install from NPM.

Ref link: https://github.com/rrag/react-stockcharts/issues/385

**Comment by rrag** [comment]
is this problem visible in the examples also or is this happening only in your code?

Also could you record a video and share please

**Comment by rrag** [comment]
Yes, i see the problem, thank you for reporting, I am looking at it now

**Comment by rrag** [comment]
Fixed in `0.7.0-beta.21` Thank you for reporting

**Comment by QRMarketing** [comment]
Hello rrag, I confirm to you this has been fixed. Thanks, nice work! One very minor picky thing on some of the added props. When using fontSize of 11 the text in the arrow is poorly skewed depending if it is right or left. The following was a ugly hack to fix it. 

       `        
               // BPT KLUGE { key: 2, x: edge.coordinate.edgeXText + 8, for right none for left	
		        		
                var kluge = edge.orient === "right" ? edge.coordinate.edgeXText + 8 : edge.coordinate.edgeXText;

		coordinate = _react2.default.createElement(
			"text",
			{ key: 2, x: kluge,
				y: edge.coordinate.edgeYText,
				textAnchor: edge.coordinate.textAnchor,
				fontFamily: edge.coordinate.fontFamily,
				fontSize: edge.coordinate.fontSize,
				dy: ".32em", fill: edge.coordinate.textFill },
			edge.coordinate.displayCoordinate
		);

`
