### ISSUE TITLE
Bottom padding

### ISSUE THREAD

**Issue by esseswann** [rrag/react-stockcharts#402]
I there a way to add some bottom "padding" for my charts so the sticks would begin a little above the baseline, while YAxis would begin from the actual bottom. I need it to prevent chart to overlap the volume bars, while having a consistent YAxis labels

![capture](https://user-images.githubusercontent.com/6066417/33407063-b3705d80-d580-11e7-8db1-7f98af92e2f9.PNG)

**Comment by rrag** [comment]
:) yes upgrade to `0.7.0-beta.21`

**Comment by esseswann** [comment]
I have never seen feature requests satisfied on GitHub, 2 minutes after issue creation 😲

**Comment by rrag** [comment]
its your lucky day :) !!!

**Comment by esseswann** [comment]
If anybody wondering: add `padding: { bottom: 100, top: 0, left: 0, right: 0 }` to a `<Chart />` component
