### ISSUE TITLE
Chart updates incorrectly on resize in v0.7.0-beta.21

### ISSUE THREAD

**Issue by alexandr-bbm** [rrag/react-stockcharts#403]
After update from `v0.7.0-beta.20` to `v0.7.0-beta.20` rendering the chart with new width leads to incorrect calculation. For example, if we increase the width of window, the left area of a chart remains empty.

It was noticed both on hybrid and svg types, and for different charts (BarSeries and AreaSeries).

It could possibly happen after [this commit](https://github.com/rrag/react-stockcharts/commit/dc2d3a7baabb3afc2a0789c93539424e2b9eee5b).

**Comment by rrag** [comment]
Hi @alexandr-bbm the default resize behavior was changed to [this](https://github.com/rrag/react-stockcharts/issues/335#issuecomment-329519821) in the commit you identified, but I dont see the problem you have described.

I opened up,
http://rrag.github.io/react-stockcharts/documentation.html#/theme_dark
 and was resizing the window, and there was no problem with the left area being empty

If you prefer the original behavior which will try to fit the same number of candles in the new width try out

```
<ChartCanvas ... maintainPointsPerPixelOnResize={false} ... >
```

it would be very helpful if you can share a gif or screencast of the problem.

**Comment by rrag** [comment]
Hi @alexandr-bbm  any feedback please

**Comment by rrag** [comment]
closing this issue, please add more details if you still have the problem and I will reopen
