### ISSUE TITLE
JSON data format to provide for stock chart

### ISSUE THREAD

**Issue by Rangarajan0603** [rrag/react-stockcharts#405]
I tried to provide the data to the stock chart as 
`[ {"date": new Date(2010, 0, 3), "open": 25.43, "high": 25.83, "low": 25.41, "close": 25.71, "volume": 38409100 }...]`
But it is not working. 

What is the correct format to provide data to the stock chart as JSON?

**Comment by tombohub** [comment]
Do you support JSON?
