### ISSUE TITLE
Adding Symbols to Chart?

### ISSUE THREAD

**Issue by flavioespinoza** [rrag/react-stockcharts#406]
Is there a way to mark Buy and Sell Orders with a circle or symbol? Please see attached image.

<img width="519" alt="screen shot 2017-12-11 at 10 41 33 pm" src="https://user-images.githubusercontent.com/2214913/33869186-b06dd4bc-dec4-11e7-8bc3-f061943a2bb1.png">

**Comment by rrag** [comment]
Yes any svg shape can be drawn on the chart, an e.g is [here](http://rrag.github.io/react-stockcharts/documentation.html#/ma_crossover_using_svg_shape)

**Comment by flavioespinoza** [comment]
Thank you, Ragu!
