### ISSUE TITLE
How to customize indicator to use the MovingAverageTooltip tag

### ISSUE THREAD

**Issue by tossers** [rrag/react-stockcharts#408]
Hello, I've been using this library recently to write some charts and find that the MovingAverageTooltip tag is easy to use, but the options configuration in it can only be an existing indicator, such as ema ().How can I customize my indicator, and then how to configure it to be introduced to MovingAverageTooltip?Can you give me an example or a tutoria.

**Comment by rrag** [comment]
> How can I customize my indicator, and then how to configure it to be introduced to MovingAverageTooltip

the `options` object takes a `type` may be that can help?

https://github.com/rrag/react-stockcharts/blob/master/src/lib/tooltip/MovingAverageTooltip.js#L125-L129

**Comment by tossers** [comment]
Thank you for your reply, although this lets me know the type of parameter, but I don't know how to implement it in detail.
For example, yAccessor(), if I pass an empty function () => {}, then it's wrong.
In fact, I'm thinking of adding an average and MA line with this tag, but I don't know how to do that.

**Comment by rrag** [comment]
`yAccessor` will have to be the accessor for you moving average, for instance you have 

```
const data = [
  { date, open, high, low, close, myownCoolMovingAverage },
  { date, open, high, low, close, myownCoolMovingAverage },
  { date, open, high, low, close, myownCoolMovingAverage },
  { date, open, high, low, close, myownCoolMovingAverage },
  ...
]
```

`yAccessor` will be `d => d.myownCoolMovingAverage`
