### ISSUE TITLE
suggestion Indicators  "Force Index" , Elder Ray

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#41]
Calculation Force Index

Force Index(1) = {Close (current period)  -  Close (prior period)} x Volume
Force Index(13) = 13-period EMA of Force Index(1)

more: 
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:force_index

Elder Ray:

Bull Power = Daily High - n-period Exponential Moving Average (EMA)
Bear Power = Daily Low - n-period EMA

http://d3fc.io/playground/playground.html?example=components/indicator/elderRay

**Comment by rrag** [comment]
will try to add to 0.4

**Comment by rrag** [comment]
made some progress on this on the `next` branch

[force index](http://rrag.github.io/react-stockcharts-next/documentation.html#/indicators_forceindex) - this is complete

[elder ray](http://rrag.github.io/react-stockcharts-next/documentation.html#/indicators_elderray) - have to create a new series to super impose the bull and bear power like d3fc does

**Comment by rrag** [comment]
Done, will be released when 0.4 is out
