### ISSUE TITLE
consider not to drop svg support

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#410]
> Explore removal of svg mode & all svg components completely, so this becomes a canvas only library (Tentative)

Svg provides 
- "automatic scaling", 
- "crisp resolutions" (does not matter, 4k or higher), 
- "less memory and energy consumptions" (mobile, tables) 
- much easier styling (by css)
- (the vast amount of d3 modules..)
- a lot of user interactions within svg is actually slower than canvas (but only until now..)

Echarts, for example, has included svg support recently after its canvas rendering (https://ecomfe.github.io/echarts-doc/public/en/tutorial.html#Render%20by%20Canvas%20or%20SVG) for special reasons. Please consider to let abstract the rendering part so user can choose between svg or canvas even in the future.

By the way, look at the styling of 
- https://www.sylvaindurand.org/d3-stockcharts/
- http://techanjs.org/

They all are based on svg with d3.
Maybe you can adapt some the nice visual parts.

**Comment by piotryordanov** [comment]
I'm not the maintainer, but I have worked with the source code, so I can tell that keeping both modes means that every single rendering function needs to be written twice, which can become painful to maintain.

That said, the 2 libraries have not been updated in over a year. I don't know what it says about the relevance of the argument.

That being said, I personally only use svg and not canvas because canvas was not rending as I wanted it to render.

**Comment by nimo23** [comment]
>both modes means that every single rendering function needs to be written twice

Echarts has solved this by introducing an abstraction layer called "zrender". Maybe a similiar layer can be build.

**Comment by piotryordanov** [comment]
Probably. @rrag would know better on that one.

**Comment by rrag** [comment]
Hey thanks for bringing this up. I dont think I will be dropping svg support. I should update the roadmap to reflect that. I quite like svg during development it is the best.

However I do want to clear up some of the statements made which I do not believe is accurate

> "automatic scaling",

Yes vector graphics scales infinitely, however for practical purposes you can basically draw a canvas with a given height and width and still get the desired chart

> "crisp resolutions" (does not matter, 4k or higher),

This is addressed in canvas using the `ratio` property on `ChartCanvas`, if you do see problems where canvas is not as crisp as svg, then it is a bug

> "less memory and energy consumptions" (mobile, tables)

I find that hard to believe, svg is more elements for a chart, I am not sure how it can be better. I have tested a chart with 1000 shapes on an ipad air 1 svg is so slow compared to canvas. I did profile it on a One plus one and there also canvas beats svg

like @piotryordanov said every visual component has 2 functions for drawing, one each for canvas and svg. The only problem is maintaining them both and fixing any bugs on both implementations, it is quite easy to miss one. During development I usually start with svg, and then when I get the shape I want I go on to creating the canvas, but after that I tend to add more styling options to the canvas only, and forget about svg. My laziness and lack of tests are only to blame for this.

I do like the idea to defining a strategy for rendering. I dont know how Echarts solved it if there is a blog or some material you can point me to I would appreciate that

Once thing to consider in this project though is that we have separate react components for each visual element, and right now each of these have 2 functions, so if we separate the rendering as a separate strategy not sure how that would fit with the components for each approach.

**Comment by nimo23** [comment]
> Vega provides an abstraction layer for both rendering and event processing, which in turn provides flexibility. By using an internal scenegraph (rather than the DOM), Vega can render visualizations **using either HTML5 Canvas or SVG**..For common yet customizable chart types, programmatic generation, and **flexible rendering**, we believe Vega can further facilitate the use of data visualization across a variety of new tools and web applications.

>..generate interactive views using either HTML5 Canvas or SVG

- https://vega.github.io/vega/about/vega-and-d3/
- https://github.com/vega/vega

Vega uses a abstraction layer to choose between svg and canvas. The look into source can provide how abstraction layer is implemented.
