### ISSUE TITLE
consider to use static properties within class

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#411]
A minor notice:

You can use **statics** within class instead of objects out of the class.

So instead of this:

```
class Summary extends React.Component {
  ..
}

propTypes = {..}
export defaultProps={..}
```

use this:

```
class Summary extends React.Component {
  static propTypes = {..}
  // no more undefined
  static defaultProps={..}
  ..
}
```

With this statics are only created once.

Btw: to measure/debug performance of you can use 

`npm install react-addons-perf --save-dev`

**Comment by rrag** [comment]
yeah I like `static propTypes` and `static defaultProps` I think they are still stage-2 though, so once it becomes stage 3 I am all for it.
