### ISSUE TITLE
no need for "use strict"; in ES6-modules

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#412]
A minor thing:

you can delete all `"use strict";` at the beginning of a file, because ES6 modules are already in strict mode by default. https://stackoverflow.com/questions/31685262/not-recommended-to-use-use-strict-in-es6

**Comment by rrag** [comment]
got it, want to send a PR for this?

**Comment by nimo23** [comment]
yes, I will do that the next time.

**Comment by rrag** [comment]
Removed `"use strict"`
