### ISSUE TITLE
How to display multiple series with separate X axis values?

### ISSUE THREAD

**Issue by michaelr524** [rrag/react-stockcharts#413]
Is it currently possible with react-stockcharts to display multiple time series on the same chart, where each series has different X axis values?
We'd like to display the raw trades together with asks and bids, without time interval aggregation.

**Comment by michaelr524** [comment]
Looks like the current code doesn't support that use case. I might be able to add this feature, if it's something that you'd consider to merge.
Please let me know what you think. @rrag

**Comment by rrag** [comment]
Hi @michaelr524 sorry for the delay, if I understand this correct, you want to show asks and bid, like 

![tt_f_depth](https://cloud.githubusercontent.com/assets/6270599/11039225/a12c9b16-8717-11e5-831e-242105741ae9.jpg)

market depth chart or is this something else? Can you share a screenshot of what you are thinking so I can better understand it.

**Comment by michaelr524** [comment]
Yes, I guess that I wasn't really clear about this. What we are actually putting on the chart is the ticker (highest bid, lowest ask), together with the trades.
You can see it on the attached screenshot, blue dots are trades, green are highest bids, and yellow lowest ask.
So, the ticker series has different X values than the trades series.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/1745556/34372086-0edb27da-eadb-11e7-9b43-dbf399f28bef.png">

**Comment by michaelr524** [comment]
Screenshot is from Grafana, BTW.

**Comment by rrag** [comment]
This is a good one. so this is possible by adding a custom series. I did one such to draw a line series of unrelated data, 

in this e.g. below you can see the ohlc price chart and gold price and EBIDTA all in the same plot

![deepinscreenshot_select-area_20171227061448](https://user-images.githubusercontent.com/10691183/34381301-537686ae-eacd-11e7-9a5a-5dae1724a47d.png)

here this chart has 3 different types of data, ohlc price, gold price, EBIDTA values, and the data of these do not really match up well on the x. So what I ended up doing was create a new custom component which will take in a different data like so

```
<Chart ...>
  <MyMacroEconomicOrFundamentalDataSeries data={goldprices} ... />
</Chart>
```

and inside this component use the first and last values of the `plotData` to determine what is shown and then filter out the rest from the `data` prop, and then plot the filtered data using `LineSeries`.

In your case you will need a `ScatterSeries` for the dots, and a `LineSeries` for the line, so one each of this pair of Scatter, Line for bid and ask

I can add an example, but it might be late next week before I do that.

**Comment by michaelr524** [comment]
Thanks!
I think that this is exactly what I was looking for.
Will try to implement and will let you know of any issues.

**Comment by michaelr524** [comment]
I've made some progress and now it displays the ticker data with the trades. 
CrossHairCursor doesn't snap to the ticker points however.
Do I need a different, modified version of it in order to support my use case?

<img width="950" alt="image" src="https://user-images.githubusercontent.com/1745556/34424116-c74cfd58-ec29-11e7-8a76-e3e9338a7593.png">

**Comment by rrag** [comment]
nice work,

> trade not aligning with the x axis

you could interpolate each trade in your custom series so that each trade you draw snaps to the nearest x of a candle in the `plotData`.

**Comment by michaelr524** [comment]
@rrag Hi
I think that you've answered someone else's issue here :-)

**Comment by michaelr524** [comment]
In any case, I would appreciate any advice regarding how I should approach this. As I've mentioned before, I might be able to add the necessary support to react-stockcharts.
Just need to know if you'd be interested in merging this.

**Comment by rrag** [comment]
alright, I am back. sorry for the delay in response.

what I meant to ask was 

> CrossHairCursor doesn't snap to the ticker points

why is this? you could interpolate each trade in your custom series so that each trade you draw snaps to the nearest x of a candle in the plotData.

I will be happy to take a PR, sure.

**Comment by michaelr524** [comment]
Hi @rrag 
I'm not sure that I completely understand your solution to my problem.
The core issue is that ChartCanvas supports only one set of X values.
CrossHairCursor is not aware that these additional values exist.
My thinking is that the issue should be solved in ChartCanvas by making it support multiple sets of X values. 
Do you think that this could be the right approach to solve this problem?

Here is some pseudo JSX that demonstrates my current structure of the components, and their respective data sources:

```XML
<ChartCanvas data=trades>
  <CrossHairCursor> 
  <Chart>
    <XAxis>
    <YAxis>
    <MouseCoordinateY>
    <MouseCoordinateX>
    <LineSeries>
    <ScatterSeries>
    <TickerWrapper data=ticker_bids>
      <LineSeries>
      <ScatterSeries> 
    </TickerWrapper>
    <TickerWrapper data=ticker_asks>
      <LineSeries>
      <ScatterSeries> 
    </TickerWrapper>
    <PriceCoordinate>
  </Chart>
</ChartCanvas>
```

**Comment by rrag** [comment]
can we chat on https://gitter.im/rrag/react-stockcharts will be easier for back and forth

**Comment by ale316** [comment]
Hey, I'm doing something like this:

**Comment by ale316** [comment]
Hey, I'm doing something like this:

```javascript
<TradeMarkers data={this.props.closedOrders}>
    <ScatterSeries
        yAccessor={d => d.r}
        marker={TriangleMarker}
    />
</TradeMarkers>
```

Where `TradeMarkers` is just a wrapper rendering `this.props.children`. It seems though that `ScatterSeries` is still using the data coming from the `ChartCanvas`, which is a completely different data set.

Am I missing something? How do I pass a different dataset to the `ScatterSeries` embedded in another chart?

**Comment by michaelr524** [comment]
@ale316 
Hi. Please check my sample pseudo code above.
The wrapper component (TickerWrapper) receives as property the different dataset and then passes it down to it's child by overriding the context (gitChildContext).
The property that you need to override is plotData.

That said, this method has it's own issues. For example CrossHairCursor isn't aware of the different dataset.
We've stepped down from this requirement at the moment.
But I think that it may help you to check the discussion between @rrag and myself in the gitter channel. 
@rrag proposed several other ways to achieve the same thing.

**Comment by ale316** [comment]
Thanks a lot for the pointer @michaelr524! I can override the context like you mentioned and pass it through to the `ScatterSeries`, but I'm still lost as to how to get the `plotData` within my wrapper so that I can make sure I'm only displaying what needs to be displayed.

Do I need to render a `GenericChartComponent` from the wrapper, or is there a cleaner way to just get that `plotData` so I can filter out my data?

Sorry to intrude here..

**Comment by michaelr524** [comment]
The original plotData (the one coming from ChartCanvas) is passed by Chart to the wrapper. So you can access it as you would usually access props.

**Comment by rrag** [comment]
@michaelr524 how did it go? do you still think there is a change needed on the library itself to support your usecase?

**Comment by michaelr524** [comment]
@rrag Thanks for asking!
I didn't attempt any of the solutions that we've discussed, as we've changed the requirements in a way that this is no longer needed.

**Comment by rrag** [comment]
thats cool, I am closing this now.

**Comment by sophana** [comment]
Hi

It would be nice if you could make an example for this very useful use case please.
Or add this as a feature.
I'm too new to react and javascript to do this by myself.

I could play with the library and could display bid/ask using AreaOnlySeries with the curveStepAfter quite easily.
Displaying orders and other informations from other dataset would be very nice.

Thanks

**Comment by sophana** [comment]
After searching and learning about react and javascript (I'm a javascript newbie), I could succesfully do it.

![image](https://user-images.githubusercontent.com/2486318/48808496-532d9500-ed21-11e8-8444-72037b071b0c.png)

As said above, the key is using react's context overriding method: getChildContext
Here is a working DataWrapper.js:
```
import React from "react";
import PropTypes from "prop-types";

class DataWrapper extends React.Component {
	render() {
		return(
			this.props.children
		);
	}
	getChildContext() {
		const { childData } = this.props;
		return {
			plotData: childData
		};
	}
}
DataWrapper.childContextTypes= {
    plotData: PropTypes.array,
}

export {DataWrapper};
```
it is used like this:
```
		<AreaOnlySeries
			yAccessor={d => d.bid}
			base={(scale,d) => scale(d.ask)}
			interpolation={curveStepAfter}
			opacity={10}
			fill="blue"
		/>
		<DataWrapper childData={data2}>
			<ScatterSeries
				yAccessor={d => d.price}
				marker={SquareMarker}
				markerProps={{ 
					width:  d => Math.sqrt(d.vol)*0.5
				,	stroke: "#2ca02c"
				,	fill: "#2ca02c" 
				}}
			/>
		</DataWrapper>
```

Hope this helps

**Comment by ahmed-numaan** [comment]
@sophana using your approach, panning does not seem to be working properly as shown in the video clip. Do you have any idea about this issue?
https://www.screencast.com/t/aJp88p4q
Let me know if you want me to share related source code or more information.
cc @rrag
