### ISSUE TITLE
Cannnot use Gann fan along with Trendline 

### ISSUE THREAD

**Issue by Rangarajan0603** [rrag/react-stockcharts#414]
I'm trying to use Trendline and Gann fan. The trendline is working fine and when and draw a Gann fan TypeError occurs in the ..\react-stockcharts\lib\interactive\TrendLine.js in line 222.

The error is as follows
**Uncaught TypeError: Cannot read property '0' of undefined**

The code in that line is
`x1Value: (0, _utils2.getValueFromOverride)(override, idx, "x1Value", each.start[0])`

**Comment by rrag** [comment]
could you please share a codesandbox with the issue. I dont see the problem, I have been using it in the new demo v2 ok

![deepinscreenshot_select-area_20171226222510](https://user-images.githubusercontent.com/10691183/34370685-b68e1316-ea8b-11e7-8862-ddb0e06b7efa.png)

**Comment by Rangarajan0603** [comment]
I've created a small codesandbox project with this issue. Please find the project [Here](https://codesandbox.io/s/zq75ykv13p), You could see that the Trendline and Fibonacci Retracement are working and the error occurs when trying to draw a Gann fan.

**Comment by rrag** [comment]
you were setting `this.state.trends` when a fan was complete

```diff
<GannFan
    ref={this.saveInteractiveNodes("GannFan", 1)}
    enabled={this.state.enableFans}
    onStart={() => console.log("START")}
-   onComplete={this.onDrawComplete}
+   onComplete={this.onFanComplete}
    fans={this.state.fans}
/>
```

fixed - https://codesandbox.io/s/n965z5mw1l

**Comment by Rangarajan0603** [comment]
My bad, Thanks...
