### ISSUE TITLE
rename js files to jsx if jsx syntax is used

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#415]
Please rename all js-files to jsx, because javascript is not jsx (but vice versa). 

For example, javascript syntax (coupled with *.js) do not have the ability for this syntax:

```
// this is not valid js-syntax, therefore not valid javascript
// this is valid jsx-syntax, hence save it under "*.jsx"
return (
            <TypeChooser>
                {type => <Chart type={type} data={this.state.data} />}
            </TypeChooser>
        )
```
Js-Editors complain about this syntax, but Jsx-Editors do not.

Unfortunatley, when doing this, all import statements must also change to have suffix ".jsx".
I dont know if its worth. But actually, it s not correct to save jsx syntax in js-files.

**Comment by rrag** [comment]
It used to be .jsx, and I [changed](https://github.com/rrag/react-stockcharts/commit/9fa4b1be237a1933e969ec3d9a9dff83dd2c001e) them all to .js, the debate is never ending and I don't fancy to indulge in it.

Any case .jsx suffix is not needed during import, by adding a webpack config for that extension.

**Comment by nimo23** [comment]
>It used to be .jsx, and I changed them all to .js..

Why? javascript is not jsx and will never be.

**Comment by rrag** [comment]
code that contains `<XYZ ... />` is jsx but one which has `React.createElement(XYZ` is js

for instance 
[this source](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/AreaSeries.js)

gets converted to 

[this](https://unpkg.com/react-stockcharts@0.7.0-beta.22/lib/series/AreaSeries.js)

the later is valid js and that is what is in npm. I dont want to complicate that compile step to include rename of .jsx to .js.

So while the actual source in this lib is not true js, it gets compiled to one, and that is enough to keep the file name .js

Also this topic of file extensions .js vs .jsx has been much debated, and there are views on both sides. I happen to be on the .js side - atleast for now

**Comment by nimo23** [comment]
> the later is valid js and that is what is in npm.

yes, the end result is transpiled into js.

In my opinion, for collaborating, it is easier to differ between the two file formats. It s the same as one would save a .ts-file as js, which is also not valid. 

I renamed the files to jsx and when making a PR, I must rename it again to js.

https://github.com/airbnb/javascript/tree/master/react#naming
