### ISSUE TITLE
no need to use state or event handlers within constructor

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#416]
For example, ChartCanvas.js or the like, set up "state" within constructor. No need for that: you can put it as member property without the need to call super(). The same goes for event handlers, you can bind it by member property with arrow function instead of repetitive binding within constructor.

https://michalzalecki.com/react-components-and-class-properties/

**Comment by rrag** [comment]
I like `state` as a member, but that is also part of the stage-2 proposal. Once it becomes stage-3 I am all for it.
