### ISSUE TITLE
Getting price from mouse click events

### ISSUE THREAD

**Issue by mkondel** [rrag/react-stockcharts#417]
Is it possible to get the Y-axis value from <ClickCallback/>? I can get the current candle OHLC values from moreProps.currentItem, but not where the mouse was clicked. I would like to be able to post orders and set the price via react-stockcharts.

**Comment by rrag** [comment]
the current `mouseXY` gives the x, y in pixels, you can do `chartConfig.yScale.invert(mouseXY[1])` and round to the nearest 2 decimal places or your preference to get the price

That same logic is done in the `MouseCoordinateY` which shows the y value on the crosshair
