### ISSUE TITLE
remove propTypes in production bundle

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#418]
There is no need for "propTypes" in production code (dead code). React does not check props in production.

Please use https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types to remove such unneeded code.
```

{
  "presets": ...,
  "env": {
    "production": {
      "plugins": ["transform-react-remove-prop-types"]
    }
  }
}
```

**Comment by rrag** [comment]
If I understand this correctly, this is for a bundle, the code published in npm is just compiled with babel.

Any application which one bundles should include the plugin you mention. Applying this plugin for the npm published code would make development harder without useful error messages

**Comment by nimo23** [comment]
>If I understand this correctly, this is for a bundle

yes, this is only for the bundle.
