### ISSUE TITLE
is there a way to disable the default cursor?

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#419]
i want to repalce the cross cursor to a normal mouse cursor, is there a way to achieve that?

**Comment by rrag** [comment]
the default cursor is set by 

this - https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L1058

function,
you could override those same styles with an `!important` or pass `<ChartCanvas useCrossHairStyleCursor={false} ...`
