### ISSUE TITLE
Feature Request..labels for Axis? 

### ISSUE THREAD

**Issue by raptoria** [rrag/react-stockcharts#42]
is it possible to label the axis?  ex:

![image](https://cloud.githubusercontent.com/assets/7387035/11275642/a11c262c-8eac-11e5-91bb-2f659b1ec982.png)

**Comment by rrag** [comment]
it should be possible. but is there ever a case where the label would change as part of interaction with the chart?

**Comment by Pinxie** [comment]
I did a modification of ReStock to do this, but as I can have several axis on the same side, i put the labels on top :

![plotaxisnames](https://cloud.githubusercontent.com/assets/15984761/12295004/8cbd6e5c-b9fe-11e5-904a-068148f0042e.png)

I just had to modify the Axis class, it was surprisingly easy (I did add an offset attribute to avoid overlap)

**Comment by raptoria** [comment]
I can't think of a case..but I'm not a charts guru. Awesome!!! when's your next release? =)))
How do you put several charts on the same side? Do you have an example for this yet?

**Comment by rrag** [comment]
This is cool. Did you do that on both svg and canvas?

**Comment by Pinxie** [comment]
Nope only canvas, I don't know enough about svg unfortunately :) 

To add several charts on the same side, you just have to specify a pixel offset to YAxis
<YAxis axisAt={self.state.width - offset} .../>
You also have to let enough space to the right by specifying the margin

var margin = {left: 40, right: enoughSpaceForYAxis, top:30, bottom: 50};
 
I think i had problems putting several axis to the left though, I don't know if it is possible with the same process

**Comment by rrag** [comment]
@raptoria [here](http://plnkr.co/edit/8buB2vi26AjUVTcmyMK7?p=preview) is an updated example which I had shared with @Pinxie a while ago about multiple axis.

I updated it with axis on both left and right

**Comment by rrag** [comment]
@raptoria are you ok with the solution? or you need a native solution by the library itself? I think it is a worthwhile addition.

**Comment by raptoria** [comment]
I think a native solution would be ideal, if you have the time!

**Comment by Pinxie** [comment]
Well @rrag  I can do a branch (from branch next) of my modifications? it adds the following attributes to Axis : 

+       axisName: React.PropTypes.string,
+       axisNameOffset : React.PropTypes.number,
+       axisNameFontFamily : React.PropTypes.string,
+       axisNameFontSize : React.PropTypes.number,
+       axisNameMaxSize: React.PropTypes.number

**Comment by rrag** [comment]
That would be great.

I was thinking of it differently

Create a `Label` component which takes the following props

- value: React.PropTypes.string,
- orientation: React.PropTypes.number, // This will be between 0 and 360
- fontFamily : React.PropTypes.string,
- fontSize : React.PropTypes.number,
- origin: React.PropTypes.arrayOf(React.PropTypes.number) // will be a [x, y] 
- textAnchor: React.PropTypes.string,

and we can create as many Label Components as needed. This also follows the [d3 approach](http://stackoverflow.com/questions/11189284/d3-axis-labeling) of not mixing the label and axis together. This way we can have as many labels as needed, they can be used as chart title too.

Thoughts?

**Comment by rrag** [comment]
and `XAxis` and `YAxis` can accept the props you mentioned, and it can delegate to both `Axis` and `Label`

**Comment by Pinxie** [comment]
Yes doing a separate component for labels would be better I agree, (and I need this juicy Chart title, and labels everywhere! ). All right I will push what I have on an other branch (next-pinxie) and continue with this when I have the time (probably in the next few days I hope)

**Comment by rrag** [comment]
This is complete on the `next` branch, [example](http://rrag.github.io/react-stockcharts-next/documentation.html#/annotations)

with both canvas and svg support. Appreciate feedback

https://github.com/rrag/react-stockcharts/blob/88ac730b46e633e485eeb463128a324b119877eb/docs/lib/charts/CandleStickChartWithAnnotation.jsx#L71-L72

**Comment by rrag** [comment]
fixed, published in 0.5
