### ISSUE TITLE
clamp on ChartCanvas hides half of (last/first) candle

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#423]
I have a ChartCanvas with clamp enabled. The candlesticks are cut when using clamp:
- When using clamp="both", then first and last candlestick is not fully shown.
- When using clamp="right", then last candlestick is not fully shown. 
- When using clamp="left", then first candlestick is not fully shown. 

You can see this also on http://rrag.github.io/react-stockcharts/documentation.html#/zoom_and_pan. (enable "clamp" and drag to right candle)

**Comment by nimo23** [comment]
Does it relate to https://github.com/rrag/react-stockcharts/issues/3? However, when disabling clamp, then first/last candlesticks are not cut.

**Comment by rrag** [comment]
first and last candle showing just half is expected as the entire width of the chart is used to render the candles, you can use `<ChartCanvas padding='...` or the `clip={false}` mentioned in https://github.com/rrag/react-stockcharts/issues/196

**Comment by nimo23** [comment]
Setting `clip={false}` does not help. But with` padding={..},` it works. 

So for what is `clip={false}`?

**Comment by nimo23** [comment]
ChartCanvas.propTypes does not have a "clip"-property. Could you add this again? According to #196, "clip"-property exist in a older version.

**Comment by rrag** [comment]
`clip` is on the `XXXSeries`, like `<AreaSeries clip={false}` so you can choose to clip individual components

**Comment by nimo23** [comment]
thanks. 

I have this <`CandlestickSeries clip={false} />`  within  a chart and below this chart, I have another chart with volumebar. The rendered output with clip=false, only works for the first candle, but the last candle looks like this:

maximum zoom in (last candle is not within the chart border):

![clampnotworking](https://user-images.githubusercontent.com/3045549/34575137-efc54d94-f179-11e7-8711-006ba34e895a.png)


not maximum zoom in (last candle is not within the chart border):
![clamp2](https://user-images.githubusercontent.com/3045549/34575261-5aa05492-f17a-11e7-8c3b-7979144c78c7.png)


It works when using padding within ChartCanvas, however, then all its chart components are padded. Could you improve clip so the last candle always fits within the chart-canvas-border?

**Comment by moonlight16** [comment]
Note: I found you must use padding on the ChartCanvas, and not the Chart object.
