### ISSUE TITLE
provide automatic layout

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#425]
Actually, charts are stacked at the same position (0,0), when not setting the properties "height" and/or "origin" of a chart. A chartCanvas can be made up of multiple charts. It would be nice to provide automatic vertical stacked layout independent of the number of charts within a chartCanvas. 

So for example, if I have a chartCanvas with 4 Charts, then it should **automatically** position/resize the 4 charts **vertically within the charts available size without overlapping**. Is this possible?

**Comment by nimo23** [comment]
For example, by a new property for ChartCanvas "autoLayout=200": When set to true, all its charts are stacked vertically with a default height of 200.

**Comment by rrag** [comment]
I like this idea, it can also be like `<ChartCanvas height={600}` and say there are 

```
<ChartCanvas height={600} ...>
  <Chart ...></Chart
  <Chart height={100}></Chart>
  <Chart height={100}></Chart>
</ChartCanvas>
```

then the chart `1` will take height as `400`

Would you be able to take this up?

**Comment by nimo23** [comment]
I try and let you know in the next days..

**Comment by nimo23** [comment]
The "height" of "ChartCanvas" must be automatically calculated with the help of the declared height of each Chart-Component.

So for example,

```
<ChartCanvas>
  <Chart height={300}></Chart
  <Chart height={100}></Chart>
  <Chart height={100}></Chart>
</ChartCanvas>

```
The "ChartCanvas" must use automatically a height of 300+100+100= 500. I dont know how to implement this. It must be something like this: 
- Iterate through the list of each chart-components within a chartCanvas
- get each height and cumulate
- return the cumulated summary (= height of ChartCanvas)

**Comment by rrag** [comment]
ooh, yeah I forgot about this, this is not straightforward. there is "read a `Chart` child from parent `ChartCanvas` happening"

here - https://github.com/rrag/react-stockcharts/blob/v0.7.0-beta.22/src/lib/utils/ChartDataUtil.js#L59-L74

I really don't like doing that, and have wanted to remove that, but never found a good solution. The biggest problem I have with this approach is that I cannot do

```
function MainChart() {
  return <Chart id={0} ...>
    ...
    ...
  </Chart>
}
function VolumeChart() {
  return <Chart id={1} ...>
    ...
    ...
  </Chart>
}

...
<ChartCanvas ...>
  <MainChart />
  <VolumeChart />
  <MACDChart />
  <SomeOtherChart />
</ChartCanvas>
```

now when I have a big chart the render function is just too long.

I am sorry to say, while I like this feature you are proposing, I dont want to add more of this reading a child prop from parent code.

an alternative (breaking api change) I am thinking is

```
const chartConfigList = [
  { name: "MainChart", height: 300, yExtents: ..., yScale: ..., some more props },
  { name: "VolumeChart", height: 300, yExtents: ..., yScale: ..., some more props },
  { name: "MACDChart", height: 300, yExtents: ..., yScale: ..., some more props }
]

const { ChartCanvas, MainChart, VolumeChart, MACDChart }  = getChartPrimitivesForConfig(chartConfigList)

/*
use ^^ ChartCanvas and XXXChart like
<ChartCanvas ...>
  <MainChart />
  <VolumeChart />
  <MACDChart />
  <SomeOtherChart />
</ChartCanvas>

getChartPrimitivesForConfig will have be exported from the library, and the existing ChartCanvas, Chart removed (or at least deprecated)
*/
```

What do you think? I am not thrilled to make breaking changes but could be convinced if this approach can benefit potential future changes.

**Comment by nimo23** [comment]
Solved: https://github.com/rrag/react-stockcharts/pull/435

No need for "breaking api change" or ChartDataUtils.
