### ISSUE TITLE
cannot change "stroke" of Axis

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#426]
The property "stroke" is not changable:

```
XAxis.defaultProps = {
stroke: "#000000", // x axis stroke coloe (TODO: should be named "color")
..
}
```

when using this:

```
<XAxis axisAt="bottom" orient="top" stroke="#ccc" tickStroke="#ccc"/>
<YAxis axisAt="bottom" orient="top" stroke="#ccc" tickStroke="#ccc"/>
```

only the color "tickStroke" is changed, but stroke does not change (it remains "#000000").

**Comment by nimo23** [comment]
stroke color actually only works in svg-mode, not in canvas-mode.

**Comment by rrag** [comment]
ah another property not consistently implemented between svg and canvas. Thanks for pointing it out. I will work on this soon

**Comment by rrag** [comment]
both `stroke` and `tickStroke` work in svg and in canvas mode. 

```jsx
<XAxis axisAt="bottom" orient="bottom" stroke="#DE751F" tickStroke="#3490DC"/>
```

I am guessing the 3 digit notation `#CCC` might be the problem use the 6 digit notation `#CCCCCC`

Let me know if you still have problems after that

**Comment by Morriz** [comment]
The behaviour of all these seperate items is so inconsistent, I believe a good refactoring to use helpers instead of bad copy/paste actions would be helping us a lot. I am wasting a lot of time figuring out why some items render both '555555' and '#555555', while others only render '555555'. What's up with that? So weird, as if "smart logic" (decided by the programmer) (d)evolved over time and the landscape is filled with anomalies. BEWARE!!

Ugh, I don't feel up to this...pfff

**Comment by Morriz** [comment]
Sorry for the venting of frustration, I am looking into the code and am trying to figure out why that weird behavior exists. It must be some weird svg anomalies. I see very thin dotted lines if I render XAxis or YAxis with '#FF0000', but with 'FF0000' it looks like the lines get drawn twice, but slightly off, and making the lines jagged and bright. Try for yourself!

**Comment by Morriz** [comment]
with 'FF9900':
https://www.dropbox.com/s/gpzr2xjvtzqm9wf/Screenshot%202019-01-02%2001.41.51.png?dl=0
with '#FF9900':
https://www.dropbox.com/s/wncinbrxa872pkf/Screenshot%202019-01-02%2001.43.55.png?dl=0

**Comment by Morriz** [comment]
Nevermind, I was on a wild goose chase. Even though my observations are valid, and these are rare findings, I managed to find why the dotted grid lines were hardly visible: opacity 0.2 ;p
