### ISSUE TITLE
Customize candlestick on canvas+svg

### ISSUE THREAD

**Issue by XmelesX** [rrag/react-stockcharts#43]
Hello rrag and everyone, I have a some problems with candlestick chart.
As template I took the settings from 
```<HistogramSeries fill={(d) => d.close > d.open ? "rgba(0,166,81,0.5)" : "rgba(204,36,36,0.5)"}/>```
it's work nice!
But if I take the following code (CandlestickSeries)
```<CandlestickSeries widthRatio={(d) => d.volume > 0 ? 0.5 : 0} />```
not working ((
But this:
```<CandlestickSeries widthRatio={0} />```
working!
What I'm doing wrong? (

**Comment by rrag** [comment]
`widthRatio` does not take a function as input. I am not following what you are trying to do. Just remove the `widthRatio` on the `CandlestickSeries`

**Comment by XmelesX** [comment]
thank for reply.
I'm try to remove undefined candlestick. 
Мaybe there are other solutions? 
Look at stock AAAP intraday(https://www.google.com/finance?q=AAAP&ei=i9ecVumbI8fjsgGb2o-oBQ) we have many gaps in price.
How can correctly display this chart?

**Comment by rrag** [comment]
Intra day is not supported right now. https://github.com/rrag/react-stockcharts/issues/40 It is on the roadmap.

`widthRatio` is not a solution for price gaps. The stockscale ignores the price gaps, it would show the candles as next to each other, so in your e.g. the candle for 11:32 will be next to the candle for 14:32. without any gap.

Does that answer your question?

**Comment by XmelesX** [comment]
Thank you!
I mean not price gap.I mean time gap.
found solution in stock datafeed prepared.
My provider datafeed(example json):
```[{"date":"2016-01-15","close":"24.85","high":"24.85","low":"24.85","open":"24.85","volume":108},{"date":"2016-01-15","close":"26.024","high":"26.024","low":"26.024","open":"26.024","volume":100},{"date":"2016-01-15","close":"na","high":"na","low":"na","open":"na","volume":" "},{"date":"2016-01-15","close":"na","high":"na","low":"na","open":"na","volume":" "},{"date":"2016-01-15","close":"na","high":"na","low":"na","open":"na","volume":" "} ...```
need change 'na'  to  'undefined'.
thanks again!

**Comment by rrag** [comment]
Ah. Cool.

How did you go about finding this as the root cause. any suggestions on what kind of error messages would have helped you identify the problem sooner?
