### ISSUE TITLE
is seriesName used?

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#436]
Actually, the ChartCanvas has a property "seriesName". However, I cannot find a property something like **"showSeriesName: PropTypes.bool"**. Maybe this property can be included within the Chart.js, so if Chart.js showSeriesName=true, then the seriesName (declared in ChartCanvas) is rendered at the top left corner of a chart-component. (Or maybe instead of chart, the ohlc-tooltip can have the property "showSeriesName", so it can be shown like this: "seriesname + ohlc"

**Comment by rrag** [comment]
Sorry for the delay
Good question, `seriesName` is used only to determine if the chart has to be reset, This is a means to determine if an update is meant to be trivial like a window resize or new data point added vs a complete change in the data to show a different series.

Showing the series name is not the purpose. If that is a need I believe creating a separate component to show it where you desire is the right solution.

**Comment by nimo23** [comment]
ok, so maybe consider to rename "seriesName" to something like "seriesId", some think "seriesName" is a visual part of the chart..
