### ISSUE TITLE
performance issue when loading several charts on a page

### ISSUE THREAD

**Issue by omryr** [rrag/react-stockcharts#438]
i was wondering if you might have an idea how to make a page with multiple charts run smoother, i have about 15 charts with 170 points each and it really takes a toll on performance, any tips or ideas of how to improve the situation? thanks for the help!

**Comment by rrag** [comment]
could it be related to this? - https://github.com/reactjs/react-redux/issues/263

see similar issues prior
https://github.com/rrag/react-stockcharts/issues/115
https://github.com/rrag/react-stockcharts/issues/280

I also recall @itsjimbo had some serious setup, with 320 charts 

https://github.com/rrag/react-stockcharts/issues/149#issuecomment-250817016

**Comment by omryr** [comment]
its less about new data coming in as much as it seems about the drawtime, if i already have all the data and i just move to a different screen and back to the graphs there is a slight hickup but the points you gave are actually really helpful for problems i would probably face later anyway!

**Comment by rrag** [comment]
@omryr any pointers on where there could be problems? I had been working on the demov2 and any performance problem I was able to resolve it outside of the library itself.

Could you use the chrome profiler to narrow down the problem area.
