### ISSUE TITLE
Investigate to remove "react"

### ISSUE THREAD

**Issue by nimo23** [rrag/react-stockcharts#440]
Actually, "react-stockcharts" are build on react, however, there are drawbacks in relation to performance, memory consumption and js-native extensibility (it is tightyl coupled to react). 

Imagine to reorganize all "stockcharts-components" to be written in **plain es6 literals** which also handles components, live update and state in a native and maximum performant way:

To understand what I mean, please read this:

https://www.zeolearn.com/magazine/hyperhtml-vs-vdom

Maybe you come to the conclusion, that **"s-charts**" (="react-stockcharts") can be build by using only **es6 templating** with the help of **hyperHtml** or **lit-html**:
- https://github.com/WebReflection/hyperHTML
- https://viperhtml.js.org/hyper.html
- https://github.com/PolymerLabs/lit-html
- see comparison here: https://gist.github.com/WebReflection/fadcc419f5ccaae92bc167d8ff5c611b

Look at this (such performance impossible with react):
https://webreflection.github.io/hyperHTML/test/dbmonster.html

Example with thousands of svg-nodes which cannot be beat by react:

https://webreflection.github.io/hyperHTML/test/double-rainbow.html

Please read docs https://viperhtml.js.org/hyperhtml/documentation/#introduction-0 and maybe you come to the same conclusion that "react-stockcharts" can be relieved from "react" when using such techniques.

As react-stockchars main thing is the svg-part and its properties, it should be not difficult to move these code base to the new es6 templating lib (es6 also provides template compositions = component compositions) or (https://viperhtml.js.org/hyperhtml/documentation/#components-3 or https://github.com/WebReflection/hyperHTML-Element).

Examples using es6-template-iterals against react:
https://viperhtml.js.org/hyperhtml/examples/
http://wesbos.com/template-strings-html/

**Comment by rrag** [comment]
It is quite possible that there are multiple options to be faster than react. I started this library when I had no knowledge of react. and it was my approach to learning it. Build something to learn it, right.

I have no plans to drop react support, that is a bigger undertaking. Unfortunately I don't have the time or motivation to do that right now.

**Comment by GoChartingAdmin** [comment]
@nimo23 
Have you checked the below using react
http://web-perf.github.io/react-worker-dom/test/dbmonster/index.html#count=1&timeout=0&worker=false&rows=50

**Comment by nimo23** [comment]
@GoChartingAdmin after reading https://www.zeolearn.com/magazine/hyperhtml-vs-vdom, you may come to the conclusion that memory consumption and latency of vdom is not to ignore. At last dom actions must be made, with or without vdom. With a lot of svg, vdom has a lot to map..and in my opinion, svg is by nature fast, but maybe vdom brakes this out. Svg has a lot of interactions and changes, so no need to use vdom which looks what is changed and so on..this hurts performance and memory and even using svg without react may be a performance boost. 

**Using vdom for graphically intense applications does not fit.**
