### ISSUE TITLE
[Question] How do I get the chart to take up 100% width and height?

### ISSUE THREAD

**Issue by Industrial** [rrag/react-stockcharts#442]
Hi!

This is my current [page (screenshot)](https://i.imgur.com/ZEd4P4B.png).

I want the chart to be 100% width and 100% height of the parent container, which has some padding (due to a grid system).

Ideally it would work on all devices/sizes (so as I resize my window, it would adapt).

I also plan to add a toolbar that might reflow from minimized state on the left side to the folded out state or move itself to the top for small devices/sizes. So the container element size might change.

Is this possible?

Should it be done with CSS or JS?

**Comment by Industrial** [comment]
I see that this excellent example (and redux app) does this:

http://rrag.github.io/stockcharts-demo/

Would it be possible for this source code to also be made into an example?

It would be the ultimate integration (of this library) example I guess :-)

**Comment by rrag** [comment]
Canvas and svg need to specify the width and height. You have to use js to listen to window resize and set the width and height.

All the examples set the width based on the parent container. You can use a similar techniques for height also

**Comment by rrag** [comment]
There is also 

https://github.com/rrag/react-stockcharts/blob/master/src/lib/helper/fitDimensions.js you can use to set width and height

**Comment by byouloh** [comment]
I followed your advice, and adapted "fitDimentsions" to "CandleStickStockScaleChartWithVolumeBarV3" example. But, its height is alway 156 in spite of resizing browser.

I added "height" to this.props and change CandleStickStockScaleChartWithVolumeBarV3 = fitDimensions(CandleStickStockScaleChartWithVolumeBarV3); in Chart.js

**Comment by Tse-ChiKit** [comment]
Have the same problem, the height is always 155 when using fitDimenions.

I took a look at the code in fitWidth.js. I can see that the width is calculated by window.getComputedStyle, but why the height never changes from the calculation. And how is the initial width is calculated since I cannot see any initial widths are provided for canvaschart component. @rrag

**Comment by jhchill666** [comment]
Just revisiting this for anyone that's interested.

Using React Hooks api, is pretty simple to provide explicit dimensions to the chart canvas, based on the parent's calculated size.

```
import React from 'react'
import useDimensions from 'react-use-dimensions'
import Chart from './chart'

function ChartWrapper (props) {
  const [ref, { width, height }] = useDimensions()
  return (
    <div ref={ref} style={{ width: '100%', height: '100%' }}>
      <Chart
        height={height}
        width={width}
      />
    </div>
  )
}

expor default ChartWrapper
```

Also resizes nicely :)

**Comment by lizzard-winner** [comment]
@jamiehill  how would you use this function?

**Comment by jhchill666** [comment]
You'd use as is.  As a functional component, using the `useDimensions` hook, it will be re-rendered, when ever your app's dimensions change.

https://reactjs.org/docs/hooks-reference.html

**Comment by lizzard-winner** [comment]
Alright thanks, I ended up using SizeMe.
