### ISSUE TITLE
Documentation Link Not Working

### ISSUE THREAD

**Issue by ethankong113** [rrag/react-stockcharts#445]
The documentation is now founded with this link:
http://rrag.github.io/react-stockcharts/documentation.html

It's found on by clicking documentation: http://rrag.github.io/react-stockcharts/

**Comment by rrag** [comment]
Please share the broken link and from where it is referenced.

The link - http://rrag.github.io/react-stockcharts/documentation.html

does work

**Comment by ethankong113** [comment]
![screen shot 2018-01-31 at 10 18 36 am](https://user-images.githubusercontent.com/17715975/35639820-42db27dc-0670-11e8-87ba-b87c27731772.png)

This is what i get... i only see an arrow and something is wrong with the array

**Comment by rrag** [comment]
Could you please share the  browser and version you using?

it works on all major browsers for me.
Any one else have this problem?
