### ISSUE TITLE
Release Date for disableInteraction?

### ISSUE THREAD

**Issue by ethankong113** [rrag/react-stockcharts#446]
When is this change going to be released: https://github.com/rrag/react-stockcharts/pull/441/commits

It's on master but not on v6.1. Seems important to have `disableInteraction` for backward compatibility when adding drag events?

**Comment by rrag** [comment]
I will be releasing a new 0.7 beta in the next few days, no plans to release 0.6.x

I also think it is time for 0.7 to get out of beta also. I am thinking next week

**Comment by ethankong113** [comment]
Thanks! Hopefully it will be launched soon!

(I will close this issue now)
