### ISSUE TITLE
Bollinger Band Tooltip issue.

### ISSUE THREAD

**Issue by Princezhm** [rrag/react-stockcharts#448]
@rrag 
I was trying to add an OnClick callback to the bollinger band tooltip, right?
but looking at your code, looks like you are calling it directly from the svg object, so I'm getting the event
I was hoping to do something like you have on your demo and control the settings of the BB.
so, in the BB tooltip we have:
```javascript
onClick={onClick}
```

while we have on the Moving Average Tooltip example we get some custom properties and then I was checking the code of the MAT and I saw that there is a custom handleClick
```javascript
handleClick(e) {
    const { onClick, forChart, options } = this.props;
    onClick({ chartId: forChart, ...options }, e);
}
```

as you can see you are creating a custom callback on the MAT, but in the BB you are just returning the event.

how did you manage to create the behaviour that you have on your demo?
what about the others tooltips? do they have an OnCLick custom function or are they returning the event?

**Comment by rrag** [comment]
`MATooltip` is a special kind of tooltip in that it groups multiple moving average series into a single tooltip

other tooltips have a 1 : 1 relationship with the series.

You will have to bind other props which you need to get on click like

```
<BBTooltip ... onClick={this.handleClick.bind(null, otherPropsyouwant to bind)} />
```

**Comment by Princezhm** [comment]
thanks for answering, I'll try to modify a simple example using the bollinger band and then I'll let you know.
