### ISSUE TITLE
How to integrate it with socket.io API response 

### ISSUE THREAD

**Issue by abhiindia** [rrag/react-stockcharts#450]
I tried with updatingdata chart but no success. Do you have any demo over websockets?

**Comment by Princezhm** [comment]
@abhiindia can you write a bit your implementation?

**Comment by abhiindia** [comment]
I tried by fetching data from socket.io and assign in state but It is not working properly like It is not retaining all data so that i can see old data point by dragging. However chart is updating.

Also volume bar index is changing on every update but it should depend on whole array data.

-------------------
import React from 'react';
import { render } from 'react-dom';
import Chart from './Chart';
import { getData } from "./utils"
import socketIOClient from "socket.io-client";


import { TypeChooser } from "react-stockcharts/lib/helper";


class ChartComponent extends React.Component {
	
	componentDidMount() {
		/*getData().then(data => {
			console.log(data)
			this.setState({ data })
		})*/
		var data = [{
	"date": new Date(1516690800*1000),
	"open": 0.1228,
	"close": 0.1186,
	"volume": 315.152229,
	"high": 0.12455,
	"low": 0.1157
}, {
	"date": new Date(1516690860*1000),
	"open": 0.1172,
	"close": 0.1225,
	"volume": 307.384220,
	"high": 0.12465,
	"low": 0.1155
},
 {
	"date": new Date(1516690920*1000),
	"open": 0.12345,
	"close": 0.1178,
	"volume": 297.045752,
	"high": 0.1246,
	"low": 0.11555
}, {
	"date": new Date(1516690980*1000),
	"open": 0.1210,
	"close": 0.1221,
	"volume": 308.375643,
	"high": 0.12455,
	"low": 0.1155
}, {
	"date": new Date(1516691040*1000),
	"open": 0.11725,
	"close": 0.1177,
	"volume": 312.671354,
	"high": 0.12465,
	"low": 0.1155
}, {
	"date": new Date(1516691100*1000),
	"open": 0.1165,
	"close": 0.1224,
	"volume": 298.994246,
	"high": 0.12455,
	"low": 0.1154
}];
		this.setState({data});
		const socket = socketIOClient('#####ENDPOINT URL #######');

		socket.on("ticker", this._messageRecieve.bind(this));
	}

	_messageRecieve(response) {
		//console.log(this.state.data)
      //var data = this.state.data;
  		//console.log(this.state)
  		console.log(response)
      var responsedate = new Date(response.t*1000)
      var message = {
				date : responsedate,
				open : response.o,
				high : response.h,
				low : response.l,
				close : response.c,
				volume : response.v
			}
	this.state.data.push(message)
      //data.push(message);
      //console.log(this.state.data)
     // this.setState({data});
  }

	render() {
		if (this.state == null) {
			return <div>Loading...</div>
		}
		return (
			<TypeChooser>
				{type => <Chart type={type} data={this.state.data} />}
			</TypeChooser>
		)
	}
}

render(
	<ChartComponent />,
	document.getElementById("root")
);

**Comment by rrag** [comment]
the example in [codesandbox](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithUpdatingData)

it updates the `data` every second to show a streaming example

I am not sure why you have a problem but I would not do any mutation of the state 

```diff
- this.state.data.push(message)
+ this.setState({ data: [...this.state.data, message] })
```

Please refer to react docs on why state mutation will not update the component

**Comment by abhiindia** [comment]
@rrag Thanks for reply..i will remove mutation and see how it behaves.
