### ISSUE TITLE
I do not want to move the Y coordinate of the EdgeIndicator

### ISSUE THREAD

**Issue by m-morisaki** [rrag/react-stockcharts#453]
I do not want to move the Y coordinate of the EdgeIndicator.
Price will fluctuate when scrolling chart.

Is it possible to change?

`<EdgeIndicator itemType="last" orient="right" edgeAt="right" yAccessor={d => d.close} fill={d => d.close > d.open ? "#6BA583" : "#FF0000"}/>`

<img width="132" alt="2018-02-02 17 28 31" src="https://user-images.githubusercontent.com/32150594/35723679-888e5e8c-083e-11e8-8f45-14bbc36744f3.png">

**Comment by rrag** [comment]
@m-morisaki  the y coordinate moves because the y max and y min of a chart changes as you pan and zoom

if the y coordinate stays in its place then the chart has to have a fixed ymin and ymax.

you can set that by

```
<Chart id=... yExtents={[minYValue, maxYValue]}
```
