### ISSUE TITLE
How to refactor Chart Component

### ISSUE THREAD

**Issue by iamcharles777** [rrag/react-stockcharts#455]
I have 
index.js which handle the ```<ChartCanvas>``` 
I have lot of lines and decided to create a component on each ```<Chart>```
but I have got ```Uncaught (in promise) TypeError: Cannot read property 'origin' of undefined```
I think because it can't read the  ```origin={(w, h) => [0, h - 150]}``` so I decided to put a static
```origin={ [0, 150]}``` but got the same result.

Thanks

**Comment by rrag** [comment]
unfortunately you cannot put each `Chart` in a separate component and use that. it has to be a direct child of `ChartCanvas`

There are some ideas I have, but they all involve breaking changes, so i am holding off on implementing them
