### ISSUE TITLE
date issue

### ISSUE THREAD

**Issue by libasoles** [rrag/react-stockcharts#456]
Hi. Project looks amazing so far. And I've got one of the examples running quite easily. 
However I'm having troubles using a real api feed. Dates just won't work. 

See, I'm receiving this timestamp from the API: `1516654200000` 

And I'm transforming that to this: `2018-01-22T20:50:00.000Z` (string)

As far as I can say, that's the format expected by _d3_, but the graphics renders just empty and console says:

> Unexpected value NaN parsing x attribute.
> Unexpected value NaN parsing width attribute.

If I use ISO format but with an object instead of a string, the graphic renders something but it's really a mess.

So, any clue about how to convert timestamp to a correct format with d3? I'm trying this:

```
import { timeParse, timeFormat } from "d3-time-format";

const parseDate = timeParse("%s");
const formatDate = timeFormat("%s");

 console.log( parseDate(formatDate(t)) )
```

And this:

` console.log( new Date(t).toISOString() )`

**Comment by libasoles** [comment]
This is how I see the candles. 

![screenshot_20180206_174610](https://user-images.githubusercontent.com/8009070/35893316-2fcdba30-0b8c-11e8-9296-0bbfc1d2c1c7.png)

Same result if I just use the timestamp.

**Comment by abhiindia** [comment]
@libasoles- I have same problem few days back. You can add below code to make it working.

new Date(timestamp), timestamp should be  in milliseconds.

Can you share your code, how you are integrating with API, I have some problem during API integration with websockets

**Comment by libasoles** [comment]
Cool @abhiindia , that made the trick. Actually, I realized that with '1d' time period my code worked quite well. Not with shorter periods, like '1h'. But your code seems to works even with '5m' periods so it's great. It was easy!

Look, I'm using redux-saga. Not sure if that will be useful for you, guess not. Also, queries are performed by a third party lib. And I'm not planning to implement websockets by now. But maybe you could start a ticket.
