### ISSUE TITLE
Axis ticks cut off when full width

### ISSUE THREAD

**Issue by oskarer** [rrag/react-stockcharts#458]
https://codesandbox.io/s/j5w87qw6v

![image](https://user-images.githubusercontent.com/4076953/36109549-07335a1a-1020-11e8-8fc1-7429c1145cbb.png)

This is an issue when having no Y axes and the chart should cover full width of container/screen. Is there any way of hiding the ticks before they get cut off? Thanks

**Comment by rrag** [comment]
it is not possible to hide selective ticks,

why not a decent `margin` on the `ChartCanvas`?
```diff
        margin={{
          left: 0,
          top: 0,
-         right: 0,
+         right: 50,
          bottom: 50
        }}
```

**Comment by oskarer** [comment]
The problem is I want the chart to have full width, having no Y axis, so margin won't fly. Would somehow need to calculate if a tick will end up outside the container, and then not show it.

**Comment by rrag** [comment]
You would have create a custom version `XAxis.js`  to make that happen.
