### ISSUE TITLE
How to set candlestick wick based on time

### ISSUE THREAD

**Issue by Neha3011** [rrag/react-stockcharts#459]
Hi, amazing project. 
I know that the demo code here http://rrag.github.io/stockcharts-demo/ is not open source, but can you help me with an example of how to set the candlestick wick based on time (1m, 3m etc).
Also there is an UI bug in the demo header. The setting filter dropdown has extra list element. Attaching the screenshot.
<img width="567" alt="ui bug" src="https://user-images.githubusercontent.com/10024090/36148321-97dc0d34-10e1-11e8-9c9c-21c224554a4f.png">

Thanks.

**Comment by rrag** [comment]
changing the x domain of the chart to be 1 month/3 month/6 month/... has to be done by calculating the x value of the start and end candles for that period.

when user clicks on say 3 month, you have to 

```jsx
handlePeriodClick(period) {
  if (period === "3month") {
    const { plotData, fullData, xAccessor } = this.refs.chartCanvas.getDataInfo()
    const x2 = xAccessor(last(plotData))
    // const x1 = xAccessor(find the candle which is 3 months before x2 from fullData)
    this.setState({ xExtents: [x1, x2] })
  }
}
...
render() {
  ...
  return (
    <ChartCanvas ref={node => this.chartCanvas = node} xExtents={this.state.xExtents} ...>
      ...
  )
}
```
