### ISSUE TITLE
"Updating data" example bugs

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#46]
Hello! There is some bugs with "[updating data example](http://plnkr.co/edit/gist:555ea9d11c621a895171?p=preview)": 
1) when you're dragging chart to the history it often resets view to last values (usually it happens when you stops moving mouse but still holding LMB)
2) when you're zooming chart it often resets to previous zoom level

I've tried to record it:
![c](https://cloud.githubusercontent.com/assets/7679749/12465095/77d1e3a8-bfdd-11e5-8f15-63a144ec74f4.gif)

Is there some ways to fix it?

**Comment by rrag** [comment]
Ok I see it.

Here is what is happening. When you push new data points, the chart finds if the last tick is visible, and if so, it adds the new data element into the view. Since you started the pan (click and hold mouse) when the last tick was visible, and dragged it, the code assumes that the last tick is still visible (since the pan is still not complete).

I will fix this part of 0.4

**Comment by iNikNik** [comment]
@rrag thanks for fast feedback)

**Comment by rrag** [comment]
Fixed in `next` branch, will be release in 0.4 check out the fixes in

http://rrag.github.io/react-stockcharts-next/documentation.html#/updating_data

plunker/gist/block not updated yet

**Comment by iNikNik** [comment]
@rrag now it looks much better! thank you)

**Comment by yunpeng-zhang** [comment]
@rrag Is there a working example of updating data using react-stockcharts?
The one in documentation seems not working. [http://rrag.github.io/react-stockcharts/documentation.html#/updating_data](http://rrag.github.io/react-stockcharts/documentation.html#/updating_data)

**Comment by rrag** [comment]
the link works for me on Chrome 59.0.3071.115, is this a browser specific issue?

**Comment by yunpeng-zhang** [comment]
Thanks for fast response. I can see the chart, but how to activate the updating? Before pressing key 1, should I do something else? Just pressing key 1 seems not triggering the updating.

**Comment by yunpeng-zhang** [comment]
The chrome version I used is Version 59.0.3071.109 (Official Build) (32-bit)

**Comment by yunpeng-zhang** [comment]
@rrag, would you mind uploading the UpdatingData example and instructions to use to [https://github.com/rrag/react-stockcharts-examples/tree/master/examples](https://github.com/rrag/react-stockcharts-examples/tree/master/examples). Thanks.

**Comment by yunpeng-zhang** [comment]
@rrag sorry for the confusion. It indeed works and I have to press 1 and hold to see the update. I am trying to combine "updatingData" with an example " CandleStickChartWithBollingerBandOverlay". Which part of " CandleStickChartWithBollingerBandOverlay.jsx" should I change to accomodate the updating? Thanks.

**Comment by yunpeng-zhang** [comment]
@rrag  following your example [https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithUpdatingData.jsx](https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithUpdatingData.jsx), I am not sure how to update the index.html file to make it work. The logic should be data -> [CandleStickChartWithBollingerBandOverlay.jsx] ->[CandoleStickChartWithUpdatingData.jsx] ->  index.html? 
I updated the html as follows and got error message "ERROR: exports is not defined. " I am not sure where I did wrong. 
![image](https://user-images.githubusercontent.com/6248939/28190640-e3f04f46-67f9-11e7-976b-2820ffd4c6d1.png)



I got "ERRPR: exports is not defined." not sure if

**Comment by rrag** [comment]
it is a little more work to create a plunker for the updating data with the existing code, so I did not do it. The source 

the examples are more complicated than is necessary because I had to simulate new data coming in from the existing data []. in a real project though you would typically receive new data elements from websocket/ajax, and you could update the `data` in the props of `ChartCanvas`

Not sure if that helps, do you have a project with babel/webpack and all the ceremony set up?

**Comment by yunpeng-zhang** [comment]
Thanks for the reply. I am currently using react-stockcharts package directly. I guess I need to embed the data update in the .jsx itself. Am I right? 

Can you upload the code for [http://rrag.github.io/react-stockcharts-next/documentation.html#/updating_data](http://rrag.github.io/react-stockcharts-next/documentation.html#/updating_data) to git? I can adapt mine to your code to make it work.

**Comment by yunpeng-zhang** [comment]
@rrag I tried to add updatingDataWrapper.jsx to CandleStickChartWithBollingBandOverlay.jsx in order to update `data` in `ChartCanvas` with comments of changes. However, the chart won't be able to render in browser. Let me know if I miss anything. 
`"use strict";
var { ChartCanvas, Chart, series, scale, coordinates, tooltip, axes, indicator, helper } = ReStock;

var { CandlestickSeries, BarSeries, LineSeries, AreaSeries, BollingerSeries } = series;
var { discontinuousTimeScaleProvider } = scale;
var { EdgeIndicator } = coordinates;
var { CrossHairCursor, MouseCoordinateX, MouseCoordinateY, CurrentCoordinate } = coordinates;

var { OHLCTooltip, MovingAverageTooltip, BollingerBandTooltip } = tooltip;
var { XAxis, YAxis } = axes;
var { ema, sma, bollingerBand } = indicator;
var { fitWidth, TypeChooser } = helper;


const LENGTH = 130; //<--Copy over from updatingDataWrapper.jsx
class CandleStickChartWithBollingerBandOverlay extends React.Component {
	//<--Copy over from updatingDataWrapper.jsx -- Start
	constructor(props) {
		super(props);
		this.state = {
			length: LENGTH,
			data: this.props.data.slice(0, LENGTH),
		}
		this.speed = 1000;
		this.onKeyPress = this.onKeyPress.bind(this);
	}
	componentDidMount() {
		document.addEventListener("keyup", this.onKeyPress);
	}
	componentWillUnmount() {
		if (this.interval) clearInterval(this.interval);
		document.removeEventListener("keyup", this.onKeyPress);
	}
	onKeyPress(e) {
		var keyCode = e.which;
		console.log(keyCode);
		switch (keyCode) {
			case 50: {
				// 2 (50) - Start alter data
				this.func = () => {
					if (this.state.length < this.props.data.length) {
						this.setState({
							length: this.state.length + 1,
							data: this.props.data.slice(0, this.state.length + 1),
						})
					}
				};
				break;
			}
			case 80:
			// P (80)
			case 49: {
				// 1 (49) - Start Push data
				this.func = () => {
					if (this.state.length < this.props.data.length) {
						this.setState({
							length: this.state.length + 1,
							data: this.props.data.slice(START, START+this.state.length + 1),
						})
					}
				};
				break;
			}
			case 27: {
				// ESC (27) - Clear interval
				this.func = null;
				if (this.interval) clearInterval(this.interval);
				break;
			}
			case 107: {
				// + (107) - increase the this.speed
				this.speed = Math.max(this.speed / 2, 50);
				break;
			}
			case 109:
			case 189: {
				// - (189, 109) - reduce the this.speed
				var delta = Math.min(this.speed, 1000);
				this.speed = this.speed + delta;
				break;
			}
		}
		if (this.func) {
			if (this.interval) clearInterval(this.interval);
			console.log("this.speed  = ", this.speed);
			this.interval = setInterval(this.func, this.speed);
		}
	}
	//<--Copy over from updatingDataWrapper.jsx -- Complete
	render() {
		var { dataSlice } = this.state;	// <-- Define dataSlice	
		var { type, width, ratio } = this.props; // <-- Take out data

		var ema20 = ema()
			.windowSize(20) // optional will default to 10
			.sourcePath("close") // optional will default to close as the source
			.skipUndefined(true) // defaults to true
			.merge((d, c) => {d.ema20 = c}) // Required, if not provided, log a error
			.accessor(d => d.ema20) // Required, if not provided, log an error during calculation
			.stroke("blue") // Optional

		var sma20 = sma()
			.windowSize(20)
			.sourcePath("close")
			.merge((d, c) => {d.sma20 = c})
			.accessor(d => d.sma20)

		var ema50 = ema()
			.windowSize(50)
			.sourcePath("close")
			.merge((d, c) => {d.ema50 = c})
			.accessor(d => d.ema50)

		var smaVolume50 = sma()
			.windowSize(50)
			.sourcePath("volume")
			.merge((d, c) => {d.smaVolume50 = c})
			.accessor(d => d.smaVolume50)
			.stroke("#4682B4")
			.fill("#4682B4");

		var bb = bollingerBand()
			.merge((d, c) => {d.bb = c})
			.accessor(d => d.bb);
		return (
			<ChartCanvas ratio={ratio} width={width} height={400}
					margin={{ left: 70, right: 70, top: 10, bottom: 30 }} type={type}
					seriesName="usdt_btc"
					data={dataSlice} calculator={[sma20, ema20, ema50, smaVolume50, bb]} // <-- use dataSlice
					xAccessor={d => d.date} xScaleProvider={discontinuousTimeScaleProvider}
					//xExtents={[new Date(2016, 5, 1), new Date(2016, 10, 1)]}  //<-- comment out
					>					
				<Chart id={1}
						yExtents={[d => [d.high, d.low], sma20.accessor(), ema20.accessor(), ema50.accessor(), bb.accessor()]}
						padding={{ top: 10, bottom: 20 }}
						onContextMenu={(...rest) => { console.log("chart - context menu", rest); }}
						>
					<XAxis axisAt="bottom" orient="bottom"/>
					<YAxis axisAt="right" orient="right" ticks={5}
						onDoubleClick={(...rest) => { console.log("yAxis - double click", rest); }}
						onContextMenu={(...rest) => { console.log("yAxis - context menu", rest); }}
						/>

					<MouseCoordinateX
						at="bottom"
						orient="bottom"
						displayFormat={d3.timeFormat("%Y-%m-%d")} />
					<MouseCoordinateY
						at="right"
						orient="right"
						displayFormat={d3.format(".2f")} />

					<CandlestickSeries />
					<LineSeries yAccessor={sma20.accessor()} stroke={sma20.stroke()}/>
					<LineSeries yAccessor={ema20.accessor()} stroke={ema20.stroke()}/>
					<LineSeries yAccessor={ema50.accessor()} stroke={ema50.stroke()}/>
					<BollingerSeries calculator={bb} />
					<CurrentCoordinate yAccessor={sma20.accessor()} fill={sma20.stroke()} />
					<CurrentCoordinate yAccessor={ema20.accessor()} fill={ema20.stroke()} />
					<CurrentCoordinate yAccessor={ema50.accessor()} fill={ema50.stroke()} />


					<OHLCTooltip origin={[-40, 0]}/>
					<MovingAverageTooltip onClick={(e) => console.log(e)} origin={[-38, 15]}
						calculators={[sma20, ema20, ema50]}/>
					<BollingerBandTooltip origin={[-38, 60]} calculator={bb} />

				</Chart>
				<Chart id={2}
						yExtents={[d => d.volume, smaVolume50.accessor()]}
						height={150} origin={(w, h) => [0, h - 150]}>
					<YAxis axisAt="left" orient="left" ticks={5} tickFormat={d3.format(".0s")}/>

					<MouseCoordinateY
						at="left"
						orient="left"
						displayFormat={d3.format(".4s")} />

					<BarSeries yAccessor={d => d.volume} fill={d => d.close > d.open ? "#6BA583" : "#FF0000" } />
					<AreaSeries yAccessor={smaVolume50.accessor()} stroke={smaVolume50.stroke()} fill={smaVolume50.fill()}/>
					<CurrentCoordinate yAccessor={smaVolume50.accessor()} fill={smaVolume50.stroke()} />
					<CurrentCoordinate yAccessor={d => d.volume} fill="#9B0A47" />
				</Chart>
				<CrossHairCursor />
			</ChartCanvas>
		);
	}
};


CandleStickChartWithBollingerBandOverlay.propTypes = {
	data: React.PropTypes.array.isRequired,
	width: React.PropTypes.number.isRequired,
	ratio: React.PropTypes.number.isRequired,
	type: React.PropTypes.oneOf(["svg", "hybrid"]).isRequired,
};

CandleStickChartWithBollingerBandOverlay.defaultProps = {
	type: "svg",
};
CandleStickChartWithBollingerBandOverlay = fitWidth(CandleStickChartWithBollingerBandOverlay);


var parseDate = d3.timeParse("%Y-%m-%d %H:%M:%S");
d3["tsv"]("./usdt_btc.tsv", (err, data) => {  // //rrag.github.io/react-stockcharts/data/MSFT.tsv
	/* change MSFT.tsv to MSFT_full.tsv above to see how this works with lots of data points */
	data.forEach((d, i) => {
		d.date = new Date(d3.timeParse("%Y-%m-%d")(d.date).getTime());
		d.open = +d.open;
		d.high = +d.high;
		d.low = +d.low;
		d.close = +d.close;
		d.volume = +d.volume;
		// console.log(d);
	});
	/* change the type from hybrid to svg to compare the performance between svg and canvas */
	ReactDOM.render(<TypeChooser type="hybrid">{type => <CandleStickChartWithBollingerBandOverlay data={data} type={type} />}</TypeChooser>, document.getElementById("chart"));
});`

**Comment by yunpeng-zhang** [comment]
I found an older example, does this code work? [http://embed.plnkr.co/JMm2lgrzBgWnh3hkoTAR/](http://embed.plnkr.co/JMm2lgrzBgWnh3hkoTAR/)

**Comment by no0dly** [comment]
Is it possible to use http://rrag.github.io/react-stockcharts-next/documentation.html#/updating_data with redux?

**Comment by rrag** [comment]
@no0dly I have not tried, but dont see a problem. Why do you think there would be a problem?

**Comment by piotryordanov** [comment]
@no0dly I'm actually updating data using redux. Any issue ur facing and need help with?

**Comment by no0dly** [comment]
@rrag there is no issue, can figure out how does it work. @piotryordanov can you show your component?

**Comment by piotryordanov** [comment]
@no0dly I have redux and it's store created like in any app, and that the chartContainers is connected to it using `connect`. From that point on, the rest is just like with a standard redux setup.

My source code is pretty large to be shared. Anything in particular u want to see?
