### ISSUE TITLE
I want to adjust the final scroll position.

### ISSUE THREAD

**Issue by m-morisaki** [rrag/react-stockcharts#462]
In the demo, the final scroll coordinates are as follows.
![2018-02-15 12 43 04](https://user-images.githubusercontent.com/32150594/36239862-559a1310-1250-11e8-861c-5e74ad8f804f.png)

↓

Can I adjust the final scroll coordinates as follows?
![2018-02-15 12 43 18](https://user-images.githubusercontent.com/32150594/36239863-55c9e73e-1250-11e8-9f9f-7690224a8895.png)

**Comment by m-morisaki** [comment]
EventCapture.jsx

**Comment by rrag** [comment]
This is not possible.

I am not sure this adds value. Why do you think it will be a useful feature?

**Comment by Neha3011** [comment]
I am trying to achieve the same. But my problem is different I think. I am updating the chart based on a pusher api. The new data that is coming is not fully visible.
In the image, look at the last candlestick.
<img width="215" alt="last candlestick" src="https://user-images.githubusercontent.com/10024090/36252607-2ffd9ea4-126b-11e8-9589-b6e27e1c919e.png">
How can I add extra space at the end of the chart ?
Thanks.

**Comment by rrag** [comment]
@Neha3011 this is a different problem

you could try to add a `padding`

```
<ChartCanvas padding={10} ... > // this adds 10px padding left and right, so only candles larger than 20px are cut off
  <Chart id={/* chart id containing candlestick series */} padding={{ top: 10, bottom: 40 }} > // this avoids  the overlap between volume and candles
