### ISSUE TITLE
How could I draw a non-interactive StraightLine?

### ISSUE THREAD

**Issue by azurechen** [rrag/react-stockcharts#463]
I have tried to use `react-stockcharts/lib/series/StraightLine` and it is easy to draw a horizontal or vertical line. But I don't just want to draw the horizontal and vertical lines.

So I use the `react-stockcharts/lib/interactive/components/StraightLine` component and set the xValue and yValue for the StraightLine
```
<StraightLine type="LINE"
            noHover
            x1Value={100}
            y1Value={200}
            x2Value={100}
            y2Value={200}
            stroke={"blue"}
            strokeWidth={5}
            strokeOpacity={1} />
```
But no line display in the chart.

**Comment by moonlight16** [comment]
Yeah I'm finding StraightLine doesn't work for me either.  I'd be happy enough if I could get just get a vertical (or horizontal) line to showup on the chart.  You said it was easy to get a horizontal or vertical line.  Can you provide an example of what you used?

**Comment by moonlight16** [comment]
> Yeah I'm finding StraightLine doesn't work for me either. I'd be happy enough if I could get just get a vertical (or horizontal) line to showup on the chart. You said it was easy to get a horizontal or vertical line. Can you provide an example of what you used?

Ok, I figured out the issue.  There's 2 versions of StraightLine.js.  I was using the incorrect one:

import StraightLine from "react-stockcharts/lib/interactive/components/StraightLine"

This is the correct one:

import { StraightLine } from "react-stockcharts/lib/series"
