### ISSUE TITLE
How to change the 1px width of bars in a candlestick chart? 

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#466]
Hey, I don't know the terminology, so I don't know how to name it properly. How do I change this (pointing with the arrow in an img) width? I think I've tried all `CandlestickSeries` props, but no luck. Maybe I missed something. https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.js.
I want it to be more bold, to have a basic width of 2-5px.

Thanks!

<img width="190" alt="screen shot 2018-02-21 at 13 58 20" src="https://user-images.githubusercontent.com/1615659/36467058-87e6487a-170f-11e8-8118-3d49fe18b95f.png">

**Comment by rrag** [comment]
that is called wick, and there is no option to change the `strokeWidth` of it

it is drawn like this 

in canvas
https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.js#L169-L170
it is basically 2 rectangles (top wick and bottom wick) of width 1, profiling showed that this is faster than a canvas line

in svg
https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.js#L105

try adding `strokeWidth` (in svg)

but in canvas you have to set a `ctx.lineWidth = ... `and then change it back to 1 after the wick is drawn so the candle can have a strokewidth of 1

Changing the state of canvas per wick takes a few millisecs, so doing it once before wick draw and then resetting it back to 1 after wick should be ok.

Try it out.
