### ISSUE TITLE
TypeError: (0 , _indicator.ema)(...).id(...).options is not a function

### ISSUE THREAD

**Issue by markolofsen** [rrag/react-stockcharts#469]
Hi @rrag! Thanks for your awesome library and need your help...
I took [this example](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/HeikinAshi) and did CopyPast into my project correctly, but got an error: `TypeError: (0 , _indicator.ema)(...).id(...).options is not a function`

Check it here [https://codesandbox.io/s/84r4z9r290](https://codesandbox.io/s/84r4z9r290)

**Comment by rrag** [comment]
please use `npm install -S react-stockcharts@next` the examples are for 0.7 beta.

I should probably just go ahead and rip the bandaid, publish 0.7 soon

**Comment by markolofsen** [comment]
@rrag  Thanks a lot! It helped!
