### ISSUE TITLE
[SUPPORT] How to implement own XAxis ticks format

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#47]
I need to implement custom ticks format for XAxis. it should looks like:

format                            |                |                  |                 |
------------------------------ | ----------- | ------------- | ------------ |
tick time - current time | 60            | 40            | 20            |
tick time                         | 12:47:00 | 12:47:20 | 12:47:40 |

What should I do? Implement my own [polylineartimescale](https://github.com/rrag/react-stockcharts/blob/79bc0977f90713909ce609abb634d0dea462a329/src/lib/scale/polylineartimescale.js) and [StockscaleTransformer](https://github.com/rrag/react-stockcharts/blob/a6ad7419d679ca1edea9f8974388c08ad48aae70/src/lib/transforms/StockscaleTransformer.js) ?

**Comment by rrag** [comment]
is the 40 and 20 swapped in first row?

**Comment by rrag** [comment]
I believe you are looking for an intra day scale, it is in the roadmap

**Comment by filod** [comment]
@rrag great job, i also wondering the differences between markets.
such as Shanghai Stock Exchange, their intra day time is like :
```
9:30 ~ 11: 30
13:00 ~ 15:00
```
can react-stockcharts support fine with cases like this?

**Comment by rrag** [comment]
Intra day is not supported yet, for any market.

I did not know about the Shanghai Stock Exchange timings, good to know. So when you plot data which has discontinuity between 11:30 to 13:00 would the tick for 11:30 appear right next to the tick of 13:00 or will there be a straight line between them?

**Comment by filod** [comment]
i assume you are talking something like:
```
            |
            |
            |
 __________________________
      11:30 | 13:00
```
that would be a great choice, 

but this one can be good enough: 
![image](https://cloud.githubusercontent.com/assets/679897/12508609/ed88d2a4-c137-11e5-9668-18198452503d.png)

http://xueqiu.com/S/SH601009

**Comment by rrag** [comment]
where is the discontinuity on this chart?

**Comment by filod** [comment]
actually there's no discontinuity, 11:30 is next to 13:00 tightly
![image](https://cloud.githubusercontent.com/assets/679897/12509325/a3c5ef12-c13c-11e5-8a9c-f14a7f80008b.png)
![image](https://cloud.githubusercontent.com/assets/679897/12509338/b3302bd4-c13c-11e5-93cf-1fdb428ad564.png)

**Comment by rrag** [comment]
Yup that is how it will show once implemented. For reference you can see the examples and see that weekends are handled the same way. Renko, Kagi have best examples where the x scale is not linear and the discontinuity of dates is not shown on the x.

**Comment by iNikNik** [comment]
@filod @rrag thx for feedback) I've implemented my own data transformer and scale:

![intraday](https://cloud.githubusercontent.com/assets/7679749/12495298/f8ccfd5e-c09f-11e5-933f-34aebf5ba8ce.gif)

**Comment by rrag** [comment]
cool, this is great. Would you mind sharing the code?

I was going to rewrite polylinearscale in 0.5 to change it to be more functional and also evaluate if the same scale can support both intraday and also end of day

**Comment by iNikNik** [comment]
@rrag it's pretty hacky implementation because I have no zoom (only pan) and x-scale always the same:

```javascript

import stockScale from './myScale';

const defaultOptions = {
  dateAccessor: (d) => d.date,
  indexAccessor: (d) => d.idx,
  dateMutator: (d, date) => { d.date = date; },
  indexMutator: (d, i) => ({ ...d, idx: i })
};

function IndexTransformer() {
  let newOptions;

  function transform(data, interval) {
    const { indexMutator } = newOptions;
    const responseData = {};
    const dd = data[interval];

    responseData.D = dd.map(indexMutator);
    return responseData;
  }

  transform.options = (opt) => {
    newOptions = { ...defaultOptions, ...opt };
    newOptions.xAccessor = newOptions.indexAccessor;
    newOptions.xScale = stockScale(newOptions.xAccessor);
    return newOptions;
  };

  return transform;
}

export default IndexTransformer;
```

```javascript

import d3 from 'd3';

function financeTimeScale(drawableData, indexAccessor, backingLinearScale, dateAccessor = d => d.date) {
  function formater(d) {
    return d3.time.format('%H:%M:%S')(dateAccessor(d));
  }

  function scale(x) {
    return backingLinearScale(x);
  }

  scale.isPolyLinear = function() {
    return true;
  };
  scale.invert = function(x) {
    return backingLinearScale.invert(x);
  };
  scale.data = function(x) {
    if (!arguments.length) {
      return drawableData;
    } else {
      drawableData = x;
      // this.domain([drawableData.first().index, drawableData.last().index]);
      this.domain([indexAccessor(drawableData[0]), indexAccessor(drawableData[drawableData.length - 1])]);
      return scale;
    }
  };
  scale.domain = function(x) {
    if (!arguments.length) return backingLinearScale.domain();
    // console.log("before = %s, after = %s", JSON.stringify(backingLinearScale.domain()), JSON.stringify(x))

    let d = [x[0], x[1]];
    // console.log(d);
    backingLinearScale.domain(d);
    return scale;
  };
  scale.range = function(x) {
    if (!arguments.length) return backingLinearScale.range();
    backingLinearScale.range(x);
    return scale;
  };
  scale.rangeRound = function(x) {
    return backingLinearScale.range(x);
  };
  scale.clamp = function(x) {
    if (!arguments.length) return backingLinearScale.clamp();
    backingLinearScale.clamp(x);
    return scale;
  };
  scale.interpolate = function(x) {
    if (!arguments.length) return backingLinearScale.interpolate();
    backingLinearScale.interpolate(x);
    return scale;
  };
  scale.ticks = function(m) {
    const ticks = drawableData
        .filter(d => dateAccessor(d).getSeconds() % 10 === 0)
        .reduce((res, d) => {
          if (!res.length) {
            return [ d ];
          }
          /*
             We should filter data with same seconds
             [ 11:30:20.123, 11:30:20.423 ] -> [ 11:30:18.123 ]
           */
          return Math.abs(dateAccessor(res[res.length - 1]).getTime() - dateAccessor(d).getTime()) > 1000 ?
            [ ...res, d ] :
            res
          ;
        }, [])
        .map(indexAccessor)
      ;
    // return the index of all the ticks to be displayed,
    return ticks;
  };
  scale.tickFormat = function(/* ticks */) {
    return function(index) {
      // for each index received from ticks() function derive the formatted output
      const tick = drawableData.find(item => indexAccessor(item) === index);
      return formater(tick);
    };
  };
  scale.nice = function(m) {
    backingLinearScale.nice(m);
    return scale;
  };
  scale.copy = function() {
    return financeTimeScale(drawableData, indexAccessor, backingLinearScale.copy());
  };
  return scale;
}

const defaultFinanceDateTimeScale = function(indexAccessor) {
  return financeTimeScale([0, 1], indexAccessor, d3.scale.linear());
};

export default defaultFinanceDateTimeScale;
```
