### ISSUE TITLE
LineScatter documentation vs codepen differ

### ISSUE THREAD

**Issue by TomYeoman** [rrag/react-stockcharts#471]
Hi,

Thanks for the hard work you've put into the project, it's really great to use however I did have to stumble through this for a while first.

http://rrag.github.io/react-stockcharts/documentation.html#/line_scatter

The documentation shows 3 lines, but then once into codepen we only have 1 showing.

After investigation it seems the data it's fetching ( MSFT.tsv ) doesn't actually contain the headers for 2/3 of the lines we're trying to draw such as AAPLClose / GEClose.

Changing these LineSeries to reference the close / open / high properties lets me see 3 lines plotted, perhaps the codepen should be updated to use those properties / the dataset updated.

**Comment by rrag** [comment]
Thanks for reporting. Will fix the data source, it should be `comparison.tsv`

**Comment by rrag** [comment]
fixed [codesandbox](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/LineAndScatterChart)
