### ISSUE TITLE
Is it impossible to put charts in separate components?

### ISSUE THREAD

**Issue by JimVanEeden** [rrag/react-stockcharts#473]
First of all: This is an absolutely great project!

So I'm building a chart with different lines depending on the input data, so I need to split out charts in the ChartCanvas and map them in like below.

```
<ChartCanvas>
    {chartData.map(LineChart)}
</ChartCanvas>

function LineChart(data) {
   return <Chart>...</Chart>;
}
```

But it seems I can't do that at all because I get errors whenever I put Chart elements in separate components instead of directly in the ChartCanvas. 

```
Uncaught TypeError: Cannot read property 'origin' of undefined
    at t.value (Chart.js:107)
    at ReactCompositeComponent.js:793
    at s (ReactCompositeComponent.js:73)
    at m._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:792)
    at m._renderValidatedComponent (ReactCompositeComponent.js:819)
    at m.performInitialMount (ReactCompositeComponent.js:359)
    at mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at m.performInitialMount (ReactCompositeComponent.js:368)
    at mountComponent (ReactCompositeComponent.js:255)
    at Object.mountComponent (ReactReconciler.js:43)
    at g.mountChildren (ReactMultiChild.js:234)
    at g._createInitialChildren (ReactDOMComponent.js:701)
    at g.mountComponent (ReactDOMComponent.js:520)
    at Object.mountComponent (ReactReconciler.js:43)
    at g.mountChildren (ReactMultiChild.js:234)
```

It seems the Chart isn't loaded in the context.chartConfig anymore. Is there any way around this?

**Comment by rrag** [comment]
you are correct, right now Chart has to be a direct child of ChartCanvas. I have some ideas on how to change this but it would be a breaking change.

**Comment by JimVanEeden** [comment]
If you could implement that at some point that would be great. Because now I have to hardcode some stuff and that's quite annoying. Thanks!

**Comment by rrag** [comment]
Yes that is the idea, cannot promise any timelines though

**Comment by kglazkov** [comment]
Hi, Jim! What kind of hard code did u do? :)

**Comment by JimVanEeden** [comment]
Well I wanted to put Charts in separate components so I could map an array with the chart data over to those react components, now I had to do it hard coded like:

```
<Chart>...</Chart>
<Chart>...</Chart>
<Chart>...</Chart>
```

**Comment by kglazkov** [comment]
Right now I use pure functions for separating charts which returns chart component with content. And will be waiting for breaking changes by Ragu.

**Comment by garana** [comment]
Is there any workaround for this?

**Comment by garana** [comment]
Just in case this helps someone else, I managed to get charts in child components, as long as they are  functions, not objects:
```

<ChartCanvas height={...} ...>
     { Charts1(some props/args) /* <<< this has to be a function, returning an array of <Chart/> */ }
     { Charts2(some other props/args) /* <<< or a single <Chart/> */ }
</ChartCanvas>

/* This is the function that returns an array of Charts. */
function  Charts1(args) {
    return [
       <Chart id={...} ... >...</Chart>,
       <Chart id={...} ... >...</Chart>
    ]
}

function  Charts2(args) {
    return <Chart id={...} ... >...</Chart>
}

```
