### ISSUE TITLE
Controling the Zoom

### ISSUE THREAD

**Issue by CharifAbdeslam** [rrag/react-stockcharts#475]
First thank you for this Amazing librairie , My issue is , i want to start the chart with a full Zoom , is their a way on how to control the zoom on the chart before the screen load ?

**Comment by rrag** [comment]
you could set 

```jsx
<ChartCanvas
  xExtents={[xAccessor(leftCandle you want to see), xAccessor(right most candle)]}
  ...
>
```

does that help?

**Comment by CharifAbdeslam** [comment]
Thanks m8t it working :D
