### ISSUE TITLE
More than 3 strokes for RSISeries

### ISSUE THREAD

**Issue by nkpgardose** [rrag/react-stockcharts#480]
Hi! 👋 RSISeries have `top`, `middle`, and `bottom` stroke options. Is there any way to make multiple lines for it? I.E. I have a tick of 20, 30, 70, 80.

**Comment by rrag** [comment]
add 
```jsx
<RSISeries ... />
<StraightLine ... yValue={20} />
<StraightLine ... yValue={80} />
```

**Comment by nkpgardose** [comment]
@rrag thank you for this helpful tips!
