### ISSUE TITLE
Uncaught TypeError: Cannot read property 'date' of undefined at xAccessor

### ISSUE THREAD

**Issue by Neha3011** [rrag/react-stockcharts#481]
Hi,
I am facing an issue when I only have 1 data for the Chart.
My data is: 
[[1519603200, 711000, 1400000, 690000, 1200000, 343.9744]]
This is throwing error in code `const xAccessor = d => d.date;`, date of undefined.

This works fine for more than 1 row of data. Is there anything I can do to fix this?

Thanks in advance for your help.

**Comment by rrag** [comment]
you need minimum 2 data points,
the chart needs to calculate left and right values on the x, with just 1 data point they both will be the same
