### ISSUE TITLE
Realtime data using web socket

### ISSUE THREAD

**Issue by Ejnot** [rrag/react-stockcharts#482]
![image](https://user-images.githubusercontent.com/25398663/36889985-3827409e-1e37-11e8-9e69-cc98d451ed2c.png)

Hi, I am trying to make a real time chart with web socket in continuously throwing data I push the data to an array and I filtered it then setState every time i receive a message from websocket.

Buy the problem is the candles are getting thin and thin and the xaxis is always changing everytime the it updates data. And even after i filtered the data by 30 min the xasis shows an interval of 3hours and the candles is overlaying with each other.

**Comment by colorwheeloflife** [comment]
As far as I know, this should do the trick for you: https://rrag.github.io/react-stockcharts/documentation.html#/updating_data 

Each time new data arrives I believe you just add it to the existing data array.  I'm still in the setting up phase myself and will be doing the same with websockets within the week.  Tis how I've scoped it out.

**Comment by Ejnot** [comment]
I figured out the problem its because i was receiving the same date/time/timestamp and that data shouldn't be pushed as new but to update the existing data with === to timestamp i pretty much solve the issue but i'm looking forward seeing how you set up your's using websocket.
