### ISSUE TITLE
Apply multiple colors into the Area Chart

### ISSUE THREAD

**Issue by gglee89** [rrag/react-stockcharts#484]
Hi,

Hope I can get a little bit of assistance with my attempt to **apply multiple colors into the Area Chart**.

Currently, I understand we're able to apply different colors by through the `fill` props:
```js
<AreaSeries 
      fill="#FF0000" // AREA CHART COLOR
      yAccessor={d => d.totalVolume} 
/>
```

![screen shot 2018-03-02 at 7 32 48 pm](https://user-images.githubusercontent.com/16644017/36894992-99c01024-1e50-11e8-9724-e9ba7a758b4b.png)

## __Here is my question:__
Would it be possible to add multiple colors like the image below?
![screen shot 2018-03-02 at 7 28 31 pm](https://user-images.githubusercontent.com/16644017/36895053-d36ef272-1e50-11e8-95c4-8230bac7c30e.png)

My only attempt, and so far unique way I thought of doing was by doing something like this:
```js
<AreaSeries 
      fill={d => d.type === "" ? "#FF0000" : "#00FF00" } // Apply Red and Green
      yAccessor={d => d.totalVolume} 
/>
```

But I checked the actual `AreaSeries` component, and the fill property applies color into the entire area chart.

Thank you in advance.

**Comment by nimo23** [comment]
I think, it the same issue as https://github.com/rrag/react-stockcharts/pull/431 with fill/stroke-function, but only for AreaSeries (which actually cannot accept a function, because of `fill: PropTypes.string.isRequired`).

**Comment by gglee89** [comment]
That's amazing. Much appreciated @nimo23.
How soon do you think we can have this included into the component's library?

Thank you.

**Comment by nimo23** [comment]
Actualy, I dont have time for the rest of the month and I also want to wait after https://sourceforge.net/projects/eclipsenotepad/files/eclipsenotepad/ is merged or improved.

I guess other components stroke and fill as parameter can also be benefit from getFillColor() and getStrokeColor(), hence we should also check to outsource this into a helper class..


 I do not know when and how I can do a PR for this.

**Comment by gglee89** [comment]
Hi @nino23 much appreciated indeed!
Let me know if you want me to then close this issue or leave it opened~ 

Since this item is somewhat a duplicate of #431 if you want, then please go ahead and close this issue! Or I can even do it~~

**Comment by rrag** [comment]
I must apologize to @nimo23 for not spending time and creating a delay on the PRs, I will get to it this month. Sorry

Hi @gglee89 you have to implement this as 2 `AreaSeries`

related - https://github.com/rrag/react-stockcharts/issues/474

An area can have one fill color, and not possible to fill an area with multiple colors. There are tricks like clip that can be used to achieve things like [this](https://github.com/rrag/react-stockcharts/issues/349) but that is not needed here as you always need only 2 colors and it is predefined, so go with 2 `AreaSeries`

**Comment by gglee89** [comment]
Hi @rrag, thank you for your response!
I will try the option you've mentioned!

**Comment by jaymontana** [comment]
Hey @gglee89 this reminds me of a depth chart, is it possible to achieve this image? with your method, if so I'd appreciate if you could show us how, thanks!
![6791ef2b956d640b322f60eeefc8194d](https://user-images.githubusercontent.com/19938321/37546726-1fc32d62-2966-11e8-87f4-eab518372bd4.png)

**Comment by gglee89** [comment]
@jaymontana Sure thing.
This is a quick sample of what you could use to start building your depth chart.

```js
class AreaChart extends React.Component {
    render() {
        const {
            axisColor,
            data,
            height,
            type,
            margin,
            width,
            ratio,
        } = this.props;

        const xScale = scaleLinear();
        const xExtents = [0, data.length - 1];

        return (
                <ChartCanvas
                       ratio={ratio}
                       width={width}
                       height={height}
                       margin={{ left: 0, right: 50, top: 0, bottom: 30 }}
                       seriesName="MSFT"
                       data={data}
                       type={type}
                       xAccessor={d => d.x}
                       xExtents={xExtents}
                       xScale={xScale}
                >
                    <Chart id={0} yExtents={d => d.totalVolume}>
                       <XAxis
                                axisAt="bottom"
                                orient="bottom"
                                tickStroke={axisColor}
                        />
                        <YAxis
                                axisAt="right"
                               orient="right"
                               tickStroke={axisColor}
                        />
                        <AreaSeries yAccessor={d => d.type == "bids" && d.totalVolume} fill="#00FF00" />
                        <AreaSeries yAccessor={d => d.type == "asks" && d.totalVolume} fill="#FF0000" />
                        <HoverTooltip
                               fontSize={15}
                               tooltipContent={tooltipContent([])}
                               yAccessor={d => d.totalVolume}
                        />
                    </Chart>
</ChartCanvas>
```

It should give you back this:
![screen shot 2018-03-19 at 2 54 54 pm](https://user-images.githubusercontent.com/16644017/37580154-93051f44-2b85-11e8-883e-ce0bd906e12a.png)

**Comment by chanmathew** [comment]
@gglee89 Hey Gustavo, do you mind sharing how to always keep the spread centered even during zooming? Trying to figure that out, much appreciated!

**Comment by ashwinkalyanpur** [comment]
HI how can i have different Area chart with different background color. i am loading 5 tabs i need different area chart background color in react

**Comment by heeropunjabi** [comment]
@gglee89 is it possible to post the complete solution or if you can give us what data needs to be passed to the component that will also be helpful.

**Comment by baskey006** [comment]
i have tried a sample for the chart. https://codesandbox.io/s/depth-chart-edited-7d6se.
