### ISSUE TITLE
Error while using SAR indicator with svg

### ISSUE THREAD

**Issue by Rangarajan0603** [rrag/react-stockcharts#485]
The following error is displayed while using sar indicator and chart type as svg
"Received NaN for the `cy` attribute. If this is expected, cast the value to a string."

The error can be noticed in the console of the [code sandbox](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithSAR) when we scroll to the first bar.

**Comment by Rangarajan0603** [comment]
The error **" Received NaN for the `some` attribute"** occurs while using SVG with macd, elderRay and few other indicators also.

**Comment by rrag** [comment]
Fixed it in SAR, and BarSeries,
MACD and ElderRay used BarSeries behind the scenes which caused this problem.
Thanks for reporting. Will be fixed in the next npm publish
