### ISSUE TITLE
Provide `yAccessor` for Annotations

### ISSUE THREAD

**Issue by MattiSG** [rrag/react-stockcharts#486]
Hi and thanks for offering react-stockcharts to the community, really super useful! 👏 

When using annotations, I was confused by what seems to be an inconsistency in the API.

I can indeed specify the abscissa of an annotation with the `xAccessor` property, just like for a canvas. But I cannot specify its ordinate through an equivalent `yAccessor`: I have to compute `y` myself using the provided `yScale` and `datum`.

If that is the expected behaviour, I'm happy to open a PR to improve the doc.
Otherwise, I would recommend adding a `yAccessor` to `Annotate` that behaves similarly to what `xAccessor` does 🙂

**Comment by rrag** [comment]
Sorry for the late reply, It is inconsistent I agree. This offers a way for the user to do 

1. plot the annotation at the top/bottom of the yaxis
2. plot the annotation at a desired place if you already know the y value

I am open to other options but this flexibility is something I felt was needed for things like an annotation for a dividend, it does not matter the price, but the date it happened, and the dividend annotation can be at the bottom of the y scale.

what do you think?

**Comment by MattiSG** [comment]
I just think the API should be as consistent as possible for all components 🙂

If you feel like providing the `y` for added flexibility that's good, but I am expecting `yAccessor` to also be present, as is the case for other components. I personally did not encounter the need to compute `y` directly though, as my use was recreating something like `yAccessor` and then wrapping in the call to `yScale`.

Maybe one way to do that would be to add `yAccessor`, deprecate `y`, and see if users have a problem with the deprecation? 🙂

> As a side note, I won't be working with react-stockcharts in the foreseeable future and will thus not be available to work further on this issue.
