### ISSUE TITLE
How to make PriceCoordinate line dashed?

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#488]
Hey, I need to have a line on a chart indicating a price coordinate with a dashed style.

What I want:
<img width="354" alt="screen shot 2018-03-09 at 11 08 14" src="https://user-images.githubusercontent.com/1615659/37204835-4e1ed9ae-238a-11e8-83a7-924fe113407d.png">

What I have:
<img width="429" alt="screen shot 2018-03-09 at 11 08 04" src="https://user-images.githubusercontent.com/1615659/37204839-539d331c-238a-11e8-942b-9aa471240409.png">

Looking at https://github.com/rrag/react-stockcharts/blob/93b90cb46ed62136c6a0975777cbbdcc11e8ca28/src/lib/coordinates/PriceCoordinate.js I can't seem to find a prop for it. Ideally, I'd like `PriceCoordinate` to have support for the `strokeDasharray` like `CrossHairCursor` has.

Is there any way to style the line right now until the prop support arrives? Thank you!

**Comment by rrag** [comment]
0.7.1 now published includes support for this http://rrag.github.io/react-stockcharts/documentation.html#/price_marker_demonstration
