### ISSUE TITLE
How to make PriceCoordinate and EdgeIndicator fill transparent, but have a border?

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#489]
Hey, I need to have a `PriceCoordinate` and `EdgeIndicator` fill transparently (or I can just set its fill to the background color), but have a border. So in short, how do I add a border to the fill part of it? (btw how to call it properly?)

What I want:
<img width="354" alt="screen shot 2018-03-09 at 11 08 14" src="https://user-images.githubusercontent.com/1615659/37205008-ff3d1dae-238a-11e8-80e9-be0557e86d45.png">

What I have:
<img width="429" alt="screen shot 2018-03-09 at 11 08 04" src="https://user-images.githubusercontent.com/1615659/37205019-036e4b78-238b-11e8-99f5-b756970f80bd.png">

Is there any way to style the line right now until the prop support arrives? Thank you!

**Comment by cbrwizard** [comment]
Ok, I've found a way to do it for `EdgeIndicator`:
1. fill it with background color, like `fill="#000"`
2. add a border with `stroke`, like `stroke={d => (d.close > d.open ? BID_COLOR : ASK_COLOR)}`

However, there doesn't seem to be a way to add `stroke` for a `PriceCoordinate`. I see that the support for it is seemingly added in this commit, but I can't get it working.
Here is the code:

```js
            <PriceCoordinate
              at="right"
              orient="right"
              price={Number(priceAlert.price)}
              stroke="red"
              strokeWidth={3}
              strokeOpacity={1}
              displayFormat={format('.8f')}
              key={priceAlert.price}
            />
```

What is the solution here? @borovik96 @rrag

**Comment by borovik96** [comment]
It seems that 0.7 version doesn't have this commit
https://github.com/rrag/react-stockcharts/blob/v0.7.0/src/lib/coordinates/PriceCoordinate.js

**Comment by rrag** [comment]
0.7.1 published with all these changes and more

http://rrag.github.io/react-stockcharts/documentation.html#/price_marker_demonstration
