### ISSUE TITLE
Styling in Chrome

### ISSUE THREAD

**Issue by svk31** [rrag/react-stockcharts#49]
First off let me just say great work on this library!

I work on a decentralized crypto currency exchange [Bitshares](https://github.com/cryptonomex/graphene-ui) where I've used Highstock to build the trading graphs, but I hope to replace it with this library asap.

I've made some basic progress using your docs (which are awesome btw), but I have this weird styling issue in Chrome that I can't quite figure out. It works fine in Firefox, and your examples also have the correct styling in Chrome, but in my own implementation all the svg styling attributes get ignored. Here's a screenshot of what it looks like in Chrome:

https://github.com/cryptonomex/graphene-ui
![image](https://cloud.githubusercontent.com/assets/6890015/12592112/5026cbce-c46b-11e5-8601-580d1f720c0c.png)

And in Firefox:

![image](https://cloud.githubusercontent.com/assets/6890015/12592148/787e97fa-c46b-11e5-980f-4d2f0d2c4c8b.png)

Any idea what's going on here?

My code is here: https://github.com/cryptonomex/graphene-ui/blob/react-stockcharts/web/app/components/Exchange/PriceChartD3.jsx

**Comment by rrag** [comment]
can you show this somewhere? I recall having this issue long ago if I remember right, it was a missing close tag somewhere.

If you can recreate this on a plunker or a github page, I will look at what is going on

**Comment by svk31** [comment]
Thanks for the quick reply. I was able to reproduce it in a Plunkr here:

http://plnkr.co/edit/DLRdnckgY4B09K5QRJ2W?p=preview

**Comment by rrag** [comment]
this is silly :)

move `<TooltipContainer>` to the next line

**Comment by svk31** [comment]
Haha I just noticed that as well!

**Comment by rrag** [comment]
since you are working on a dark background, check out http://plnkr.co/edit/gist:23dd469fe32d7fc1977c?p=preview

**Comment by svk31** [comment]
Thanks :)
