### ISSUE TITLE
Two different data sets in the same chart

### ISSUE THREAD

**Issue by apa512** [rrag/react-stockcharts#494]
I've been trying to figure out how to display two series with different data (one should include all trades and one should include a few extra interesting trades with associated tooltips), without finding much of use.

Is this at all possible?

**Comment by rrag** [comment]
There is no ready made example for your case, but it can be achieved with a custom component. You can see [this comment](https://github.com/rrag/react-stockcharts/issues/413#issuecomment-354106654)  where I explain how it could be done.
