### ISSUE TITLE
Numbers scaling issue

### ISSUE THREAD

**Issue by jaymontana** [rrag/react-stockcharts#495]
Hey Ragu, i'm loving the chart library, but I'm having an issue, how would I scale the chart to show all the numbers no matter the decimals? 
![cfb9da4967895627aa4fb2867b4d48b0](https://user-images.githubusercontent.com/19938321/37498384-fc2e256a-28b5-11e8-87f4-cedbb8d62667.png)

**Comment by rrag** [comment]
to show more decimals on the 

`YAxis` set the tickFormat to a higher precision 
```jsx
<YAxis axisAt="right" orient="right" tickFormat={format("%.2f")} />
```

however you seem to indicate to show all the decimals, so you can pass it a function 
```jsx
<YAxis axisAt="right" orient="right" tickFormat={d => String(d)} />
```
which converts a number to string

`format(...)` returns a function which takes a number and returns a string of desired formatting, so you can create your custom functions and use them

for
`MouseCoordinateY` 
```jsx
<MouseCoordinateY
    at="right"
    orient="right"
    displayFormat={format(".2f")} /* change the format function here */
/>
```
