### ISSUE TITLE
xExtents resetting zoom/padding when data is updated

### ISSUE THREAD

**Issue by Ejnot** [rrag/react-stockcharts#496]
Hi I'm having a problem with i think its the xextents that is resetting the view of the chart when data is updated if i remove xextents it will be fixed but the problem is it displays a large series of data causing the candles to be really small. Thanks!

**Comment by borovik96** [comment]
I have same problem, the resetting caused this code:
```javascript
const xExtents = [chartStart, chartEnd];
```

I think needs to save the `chartStart` and `chartEnd` in the state and update them after `drag` and `zoom` events, but i didn't find how to subscribe to them. 

@eaglus is it possible to subscribe to the `drag` and `zoom` events?

**Comment by Ejnot** [comment]
I was able to solve this by setting xextents only on the first chart receives the data. I set xextents in componentwillmount On your chart component if you notice the xextents are being set in every render. I dont know if its the best solution but it works fine.

**Comment by rrag** [comment]
You dont need to subscribe to any events to make the chart not reset. please see 
https://github.com/rrag/react-stockcharts/issues/490#issuecomment-375931938
