### ISSUE TITLE
How to use Z-Index on the charts? I'd like my volume bars to be behind the candlestick 

### ISSUE THREAD

**Issue by jaymontana** [rrag/react-stockcharts#497]
![eabdaea0cfed23fced60dc4bef24c3e4](https://user-images.githubusercontent.com/19938321/37546678-c9f0cd36-2965-11e8-8375-ed8fe452e487.png)

**Comment by rrag** [comment]
there is no `zIndex` but it is like svg, where you draw the objects which you want front after the objects you want in the back.

so

```jsx
<ChartCanvas ...>
  <Chart id="volumeChart" ...>...</Chart>
  <Chart id="mainChart" ...>...</Chart>
</ChartCanvas>
```

similarly inside a `Chart` which has say 
```
<Chart id="mainChart" ...>
  <CandlestickSeries />
  <BollingerSeries />
</Chart>
```

Bollinger band is drawn on top of the candle, if you want the order changed then change the order they are placed inside the render function
