### ISSUE TITLE
Typescript Declaration Files

### ISSUE THREAD

**Issue by drevie** [rrag/react-stockcharts#498]
Are there plans to create typescript declaration files for this project?

**Comment by rrag** [comment]
No plans now

**Comment by CodeSnooker** [comment]
I specifically started learning react (after ditching AngularJS) to use this library in my project. Being a Typescript fan, I chose the hardest part, to learn React using Typescript. Now when my project layer is ready, I found out no types files available for this library. I should have checked this earlier and should have wrote the project in JS. :cold_sweat: :tired_face:

**Comment by yhnavein** [comment]
@CodeSnooker But it's just one library. You can write typings if you want or you can just ignore types for this library (and treat it as a big `any`).
You will have types everywhere but this library :)

**Comment by suenot** [comment]
any updates? most of development right now in ts
