### ISSUE TITLE
rendering again with new data

### ISSUE THREAD

**Issue by gschrader** [rrag/react-stockcharts#5]
Once the chart is rendered the first time it won't update with new data.  I can force it by removing the child dom nodes but I'm thinking that's a hack and defeats the purpose of using react.

I've created an example to illustrate the issue [here](http://plnkr.co/edit/S5S9LFZaxjEAeCWPGeig?p=preview).

**Comment by rrag** [comment]
Thank you for the example, it puzzles me too, I will figure this out today evening

**Comment by gschrader** [comment]
Just looking at the code it looks like maybe ChartCanvas needs a componentWillReceiveProps.

**Comment by rrag** [comment]
you are right, I just pushed a fix for that into the gh-pages branch for the docs. The example you created works now after I removed the `while` loop. I will push the changes in now.

**Comment by gschrader** [comment]
Thanks for fixing this so quickly!

**Comment by rrag** [comment]
Sure thing, I have been working on 0.2 for some time and finding it hard to update the npm package since there are examples updated for that.

Are you using the npm version? I can update the same fix and push a 0.2.0-alpha to npm if you are willing to give it a test drive.

**Comment by gschrader** [comment]
Yes I'm using the npm version and would be willing to try the alpha.

**Comment by rrag** [comment]
cool, it also updates a few other defects with compare and window resize.

Most of the work is on 
- removing the dependency on the .css file and using svg attributes
- using pure react axis
- option to use canvas + svg instead of svg only

I will try to get the alpha out to npm

**Comment by gschrader** [comment]
Ok sounds good.

I just managed to figure out how to add the css using webpack, I guess I could have saved some time there :grin:

**Comment by rrag** [comment]
I published both 0.1.5 and 0.2.0-alpha-1

the docs using 0.2.0-alpha-1 code are available in

http://rrag.github.io/react-stockcharts-v0.2-alpha/

The documentation is still not updated, but you can check out `canvas` and `svg` used there. Working on updated documentation for 0.2

**Comment by gschrader** [comment]
0.1.5 works like a charm, I'll give 0.2.0 a go now.

**Comment by rrag** [comment]
if you have styling issues, look at the examples in https://github.com/rrag/react-stockcharts/tree/v0.2/docs/lib/charts

v0.2 does not use .css so all 0.1.x examples wont style properly.

**Comment by gschrader** [comment]
I think I'm part way there, I had issues with importing the axis but got that figured out.  I still have an issue with the area chart drawing, I'm not sure if it's a style thing or something else as it doesn't look like I get a path element.

**Comment by rrag** [comment]
can you create a plunker with http://rrag.github.io/react-stockcharts-v0.2-alpha/dist/react-stockcharts.js

The reason path element is not present is 0.2 uses canvas based drawing as default, svg is still used for cross hair, axis.

https://github.com/rrag/react-stockcharts/blob/v0.2/src/lib/ChartCanvas.jsx#L150&L157

I am finding canvas performing much better for pan actions, hence the change in default. I am open to feedback

**Comment by gschrader** [comment]
I'm not sure what I have wrong on the go, it works perfectly fine on plunker.

my import used to be:
`import {AreaChart, ChartCanvas, Chart, XAxis, YAxis, DataSeries, AreaSeries} from 'react-stockcharts';`

I changed it to `import ReStock from 'react-stockcharts';`
along with defining the vars as: `            var ChartCanvas = ReStock.ChartCanvas
                    , XAxis = ReStock.axes.XAxis
                    , YAxis = ReStock.axes.YAxis
                    , AreaSeries = ReStock.AreaSeries
                    , Chart = ReStock.Chart
                    , DataSeries = ReStock.DataSeries;
`
The axis show up but no area chart, no error in the console.

**Comment by rrag** [comment]
I will update the docs with 0.2 code and also update a few of the examples on gist to use the 0.2 version. I did change `XAxis` and `YAxis` to go inside `ReStock.axes.` probably should have continued to reference it from `ReStock`. Let me know if I can help help with anything.

**Comment by rrag** [comment]
@gschrader were you able to figure it out. I got another version out and have a plunker http://plnkr.co/edit/gist:f7d18bd9a88b97aa069f?p=preview based on that. May be this will help

**Comment by gschrader** [comment]
sorry @rrag, I had other things get in the way.  I'll try to get back to this soon.

**Comment by gschrader** [comment]
I finally got back to this and was able to get 0.2.5 working successfully.  I did have to use the import syntax above for my ES6 code so that might be worth mentioning somewhere in the docs.
