### ISSUE TITLE
Feature request : Tooltip describing data point nearest to the mouse (MouseCoordinates)

### ISSUE THREAD

**Issue by Pinxie** [rrag/react-stockcharts#50]
As I can have several Y axis, I want the user to be able to know the X and Y values of the point nearest to his mouse. For this : 
- the cursor should be Y magnetized (in addition to X magnetized) so the cursor is automatically "snapped" to the nearest data point.
- Thus, the Y value displayed is one of a point, not the mouse's Y position (especially interesting when there are several Y axes, it shall display only the point's Y value)
- The tooltip shall be located near the mouse cursor (giving X and Y value of the point, plus a description).

Here are some screenies of what I partially did in my fork repo, and a chart which can display this is http://localhost:8090/documentation.html#/edge_coordinate 
![tooltiphighest](https://cloud.githubusercontent.com/assets/15984761/12652428/12106652-c5eb-11e5-87d0-19533711773d.png)
![tooltiplowest](https://cloud.githubusercontent.com/assets/15984761/12652432/138220ca-c5eb-11e5-8420-dbaf78162580.png)
As you can see here, the pink curve is related to JCVD axis, and the blue points are related to Theodorus

**Comment by rrag** [comment]
Instead of the cross hair snapping to the y, I was thinking of an in-place tooltip, like [this](http://www.highcharts.com/demo/line-basic). This will be a new tooltip component `InPlaceTooltip` and anyone can use this along with or as a replacement of `MouseCoordinate`.

**Comment by Pinxie** [comment]
Oh yes that would be great, that's exactly what I would need. Adding an optional callback when a tooltip is requested ( `tooltipRequested` )on a data point would be great too (to specify its text content). 

One problem I have with what I have done with my modifying of MouseCoordinates is that no matter how close the mouse pointer is from a point, it has to be the closest X-wise first, then Y-wise, so the user experience in some cases can be a real pain (try "tooltiping" the third orange data point in your example, here it's not an issue because the Y axis is the same).

To avoid this problem of point, it might be nice to be able to specify which curve (or, at least, Chart) is "tooltipable" or not.

**Comment by rrag** [comment]
Work in progress version [here](http://rrag.github.io/react-stockcharts-next/documentation.html#/hover_tooltip)

**Comment by Svjard** [comment]
Excellent work! Been hoping to see hover tooltip at some point.

**Comment by rrag** [comment]
fixed, published in 0.5
