### ISSUE TITLE
How to get most left, right visible values from XAxis?

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#500]
Hey, I have a question. I couldn't find it anywhere in the docs.

How can I get the most left and right values from the displayed XAxis? Is there a prop I can read? A method to call on ref? Thank you!

**Comment by rrag** [comment]
```jsx
<ChartCanvas ref={node => { this.chartCanvasNode = node} ...
```

```
const { xAccessor, plotData } = this.chartCanvasNode.getDataInfo()
// plotData this is the array of elements currently visible
xAccessor(_.head(plotData)) // x value of the left most candle
xAccessor(_.last(plotData)) // x value of the right most candle
```

**Comment by cbrwizard** [comment]
This can be helpful when we want to get the data about the most left/right visible chart element like a trade candle. But I actually need to know what are the most left/right visible values on the XAxis itself, like which time is actually displayed so that I can fetch up the chart data for that time. How can I do that?

**Comment by cbrwizard** [comment]
Turned out I should use `onLoadMore` callback on `ChartCanvas`. It will run just as needed, passing the time arguments inside. Check this example https://rrag.github.io/react-stockcharts/documentation.html#/load_more_data_on_pan
