### ISSUE TITLE
On Balance Volume

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#501]
Greetings and thx for this awesome library.

I'm wondering, is the OBV indicator available? 
If not, what's the recommended way to adding it?

Thank you

**Comment by rrag** [comment]
OBV is not available, You could refer to any of the existing indicators

According to
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:on_balance_volume_obv

it is a line, so if you have the math figured out and available a simple `LineSeries` can draw this
