### ISSUE TITLE
RSI dashed top/bottom

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#502]
I see that the default RSI is using a `StraightLine` for the overbought/oversold levels.
Is there any way to make this into a dashed line (or any of the other types of lines) without having to edit the `RSISeries` source code?

**Comment by rrag** [comment]
> without having to edit the RSISeries source code?

No
Feel free to make a PR with the change

**Comment by rrag** [comment]
This feature is added in 0.7.3

**Comment by andyperisho** [comment]
Awesome, I saw that. Thx.
