### ISSUE TITLE
Add support for the `lineStroke` function in an `EdgeIndicator`

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#509]
Heya, I have another feature request =]

Please add a support for the `lineStroke` function in an `EdgeIndicator` so that it works the same way as a `stroke` prop. I need the line's color to be different depending on whether the price on the candle chart went up or down, same way as the edge's tag changes its color in this example https://rrag.github.io/react-stockcharts/documentation.html#/edge_coordinate

**Comment by rrag** [comment]
I think you can fix that by adding
```
lineStroke: functor(lineStroke)(item),
```
in

https://github.com/rrag/react-stockcharts/blob/master/src/lib/coordinates/EdgeIndicator.js#L148

and changing the `EdgeIndicator.propTypes` definition of `lineStroke`

Let me know how it goes. Please send a PR if that works out
