### ISSUE TITLE
Failed prop type: The prop `stroke.outsideThreshold` is marked as required in `RSISeries`, but its value is `undefined`.

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#510]
Heya. This is probably minor, but it outputs to the console:

```
Warning: Failed prop type: The prop `stroke.outsideThreshold` is marked as required in `RSISeries`, but its value is `undefined`.
    in RSISeries (at index.js:255)
    in CandleStickChart (created by fitWidth(CandleStickChart))
    in fitWidth(CandleStickChart) (at index.js:55)
    in div (at index.js:53)
```

What to do here?

**Comment by rrag** [comment]
That is correct, look at the [defaultProps](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/RSISeries.js#L181-L182)

now rsi series is made up of 2 colors, I left the `line` stroke there so users can change it.
