### ISSUE TITLE
How to fill an Area chart with the gradient?

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#511]
Heya, another question/feature request!
How can I fill an Area chart with a gradient? I've figured it might be possible to hack it when the chart is in svg mode, but how to do it when it's canvas?

**Comment by rrag** [comment]
canvas gradient is setting a new attribute like `ctx.fillStyle`

Right now there is no support, I would like to add it, but it seems it would be breaking some of the consistencies the library enjoys between svg and canvas.

I would like to hear some ideas which maintain reasonable consistency between svg and canvas mode

**Comment by rrag** [comment]
added gradient example in http://rrag.github.io/react-stockcharts/documentation.html#/area_chart
