### ISSUE TITLE
Unable to add Point & Figure chart

### ISSUE THREAD

**Issue by QRMarketing** [rrag/react-stockcharts#513]
I would like to reopen a potential issue on the Point & Figure chart. Please see the following comments I put on an existing bug that was closed and feel should possibly be reopened:

https://github.com/rrag/react-stockcharts/issues/302

**Comment by rrag** [comment]
This is likely due to the box size not being met, reduce the box size.

I have not investigated into deriving the box size automatically, that is the best solution for this. Most trading charts do this.
