### ISSUE TITLE
zoom in/out  issue 

### ISSUE THREAD

**Issue by Suprit-S-M** [rrag/react-stockcharts#515]
I am controlling the zoom like below ,

<ChartCanvas
  xExtents={[xAccessor(leftmost bar i want to see), xAccessor(right most bar )]}
  ...
>

and its setting the zoom level as expected  but when I try to zoom in/out or reset nothing works . Its behaviour is kind of static . Could you please help me to solve this issue .  
Thank you,

**Comment by rrag** [comment]
could you try to 

```jsx
componentWill/DidMount or some other method() {
  this.setState({
    xExtents: [xAccessor(leftmost bar i want to see), xAccessor(right most bar )]
  })
}
render() {
  return (
    <ChartCanvase xExtents={this.state.xExtents} ...
  )
}
```

by doing `xExtents={[a, b]}` xExtents is a new array every time the render function is called.

**Comment by Suprit-S-M** [comment]
Yeah  will try that , Thank you

**Comment by Suprit-S-M** [comment]
Yeah it works , thank you .
