### ISSUE TITLE
Issue with Pinch-To-Zoom

### ISSUE THREAD

**Issue by Juttaro** [rrag/react-stockcharts#517]
Hey, I am having an issue with pinch to zoom on mobile. This might just be an issue related to codesandbox. I have been testing some ideas about what I want my charts to look like with the codesandbox examples from react-stockcharts-examples2 and I noticed that none of the examples pinch to zoom functionality actually work on sandbox on mobile browser. The odd part is when I look at examples that @rrag has posted on bl.ocks.org the pinch zoom works perfectly. yet in some of his bl.ocks examples he doesn't specify zoom anywhere. I am unsure if it has something to do with sandbox, the version of the package that is being used or the babel transpile in the html. 

For example this is what I have been working with (full sandbox:  https://codesandbox.io/s/2w3l9m58lr) (display: https://2w3l9m58lr.codesandbox.io/) and I have updated all the dependencies in the sandbox. Panning works okay although it will zoom when I pan to the right if I am already at the maximum x-axis value.

here is the blocks example @rrag posted it works perfect on mobile, aside from it not clamping, I want it to function identical to this one https://bl.ocks.org/rrag/b944f7ef22a42956198d3384c05f1777 .

**Comment by rrag** [comment]
You are correct pinch zoom is broken, let me check it out.
