### ISSUE TITLE
Candle-ticks chart breaks after update from 0.7 to 0.7.4

### ISSUE THREAD

**Issue by borovik96** [rrag/react-stockcharts#518]
I have next data:
```javascript
  data: [
    {
      date: 1522251000000,
      open: '0.0001',
      close: '0.0001',
      high: '0.0001',
      low: '0.0001',
      volume: '0.02'
    },
    {
      date: 1522252500000,
      open: '0.0001',
      close: '0.0001',
      high: '0.0001',
      low: '0.0001',
      volume: '0.02'
    },
    {
      date: 1522253100000,
      open: '0.0001',
      close: '0.0002',
      high: '0.0002',
      low: '0.0001',
      volume: '0.14'
    }
  ]
}
```

Chart before update:
![image](https://user-images.githubusercontent.com/9018702/38044023-43a27f80-32c1-11e8-9850-04964f9c5d23.png)

Chart after update:
![image](https://user-images.githubusercontent.com/9018702/38044101-7c5405f6-32c1-11e8-9f8b-c5b4253490d1.png)

I use `react@16.2.0`

**Comment by rrag** [comment]
could this be the same as https://github.com/rrag/react-stockcharts/issues/519 ?

are you using `timeIntervalBarWidth` for the `CandlestickSeries` ?

**Comment by borovik96** [comment]
I use `CandlestickSeries`

```jsx
<CandlestickSeries
 fill={d =>
  d.close > d.open ? "rgba(14,153,95, 1)" : "rgba(255,52,52, 1)"
 }
 wickStroke={d =>
  d.close > d.open ? "rgba(14,153,95, 1)" : "rgba(255,52,52, 1)"
 }
/>
```

**Comment by rrag** [comment]
> doesn't with `width={timeIntervalBarWidth(utcMinute)}`

I assume it is a 1min candle you were showing?

**Comment by borovik96** [comment]
Hm, no, my really data interval is 5 minutes

**Comment by rrag** [comment]
can you try with

`width={timeIntervalBarWidth(utcMinute.every(5))}`

I assume this would work ok,

**Comment by rrag** [comment]
last option 

create a new function on your side

```js
export function customBarWidth(props, moreProps) {
	const { widthRatio = 0.8 } = props;
	const { xScale, xAccessor, plotData } = moreProps;

	const width = Math.abs(
		(xScale(xAccessor(last(plotData))) - xScale(xAccessor(head(plotData)))) / (plotData.length - 1)
	);
	return width * widthRatio;
}
```

 and use it like

```jsx
<CandlestickSeries width={customBarWidth} />
```

**Comment by borovik96** [comment]
Thanks for help, I'll try and will text here about results

**Comment by borovik96** [comment]
It works fine with `width={timeIntervalBarWidth(utcMinute.every(5))}`. Thank you
