### ISSUE TITLE
Great library, But any better document?

### ISSUE THREAD

**Issue by JoeHetfield** [rrag/react-stockcharts#522]
Thanks for the wonderful library!! 

I read all the document list here: https://rrag.github.io/react-stockcharts/documentation.html#/area_chart

But I still felt missed a lot of contents -- for example the fitWidth HOC, tons of props of the components. 

Is there any better document or wiki out there? or I have to go through the source code ...

**Comment by rrag** [comment]
Detailed documentation for every component is not, looking at the propTypes and defaultProps is the best solution at this time.
