### ISSUE TITLE
ScatterSeries -> markerProps > stroke when passed a function always draws in black color

### ISSUE THREAD

**Issue by michaelr524** [rrag/react-stockcharts#523]
Passing a string value with a hex color code works fine. But when I'm passing a function that returns the same hex color string it always draws the marker stroke in black color.

**Comment by rrag** [comment]
`fill` and `stroke` on the `CircleMarker, SquareMarker` accepts only a string, in the `TriangleMarker` it  accepts a function or string.

Welcome a PR to make this consistent
