### ISSUE TITLE
How to change the bar color of the MACD series depending on the positive/negative value?

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#524]
Heya, I want to change the color of the bars on the MACD series depending on whether it's below or above the signal line.

Here is what I need: 
<img width="1083" alt="screen shot 2018-04-04 at 11 49 12" src="https://user-images.githubusercontent.com/1615659/38297804-3a1715d8-37fe-11e8-8789-172774e8b2e1.png">

Is there a way to do this?

**Comment by cbrwizard** [comment]
Ok, I've found it myself. You need to specify a function to fill.divergence:
```
    divergence: d => {
      if (d.macd.divergence > 0) {
        return BID_COLOR
      }
      return ASK_COLOR
    },
```

The only issue now is that I get a warning `Warning: Failed prop type: Invalid prop `fill.divergence` of type `function` supplied to `MACDSeries`, expected `string`.`

**Comment by rrag** [comment]
Great, appreciate a PR to change the propType validation
