### ISSUE TITLE
Please add support for making the bars in the macd chart wider

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#525]
Hey, I need to have the bars wider on the macd chart.

What I have:
<img width="931" alt="screen shot 2018-04-04 at 12 05 25" src="https://user-images.githubusercontent.com/1615659/38298634-960f35b2-3800-11e8-885f-0047eea81afd.png">

What I need to have:

<img width="1083" alt="screen shot 2018-04-04 at 11 49 12" src="https://user-images.githubusercontent.com/1615659/38298602-80c613ba-3800-11e8-8277-c6f592c71f80.png">

I suppose for that I need to be able to pass `widthRatio` to the `MACDSeries` so it passes it to the `BarSeries`, am I right?

**Comment by rrag** [comment]
`MACDSeries` does not take a `width` prop, it has to be changed to take a configurable `width` and `widthRatio` prop which will be passed down to the `BarSeries`

It would be great if you can send a PR for this
