### ISSUE TITLE
Create a method to trigger drawing a trendline programmatically.

### ISSUE THREAD

**Issue by stormnmos** [rrag/react-stockcharts#527]
Hi! 

I want to be able to start a new trendline when a previous trendline is completed, so I can make a multipoint trendline, like below.

<img width="1167" alt="screen shot 2018-04-10 at 7 52 54 pm" src="https://user-images.githubusercontent.com/817126/38571539-7291195e-3cf9-11e8-8847-7159a57f39f5.png">

**Comment by rrag** [comment]
Nice feature, but why only programmatically?

similar to the other interactive components
this new component should listen to clicks and draw a line.
and also draw a line when the different vertices are passed in
