### ISSUE TITLE
Can't pan on firefox

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#528]
I'm on Arch linux using the magic mouse.
On Vivaldi or Chrome I can pan and zoom without any problem.
On Firefox, I can zoom, but panning is super slow. 
I tried this on multiple examples from the demos and ready to use code with the same result.

Any idea what might be causing the problem?

**Comment by rrag** [comment]
I am not able to reproduce this problem. I use manjaro linux (which is based on arch) for development and firefox works ok.

I also do not have the magic mouse or a plain arch linux based computer to test this
