### ISSUE TITLE
Areaseries Maximum data always on center?

### ISSUE THREAD

**Issue by Ejnot** [rrag/react-stockcharts#529]
![image](https://user-images.githubusercontent.com/25398663/38608290-863756ee-3dad-11e8-9f5e-4afe50c95a4e.png)

So i have successfully made this orderbook chart using area series and added curvestepbefore as interpolation.

The problem in here is this
![image](https://user-images.githubusercontent.com/25398663/38608123-1be29a92-3dad-11e8-9eb3-08cc298fbd95.png)

when the orderbook bid, asks is unbalance it will result it asks taking over the whole chart is it possible to keep the asks always at the middle of the chart?

Sorry if my explanation is bad.
But basically i need the areaseries to always meet at the center. right now in extents im just using first, and last of the data.

**Comment by rrag** [comment]
you need to adjust the data to keep the spread at the center. This is not a feature of the library

**Comment by aguidis** [comment]
@Thurstonjhon hello, I'm facing the same issue than you. Did you find any workaround ? Could you share your code so we can help each other ?
