### ISSUE TITLE
how to mark  candlesticks  bar just as "EdgeIndicator"

### ISSUE THREAD

**Issue by mymickey** [rrag/react-stockcharts#530]
first thanks this a great lib;
I need mark  data use highest and lowest the value in "current viewport" , just as EdgeIndicator mark, follow user zoom viewport ,mark last the data
```
<EdgeIndicator
 itemType="last"
 orient="right" 
edgeAt="right"
yAccessor={d => d.close} fill={d => d.close > d.open ? "#6BA583" : "#FF0000"}/>


```

maybe this code?

```
<EdgeIndicator
 itemType="low"
 orient="candle-bar" 
edgeAt="candle-bar"
yAccessor={d => d.low} />
```

just as this

![image](https://user-images.githubusercontent.com/572102/38619177-2ec95e0e-3dce-11e8-940c-a5740d8a3b03.png)

i can not find in [https://github.com/rrag/react-stockcharts-examples2](examples2) about mark the demo

**Comment by rrag** [comment]
try with [this](http://rrag.github.io/react-stockcharts/documentation.html#/ma_crossover_using_svg_shape) example
