### ISSUE TITLE
Mousewheel zooming doesn't respond most of the time

### ISSUE THREAD

**Issue by brentd** [rrag/react-stockcharts#531]
Zooming works great with a trackpad, but zooming often doesn't occur when scrolling with the mouse.

It appears to be the trackpad two-finger panning logic that's interfering. Commenting out the conditional so only `onZoom` is called gives correct behavior with the mousewheel, but then two-finger panning no longer works on a trackpad.

https://github.com/rrag/react-stockcharts/blob/master/src/lib/EventCapture.js#L115-L149

**Comment by rrag** [comment]
2 finger swipe to pan is a good feature, I dont see that going away
