### ISSUE TITLE
Force Index calculator returns "NaN"

### ISSUE THREAD

**Issue by Rangarajan0603** [rrag/react-stockcharts#532]
`import {forceIndex} from "react-stockcharts/lib/indicator";`

```
const fiCalc = forceIndex()
            .merge((d, c) =>
            {
                d.fi = c;
            })
            .accessor(d => d.fi);
```

This function adds `NaN` to the input data instead of values and so `Warning: Received NaN for the `height` attribute`  error occurs when trying to use force index indicator.

**Comment by rrag** [comment]
could you add a codesandbox with the problem. I am not able to get this in svg mode in http://rrag.github.io/react-stockcharts/documentation.html#/forceindex
