### ISSUE TITLE
CandlestickSeries chart is hidden on very big zoom out

### ISSUE THREAD

**Issue by borovik96** [rrag/react-stockcharts#533]
Is it normal that `CandlestickSeries` chart is hidden on very big zoom out?
I have next screenshots, every next screenshot have zoom smaller than previous. On the last screen `CandlestickSeries` is disappeared.

![screenshot from 2018-04-17 13-11-24](https://user-images.githubusercontent.com/9018702/38863878-a5374df4-4241-11e8-81af-8dd7586464d0.png)
![screenshot from 2018-04-17 13-11-50](https://user-images.githubusercontent.com/9018702/38863881-a81ff6b0-4241-11e8-9d68-ece899346cc9.png)
![screenshot from 2018-04-17 13-12-03](https://user-images.githubusercontent.com/9018702/38863885-a9e149cc-4241-11e8-956a-b171dd4d242c.png)

**Comment by rrag** [comment]
is the open/high/low/close the same value, and when you zoom out so much
you expect to see a candle of  1px / 1px ?

**Comment by borovik96** [comment]
Good point, i think i need to fetch data with bigger interval on big zoom out. Thanks you
