### ISSUE TITLE
Folder structure is different when linking react-stockcharts locally

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#535]
Hey, I have an issue with running react-stockcharts locally from another project using `yarn link`. The problem is that old imports don't work anymore, as the folder structure is different.

An example error: 
```
Module not found: Can't resolve 'react-stockcharts/lib/annotation' in '/Users/cbrwizard/apps/mothership/exchange/client/src/components/base/ChartIndicator'
```

Folder structure of react-stockcharts when running `yarn link`:
<img width="282" alt="screen shot 2018-04-23 at 11 36 39" src="https://user-images.githubusercontent.com/1615659/39115536-a111d76e-46ea-11e8-8a20-b7249c44bb11.png">

Folder structure of react-stockchars when installing it from remote npm:
<img width="238" alt="screen shot 2018-04-23 at 11 29 33" src="https://user-images.githubusercontent.com/1615659/39115247-d3eb6516-46e9-11e8-918e-20e095d61a96.png">

I've ran `npm run watch`, as specified in https://github.com/rrag/react-stockcharts/blob/master/CONTRIBUTING.md, but it didn't help with this.

I believe I need to properly compile the files and maybe change the paths? What should I do? Thank you!

**Comment by rrag** [comment]
This is my suggestion, not sure if there is a better way, try it out

```sh
$ cd react-stockcharts
$ npm run clean
$ npm run babel:cjs:watch
```

in another terminal window

```sh
$ cd /path/to/your/project
$ npm link /path/to/react-stockcharts/build # use npm link not yarn link
$ # start your webpack in watch mode
```

now any change inside `/path/to/react-stockcharts` will trigger a file change event in your webpack

let me know if you have any trouble
