### ISSUE TITLE
Chart gets resetted when the browser's window size is changed

### ISSUE THREAD

**Issue by dklodner** [rrag/react-stockcharts#540]
Hi rrag, chart gets resetted when the browser's window size is changed. Is it by design? Because there's also an inconsistency of this behavior between your two examples, 
- http://rrag.github.io/react-stockcharts/
- https://demo.reactstockcharts.org/

Am I missing a property settings?

**Comment by dklodner** [comment]
The problem was in : ChartContainer = fitWidth(ChartContainer);

**Comment by khaphannm** [comment]
Hi @dklodner I had the same issue as yours. Did u have any solution for that? Any help would be appreciated
