### ISSUE TITLE
Allow adding an arrow to the MouseCoordinateX

### ISSUE THREAD

**Issue by cbrwizard** [rrag/react-stockcharts#542]
Hey, I need to have an arrow displayed where the line meets X axis on MouseCoordinateX, like here:

![image_preview 1](https://user-images.githubusercontent.com/1615659/39182006-081825b0-47c4-11e8-8ab5-a8bfda04d36f.png)

How can I do that? Thank you!

**Comment by cbrwizard** [comment]
Also, it would be great to have an option to add padding inside the rectangle so that there is more space between borders and the text

**Comment by rrag** [comment]
done, available in - http://rrag.github.io/react-stockcharts/documentation.html#/interactive_y_coordinate
