### ISSUE TITLE
VolumeProfile broken

### ISSUE THREAD

**Issue by ghost** [rrag/react-stockcharts#544]
I noticed the the `Volume Profile` on the demo2 is not working. Clicking on it, nothing happens.

Also, when using `VolumeProfileSeries` on my own code, I noticed that only the `down` show up, but not the `up`. Where's the bug?

I noticed that the default `absoluteChange` method  is:
```
    absoluteChange: d => d.absoluteChange,
```

Does it mean that it's up to the user to supply an absoluteChange method? If so, what is does it have to be?

Picture attached.
![1525280373](https://user-images.githubusercontent.com/34944098/39537813-e5013452-4e64-11e8-9a14-4244d0855dc6.png)

**Comment by rrag** [comment]
I am taking down the demo. Thank you for informing the problem I have fixed it on other places where I have used the demo for
