### ISSUE TITLE
Flat Top/Bottom 

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#546]
Is it possible to create a flat top/bottom drawing that looks like this:

![1525412186](https://user-images.githubusercontent.com/34944098/39614160-d4ca0de6-4f97-11e8-9967-2b87032cf166.png)

If it's not currently possible with the library, then how hard is it to create it given that there is currently only a parallel channel?

**Comment by rrag** [comment]
No plans to add this for now
