### ISSUE TITLE
Binary Bundle?

### ISSUE THREAD

**Issue by andyperisho** [rrag/react-stockcharts#550]
Is it possible to include this library in the `index.html` file instead of importing it in the code?
I'm hoping that by doing so, I will release some of the resources spent during dev to import the library at every single build.

Would a binary help me achieve my goal?
If yes, how can I create such a bin?

**Comment by rrag** [comment]
not creating a bundle starting 0.7, only available via npm. you will have to create a bundle yourself using webpack/rollup
