### ISSUE TITLE
Moving Average is not working 

### ISSUE THREAD

**Issue by Suprit-S-M** [rrag/react-stockcharts#552]
I am displaying an chart time vs price and vol where I am trying to create Moving Average chart using react-stockchart but it's not working. Can you please help me. 
This how my data series look like 
data=[{"day":2018-07-24,"vol":0.3,"price":3},{"day":2018-08-27,"vol":2,"price":5},....]

**Comment by rrag** [comment]
there are many examples of moving average. Please provide a codesandbox to replicate the problem.
