### ISSUE TITLE
Veritcal colored bands

### ISSUE THREAD

**Issue by electic** [rrag/react-stockcharts#553]
First off, great component. I have a question regarding the ability to add bands like this:

<img width="1185" alt="screen shot 2018-05-09 at 2 20 44 pm" src="https://user-images.githubusercontent.com/43028/39840479-672e1dbc-5394-11e8-8018-9815778133ea.png">

Is this something that is possible? I can't seem to find any reference to how to do this in the documentation or past issues.

**Comment by rrag** [comment]
not possible right now, you might have to implement a custom version of the `XAxis` component

**Comment by electic** [comment]
Thank you @rrag!

**Comment by hoangviet-98** [comment]
can you give me the code <3

> First off, great component. I have a question regarding the ability to add bands like this:
> 
> <img alt="screen shot 2018-05-09 at 2 20 44 pm" width="1185" src="https://user-images.githubusercontent.com/43028/39840479-672e1dbc-5394-11e8-8018-9815778133ea.png">
> 
> Is this something that is possible? I can't seem to find any reference to how to do this in the documentation or past issues.
