### ISSUE TITLE
Props `tickInterval` and `loadMore` are not friends

### ISSUE THREAD

**Issue by AlimovSV** [rrag/react-stockcharts#554]
Example: https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartPanToLoadMore

1) remove showTicks={false} outerTickSize={0}
2) add tickInterval={50}
3) scroll the chart to load more items

![stockcharts](https://user-images.githubusercontent.com/4921904/39910517-b97e0c38-5508-11e8-98c1-ee7847f443c0.png)

**Comment by rrag** [comment]
Happy to take a PR as a fix
