### ISSUE TITLE
xScale in different timezone

### ISSUE THREAD

**Issue by diegolacarta** [rrag/react-stockcharts#558]
Hi, is there any way to render xAxis with a scale in a different timezone?

I can convert the labels with `tickFormat`, but I'd like to still only render "round" times (like 00:00, 12:00) regardless of the timezone.

**Comment by rrag** [comment]
Feels like a d3 scale question

> but I'd like to still only render "round" times (like 00:00, 12:00) regardless of the timezone.

the `ticks` are provided by d3 scale, so you probably want to send the `tickValues` attribute with the desired ticks you want to show
