### ISSUE TITLE
Multiple Series in one Chart 

### ISSUE THREAD

**Issue by FaBeyyy** [rrag/react-stockcharts#559]
I have a few different Charts I need to display, that have different xAccessor values (different but sometimes overlapping dates) and are preferably in a different data array.

The problem I am facing right now is, that the xAccessor and data are both bound to the ChartCanvas component and not the Chart, so I cannot simply create another chart or series inside the same canvas.

Anyone any idea on how to get this done?

**Comment by rrag** [comment]
Not possible right now, you have to interpolate with another series this comment might help you

https://github.com/rrag/react-stockcharts/issues/413#issuecomment-354106654

but I dont have any examples to share
