### ISSUE TITLE
Feature request / help needed : Setting a gap between ticks for Y

### ISSUE THREAD

**Issue by Pinxie** [rrag/react-stockcharts#56]
I would like to put any gap I want for Y ticks. Here is an example with a 42 gap :

![gapyaxis](https://cloud.githubusercontent.com/assets/15984761/12724553/b5f25f52-c90e-11e5-9770-7c76f7c69bff.png)

I managed to do this but I'm not happy with how I have done it and it leads to bugs, particulary with zooming. What I did is that, when rendering, I get the previous domain for the Y axis (which I know is the root of the problem):

`let yScale = self.refs[myChartRef].yScale();`

get Min / max value: 

`let top = yScale.domain()[1];`
`let bottom = yScale.domain()[0];`

then, the short of it, is that I construct an array of values for my ticks, feeding them to YAxis tickValues.

Of course, when zooming and resetting zoom, it doesn't work, because the domain is limited to the chart when it was zoomed. The problem is that I can't predict the bottom / top values inside render() function (I guess browsing all my data points would be really overkill just for this)

I was thinking to make a callback to setState which would get the yScale domain, then setState with the correct top & bottom values. Is that the correct approach?

**Comment by Pinxie** [comment]
Well that seems to do it, simply doing a callback on setState which update the Y tickValues (which belong to state) when adding / removing points, and using my state' tickValues on YAxis.

**Comment by rrag** [comment]
in 0.4, there will be a `yTicks={...}` in the `Chart`.
`yTicks` would accept either an array or a `function(domain, plotData) { /* calculate ticks */ return [tick1, tick2]; }`

The function seems to solve your problem natively, no?

**Comment by rrag** [comment]
sorry. I take it back I like your solution better.

how about changing the `ticks` on XAxis and YAxis to accept a function or array?

**Comment by Pinxie** [comment]
Yes, a props of XAxis / YAxis that, given the domain, would return all the ticks would be enough. 
I don't know about changing the `ticks` signature though,  even if d3 doesn't always obey you when specifying  a precise tick number, the users might not want to bother ?

**Comment by rrag** [comment]
yeah not `ticks` I meant to say `tickValues` edited the comment after
