### ISSUE TITLE
Retrieve data showed on xAxis

### ISSUE THREAD

**Issue by ruffo92** [rrag/react-stockcharts#562]
How can i retreive the value on the xAxis of the currently showed chart?
I need to store the interval of the currently showed chart to make some operations with them.
![image](https://user-images.githubusercontent.com/11821779/40185474-f7b2d080-59f2-11e8-9478-339f16917ffc.png)
Example of the desired data based on the image
intervals=[6900, 6950, 7000, 7050, ... , 7400]

Thank you in advance

**Comment by rrag** [comment]
Not possible from the `YAxis` but you can use the `d3.scaleLinear` to get the ticks yourself.
