### ISSUE TITLE
Library is not displaying line(any) chart

### ISSUE THREAD

**Issue by Suprit-S-M** [rrag/react-stockcharts#565]
I have below data series and  am trying to display two line charts but its not working . Can you please tell whether this kind of series works or not.

data =[
			{"sk":"001","v_u18-u18":10},
			{"sk":"001","v_n18-n18":80},
			{"sk":"05","v_u18-u18":20},
			{"sk":"05","v_n18-n18":100},
			{"sk":"001","v_u18-u18":30},
			{"sk":"001","v_n18-n18":150},
			{"sk":"05","v_u18-u18":40},
			{"sk":"05","v_n18-n18":200}
		]

**Comment by rrag** [comment]
There are many examples showing how to draw `LineSeries` please follow them
