### ISSUE TITLE
[CSP Support] Injecting a <style> tag breaks CSP style rule

### ISSUE THREAD

**Issue by mpsq** [rrag/react-stockcharts#566]
The `<style>` tag injected in:

https://github.com/rrag/react-stockcharts/blob/e0ef22ba255113e19ff3bd527899e51ece2a1b32/src/lib/ChartCanvas.js#L51

Does not support the nonce attribute, therefore it breaks the [style-src rule](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src). This library forces the user to set the CSP rule to `'unsafe-inline'` which is not ideal.

Solutions:
I.
Checking if a script / style tag already exists, get the nonce (if any) and inject the style tag with the nonce. Something like:

```javascript
const { nonce } = document.getElementsByTagName('style')[0] || document.getElementsByTagName('script')[0] || {};
...
return (<style nonce={nonce || ''} type="text/css">{tooltipStyle}</style>);
```

---> seems hacky but it is the way some people ([aphrodite](https://github.com/Khan/aphrodite)) solve the issue and it does not involve any changes for the users.

II.
Move the css to a .css file (update Webpack build), then the users would have to:

```javascript
import 'react-stockcharts/react-stockcharts.css'
```

---> seems to be the standard way, this is how react-table works for [example](https://github.com/react-tools/react-table#installation), however this require the users to change their code.

III.
Support the `__webpack_nonce__` variable, cf. [documentation](https://webpack.js.org/guides/csp/)

---> Best way (super clean) way to fix the issues, however this will fix the problem only for Webpack users.

My opinion (if someone cares):
Maybe we should do III. and fallback to II. if the var is not set:

```javascript
const { nonce } = __webpack_nonce__ || document.getElementsByTagName('style')[0] || document.getElementsByTagName('script')[0] || {};
...
return (<style nonce={nonce || ''} type="text/css">{tooltipStyle}</style>);
```

What do you think?

References:
[CSP on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
[Why CSP](https://scotthelme.co.uk/content-security-policy-an-introduction/)

**Comment by rrag** [comment]
Thanks for reporting.

I like option 2,

The reason I did it as style and not css file is that if we use the `saveSvgAsPng` it will not be able to read external css, so the `style` inside a svg was useful to retain the style on the png also,

But now this is not a problem anymore as all the color/width related styles are removed completely. I will work on this with the next update
