### ISSUE TITLE
Failed to minify the code from this file:   ./node_modules/save-svg-as-png/saveSvgAsPng.js:3 

### ISSUE THREAD

**Issue by sulliwane** [rrag/react-stockcharts#567]
Hello,

I'm using this package in my create-react-app, and when I run npm run build I get this error:

```
Failed to minify the code from this file: 
 	./node_modules/save-svg-as-png/saveSvgAsPng.js:3 
Read more here: http://bit.ly/2tRViJ9
```

Could you confirm this package is not ES5 compatible?
Thank you!

**Comment by sulliwane** [comment]
cross posted on the specific package page: https://github.com/exupero/saveSvgAsPng/issues/171

**Comment by igorbpf** [comment]
+1

**Comment by sulliwane** [comment]
I opened a PR https://github.com/rrag/react-stockcharts/pull/571 that fixes this problem

**Comment by rrag** [comment]
Thanks for the PR.
