### ISSUE TITLE
Help me config `chartTypeSelector` and `quickly change the period of the chart`

### ISSUE THREAD

**Issue by honeypc** [rrag/react-stockcharts#568]
I have tried finding the example to config render them but I can't make it work. May I have an example of them. Thank a lot
Eg: 
<img width="1085" alt="screen shot 2018-05-25 at 9 05 54 pm" src="https://user-images.githubusercontent.com/3039346/40548645-7c03edb6-605f-11e8-97ad-f4a5900cb8a5.png">
<img width="1402" alt="screen shot 2018-05-25 at 9 06 01 pm" src="https://user-images.githubusercontent.com/3039346/40548649-7e03b0c4-605f-11e8-9b83-8c358e33fccb.png">

**Comment by rrag** [comment]
Demo v2 is close source sorry I cannot share it
