### ISSUE TITLE
Candlestick outline

### ISSUE THREAD

**Issue by XmelesX** [rrag/react-stockcharts#57]
react-stockcharts(zooming) /re upload/:
![no_zoom](https://cloud.githubusercontent.com/assets/16750139/12855613/84f927d2-cc51-11e5-8ae5-eb5c7f4a9025.png)

Example chart(zooming):
![examle_chart](https://cloud.githubusercontent.com/assets/16750139/12848284/f6f5590a-cc29-11e5-8ea8-c39e52897d01.png)

**Comment by rrag** [comment]
how did you get the first image? I dont see that behavior when I zoom

**Comment by XmelesX** [comment]
The first it only image zoom, not chart zooming.
I want to get a black frame around the body of the candlestick. Like second chart.

**Comment by XmelesX** [comment]
Add **stroke** array on **CandlestickSeries**
`<CandlestickSeries stroke={{ up: "#000000", down: "#000000" }}/>`
work only on SVG (need canvas+svg)
example:
![svg](https://cloud.githubusercontent.com/assets/16750139/12857769/17003692-cc5d-11e5-9fd1-8e5a220d3bb2.png)

**Comment by rrag** [comment]
I will change both `fill` and `stroke` to accept a function or string like 

https://github.com/rrag/react-stockcharts/blob/next/src/lib/series/HistogramSeries.jsx#L28-L30

**Comment by rrag** [comment]
in v0.4

**Comment by rrag** [comment]
still not released to npm, and all docs need updats

but code examples are updated and available
http://rrag.github.io/react-stockcharts-next/documentation.html#/brush
