### ISSUE TITLE
Trendline date(x-axis) to accept Date format value

### ISSUE THREAD

**Issue by johnreytanquinco** [rrag/react-stockcharts#572]
Im new to react, and im still trying to do a lot of research. I noticed that how the trendline is being plotted on this [chart](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithInteractiveIndicator) is: its x-axis is counted from the beginning of the candles stick data, from left to right, in this example thats `1606` and `1711` in `[1606, 56], end: [1711, 53]`. And when I tried to use timestamp format, say with value `1527815142480`, of course it wont display on chart. How can I have the trendline accepts a date format value of example `Tue May 08 2018 07:00:00 GMT+0800`. Thanks!

**Comment by rrag** [comment]
say you have
```
data = [
{ date: today 1:00am, open, high, low, close, },
{ date: today 1:01am, open, high, low, close, },
{ date: today 1:02am, open, high, low, close, },
{ date: today 1:03am, open, high, low, close, },
{ date: today 1:04am, open, high, low, close, },
{ date: today 1:05am, open, high, low, close, },
]
```

`1.00 am` candle is index 0, `1.01 am` is index 1 and so on so if you wish to draw a line between say `1.04 am` and `1.20 am` you have to derive the index values of those

I suggest you use binary search using either `lodash sortedIndex` or `d3.bisectLeft` and find the left and right items

once you have the left and right objects, `xAccessor(left), xAccessor(right)` gives you the index of left and right points.

Hope that helps

**Comment by johnreytanquinco** [comment]
Thank you so much for your response @rrag , if I have this  code in my  `Chart.js`
```
	constructor(props) {
		super(props);
		this.state = {
			enableTrendLine: false,
			trends_1: [
				{ start: [parseFloat(props.trendstartdate), parseFloat(props.trendvalue)], end: [parseFloat(props.trendenddate), parseFloat(props.trendendvalue )], appearance: { stroke: "green" }, type: "XLINE" }
			],
			trends_2: [
				{ start: [parseFloat(props.trendstartdatetwo), parseFloat(props.trendvaluetwo)], end: [parseFloat(props.trendenddatetwo), parseFloat(props.trendendvaluetwo)], appearance: { stroke: "blue" }, type: "XLINE" }
			]	
		};
```
How can I implement your answer on it? These trends accepts values from `index.js` where `trendstartdate` and other `*date` are timestamp.

**Comment by seasick** [comment]
@johnreytanquinco simplyfied it could look like the following. I didn't test it though - just copied it together from my implementation.

```js
const data = [/* containing the data with which you build the underlying chart*/];
const trends = [
  {
    start: {
      date: 1532530000,
      value: 120
    },
    end: {
      date: 1532540000,
      value: 100
    }
  }
];

this.state = {
  trend_1: trends.map((trend) => {
    const start = data.filter((d) => {
      // Could be different, depending on your data. Also possible that you are
      // working with a Date object - use `getTime()` in such a case.
      return d.date === trend.start.date;
    })[0];
    
    const end = data.filter((d) => {
      // Same here ... 
      return d.date === trend.end.date;
    })[0];
    
    return {
      start: [xAccessor(start), trend.value],
      end: [xAccessor(end), trend.value],
      appearance: {
        stroke: 'green'
      },
      type: 'LINE'
    };
  }).filter((i) => !!i) // Filter for truthy values
}
```

See one of the examples how to use/get the xAccessor - e.g. https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithInteractiveIndicator on line 179.
