### ISSUE TITLE
how to set minimum width on candle stick when only a few data points

### ISSUE THREAD

**Issue by bonede** [rrag/react-stockcharts#573]
hi there，

when there are only a few data points on candle stick chart, sticks are stretched to fit the whole width of the chart(image below). is there a way to set minimum width of sticks? 10px, e.g.

![image](https://user-images.githubusercontent.com/15994/40974793-4704ea08-68fb-11e8-92cf-179c01557d04.png)

**Comment by rrag** [comment]
there is the `width` prop in the `CandlestickSeries` which defaults to `plotDataLengthBarWidth`

you can create a copy of that function from `barWidth.js` and add the min width logic in there.
