### ISSUE TITLE
SARSeries: deformed circles

### ISSUE THREAD

**Issue by diegolacarta** [rrag/react-stockcharts#574]
![screen shot 2018-06-05 at 16 40 30](https://user-images.githubusercontent.com/6614327/41004378-45c4814c-68df-11e8-82ae-d58860da0572.png)

As shown in the image circles are drawn as ellipses. I can submit a PR if this is not intended.

**Comment by diegolacarta** [comment]
Also SAR gets hidden when moving a drawing object on the chart, can replicate both issues in: https://demo.reactstockcharts.org/

**Comment by rrag** [comment]
that is how I had it written, the width of the ellipse depends on the candle width.
I realize it is not neat. welcome a PR to make the SAR have same x and y radius.
