### ISSUE TITLE
Question: Circles on line chart

### ISSUE THREAD

**Issue by Neha3011** [rrag/react-stockcharts#575]
Is there any way i can implement https://www.highcharts.com/demo/line-basic
basically, i am looking to have a circle on each end point and also to have a style change on hover. 

I can't find any example like this in the documentation. Can you suggest how I can achieve this? 
Thanks.

**Comment by Neha3011** [comment]
Actually, i can use SactterSeries, but i still can't apply hover on the scatter circles.

**Comment by rrag** [comment]
You are correct the `ScatterSeries` does not support the hover feature yet.
