### ISSUE TITLE
mutableState.currentItem must be reset when chart resets

### ISSUE THREAD

**Issue by diegolacarta** [rrag/react-stockcharts#577]
When passing new props to `<ChartCanvas/>`, in particular new `data` and `xAccessor`, `<MouseCoordinateX/>` breaks, because it tries to calculate `x` with the new `xAccessor` on `currentItem`, which hasn't been updated, so it still has the old data format.

A viable fix would be to reset `mutableState.currentItem` when state changes in `<ChartCanvas/>` in: https://github.com/rrag/react-stockcharts/blob/e0ef22ba255113e19ff3bd527899e51ece2a1b32/src/lib/ChartCanvas.js#L965

**Comment by rrag** [comment]
Thank you

did you mean add
```
this.mutableState = {};
```
after that `resetChart`?

**Comment by diegolacarta** [comment]
Yes, for now I'm doing 
`this.chartCanvas.mutableState.currentItem = undefined`

from my app as a hack (accessing the instance through react ref),  but I think that would fix it. The bug was caused by currentItem in particular, not sure about the rest.
