### ISSUE TITLE
how to Change OHLCTooltip css

### ISSUE THREAD

**Issue by arpitprod** [rrag/react-stockcharts#578]
I want to change OHLC tooltip css completely. like this image 

![ohlctooltip image](https://user-images.githubusercontent.com/19798516/41187539-c49c56f2-6bc8-11e8-866d-6d490fc874f8.png)

Please give me direction, How to change ?

**Comment by rrag** [comment]
the `OHLCTooltip` creates an svg text  element, I don't think it can be styled the way you have showed.
you can only change colors and font sizes with css.

My suggestion is to create your own version of `MyOHLCTooltip` component with your desired text positioning

**Comment by hassantauqeer** [comment]
@arpitprod  did you change the tooltip?

**Comment by arpitprod** [comment]
@hassantauqeer yes, I tried and changed little bit but we didn't change css style yet.

**Comment by hassantauqeer** [comment]
@arpitprod Do you know how to change the tips of bars in the bar chart 
from this
![image](https://user-images.githubusercontent.com/22445984/42147380-e02b0f28-7de6-11e8-8d9b-27d6ed72aabd.png)
to ones like you've with the same color of bar
![image](https://user-images.githubusercontent.com/22445984/42147416-189a2484-7de7-11e8-90f2-5e5a1dcab5dc.png)

**Comment by hassantauqeer** [comment]
And I see there is no documentation for css and styling in [docs](http://rrag.github.io/react-stockcharts/documentation.html). Is there any? If not then how to do it?

**Comment by arpitprod** [comment]
add 'wickStroke' props in 'CandlestickSeries' like below code

`<CandlestickSeries 
        wickStroke={d => d.close > d.open ? "#6BA583" : "#FF0000"}
/>`

this is [CandlestickSeries.js](https://github.com/rrag/react-stockcharts/blob/master/src/lib/series/CandlestickSeries.js#L81) file link 

Here, you can see those props which you can handle in your code.

**Comment by hassantauqeer** [comment]
Thanks MAN
