### ISSUE TITLE
Support for large data on X-axis (overlapping)

### ISSUE THREAD

**Issue by Neha3011** [rrag/react-stockcharts#581]
Hi, i have a use case where i have very large data for bar chart. I want to add scroll but i am unable to find a solution. I tried onLoadMore, but that is not working either.

Here is the codesandbox: https://codesandbox.io/s/qk3vxoqq6j

Thank you.

**Comment by rrag** [comment]
`scalePoint` is an ordinal scale, so it has a discrete domain, and does not have an `scale.invert()` function so zoom and pan is not possible. so `onLoadMore` will never be triggered.

It is not possible with react-stockcharts to show a partial view of an ordinal scale. I suppose you could only load the data needed, but then there has to be a user action like button click external to the chart where you can load more data and show that.
