### ISSUE TITLE
How to show Fibonacci Lines for full data without select range

### ISSUE THREAD

**Issue by arpitprod** [rrag/react-stockcharts#583]
How to show Fibonacci Lines for full data without select range 
like [https://poloniex.com/exchange](url) site

![screen shot 2018-06-12 at 4 56 29 pm](https://user-images.githubusercontent.com/19798516/41287825-a6d817aa-6e61-11e8-98b2-c072d36ea39e.png)

**Comment by rrag** [comment]
use `type="EXTEND"`

https://github.com/rrag/react-stockcharts/blob/master/src/lib/interactive/FibonacciRetracement.js#L243
