### ISSUE TITLE
How to combine data updating in real time and loading more data on the pan?

### ISSUE THREAD

**Issue by alexandrkondrachuk** [rrag/react-stockcharts#586]
Hello!
You provided two separate examples:

1.  [Updating data](http://rrag.github.io/react-stockcharts/documentation.html#/updating_data)

2. [Load more data on pan](http://rrag.github.io/react-stockcharts/documentation.html#/load_more_data_on_pan)

Is it possible to combine them together? Maybe you have some examples or code snippet? I would like to update my data points in real time and have an opportunity to load more data on the pan.
## Code :
**updating data**
`;

    componentWillReceiveProps(nextProps) {
        const {data: newData} = nextProps;
        const {data: prevData} = this.state;
        const indexCalculator = discontinuousTimeScaleProviderBuilder().indexCalculator();
        const {index} = indexCalculator(newData);
        const xScaleProvider = discontinuousTimeScaleProviderBuilder()
            .withIndex(index);
        const {data: linearData, xScale, xAccessor, displayXAccessor} = xScaleProvider(newData.slice(-prevData.length));
        this.setState({
            linearData,
            data: linearData,
            xScale,
            xAccessor, displayXAccessor
        });
    }`
**load more data**
`   }

    onLoadMore = (start, end) => {
        if (Math.ceil(start) === end) return;
        const {data: prevData} = this.state;
        const {data: inputData} = this.props;

        if (inputData.length === prevData.length) return;
        const rowsToDownload = end - Math.ceil(start);
        const dataToCalculate = inputData
            .slice(-rowsToDownload - prevData.length, -prevData.length);
        const calculatedData = dataToCalculate;
        const indexCalculator = discontinuousTimeScaleProviderBuilder()
            .initialIndex(Math.ceil(start))
            .indexCalculator();
        const {index} = indexCalculator(
            calculatedData
                .slice(-rowsToDownload)
                .concat(prevData));
        const xScaleProvider = discontinuousTimeScaleProviderBuilder()
            .initialIndex(Math.ceil(start))
            .withIndex(index);
        const {data: linearData, xScale, xAccessor, displayXAccessor} = xScaleProvider(calculatedData.slice(-rowsToDownload).concat(prevData));
        this.setState({
            data: linearData,
            xScale,
            xAccessor,
            displayXAccessor,
        });
    } `
**Here is the issue that I get (Next update moves the chart to the right):**

![updating loa](https://user-images.githubusercontent.com/19354574/41347613-d5737850-6f12-11e8-8d2d-7d33ca8256ee.gif)

Hope you can help. Thanks in advance!

**Comment by jensen** [comment]
This seems more like a stackoverflow style question than an issue report.

**Comment by alexandrkondrachuk** [comment]
Thanks so much for your response!
What exactly do you propose to do? I have to ask my question on
StackOverflow or change my question style?

2018-06-14 11:36 GMT+03:00 Karl Jensen <notifications@github.com>:

**Comment by hassantauqeer** [comment]
@alexandrkondrachuk Why closed? Where  is the solution?

**Comment by alexandrkondrachuk** [comment]
Hi, @hassantauqeer ! The issue has been closed because I found a solution by my self. If you are interested in my solution here is working code snippet [https://codesandbox.io/s/k5q55018no](https://codesandbox.io/s/k5q55018no) .
