### ISSUE TITLE
How to provide buffer space to the right of candlestick series?

### ISSUE THREAD

**Issue by colorwheeloflife** [rrag/react-stockcharts#588]
Hi there

We would like to have the initialization/reset position off to the right of the most recent data point.  This is a common practice in candlestick charts as I'm sure you're well aware. 

Haven't come across anything in the docs/source code that leads me to where this can be done.

Any suggestions? 

![screen shot 2018-06-13 at 11 35 48 am](https://user-images.githubusercontent.com/10913613/41371060-1df33896-6efe-11e8-8195-73a2faec9572.png)

**Comment by jensen** [comment]
ChartCanvas has a padding property. Try 

```
padding={{
  left: 0,
  right: 100
}}
```

**Comment by roller-project** [comment]
thanks @michaelr524 .
i want update data form socket or after 60s. 
You have solution pls

**Comment by rrag** [comment]
adding a padding right will give you the space on right but that space will not be usable for future candles. I don't have any other solution other than setting `xExtents` appropriately
