### ISSUE TITLE
Undefined 'firstChild' error from v0.3.1 for Meteor with React 0.14.3

### ISSUE THREAD

**Issue by laomouzi** [rrag/react-stockcharts#59]
TypeError: Cannot read property 'firstChild' of undefined
    at Object.ReactMount.findComponentRoot (ReactMount.js:715)
    at Object.ReactMount.findReactNodeByID (ReactMount.js:679)
    at Object.getNodeFromInstance (ReactMount.js:180)
    at Object.findDOMNode (findDOMNode.js:43)
    at Object.newFn [as findDOMNode] (deprecated.js:38)

**Comment by rrag** [comment]
This is not a problem with the library. but due to 2 versions of React

http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined

**Comment by laomouzi** [comment]
Yes. I see versions of React. I removed them, but both come back when I built. Any suggestion on how to resolved the issue? I tried the suggestions on the stackoverflow link, but no luck.

**Comment by rrag** [comment]
how did you get 2 versions of react in the first place? it should not happen.

```
cd your_project_folder_where_package.json is available
npm install -g npm # this is an optional step, I assumed you are using npm 2.x if you continue to have problems without this step, try again with this
rm -rf node_modules/
npm i
```

The other reason I can think of is that you have a clone of react-stockcharts in your node_modules folder and not the npm installed version. And inside this clone also you have done a npm install, so your app looks like

```
your_project_folder\
  |
  --package.json
  --node_modules\
     |
     --react\
     --react-dom\
     --react-stockcharts\
     |   |
     |   -node_modules\
     |      |
     |      --react\
     |      --react-dom\
     |      --more...
     --other dependencies you have
```

if this is your setup, I suggest you use the npm version, by following the above steps. But if you want to continue to maintain it this way, I recommend simply softlinking both `react` and `react-dom` to the  installation, so you will be able to work on both projects and make a change in one, and not have to to publish to npm and install again.  `npm link` also solves the same problem simply by installing both `react` and `react-dom` as global dependencies. I am not a fan of that approach, so the softlinking works just fine.

**Comment by laomouzi** [comment]
Thanks. I'm not sure how multiple versions are introduced. Maybe by the meteor?  Anyway, I followed your suggestions and ends up with the same problem. The issue can be replicate by the following steps:

meteor create abc
meteor add react-template-helper
meteor add react
meteor add cosmos:browserify
meteor create --package test

cd packages/test/
npm install react-stockcharts
npm install d3

<template name="stockChart">
    <div id="chart">
    </div>
    <div>{{> React component=CandleStickChartWithMA data=data type=type width=width }}</div>
</template>

Finally, use the template {{> stockChart}} in the abc.html

**Comment by rrag** [comment]
I dont know how meteor works, but by looking at your steps, I think

```
...
meteor add react
...
npm install react-stockcharts
```

both of these would each bring in a version of react. Can you try to remove the react which is installed by `react-stockcharts`? This seems to be a problem in meteor for any library which depends on react,  I am sorry, I am not of much help
