### ISSUE TITLE
How to interact brush graph with candlestick graph 

### ISSUE THREAD

**Issue by arpitprod** [rrag/react-stockcharts#591]
How to interact brush graph with candlestick graph like this site
[https://poloniex.com/exchange#usdt_btc](https://poloniex.com/exchange#usdt_btc)

Please let me know, how can I add this functionality in my graph

![screen shot 2018-06-20 at 12 57 16 pm](https://user-images.githubusercontent.com/19798516/41644567-0d38495e-748c-11e8-9308-dd38b8c0c3b6.png)

**Comment by rrag** [comment]
Such functionality is not built in you have to create 2 separate charts and link them
or roll out your own pan. I have no plans to add such a functionality
