### ISSUE TITLE
Non-Interactive StraightLines - Programmatically creating trend lines on highs and lows

### ISSUE THREAD

**Issue by marktellez** [rrag/react-stockcharts#595]
I want to do this programatically... it seems the only way to do it (based on the examples) is interactively using the mouse.

https://dailypriceaction.com/free-forex-trading-lessons/how-to-trade-equidistant-channels

Interactive example: https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithEquidistantChannel

I am digging through the code to see how i can get the xy points of the candlesticks from the series, but I don't see any straightforward way.

Any tips?

Thanks for the AWESOME library!

**Comment by seasick** [comment]
Taken from [this example](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithInteractiveIndicator).
```
const trendlines = [
  // start: [x, y], end: [x, y] - you should be able to find correct values with `xAccessor` and `yAccessor`
  { start: [1606, 56], end: [1711, 53], appearance: { stroke: "green" }, type: "XLINE" }
];

return <TrendLine
  enabled={false}
  type="RAY"
  snap={false}
  trends={trendlines}
/>
```

**Comment by rrag** [comment]
you would have to create a custom component to draw a line between `(x1, y1)` to `(x2, y2)`
no built in non interactive series exists
