### ISSUE TITLE
Better touch support

### ISSUE THREAD

**Issue by Jabher** [rrag/react-stockcharts#597]
Hi! I'm trying to play with this lib, it feels great, but has serious issues with touch. 

1. simple drag is dropping performance to around 3-5FPS. Device: win10, chrome 67, 2x display ratio, maybe this will help.
2. after touch drag mouse is ignored 
3. gestures like pinch are not supported, i'm pinching page instead :(

**Comment by rrag** [comment]
Thank you

yes there are problems with touch support. Pinch zoom does work though.

RE: performance dropping below 5fps on win10
I do not have a win10 touch device. I have tested with an older generation ipad air and it is good there.
Not sure if win10 is the issue. I have no way to tell
