### ISSUE TITLE
Updating data points & Load more data on the pan

### ISSUE THREAD

**Issue by alexandrkondrachuk** [rrag/react-stockcharts#598]
Hi, there!
Updating data points in real time and load more data do not work fine together.
**Here are my code snippets:** 
[https://codesandbox.io/s/k5q55018no](https://codesandbox.io/s/k5q55018no)
**I recorded the problem I have:** 

![stock-chart](https://user-images.githubusercontent.com/19354574/42223654-ee5e5ce4-7ee0-11e8-9cae-1775d5d90a53.gif)

I will be really appreciated if you can help. Thanks in advance!

**Comment by alexandrkondrachuk** [comment]
Hi, I figured out where was my mistake. Sorry for the inconvenience

**Comment by ezekg** [comment]
@alexandrkondrachuk what was the issue/solution? I'm seeing the same behavior.
