### ISSUE TITLE
How to get date values from onLoadMore start/end x-axis indexes?

### ISSUE THREAD

**Issue by coderdenver9** [rrag/react-stockcharts#599]
Hi. How can I get date values from `onLoadMore` for a candlestick chart? I get back a `start` and `end` index, but I don't know how to turn those into date values so that I can send that to the server. The server ([Coinbase Pro API](https://docs.pro.coinbase.com/#get-historic-rates)) accepts a `start`/`end` date range.

For example, `onLoadMore` recieves `start = -62.911, end = 0`. But how do I turn those indexes into a date value according to my chart's X axis?

Sorry if this is obvious, I'm new to charting. This is a great library, by the way.

**Comment by rrag** [comment]
there is no way the library can tell what the `start` will be if you are using
the `discontinuous` time scale.

`end` date can be the very first data point you have.

If you are using continuous data use `d3.timeScale` instead and that would give you start, end as dates

**Comment by Industrial** [comment]
To get this right; say my axis shows candles for days, if I receive a start value of -10, that means 10 days and if it were candles for minutes it would mean 10 minutes?
