### ISSUE TITLE
Feature Request Volume Profile Options

### ISSUE THREAD

**Issue by aajtodd** [rrag/react-stockcharts#60]
I know volume profile is on the roadmap, wanted to throw out a few things to consider when implementing:

If you've ever used Think or Swim there are quite a few ways to show volume profile:
https://readtheprospectus.wordpress.com/2010/02/28/volume-profile-goes-native-to-think-or-swim/

* Tick/user defined vs automatic bin sizes
* Show/hide the point of control
* Show/hide % range. Usually set to 70% but could be user configurable.
* Show on left vs right OR plot on top of price action for each defined time range.

I would love to see the option for expanded vs on top of the price action. Personally I prefer on top of price action since it's nice to see week to week profiles for example, but it would be nice to see both.

Feel free to close as you see fit, I just wanted to throw out some ideas to consider.

**Comment by rrag** [comment]
sorry for late response. Thanks for the feedback. I will have to do some reading on this topic. any other recommended articles on how to calculate these? I was thinking of something like [this](https://www.tradingview.com/x/pJUQf0Gv/) it would be a simple addition of all the volume activity at that price.

I am not able to find any good articles explaining how to calculate these. If you can explain yourself that would be great too. we can hop on gitter if you want.

**Comment by aajtodd** [comment]
Sorry as well for delayed response.

Yes, I believe that shows total volume activity at a specific price. I think that should be reasonably straight forward but I have never actually calculated it. What I was pointing out to consider is the ability to show volume profile over a defined session/period like below.

![session_profile](https://cloud.githubusercontent.com/assets/5158304/13879077/d686c5b8-eceb-11e5-906e-4154cc5b0d98.png)


Trading view's documentation and playing around with their settings show their are quite a few ways to do volume profile (in their terminology I guess I was referring to volume profile per session).

https://www.tradingview.com/stock-charts-support/index.php/Volume_Profile


I'm not entirely sure how much help I can be (I know next to nothing about d3, canvas, svg, etc). Your best bet is to play around with trading view to get an idea of the options and their effect before you sit down writing something.

The display could be affected depending on:
1. Fixed time range
2. Visible data
3. By individual trading session

One and two are the same calculation/chart just different slices of data. This would be the chart you referred to which shows volume profile off to one side of the chart. Three is understandably more difficult but conceptually the same. Take a trading session (lets say 1 day). We would slice the data and do the same calculation for each trading session. The graph gets overlayed starting at the open of the trading session. 

I'm in a rush at the moment but we can discuss further.

**Comment by rrag** [comment]
This is great, thanks

**Comment by rrag** [comment]
work in progress version [here](http://rrag.github.io/react-stockcharts-next/documentation.html#/volume_profile)

[source](https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/VolumeProfileChart.jsx#L65)

Change [orient](https://github.com/rrag/react-stockcharts/blob/next/src/lib/series/VolumeProfileSeries.jsx#L43) to left/right to get the profile align to the right/left.

Still working on the Volume profile by session

**Comment by rrag** [comment]
[Volume profile by session](http://rrag.github.io/react-stockcharts-next/documentation.html#/volume_profile_by_session) - work in progress 

Next

- [ ] Show/hide point of control
- [ ] show/hide value area

**Comment by rrag** [comment]
No plan to implement these additional features for now. already have volume profile and by session

**Comment by AdvaithD** [comment]
Hey @rrag was wondering its possible to modify the length of a session. Been a huge fan of react-stockcharts btw 👍
