### ISSUE TITLE
[Improvement] codesandbox - Unhandled Rejection (TypeError) Failed to fetch - WorkAround

### ISSUE THREAD

**Issue by datgrog** [rrag/react-stockcharts#606]
**Error:**

When codesandbox runs
```
fetch("//rrag.github.io/react-stockcharts/data/MSFT.tsv")
```
it does not works for some reason, probably CORS issue.

**WorkAround:**

- Download the file locally `wget rrag.github.io/react-stockcharts/data/MSFT.tsv` for instance.
- Go to your exemple you want to see online [AreaChart](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/AreaChart)
- Drag and Drop `MSFT.tsv` within `src` directory
- Open `utils.js` and add 
```
import MSFT from "./MSFT.tsv";
```
and replace `getData` function
```
export function getData() {
  return new Promise(resolve => {
    const data = tsvParse(MSFT, parseData(parseDate));
    resolve(data);
  });
}
```

**Comment by rrag** [comment]
Thanks for the report. github.io must have stopped supporting CORS recently. updated all examples now to use rawgit instead
