### ISSUE TITLE
On drastic window resize: TypeError Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by synnovsh** [rrag/react-stockcharts#607]
When resizing the window drastically in [this example](https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChart) I get the above error. Some testing with [other example charts ](https://github.com/rrag/react-stockcharts-examples2) give other errors. Wondering if there is a way to gracefully handle this or where the error comes from.

**Comment by rrag** [comment]
in real life make sure you set a css `min-width` property for the container of the charts. making the chart width so small will definitely cause problems
