### ISSUE TITLE
Is there any way to make interactive components static/non-interactive?

### ISSUE THREAD

**Issue by ebspeter** [rrag/react-stockcharts#608]
I'm having trouble to handle interactive lines on different time-frames. 

If i have a line drawn on hourly time-frame it can easily span days, but on a small time-frame it won't fit unless i add "placeholder" data points from the line start until the start of the data, which in my case is 1000 periods back. This works well for modifying the endpoint of the line because the whole line is inside the data.

The problem is performance, with more than around 15,000 data points the chart becomes slow. 

So what i want to do instead is to make the line static if it doesn't fit within the data, but i can't see how to "remove" the interactivity of the TrendLine component. Even if i set enabled={false} it is still interactive using the mouse. 

Alternatively i would like to draw a simple svg path and render that instead of the TrendLine if it doesn't fit.

**Comment by rrag** [comment]
You are correct there is no way to lock the interactive elements now.
May be in the future part of the next version upgrade I would like to add this feature.

**Comment by ebspeter** [comment]
Alright, thanks. And thanks for a great project!

I've solved the issue with a custom version of StraightLine for now, together with logic to display that or the TrendLine. 

Also not using the empty datapoints instead adding data on zoom/pan. Are you interested in a PR to react-stockcharts-examples2 with a Binance example including websocket real-time data and on demand adding of data?
