### ISSUE TITLE
Use cross-env to set IP and POST for windows users

### ISSUE THREAD

**Issue by WaiSiuKei** [rrag/react-stockcharts#61]
Windows users will be failed to run `watch`, how about using `cross-env` to set IP and POST of `watch` task in `next` branch?

**Comment by rrag** [comment]
did not know about `cross-env`, I will add that soon

Was trying out cloud9 IDE and it would listen to IP and PORT, so had to use them in the watch script.

**Comment by WaiSiuKei** [comment]
you could install `cross-env` as devDependency and change the follwing
` "watch": "npm run clean && IP=0.0.0.0 PORT=8080 node scripts/watch.js",`
to
` "watch": "npm run clean && cross-env IP=0.0.0.0 PORT=8080 node scripts/watch.js",`,
`cross-env` just help to set then env args.

**Comment by rrag** [comment]
Done
