### ISSUE TITLE
Add Radius to CandleSticks

### ISSUE THREAD

**Issue by elliotaplant** [rrag/react-stockcharts#610]
I have a design need to add a border radius to the candlesticks in the `CandleStickSeries` component. I see two ways of doing this:
1. Add a `candleBorderRadius` prop to the `CandleStickSeries` that gets passed along as `rx` and `ry` to the candle `<rect />`
1. Add `wickProps` and `candleProps` props to the `CandleStickSeries` that get passed along and spread on the wick and candle respectively.

I'll make two PR's with updates to the components and docs for anyone that wants to see the code in detail.

**Comment by rrag** [comment]
Thanks for the PRs, but I am not going to accept them for reasons mentioned in the PRs.

Thank you for your effort, sorry I could not merge it but
performance of candlestick chart is very important for me to compromise
