### ISSUE TITLE
Scrollbar on gocharting.com is difficult to use

### ISSUE THREAD

**Issue by benmccann** [rrag/react-stockcharts#614]
It's not directly related to this library, but I wanted to provide some feedback that the scrollbar on gocharting.com is very frustrating. When I move my mouse to the right side of the screen the scrollbar does not appear like I would expect (i.e. like the native scrollbar would). It also seems like it has an acceleration / momentum that is very different than the standard scrollbar and thus does not work as I'd expect. I would prefer the native scrollbar and don't see much benefit from having one that is different

**Comment by GoChartingAdmin** [comment]
Hi,

Appreciate your feedback.  Could you send a screenshot of the scrollbar that is troubling you.  We will consider replacing it with a native scrollbar if we are able to understand the exact issue.

**Comment by benmccann** [comment]
Thanks. Closing here and responding on the other issue
