### ISSUE TITLE
Expired certificate on demo.reactstockcharts.org

### ISSUE THREAD

**Issue by benmccann** [rrag/react-stockcharts#615]
Visiting https://demo.reactstockcharts.org/ gives me:

Your connection is not private
Attackers might be trying to steal your information from demo.reactstockcharts.org (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID

**Comment by benmccann** [comment]
Common Name (CN)	Let's Encrypt Authority X3
Organization (O)	Let's Encrypt
Organizational Unit (OU)	<Not Part Of Certificate>
Issued On	Friday, February 23, 2018 at 4:48:54 PM
Expires On	Thursday, May 24, 2018 at 5:48:54 PM

**Comment by rrag** [comment]
Thanks for the report

I am taking down the demo. I forgot about the demo instance for more than 3 months now !!!
I was spending about $10 a month on this  demo micro instance. It was running a websocket server.

I will be $10 richer next month \o/
