### ISSUE TITLE
Chart repeats itself

### ISSUE THREAD

**Issue by benmccann** [rrag/react-stockcharts#616]
If you keep hitting the `-` button to zoom out on http://demo.reactstockcharts.org/ then it starts repeating the same data. It would be preferable if it just stopped letting you zoom out more

![screenshot from 2018-08-11 10-31-57](https://user-images.githubusercontent.com/322311/43994452-d8e10a9e-9d51-11e8-9bac-7d4ebf4f7ea8.png)

**Comment by rrag** [comment]
Thanks for the report. It was a bug on the websocket server I have taking down the demo now
