### ISSUE TITLE
Is it possible to show a specific scale of series data?

### ISSUE THREAD

**Issue by rrki** [rrag/react-stockcharts#62]
e.g, the {data} contains a stock's history prices from 2000-06-01 to 2000-12-01, I want to render all data, but initially on the chart it only shows the data from 2000-08-01 to 2000-09-01. User can drag the chart left/right to see more data.
Is there any ways doing this? thanks!

**Comment by rrag** [comment]
in `v0.3.1` it is not so declarative, you will have to use `setViewRange` on the ref of `ChartCanvas` after the initial render. It is not intuitive.

in `v0.4.0-beta1` released just now. it is declarative. look at example

https://github.com/rrag/react-stockcharts/blob/next/docs/lib/charts/CandleStickChartWithEdge.jsx#L70

Big time API changes with 0.4 and the docs are also [updated](http://rrag.github.io/react-stockcharts-next/documentation.html#/area_chart)

Once I update all the plunker's will release 0.4

**Comment by rrki** [comment]
Awesome. Thanks for the help! @rrag
