### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by benmccann** [rrag/react-stockcharts#620]
This is the best stock charting library I've found. I had been writing my own for quite awhile, but may give up now that I've discovered this one

Would it be possible to add a getting started page to the documentation? Things I'm thinking it could include are:

- How to include the library (perhaps examples with pre-compiled script and/or via npm)
- What's the minimal amount of HTML or JSX that needs to be used to include the library?
- How to pass data to the library. E.g. what format does the data need to be in?
- Is it possible to call the component without writing your entire app in React?

**Comment by rrag** [comment]
Hi, there are multiple examples where has helped a lot of users.
Unfortunately these codesandbox examples are not working now.

Fixing them should provide a better getting started experience
