### ISSUE TITLE
Storing state of indicators

### ISSUE THREAD

**Issue by petscheit** [rrag/react-stockcharts#622]
I've built a chart with this library and really need to refactor my codebase now, as it became very messy. The main hurdle i'm having is managing the state of the indicators. The way I do it now is storing then in the main chart components state and passing it to the child component when editing it and then back (it works, but is very messy). I looked in to redux and it seems to be exactly what I need, but im having issues storing the indicators in redux. Is redux the right tool for this or are there any other ways of doing this? Would be great to get some pointers! 

Also, really like this library, by far the most comprehensive and customisable library out there, good work rrag! Thanks for creating this.

**Comment by rrag** [comment]
you can store the list of indicators anywhere (redux/react state and eventually to a database on server side) and reloading it on page refresh or reuse across user devices.

but I would advice against storing the `data` or the calculated data with the indicator values
on a serverside database. the data and the indicator values have to calculated on page load
or ticker change so it can be discarded when the user exits the browser
