### ISSUE TITLE
Mobile responsive Line chart

### ISSUE THREAD

**Issue by Neha3011** [rrag/react-stockcharts#623]
Hey,
I have a questions:
Is there a way I can format the X-axis to not overlap in case if chart is opened in mobile like rotate the text?

<img width="216" alt="screen shot 2018-08-15 at 2 24 04 am" src="https://user-images.githubusercontent.com/10024090/44118062-99a0f720-a032-11e8-97a2-1ab8156186f3.png">

Thanks for your help in advance.

**Comment by rrag** [comment]
change the `ticks` parameter on the `XAxis`

try something like

```jsx
<XAxis ...
  ticks={width / 60}
/>
```

change the denominator till you are comfortable with the results
