### ISSUE TITLE
How to overlay one set of data over another?

### ISSUE THREAD

**Issue by joannawheeler** [rrag/react-stockcharts#624]
I currently have a line chart displaying btc where each object look like this:
    {
        "timeStamp": "2018-03-28T00:35:00",
        "unixTimeStamp": 1522197300,
        "currentBuyValue": 7732.8,
        "currentSellValue": 7732.4,
        "highValue": 7737.9,
        "lowValue": 7731.46659349,
        "open": 7737.6,
        "close": 7732.4,
        "volume": 44.06418653
    }

I have another set of data I want to plot as points over the btc chart where each object looks like this:

{
"close": 6245,
"entryText": "BUY",
"date": "2018-07-14T18:00:00",
"numContracts": 1,
"pnl": 15
}

How do I plot each point within the btc chart? I am not sure how to use two sets of data within the same chart.

Thanks for any advice.

**Comment by rrag** [comment]
Please look into annotations

http://rrag.github.io/react-stockcharts/documentation.html#/annotations
