### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by roller-project** [rrag/react-stockcharts#627]
I need move span as image
what is code config 

![image](https://user-images.githubusercontent.com/40880733/44416501-3b693800-a59d-11e8-890c-323ca7c4f8c1.png)

**Comment by michaelr524** [comment]
@roller-project Maybe the "padding" property is what you are looking for?
https://github.com/rrag/react-stockcharts/blob/master/src/lib/ChartCanvas.js#L1156

**Comment by roller-project** [comment]
@michaelr524 not work friend :(

**Comment by roller-project** [comment]
@michaelr524 do you know other chart LIB

**Comment by michaelr524** [comment]
There are plenty of other chart libs out there..
I thought that you wanted something like here: https://github.com/rrag/react-stockcharts/issues/588

**Comment by rrag** [comment]
I am very sorry. I have no idea what the question means
