### ISSUE TITLE
Padding impact translation of Axis?

### ISSUE THREAD

**Issue by WaiSiuKei** [rrag/react-stockcharts#63]
Seems that padding is used in setting the range of scale, but have not been considered in the the translation of axes canvas ctx. I try to set a non-0 padding of `Chart` and the two axis will not join together

**Comment by rrag** [comment]
Why do you think with non zero padding on `xScale` the axis should still touch? I think what we have now is correct

What are you trying to use padding for?

**Comment by WaiSiuKei** [comment]
Left and right padding did work but bottom padding will break it. 
I am creating my repo and found the padding prop in `Chart` to be redundant.

**Comment by rrag** [comment]
`next` or `master` ?

**Comment by WaiSiuKei** [comment]
·next·

**Comment by rrag** [comment]
usage of `bottom` and `top` are flipped, top padding is affecting bottom and vice versa. I will fix it now

But it is not redundant.

**Comment by rrag** [comment]
@WaiSiuKei I am about to release 0.4 soon

If you could let me know what the problem is, may be with a plunker I can have that fixed before the release.

**Comment by WaiSiuKei** [comment]
Hi @rrag ,
I reproduced it [here](http://plnkr.co/edit/wVKHrWQX566l8bmoYeNF?p=preview), the `rs.js` was built  after the release of `0.4.0.beta-2`, only change [https://github.com/rrag/react-stockcharts/blob/next/src/lib/Chart.jsx#L63](https://github.com/rrag/react-stockcharts/blob/next/src/lib/Chart.jsx#L63) to be `padding:{top:0, bottom:20}`, FYI.

**Comment by rrag** [comment]
Sorry I am confused what the problem is. I see the padding of 20px at the bottom. That is what you have specified in the props also. Are you expecting a different behavior?

**Comment by rrag** [comment]
this padding is useful for charts like MACD, RSI, which are oscillators, so a padding of 20px top and bottom will let the line not touch the xaxis.

Even in Candlestick charts, a padding will help in making the high/low wick from not touching the xaxis

**Comment by WaiSiuKei** [comment]
Thans for you explaination of the usage of padding, maybe I am using a wrong padding in some place.I want to use the padding to add white space between charts, and I should specify the origin and height of charts.
