### ISSUE TITLE
Spacing between candlesticks when few points

### ISSUE THREAD

**Issue by oskarer** [rrag/react-stockcharts#632]
I have this problem when displaying few data points (2-10 of them), it's taking up full width and it's not possible to zoom/pan.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/4076953/44788278-e2e7fb00-ab99-11e8-8aba-30c1f09771b6.png">

I want something like this as default, where it's possible to zoom and pan as well;

<img width="737" alt="image" src="https://user-images.githubusercontent.com/4076953/44788441-5853cb80-ab9a-11e8-9760-c729a7b532a4.png">

Where should I start looking to change this?

**Comment by michaelr524** [comment]
I think that you can adjust the xExtents parameter to in order to achieve this.

**Comment by oskarer** [comment]
@michaelr524 Thanks, I god it working by doing that and creating a custom clamp function.

**Comment by ndaybreak** [comment]
hi I have the same issue, can you show me how to solve the question.  Thx

**Comment by khaphannm** [comment]
@oskarer could u help to share your solution ? I running into the same problem
