### ISSUE TITLE
Chart.propTypes padding v0.4.0

### ISSUE THREAD

**Issue by XmelesX** [rrag/react-stockcharts#64]
There is some problem on "static" chart like this [plnkr](http://plnkr.co/edit/gist:1eac0cb78f27b31415ac?p=preview). The first and the last candlestick have a cut. In React-stockchart v0.3.1 I have fixed that with padding function on Chart.propTypes, but in v0.4.0 we have padding only with "top" and "bottom" params without "right" and "left".

**Comment by rrag** [comment]
The `padding` property has been split into 2 one for left/right and another for top/bottom

for padding left/right add it to `ChartCanvas`

```jsx
<ChartCanvas ...
  ...
  padding={{left: 20, right: 10}}
  ...>
```
or
```jsx
  padding={20}
```
if you want the same padding on left and right

alternatively you can also remove the clip (introduced new in 0.4)

```jsx
<CandlestickSeries clip={false}/>
```

**Comment by XmelesX** [comment]
`<CandlestickSeries clip={false}/>`
nice solution!
and usually my results:
before:
![before](https://cloud.githubusercontent.com/assets/16750139/14266165/fe93450e-face-11e5-9712-8b7e47eec99e.png)
after:
![after](https://cloud.githubusercontent.com/assets/16750139/14266175/0d3d7ec6-facf-11e5-8b41-431c860d2f6c.png)
