### ISSUE TITLE
show trendlines and candlestick data in chart

### ISSUE THREAD

**Issue by johnreytanquinco** [rrag/react-stockcharts#643]
How can I show all contents displayed in the chart? In my case, sometimes a line will be plotted above or side of the chart.

**Actual result:**
![screenshot from 2018-09-04 15-47-51](https://user-images.githubusercontent.com/7284893/45017322-eb3cac00-b059-11e8-82d0-731ed852b236.png)

**Expected  result:**
![screenshot from 2018-09-04 15-45-40](https://user-images.githubusercontent.com/7284893/45017302-d8c27280-b059-11e8-8f2e-baa9660aa3e3.png)

**Comment by rrag** [comment]
the y domain of a chart is controlled by the `yExtents` prop
```jsx
<Chart ... yExtents={...}
```

change it to your desired value.

**Comment by johnreytanquinco** [comment]
thanks! thats right!
