### ISSUE TITLE
Stock charts docs

### ISSUE THREAD

**Issue by vixa2012** [rrag/react-stockcharts#644]
Hi dear support. I would like to create a Trading View component using react-stockcharts, but your documentation is almost empty.
Need your help!

Could you tell me how I can create the component same as on my screenshot? 
If you have a sample that looks like my screenshot, please share it.

I don't understand how to control AreaSeries height and width, how to add finish points (lines) and padding between the areaSeries and finish points, how to get YAxis coordinate and value, how to add custom figure (circle)?

<img width="1236" alt="2018-09-04 17 13 47" src="https://user-images.githubusercontent.com/1618041/45036942-7754d080-b066-11e8-8093-fa2604bd5100.png">

**Comment by rrag** [comment]
the documentation is available in http://rrag.github.io/react-stockcharts/documentation.html

I can vouch that it certainly is not empty

**Comment by vixa2012** [comment]
How I can add circle element ant setup X and Y Axis for it?
How I can get X or Y coordinates from item of array ?

**Comment by rrag** [comment]
I don't follow what you are asking.

But i suppose there are features you want that are not yet available in react-stockcharts.
The documentation with multiple examples lists all the features that are available
If it is not explained in the documentation you are looking for missing features

If you have specific issues please share a codesandbox with the problem
