### ISSUE TITLE
Feature Request: resizeable Annotations

### ISSUE THREAD

**Issue by WaiSiuKei** [rrag/react-stockcharts#65]
Hi rrag, it is possible to resize the annotations?
 Let say I am going to show daily transactions on a candlestick chart. Buys will be shown above the candle and sells are under the cancle, just like the triangles shown in [here](http://plnkr.co/edit/M8BIRndMEtKo9oSglly0?p=preview) (impleted by my repo).
I try to use the `Annotation`, but the size of the annotations will not be resized if I zoom in or out, as a result, annotations will become overlaped.

**Comment by rrag** [comment]
I am planning on implementing buy sell signals as annotations soon. The `Annotate` component will likely need to be updated to provide more props to the value of `with`

Initial thoughts: use the same logic to calculate candle width, and use that. I will update here when I make some progress

**Comment by rrag** [comment]
@WaiSiuKei how did you do the mouse hover on the annotations on canvas. hit testing?

I have been thinking of dropping `svg` support completely for sometime now but handling mouse events on tooltip is quite important for me.

**Comment by WaiSiuKei** [comment]
Yes, i subscribed the mousemove event for the hit-testing function of annotations,  it's a temporary workaround.  

How do you think about a new library base on Paper.js? I am rewriting my repo with Paper.js because mouse events will be easy to capture.

**Comment by rrag** [comment]
cool. I would love to see that. are you building on top of React?

**Comment by WaiSiuKei** [comment]
I dropped React and impleted a pure canvas chart, the main dependency is d3.scale

**Comment by rrag** [comment]
doing pan actions for with React was not fun. It slows it down. You would have seen all "optimizations" that have gone in to make pan on canvas faster. Even with all those problems, using React makes it easier for creating composable charts. So I am sticking with it. 

I feel expressiveness of the chart suffers with pure js, I love d3fc, if I had the time I would create a fork of d3fc for canvas. I am still not sure if paper is the solution. It provides some benefits sure, but it might slow down the canvas for pan actions.

**Comment by WaiSiuKei** [comment]
I am paying more attention to create a chart similar to that one at tradingview.com,  so mouse Interactions would be more important to make the chart interesting.I have tried some chart libraries but be disappointed.

As for pan/zoom actions, I am curious about applying transformation matrix to canvas instead of refactor the scale.

**Comment by rrag** [comment]
added example for [annotations](http://rrag.github.io/react-stockcharts-next/documentation.html#/ma_crossover_using_svg_shape), but these are not resizable. I dont think they should be. but the annotation does receive the following props, so any custom component can use this to size it accordingly

```jsx
xScale={xScale}
yScale={yScale}
xAccessor={xAccessor}
plotData={plotData}
datum={d}
```
