### ISSUE TITLE
Troubles with updating chart

### ISSUE THREAD

**Issue by TrueSpil** [rrag/react-stockcharts#66]
I have dinamic data, which are updating from server every 1 second. And when i tried to push it into chart? i have problem with Xaxis.

http://prntscr.com/aog3ln

now i undestand that ur lib can work only with data with min period a day. I need to get some consultation from u to understand how its work. 
pls contact me truefarsky@gmail.com

**Comment by rrag** [comment]
As you have identified the stock scale does not support intra day yet.

I am not available for private consulting now. we can discuss issues/feature requests here, and usage related questions on [gitter](https://gitter.im/rrag/react-stockcharts). I check on gitter from time to time.
