### ISSUE TITLE
Onclick Event on Line Series

### ISSUE THREAD

**Issue by Tse-ChiKit** [rrag/react-stockcharts#667]
Hi all,

I tried to select the line component via the onClick property and I found that the function passed to onclick never triggered.

`	testclick () {
		console.log("clicked");
	}`

` <LineSeries 
						yAccessor={element.indicatorCalculation.accessor()} 
						stroke={element.indicatorCalculation.stroke()}
						onClick={this.testclick}`

What is the correct way to use onClick in lineSeries?

**Comment by Sinfulelf** [comment]
Mb try this. https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithClickHandlerCallback

**Comment by Sinfulelf** [comment]
In real, I duno why - but click, doubleClick, etc - work only when 'highlightOnHover={true}'; click zone width - is hoverTolerance value;

**Comment by Tse-ChiKit** [comment]
It worked after I set highlightOnHover={true} like you said. It is just so strange..
