### ISSUE TITLE
percentage-based Y-axis?

### ISSUE THREAD

**Issue by DeeeeLAN** [rrag/react-stockcharts#672]
Hello,

Thank you for the awesome stock chart library. I am looking to change the y-axis scale of my chart to be percentage based, similar to the yahoo finance chart option. This would set the scale as a percent change from the first visible close price on the chart. 

I looked through all the examples and the only one that looked similar to what I wanted was the comparison chart, and that one is different enough that I couldn't see how it would work for a single stock. 

Does this feature presently exist, or would I need to implement the yExtents myself? If so, can you point me in the right direction? I would need to calculate it based on all the visible data, is that straightforward to do?

Thanks for the good work.

**Comment by DeeeeLAN** [comment]
[See example yahoo chart here.](https://finance.yahoo.com/quote/AAPL/chart?p=AAPL#eyJpbnRlcnZhbCI6ImRheSIsInBlcmlvZGljaXR5IjoxLCJjYW5kbGVXaWR0aCI6MjUuMjIyMjIyMjIyMjIyMjIsInZvbHVtZVVuZGVybGF5Ijp0cnVlLCJhZGoiOnRydWUsImNyb3NzaGFpciI6dHJ1ZSwiY2hhcnRUeXBlIjoiY29sb3JlZF9iYXIiLCJleHRlbmRlZCI6dHJ1ZSwibWFya2V0U2Vzc2lvbnMiOnsicHJlIjp0cnVlLCJwb3N0Ijp0cnVlfSwiYWdncmVnYXRpb25UeXBlIjoib2hsYyIsImNoYXJ0U2NhbGUiOiJwZXJjZW50IiwicGFuZWxzIjp7ImNoYXJ0Ijp7InBlcmNlbnQiOjEsImRpc3BsYXkiOiJBQVBMIiwiY2hhcnROYW1lIjoiY2hhcnQiLCJ0b3AiOjB9fSwibGluZVdpZHRoIjoyLCJzdHJpcGVkQmFja2dyb3VkIjp0cnVlLCJldmVudHMiOnRydWUsImNvbG9yIjoiIzAwODFmMiIsInN5bWJvbHMiOlt7InN5bWJvbCI6IkFBUEwiLCJzeW1ib2xPYmplY3QiOnsic3ltYm9sIjoiQUFQTCJ9LCJwZXJpb2RpY2l0eSI6MSwiaW50ZXJ2YWwiOiJkYXkiLCJzZXRTcGFuIjpudWxsfV0sImV2ZW50TWFwIjp7ImNvcnBvcmF0ZSI6e30sInNpZ0RldiI6e319LCJjdXN0b21SYW5nZSI6eyJzdGFydCI6MTUzNDQwMjgwMDAwMCwiZW5kIjoxNTM5MzI3NjAwMDAwfSwicmFuZ2UiOm51bGwsInN0dWRpZXMiOnsidm9sIHVuZHIiOnsidHlwZSI6InZvbCB1bmRyIiwiaW5wdXRzIjp7ImlkIjoidm9sIHVuZHIiLCJkaXNwbGF5Ijoidm9sIHVuZHIifSwib3V0cHV0cyI6eyJVcCBWb2x1bWUiOiIjMDBiMDYxIiwiRG93biBWb2x1bWUiOiIjRkYzMzNBIn0sInBhbmVsIjoiY2hhcnQiLCJwYXJhbWV0ZXJzIjp7IndpZHRoRmFjdG9yIjowLjQ1LCJjaGFydE5hbWUiOiJjaGFydCJ9fSwi4oCMbWHigIwgKDIwMCxDLGVtYSwwKSI6eyJ0eXBlIjoibWEiLCJpbnB1dHMiOnsiUGVyaW9kIjoiMjAwIiwiRmllbGQiOiJDbG9zZSIsIlR5cGUiOiJleHBvbmVudGlhbCIsIk9mZnNldCI6MCwiaWQiOiLigIxtYeKAjCAoMjAwLEMsZW1hLDApIiwiZGlzcGxheSI6IuKAjG1h4oCMICgyMDAsQyxlbWEsMCkifSwib3V0cHV0cyI6eyJNQSI6IiNhZTExMjUifSwicGFuZWwiOiJjaGFydCIsInBhcmFtZXRlcnMiOnsiY2hhcnROYW1lIjoiY2hhcnQifX0sIuKAjG1h4oCMICgxMDAsQyxlbWEsMCkiOnsidHlwZSI6Im1hIiwiaW5wdXRzIjp7IlBlcmlvZCI6IjEwMCIsIkZpZWxkIjoiQ2xvc2UiLCJUeXBlIjoiZXhwb25lbnRpYWwiLCJPZmZzZXQiOjAsImlkIjoi4oCMbWHigIwgKDEwMCxDLGVtYSwwKSIsImRpc3BsYXkiOiLigIxtYeKAjCAoMTAwLEMsZW1hLDApIn0sIm91dHB1dHMiOnsiTUEiOiIjNzlmNGJkIn0sInBhbmVsIjoiY2hhcnQiLCJwYXJhbWV0ZXJzIjp7ImNoYXJ0TmFtZSI6ImNoYXJ0In19LCLigIxtYeKAjCAoNTAsQyxlbWEsMCkiOnsidHlwZSI6Im1hIiwiaW5wdXRzIjp7IlBlcmlvZCI6IjUwIiwiRmllbGQiOiJDbG9zZSIsIlR5cGUiOiJleHBvbmVudGlhbCIsIk9mZnNldCI6MCwiaWQiOiLigIxtYeKAjCAoNTAsQyxlbWEsMCkiLCJkaXNwbGF5Ijoi4oCMbWHigIwgKDUwLEMsZW1hLDApIn0sIm91dHB1dHMiOnsiTUEiOiIjYWQ2ZWZmIn0sInBhbmVsIjoiY2hhcnQiLCJwYXJhbWV0ZXJzIjp7ImNoYXJ0TmFtZSI6ImNoYXJ0In19LCLigIxtYeKAjCAoMjAsQyxlbWEsMCkiOnsidHlwZSI6Im1hIiwiaW5wdXRzIjp7IlBlcmlvZCI6IjIwIiwiRmllbGQiOiJDbG9zZSIsIlR5cGUiOiJleHBvbmVudGlhbCIsIk9mZnNldCI6MCwiaWQiOiLigIxtYeKAjCAoMjAsQyxlbWEsMCkiLCJkaXNwbGF5Ijoi4oCMbWHigIwgKDIwLEMsZW1hLDApIn0sIm91dHB1dHMiOnsiTUEiOiIjMDA4OTRjIn0sInBhbmVsIjoiY2hhcnQiLCJwYXJhbWV0ZXJzIjp7ImNoYXJ0TmFtZSI6ImNoYXJ0In19fSwic2V0U3BhbiI6bnVsbH0%3D)

**Comment by DeeeeLAN** [comment]
I found the percentScale={true} option for YAxis, but it doesn't seem to do anything for me.

**Comment by Sinfulelf** [comment]
well, You might set some wrapper on the Yaxis tickFormat.
smth like that
___
<YAxis
   axisAt="right"
   orient="right"
   ticks={5}
   tickFormat={value  => '` ${value / 100}% `'  }
/>

**Comment by DeeeeLAN** [comment]
Changing the tickformat doesn't change the values, just how they are displayed. I was able to mostly resolve it by supplying a postCalculator like so:

```
const percentCalculator = ((plotData) => {
	const plotDataCopy = cloneDeep(plotData)
	const firstClose = plotDataCopy[0].close
	plotDataCopy.map(d => {
		d.open   = (d.open   - firstClose) / firstClose;
		d.high   = (d.high   - firstClose) / firstClose;
		d.low    = (d.low    - firstClose) / firstClose;
	 	d.close  = (d.close  - firstClose) / firstClose;
		d.ema20  = (d.ema20  - firstClose) / firstClose;
		d.ema50  = (d.ema50  - firstClose) / firstClose;
		d.ema100 = (d.ema100 - firstClose) / firstClose;
		d.ema200 = (d.ema200 - firstClose) / firstClose;
		return d
	})
	return plotDataCopy
})
```

But now where I am stuck is the postCalculator is applied to the chartCanvas, not to a specific chart. So the data changes apply to all the charts on the canvas, not just a single chart like what I want.

**Comment by DeeeeLAN** [comment]
Okay I figured out that problem too. Each component pulls it's data from the accessor, so all I need to do is save the data from percentCalculator in different keys (d.relOpen, d.relHigh, etc.), then I can override the accessor functions when wanted. So for a line series, I can set yAccessor={d => d.relEma20}, but leave the MovingAverageTooltip ema20 yAccessor set to the default ema20.accessor().

This way I can have the graph display percent changes, but the tooltips still display the original values.
