### ISSUE TITLE
Proper event detection

### ISSUE THREAD

**Issue by nani3105** [rrag/react-stockcharts#68]
This piece of code in EventHandler

> inputType === "mouse"

is causing the code to always default to touch. 

I believe inputType is an Object.

**Comment by rrag** [comment]
`inputType` is a string

`"mouse"` is passed from [here](https://github.com/rrag/react-stockcharts/blob/b614598c4a7f66a83957c5c8c19f366cbf872416/src/lib/EventCapture.jsx#L75)

`"touch"` is passed from [here](https://github.com/rrag/react-stockcharts/blob/b614598c4a7f66a83957c5c8c19f366cbf872416/src/lib/EventCapture.jsx#L153)

I am not following the problemm, can you explain the scenario please

**Comment by nani3105** [comment]
Sorry didnt see the refactored code. Closing this.
