### ISSUE TITLE
Change date range

### ISSUE THREAD

**Issue by erichodges** [rrag/react-stockcharts#701]
Hi, I would like to change the date range on the chart. The only thing I found in the docs was:

"React stockcharts has sane defaults to show 2 data point per pixel width."

I would like to show a range that makes sense for the data that I'm getting from the API, such as 1 or 2 years. Is there a way to do this?

**Comment by kevyu** [comment]
try to set pointsPerPxThreshold props in ChartCanvas to a large number, such as 1000.

**Comment by erichodges** [comment]
Thanks @kevyu!

I tried it to set that up like the code below and there was no change. Did I do something wrong?


```
<ChartCanvas
        height={600}
        width={width}
        ratio={ratio}
        margin={{ left: 70, right: 70, top: 10, bottom: 30 }}
        type={type}
        seriesName=""
        data={data}
        xScale={xScale}
        xAccessor={xAccessor}
        displayXAccessor={displayXAccessor}
        xExtents={xExtents}
        clamp={true}
        pointsPerPxThreshold={.5}
      >
```
I tried different values.

I noticed in this example there is a lot more data showing:

https://codesandbox.io/s/github/rrag/react-stockcharts-examples2/tree/master/examples/CandleStickChartWithMACDIndicator

I don't see what has changed in the code to make this happen.

**Comment by erichodges** [comment]
This issue was solved by this code in Chart.js:

`const end = xAccessor(data[0]);`
