### ISSUE TITLE
Heatmap support / example?

### ISSUE THREAD

**Issue by kobermeit** [rrag/react-stockcharts#702]
Hey, I'm trying to create a candlestick chart with a heatmap on it (like tensorcharts, bookmap tools). I've got the candlestick chart working fine but can't figure out how to add the heatmap to it. Any ideas? 

To see what I mean, check out tensorcharts.com or bookmap.com.

EDIT: I found this https://codesandbox.io/s/m7q82r1x79 which is an example of 2 charts in 1 canvas. I haven't tried it yet but wonder if this canvas supports having a candlestick and heatmap chart in it, will give it a go.

**Comment by kobermeit** [comment]
Looking into this, another option is to just use the candlestick chart and place a canvas on top which draws the heatmap. This would be much easier if there was a way to get the X Y coordinates by passing a price/time combination. Not sure how to do that?

**Comment by bitnom** [comment]
> Looking into this, another option is to just use the candlestick chart and place a canvas on top which draws the heatmap. This would be much easier if there was a way to get the X Y coordinates by passing a price/time combination. Not sure how to do that?

Did you get anything going? Also, curious what you're working on (If you don't mind me asking).

**Comment by kobermeit** [comment]
Hey @TensorTom , I managed to get something working in react-highcharts BUT now trying to work out how to make it performant. Basically I create a chart and use type "heatmap", then I have 2 series in it, one is "candlestick" and the other is "heatmap" and then I add the data sets to it. Result is what I wanted - a heatmap series displaying on top of a candlestick that also zooms and pans.

Now I have 45k data points in the heatmap and when I try to zoom or pan, it's painfully slow, probably due to each data point being an SVG. I looked into a "boost" option which highcharts offers and it only improves the loading speed, not the panning. If I disable the heatmap, it's super fast. I've spent a bit researching into how to make highcharts as fast as possible (disable animations, labels, use GPU rendering, turbo threshold, boost threshold etc) but so far still slow to zoom/pan. 

Someone recommended I try the hacky option of drawing a heatmap in a canvas and then lay it on top of the chart and just modify the size/position when the chart changes, but I'm not a fan of that solution at all. I think I need to find another chart library maybe?

My end goal here is just a fun personal project/learning experience, I want to make my own version of tensorcharts.com for myself where I can personalize it and add a few ideas I have (like ability to export image and upload to my discord server when I use a command).

**Comment by bitnom** [comment]
> Hey @TensorTom , I managed to get something working in react-highcharts BUT now trying to work out how to make it performant. Basically I create a chart and use type "heatmap", then I have 2 series in it, one is "candlestick" and the other is "heatmap" and then I add the data sets to it. Result is what I wanted - a heatmap series displaying on top of a candlestick that also zooms and pans.
> 
> Now I have 45k data points in the heatmap and when I try to zoom or pan, it's painfully slow, probably due to each data point being an SVG. I looked into a "boost" option which highcharts offers and it only improves the loading speed, not the panning. If I disable the heatmap, it's super fast. I've spent a bit researching into how to make highcharts as fast as possible (disable animations, labels, use GPU rendering, turbo threshold, boost threshold etc) but so far still slow to zoom/pan.
> 
> Someone recommended I try the hacky option of drawing a heatmap in a canvas and then lay it on top of the chart and just modify the size/position when the chart changes, but I'm not a fan of that solution at all. I think I need to find another chart library maybe?
> 
> My end goal here is just a fun personal project/learning experience, I want to make my own version of tensorcharts.com for myself where I can personalize it and add a few ideas I have (like ability to export image and upload to my discord server when I use a command).

I never really got into react so have not been able to use those nice charts :( I did recently get accepted to the TradingView SDK which I think can accomplish what you're doing.

**Comment by kobermeit** [comment]
I've actually got this project completely working now. I ended up using other charting libraries to accomplish it. It was quite hacky and a huge learning curve, but i'm happy with it now! Going to close this issue, completely forgot it was still open :)
