### ISSUE TITLE
intra day test

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#71]
is it possible to post new version from next branch, i would like to test intra day graph ?

**Comment by rrag** [comment]
there is still a [lot more planned](http://rrag.github.io/react-stockcharts-next/documentation.html#/coming_soon...) for 0.5

if you just want to test it could you use the source itself?

I can publish a 0.5.0-alpha1 if you have some trouble.

**Comment by rsklyar** [comment]
0.5.0-alpha1 will be perfect

thx ^_^

**Comment by rsklyar** [comment]
dependency issue in case npm install from source 
<img width="710" alt="screen shot 2016-05-07 at 13 36 07" src="https://cloud.githubusercontent.com/assets/6270599/15091664/e69e60f2-1458-11e6-8f6b-ad3b5a517f7a.png">

**Comment by rrag** [comment]
that is because you have react 15 as a peer dependency. 0.5 will support both react 0.14 and 15

**Comment by rrag** [comment]
`react-stockcharts@0.5.0-alpha1` published, you can install it as

```
npm install react-stockcharts@next
```

2 different examples of intraday data
http://rrag.github.io/react-stockcharts-next/documentation.html#/intra_day_with_continious_scale
http://rrag.github.io/react-stockcharts-next/documentation.html#/intra_day_with_discontinious_scale
