### ISSUE TITLE
Rewrite financetimescale?

### ISSUE THREAD

**Issue by rrag** [rrag/react-stockcharts#73]
The library has lacked intraday financetimescale support, and thanks to @brobits we now have one.

We now have 2 custom scales `financeEODDiscontinuousScale` and `financeIntradayDiscontinuousScale`

I was in favor of having 2 scales initially, but as I started to create some examples, my view has changed. I prefer a single scale for handling discontinuous input.

I have mentioned this in some other issues, and this issue is a good place to reiterate it.  Do not use custom scales unless you really have to. Make sure that a `d3.time.scale()` will not satisfy your need.

Here is a list of reasons you would want to use a custom discontinuous scale

1. you are working with discontinuous data, like the equity market, which is closed on weekend and on weekdays is only open during certain hours
2. want to automatically jump to the next interval when you zoom out. like [here](http://rrag.github.io/react-stockcharts-next/documentation.html#/lots_of_data) as you zoom out the interval changes from 1d to 1w to 1m

### is there no other discontinuous scale available?
There are 2 that I know of
- [d3fc](https://github.com/ScottLogic/d3fc) - [example](https://d3fc.io/components/scale/dateTime.html)
- [techan.js](https://github.com/andredumas/techan.js) - [example](http://bl.ocks.org/andredumas/17be8c0973ac92acd6e5)

d3fc is really simple, I like the fact that you can specify a discontinuity, and it uses d3.time.scale() behind the scenes and just removes a tick if it appears on the discontinuity. Unfortunately this happens.

![image](https://cloud.githubusercontent.com/assets/10691183/15101795/d27524d0-155c-11e6-9f55-041372bcd4b6.png)

techan.js - I did not see this when I started, this aligns more closely to what I like. It does not need an index to be pre-calculated. It does seem to work well, I played around by deleting different data sets in this [plunker](http://plnkr.co/edit/gist:17be8c0973ac92acd6e5?p=preview). I am now trying to understand how it works and may be we could use it too. Initial glance seems that the `domain` has to be the entire dataset and not the data which has to be drawn, there is usage of a `visibleDomain`, which I am not too excited about, but you could argue this is better than adding an index property to each element.

### My wishlist for a discontinuous scale

1. One discontinuous scale for intraday and historical, can also be used in price movement chart types like Renko, P&F for both intraday and historical - d3fc scale is ruled out here since price movement charts types do not have a defined discontinuity
1. Nice tick values. This is the main reason I started the custom scale. what I mean by this is

  ![image](https://cloud.githubusercontent.com/assets/10691183/15103443/14b1f0b2-1571-11e6-8bf5-a1a81668e2cc.png)

  `1:00 AM` above is the first tick of the next day. I would rather see `mmm dd` there instead of the time

  similarly
  ![image](https://cloud.githubusercontent.com/assets/10691183/15103461/4d262ecc-1571-11e6-8213-1efedd0d9b13.png)

  `Dec 2` is the first tick of month Dec, so I would rather see the tick value as `Dec YYYY`
  ![image](https://cloud.githubusercontent.com/assets/10691183/15103470/70fc74fa-1571-11e6-9de3-9ed3dff3e62a.png)

  `Jan 6` is the first tick of the year, I would rather see the tick value as `YYYY` This might be a small thing but it makes a huge difference for a price movement based chart

1. Show tick values beyond the last data point. - This is not possible with our existing financetimescale or the techanjs financetime scale.
1. provide a `utc` variant of the scale - both `techanjs` and `d3.time.scale` have `utc` variants

are there other financetime scales out there I am not aware of?

any thing else which should make the the wishlist?

Lately I feel that "jump to next interval automatically on zoom out" has to be implemented in userland, and should not be part of the library itself. This should also factor into the rewrite

**Comment by rsklyar** [comment]
for example
<img width="823" alt="screen shot 2016-05-10 at 17 21 18" src="https://cloud.githubusercontent.com/assets/6270599/15149977/43148974-16d4-11e6-81a6-1c9bb446f38e.png">
<img width="763" alt="screen shot 2016-05-10 at 17 22 45" src="https://cloud.githubusercontent.com/assets/6270599/15149980/48e8db98-16d4-11e6-9567-4dc66f1d5ae7.png">

**Comment by rrag** [comment]
- [x]  Add a new scale which combines both eod and intraday into one
- [x]  remove the jump to next interval feature

Examples using the new scale
Intraday - 
http://rrag.github.io/react-stockcharts-next/documentation.html#/intra_day_with_discontinuous_scale
EOD historical - http://rrag.github.io/react-stockcharts-next/documentation.html#/edge_coordinate
Price movement chart - http://rrag.github.io/react-stockcharts-next/documentation.html#/renko

Example using d3.time.scale
Intraday - http://rrag.github.io/react-stockcharts-next/documentation.html#/intra_day_with_continious_scale

This new scale addresses 1, 2, 4 from the wishlist above, 3 seems much harder to implement, I also looked at a few other charting applications which deal with discontinuous scale, and they have not implemented it too. If there are any ideas on how to implement 3 above please share them

ping: @brobits @svk31@mikewin @iNikNik

**Comment by rrag** [comment]
fixed, published in 0.5
