### ISSUE TITLE
Mouse pointer display orient

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#74]
is it possible to add default props yMousePointerDisplay(Orient), for pointer orient (left, right) like EdgeIndicator orient ? 

<img width="320" alt="screen shot 2016-05-10 at 15 34 41" src="https://cloud.githubusercontent.com/assets/6270599/15146551/c83f6cfa-16c4-11e6-941b-23645eb722e8.png">

**Comment by rrag** [comment]
on `Chart`?

**Comment by rsklyar** [comment]
yep

**Comment by rsklyar** [comment]
btw, exclude MousePointer spect into separate <MousePointer> will be fantastic.

**Comment by rrag** [comment]
Yeah, these options on `Chart` are not intutive and comprehensive. I was thinking something like

```jsx
<ChartCanvas ...>
  <Chart id={0} ...>
    ...
  </Chart>
  <Chart id={1} ...>
    ...
  </Chart>
  <MouseCoordinates>
    <XCoordinate orient=... edgeAt=... displayFormat=... />
    <YCoordinate forChart={0} orient=... edgeAt=... rectWidth=... rectHeight=... fontSize=... displayFormat=... />
    <YCoordinate forChart={1} orient=... edgeAt=... rectWidth=... rectHeight=... fontSize=... displayFormat=... />
  </MouseCoordinates>
</ChartCanvas>
```

Multiple `YCoordinate` inside a `MouseCoordinates` this way, you can have fine control over the tooltip on the crosshair, including font. also this enables you to have the same tooltip on both left and right if you so desire.

Suggestions?

**Comment by rsklyar** [comment]
Hi, 
for more customisation, i would like to suggest next big change request:

if you think to move `<X,YCoordinate>` inside separate` <MouseCoordinate> ` that probably allow to  
add `type={vertical or horizontal - as default}` for `Chart`, to enable **vertical** graph orient.

what is your primary focus on continuous development of react-stockcharts?

**Comment by rrag** [comment]
what is the use case of a vertical chart? I dont see the benefit of seeing the time on the y axis?

**Comment by rsklyar** [comment]
vertical chart - modern way of trading view

when trading 24/7 you don't need horizontal chart.

**Comment by rrag** [comment]
I have never seen that, screenshot please. I am wondering how zoom, pan works on a chart where time is on yaxis

**Comment by rsklyar** [comment]
nobody see that, check you email please.
