### ISSUE TITLE
Area Chart with YAxis zero value always at center

### ISSUE THREAD

**Issue by alexbom** [rrag/react-stockcharts#747]
Namaste! First, many thanks for your job. Stock Charts works very fast, even with react native.

I have task to create Area Chart with zero value on YAxis always at center. Like on screenshot. Could you, please, explain or give a link to example with then same realization?

Thinking, i have to change this parameter of Chart component, but don't understand how? yExtents={d => d.close}

![area-chart](https://user-images.githubusercontent.com/1853593/73831567-9d604080-4817-11ea-850c-1484b3e6f93a.png)

**Comment by rrag** [comment]
[MACD](http://rrag.github.io/react-stockcharts/documentation.html#/macd)

**Comment by alexbom** [comment]
@rrag Thank you, man!
MACDSeries is working fine with zero value at center, but i need to use Area Chart for making gradient filling.

**Comment by rrag** [comment]
https://codesandbox.io/s/react-stockcharts-example2-wyeg4

```jsx
<AreaSeries
    yAccessor={d => d.macd.signal}
    baseAt={yScale => yScale(0)}
    canvasGradient={canvasGradient}
/>
```

**Comment by alexbom** [comment]
God bless you!

**Comment by alexbom** [comment]
One more question...
Now my chart looks like this. In HoverTooltip there is value for close position. But YAxis on the right side displays some diffrence instead of real value (from tooltip). How can i change it? My code is below.

![image](https://user-images.githubusercontent.com/1853593/73873590-eb4e6600-4862-11ea-85bc-5f988b480ec1.png)

        <ChartCanvas
          ref={ref => this.canvasRef = ref}
          ratio={ratio}
          width={width}
          height={400}
          margin={{ left: 20, right: 90, top: 20, bottom: 30 }}
          seriesName='MSFT'
          type={type}
          data={data}
          xScale={xScale}
          xAccessor={xAccessor}
          displayXAccessor={displayXAccessor}
        >
          <Chart
            id={0}
            padding={{ top: 0, bottom: 0 }}
            yExtents={macdCalculator.accessor()}
          >
            <defs>
              <linearGradient id='MyGradient' x1='0' y1='100%' x2='0' y2='0%'>
                <stop offset='0%' stopColor={vars.color.negative} stopOpacity={0.5} />
                <stop offset='50%' stopColor='transparent' stopOpacity={0} />
                <stop offset='100%' stopColor={vars.color.positive} stopOpacity={0.5} />
              </linearGradient>
            </defs>
            <XAxis
              axisAt='bottom'
              orient='bottom'
              ticks={6}
              stroke={vars.color.accent}
              tickStroke={vars.color.accent}
            />
            <YAxis
              axisAt='right'
              orient='right'
              stroke={vars.color.accent}
              tickStroke={vars.color.accent}
            />
            <HoverTooltip
              yAccessor={d => d.close}
              tooltipContent={({ currentItem, xAccessor: _xAccessor }) => ({
                x: dayjs(_xAccessor(currentItem)).format('DD MMM YYYY HH:mm'),
                y: [
                  {
                    label: 'value',
                    value: `${Utils.moneyFormat(currentItem.close)} ${Utils.currencyToSymbol(currency)}`,
                    stroke: vars.color.accent
                  },
                ]
              })}
              fontSize={16}
              bgFill={vars.color.lightBg}
              bgOpacity={0.6}
              fill={vars.color.lightBg}
              stroke={vars.color.lightBg}
              fontFill={vars.color.white}
            />
            <AreaSeries
              yAccessor={d => d.macd.signal}
              baseAt={yScale => yScale(0)}
              fill='url(#MyGradient)'
              strokeWidth={1}
              stroke={vars.color.accent}
              interpolation={curveMonotoneX}
              canvasGradient={canvasGradient}
            />
          </Chart>
        </ChartCanvas>

**Comment by alexbom** [comment]
Will answear to myself )
Just need to add one more Chart component:

          <Chart
            id={0}
            yExtents={[ d => [ d.high, d.low ], ema26.accessor(), ema12.accessor() ]}
            padding={{ top: 0, bottom: 0 }}
          >
            <YAxis
              axisAt='right'
              orient='right'
              ticks={5}
              stroke={vars.color.accent}
              tickStroke={vars.color.accent}
            />
          </Chart>
