### ISSUE TITLE
safari zoom issue 

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#78]
standard zoom does not work in safari (

**Comment by rrag** [comment]
I don't have a Mac I only tested using safari on iPad pinch zoom. Appreciate if you can add more details, error messages. PR welcome.

**Comment by cesardeazevedo** [comment]
Zoom on safari is working fine on my mac, i didn't have any issues...

**Comment by rrag** [comment]
Thanks @cesardeazevedo 

I also tested with safari on mac today, not able to reproduce on both master and next branches, reopen with more details
