### ISSUE TITLE
Adding and updating values for chart indicators, on the fly.

### ISSUE THREAD

**Issue by gldstrrbt** [rrag/react-stockcharts#783]
Does this library allow for adding indicators on the fly and the ability to modify their values or remove them once they are added to a chart? Those are basic and necessary features in charting, yet they don't appear to be included in this library, and if they do where's the documentation? 

For example, rather than having an ema50 hardcoded as an accessor, is it possible to simply call click add indicator, select and call the ema component, enter the window size in a modal, then click apply to have a visual of the ema with the set window size? I've spent the whole day trying to figure this out and it's driving me nuts that I can't find this feature. I'd rather not have to rebuild an indicator that already exists in the library.

**Comment by vichaunter** [comment]
@gldstrrbt i think the prupose of the chart library is to give all the tools and capability, but this type of behavior is part of the frontend implementation (with react is about to make reactive parts and control them how you want inside). Maybe i'm wrong.
Anyway, what you want to do can be accomplished if you change parts of chart component on the fly depending on state or props.

**Comment by gldstrrbt** [comment]
The question was asked because one would think that basic charting capabilities, such as timeframe/interval options and the adding/editing/removing of included indicators, would be included in a charting library. If those capabilities were readily available and someone could've pointed them out, then I would've preferred saving the time spent these last couple days building out these components.
