### ISSUE TITLE
CandleStickChartWithUpdatingData

### ISSUE THREAD

**Issue by vakorovin** [rrag/react-stockcharts#81]
code does not work in this example: "https://bl.ocks.org/rrag/555ea9d11c621a895171",
on "http://rrag.github.io/react-stockcharts/documentation.html#/updating_data" file "http://rrag.github.io/react-stockcharts/dist/react-stockcharts-documentation.js" page too big to understand the source code. What changes need to be done in the first example to the demo work?

**Comment by rrag** [comment]
the source in the block uses v0.3 which is no longer the current version

How did you get to that link? I had removed all references to that link from documentation, if there is still some old reference to it, please let me know so I can remove that.

http://rrag.github.io/react-stockcharts/documentation.html#/updating_data

does not have a link to that block. to avoid the confusion I deleted that block now. 

Link to source is available in the above link

https://github.com/rrag/react-stockcharts/blob/master/docs/lib/charts/CandleStickChartWithUpdatingData.jsx
