### ISSUE TITLE
Uncaught TypeError: Cannot read property 'category10' of undefined

### ISSUE THREAD

**Issue by kayazinc** [rrag/react-stockcharts#84]
I got the error message "Uncaught TypeError: Cannot read property 'category10' of undefined"
generated by lib/utils/index.js line:129, 
```javascript
var overlayColors = exports.overlayColors = _d2.default.scale.category10();
```
I have traced and it seem _d2.default.scale is undefined.

**This error occurred when I tried to embed the bundle.js (generated by browserify) into existing site.  No error message if the bundle.js is running on standalone page.**

Do you have any hints or know what are the possible causes of this issue?  If yes, please share with me because I've already spent numerous days trying to resolve this and I ran out of ideas.

Thanks in advance!

**Comment by rrag** [comment]
Looks like you don't have d3 or have declared it external

**Comment by kayazinc** [comment]
> don't have d3

I should have d3 because I can run the react-stockchart with the bundle.js on a standalone page.

> d3 was declared externally

Possible, there might be other plugins (with the site) that uses d3.  Let me check on this.

Thanks for the tips, @rrag

**Comment by kayazinc** [comment]
@rrag, 

1. I've checked, the bundle.js does contains d3.
2. I have also done a quick-test to load d3 externally, together with the bundle.js on a standalone page and it still work.  Maybe I misunderstand you on what you mean by "have declared it external".  Can you give me a example or point me to any relevant article on this topic?

Thanks!

**Comment by kayazinc** [comment]
I think I will meddle with other issues first.
Don't think this issue is caused by React-stockcharts, so I shall close the issue here.
Thanks @rrag

**Comment by bendiken** [comment]
For what it's worth, I solved the exact same JS error on another project by downgrading from D3.js v4 (4.1.1) to v3 (3.5.17).

**Comment by silveur** [comment]
Same here... I had to downgrade to get it to work.

**Comment by amustafa** [comment]
Me too. 4.1.1 -> 3.5.17 fixed the problem
