### ISSUE TITLE
XAxis crowdedness (text overlapping)

### ISSUE THREAD

**Issue by igoldny** [rrag/react-stockcharts#85]
When there is many ticks with small time diff between them and usage of financeEODDiscontiniousScale as an xScale XAxis text overlapping.
when i use xScale={d3.time.scale()} instead XAxis looks fine but then i have the problem of the missing dates on the weekend.

here is demo: http://plnkr.co/edit/obOyFLz7N3ZRbrvqS78v?p=preview

**Comment by rrag** [comment]
fixed version. http://plnkr.co/edit/EzD322ou9SeIbs2FTkcl?p=preview

`financeEODDiscontiniousScale` does not suppor intra day

**Comment by kayazinc** [comment]
hi @rrag, similarly I also have this issue.

![crowded x-axis](https://cloud.githubusercontent.com/assets/19774010/18749155/17550b08-8108-11e6-8a34-fb090715c95d.PNG)
 
I am using v0.5.0 and discontinuousTimeScaleProvider for EOD data.

Please advise me how to resolve it?
