### ISSUE TITLE
data updates not visible in chart area

### ISSUE THREAD

**Issue by stocks29** [rrag/react-stockcharts#89]
When the `data` is updated on the `ChartCanvas`, initially new data is being plotted, but after the first 2-4 new data points are added, the chart appears to undergo some slight width change, after which time new data points are plotted off the right edge of the chart. These new data points are visible by panning right.

See attached giphy screencapture.

![react-stockcharts-latest-not-plotted](https://cloud.githubusercontent.com/assets/188319/16105990/3a39ae3c-335e-11e6-848d-fd227db45133.gif)

**Comment by stocks29** [comment]
I gave the chart more initial data (65 data points) and the issue is no longer happening.

**Comment by rrag** [comment]
related https://github.com/rrag/react-stockcharts/issues/70

**Comment by stocks29** [comment]
Ah, thanks for pointing that out! Looks like this'll be fixed in 0.50. Any tentative release date for that? :)

**Comment by rrag** [comment]
sorry, cant commit to any timelines now, Still working through the [list](http://rrag.github.io/react-stockcharts-next/documentation.html#/coming_soon...)
