### ISSUE TITLE
Hoover tooltip issue

### ISSUE THREAD

**Issue by rsklyar** [rrag/react-stockcharts#93]
iPad test (chrome, Safari) unable to see tooltip only ohlc text.

**Comment by rrag** [comment]
well, there is no hover state in ipad,

**Comment by rrag** [comment]
close?

**Comment by uditdubey** [comment]
OHLC Tooltip css(width) breaks when the ohlc data is high/ we minimize the screen. It should have the overflow property or something else. How can we control this? Can anyone suggest? 
![tempsnip](https://user-images.githubusercontent.com/41045663/57929681-94b68b80-78d1-11e9-8bf2-25e07d110077.png)
