### ISSUE TITLE
Where can I find demo's source code?

### ISSUE THREAD

**Issue by rrki** [rrag/react-stockcharts#95]
http://rrag.github.io/stockcharts-demo/
Is it open to public? Just want to take it as an example. Thanks!

**Comment by rrag** [comment]
I am sorry, the demo is not opensource.

**Comment by PhilTheAir** [comment]
The demo is not React based or webpack based. 
I tried to use express.js to load 2 pages illustrated in "http://bl.ocks.org/rrag/d1e5b75ac12f754bb21d" and finally they worked.
