### ISSUE TITLE
problem with chart of MACD, something wrong with the y coordinates of chart 2

### ISSUE THREAD

**Issue by sunshineying** [rrag/react-stockcharts#96]
with CandleStickChartWithMA-1.jsx is ok, but there is a  problem when  with CandleStickChartWithMA.jsx.  The y coordinates should match with bar.  But  when I use code as follows, something wrong with the y coordinates of chart 2. 
```javascript
<Chart {...macdChart}>
	<XAxis {...macdChart.xAxis} />
	<YAxis {...macdChart.yAxis} />
	<MACDSeries {...macdChart.series} />			
</Chart>
```
The plunker as follows: 
[http://plnkr.co/edit/9joqS8pvUc8iOBaa5lkH?p=preview](http://plnkr.co/edit/9joqS8pvUc8iOBaa5lkH?p=preview)

**Comment by rrag** [comment]
The chart did not even show, I changed 

```diff
    var macdChart={
...
				calculator: macdCalculator
			},
			tooltip: {
-				forChart: 2,
+				forChart: 2,
				origin: [-38, 5],
				calculator: macdCalculator
			}
		}
```

and it shows now http://plnkr.co/edit/JvJvMcllURtNRSoc1Sdd?p=preview

What is the problem you are facing?

**Comment by sunshineying** [comment]
please see my screenshot. the arrow pointed should not be like that.

![qq 20160628221901](https://cloud.githubusercontent.com/assets/18010449/16418944/87165b22-3d7e-11e6-8400-423a2e62f2b5.png)

**Comment by rrag** [comment]
did you try
```diff
-           yMousePointerDisplayFormat: d3.format(".2s"),
+           yMousePointerDisplayFormat: d3.format(".3f"),
```

**Comment by sunshineying** [comment]
thanks. It's ok now. I have made a silly mistake.
