### ISSUE TITLE
Stacked Bar Chart major issue

### ISSUE THREAD

**Issue by iNikNik** [rrag/react-stockcharts#98]
Hello! There is some bad news - stacked bar chart not working at all. Here is example with my data - http://plnkr.co/edit/xvwf2zrPVYrxcatKqRkX?p=preview . It's just code from docs, but with my data.

Main issue: when we're calling [getFilteredResponse](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/evaluator.js#L14-L22) inside data evaluator for bar chart - `left` and `right` are strings, also `xAccessor` returns string... And [getClosestItemIndexes](https://github.com/rrag/react-stockcharts/blob/master/src/lib/utils/index.js#L41) works completely wrong - because we're comparing two strings.

I've found quick fix - you can add plotFull={true} prop to ChartCanvas - http://plnkr.co/edit/w4xDGrUr7WoRDnHC9g90?p=preview . [This condition](https://github.com/rrag/react-stockcharts/blob/master/src/lib/scale/evaluator.js#L51-L53) allows us to do not call getFilteredResponse function

**Comment by rrag** [comment]
Excellent catch. Will work on this tomorrow

**Comment by iNikNik** [comment]
@rrag thanks!)
