### ISSUE TITLE
Get an instance of reactstockchart

### ISSUE THREAD

**Issue by GoChartingAdmin** [rrag/react-stockcharts#99]
Hi,

I was wondering if we create a stockchart by an ID, how can I access the instance of that chart by that ID.

I am referencing a similar query on a separate JS charting library (AmCharts) and their solution below

http://stackoverflow.com/questions/28384411/get-an-instance-of-amchart-using-id

I was hoping if something similar can be done with your library as well.

Regards,
SD

**Comment by rrag** [comment]
There is no such thing as a chart instance with this library. It is all react based, so you can have a `ref` and invoke methods that you want. Update the props and let react do its magic.
